### ISSUE TITLE
add custom cookie to socket.io-client

### ISSUE THREAD

**Issue by tasin-megamind** [socketio/socket.io-client#1000]
I need to add my custom cookie to 'socket.io-client'. For this I am using 'socket.io-client-cookie' package. But it does not set the cookie. Can any one tell me what is wrong here. 
N.B. : I have copied the engine.io-client inside node_modules of socket.io-client & xmlhttprequest inside node_modules of engine.io-client manually.

Here is the code:
var newXhr = require('socket.io-client-cookie'); 
newXhr.setCookies(cookie); 
var io = require('socket.io-client');
var socket = io.connect("localhost:3000");

**Comment by darrachequesne** [comment]
Hi! Shouldn't that belong to `socket.io-client-cookie` github repository?

**Comment by tasinn-megamind** [comment]
yes, but inside the socket.io-client there was no engine.io-client, so I doubt if there is anything wrong there. BTW, it's working now somehow

**Comment by carpii** [comment]
@tasinn-megamind Hi if there is no issue, could you close this ticket please?
