### ISSUE TITLE
Add list of supported browsers

### ISSUE THREAD

**Issue by OussamaRomdhane** [socketio/socket.io-client#1006]
Hi,

Considering adding socket.io to our project but we work with some really old browsers. Can you add an updated list of supported browsers (and the transport methods used to support these browsers)

I think it will be really helpful. Thanks a lot.

**Comment by carpii** [comment]
Maybe this will help as a start...

http://caniuse.com/#search=websocket

Anything which isn't green will not upgrade to a full websocket connection, but will instead stay on polling (assuming socket.io server allows it).

**Comment by OussamaRomdhane** [comment]
Do IE 5.5 and IE 6 support polling?

**Comment by carpii** [comment]
Oh wow, 5.5?!  I just don't know, sorry

**Comment by OussamaRomdhane** [comment]
Ok thanks for the help mate I really appreciate it :smile:

**Comment by OussamaRomdhane** [comment]
@darrachequesne Thank you for that wonderful merge :)

**Comment by darrachequesne** [comment]
Better late than never, right? :smile:
