### ISSUE TITLE
socket request wasn't sent on iOS 10.

### ISSUE THREAD

**Issue by wiadev** [socketio/socket.io-client#1007]
Hi @socketio

I'm using the socket.io-client and it's working fine on iOS 9.3.5 , Android and web browser.

but on iOS 10, the socket request wasn't sent on iOS 10.

I've checked it on heroku logs.

Any suggestions?

Thanks.

**Comment by wiadev** [comment]
The following the socket.io object on front-end.
NOTE that  connected property is false.

```
_callbacks: {$connecting: Array, $connect: Array, $message: Array, $attracted: Array, $joined venue: Array, …}
acks: {}
connected: false
disconnected: true
ids: 0
io: Manager {nsps: Object, subs: Array, opts: Object, _reconnection: true, _reconnectionAttempts: Infinity, …}
json: Socket {io: Manager, nsp: "/", json: Socket, ids: 0, acks: {}, …}
nsp: "/"
receiveBuffer: [] (0)
sendBuffer: [{type: 2, data: ["join venue", 771, "venue-1779"], options: {compress: true}}] (1)
subs: [Object, Object, Object] (3)
```

**Comment by carpii** [comment]
> I've checked it on heroku logs.

What exactly did the heroku logs show?

**Comment by wiadev** [comment]
sorry, I figured out.

**Comment by peterpeterparker** [comment]
what did you figured out @wiadev ?
