### ISSUE TITLE
Polling is not working with forceNew option

### ISSUE THREAD

**Issue by tinque** [socketio/socket.io-client#1012]
When you create many connection (usefull when you have to use different queryString connection) with the option forceNew, the polling transport is not working.

I use socket.io on version 1.5.0

**Comment by darrachequesne** [comment]
Hi! Can you provide a failing test?

**Comment by darrachequesne** [comment]
For future readers: this might due to the max number of connections in the browser: https://stackoverflow.com/a/985704

> usefull when you have to use different queryString connection

I think you may be able to use distinct [namespaces](https://socket.io/docs/v3/namespaces/) (multiplexing) for this use case.
