### ISSUE TITLE
[Bug] Manager leaks an EIO socket when disconnect is called right before connecting again

### ISSUE THREAD

**Issue by benjamin-albert** [socketio/socket.io-client#1014]
### server.js:

``` js
var io = require('socket.io')(1337);

io.of('/asd');
io.of('/foo');
```
### client.js:

``` js
var io = require('./');
var manager = io.Manager('http://localhost:1337', { transports: ['websocket'] });

var fooSocket = manager.socket('/foo');
fooSocket.on('connect', function() {
  // This disconnect should not break
  // the conection of the asdSocket.
  fooSocket.disconnect();

  var asdSocket = manager.socket('/asd');

  // Only fail if reconnect_attempt it emitted
  // even if the IEO Socket was successfully opened.
  manager.engine.on('open', function() {
    asdSocket.on('reconnect_attempt', function() {
      console.error('Why reconnect? This is a bug!');
    });
  })

  asdSocket.on('connect', function() {
    asdSocket.disconnect();
    console.error('Node.js should exit after all clients have disconnected');
  });
});
```
## Expected behavior

Node.js should exit after all clients have disconnected.
## Actual behavior

Node.js freezes for about a second (before it tries to reconnect) and then it stays open forever (doesn't exit).
## Workaround

I am aware that the proper way to do something like this is to first connect to the second namespace and then disconnect from the first namespace.

However I don't think something like this should leak an IEO socket.
## Setup
- OS: macOS Version 10.12
- browser: Node.js v4.6.1
- socket.io version: 1.5.0
### Other information

See [this commit](https://github.com/benjamin-albert/socket.io-client/commit/a4b80b2724c37a4bc5690ec54c157230e9f8bcf1) in my [fix_eio_leak branch](https://github.com/benjamin-albert/socket.io-client/tree/fix_eio_leak) which adds a failing test to  `test/connection.js`

Stay tuned for a pull request that fixes this bug.

**Comment by darrachequesne** [comment]
For future readers:

This should be fixed by https://github.com/socketio/socket.io-client/commit/99c2cb8421361487ed7c876edd8670bb69a5c5b5, included in `socket.io-client@4.4.0`.
