### ISSUE TITLE
build socket.io with different namespace 

### ISSUE THREAD

**Issue by mhf-ir** [socketio/socket.io-client#1018]
how can i build socket.io client with different name space that works well.

In other words i need this file `http://cdn.socket.io/socket.io-1.4.5.js` but i wanna use like this:

```
<script src="/js/swebsocket.io.js"></script>
<script>
  var socket = swebsocketio();
</script>
```

Use case:
Using an external javascript script for global usage that each site may have socket.io with their version. i need _no conflict mode_

**Comment by Devitgg** [comment]
Download it locally? erm?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
