### ISSUE TITLE
Can´t catch ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by delike** [socketio/socket.io-client#1023]
* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

I cant catch the "ERR_CONNECTION_REFUSED" error when the socket connection is killed.

I have the following Event-Listener in my Code:

               this.socket.on('error', (err) => {
                    console.log('Error connecting to server', err);
                });

                this.socket.on('disconnect', () => {
                    console.log('Disconnect from server');
                });

                this.socket.on('reconnect', (number) => {
                    console.log('Reconnected to server', number);
                });

                this.socket.on('reconnect_attempt', () => {
                    console.log('Reconnect Attempt');
                });

                this.socket.on('reconnecting', (number) => {
                    console.log('Reconnecting to server', number);
                });

                this.socket.on('reconnect_error', (err) => {
                    console.log('Reconnect Error', err);
                });

                this.socket.on('reconnect_failed', () => {
                    console.log('Reconnect failed');
                });

                this.socket.on('connect_error', () => {
                    console.log('connect_error');
                });
and got this Error on Chrome console:

socket connected
socket.io.service.ts:69 Disconnect from server
socket.io.service.ts:83 Reconnect Attempt
socket.io.service.ts:90 Reconnecting to server 1
zone.js:1382 GET https://XXX:3000/socket.io/?auth_token=XXX&EIO=3&transport=polling&t=LXY2NwI net::ERR_CONNECTION_REFUSEDscheduleTask @ zone.js:1382ZoneDelegate.scheduleTask @ ...
socket.io.service.ts:111 connect_error
socket.io.service.ts:97 Reconnect Error Error: xhr poll error(…)
socket.io.service.ts:83 Reconnect Attempt
socket.io.service.ts:90 Reconnecting to server 2
...

### Steps to reproduce (if the current behaviour is a bug)

Start a working app and stop the socket-server.

### Setup
- OS: macOS Sierra & Linux Debian Jessie
- browser: Chrome
- socket.io version: 1.5.1

**Comment by darrachequesne** [comment]
Hi!

> I cant catch the "ERR_CONNECTION_REFUSED" error when the socket connection is killed.

I don't understand... Aren't the events 'reconnect_error' and 'connect_error' properly emitted?

**Comment by bermanboris** [comment]
I have the same issue. Have you found any solution to this bug?

**Comment by xtremetom** [comment]
I have the exact same issue

**Comment by darrachequesne** [comment]
@xtremetom @bermanboris 

May I ask what behaviour you are expecting?

**Comment by w0xz** [comment]
I had the same problem. This message was caused by the <script src="http://your-host.tld:11111/socket.io/socket.io.js"> <- because; when the server is down you cant load that script from the server ;) you can't catch this but handle with a onerror attribute in the script file. better checking for the open port before including the script.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by kayzeeparacha** [comment]
What if we haven't included script tag for socket.io.js? Then how to solve this error?
I have angular 2 application , i just pointed out my chat component to hit the server initially and throwing error if server script is not running.

**Comment by icastillejogomez** [comment]
@kayzeeparacha This event catch the error however the error message is still displaying in console. I read in this post the message is not sending from socket.io and make sense. 😣
