### ISSUE TITLE
AutoConnect vs reconnection discrepancy [bug]

### ISSUE THREAD

**Issue by EddieOne** [socketio/socket.io-client#1024]
Say I wanted to switch socket.io servers manually, disconnect from one and connect to another. Currently with `reconnection: false, autoConnect: false` it won't work unless enabling reconnection. This also enables auto reconnection despite autoConnect false.

### Steps to reproduce (if the current behavior is a bug)

- Connect to server 1 with options `{ reconnection: false, autoConnect: false }`
- Disconnect from server 1
- connect to server 2 `socket.io.uri = 'http://server2'; socket.connect();`

Nothing happens

### Expected behaviour

I expect another option like autoReconnection. Or at least calling connect() on closed socket should allow reconnection if autoConnect is false.

### Setup
- socket.io version: 1.4.5

**Comment by thoqbk** [comment]
@darrachequesne do you think it's still worth to have a fix for this request? I can work on it.

**Comment by EddieOne** [comment]
Sorry, I missed your message. I believe this was fixed in 2.x. If not, I would suggest skipping. I can't remember which project it was needed for.
