### ISSUE TITLE
Can't connect to namespace on specified socket

### ISSUE THREAD

**Issue by NagRock** [socketio/socket.io-client#1029]
### You want to:

* [x] report a *bug*

### Current behaviour

As documentation says, to connect to namespace i should use:
`var socket = io('/my-namespace');`

But since io (or connect) method is global I can't specify on which socket I want to connect to namespace. For example:

`var firstSocket = io('localhost');`
`var secondSocket = io('localhost');`
`var namespace = io('localhost/myNamespace');`

I can't define if myNamespace connection should go through first or second socket.

### Expected behaviour

I think it should be like that:

`var firstSocket = io('localhost');`
`var secondSocket = io('localhost');`
`var firstSocketNamespace = firstSocket.connectNamespace('myNamespace');`
`var secondSocketNamespace = secondSocket.connectNamespace('myNamespace');`

**Comment by darrachequesne** [comment]
For future readers:

```js
const io = require("socket.io-client");

const socket = io("ws://example.com/my-namespace", {
  reconnectionDelayMax: 10000,
  query: {
    "my-key": "my-value"
  },
  auth: {
    token: "123"
  }
});
```

is the short form of:

```js
const { Manager } = require("socket.io-client");

const manager = new Manager("ws://example.com", {
  reconnectionDelayMax: 10000,
  query: {
    "my-key": "my-value"
  }
});

const socket = manager.socket("/my-namespace", {
  auth: {
    token: "123"
  }
});
```

The latter makes the creation of the Manager (which *manages* the low-level connection) explicit.
