### ISSUE TITLE
IllegalStateException: closed >> RealWebSocket.sendMessage(RealWebSocket.java:107)

### ISSUE THREAD

**Issue by alexvimodev** [socketio/socket.io-client#1038]
### You want to:
* [x] report a *bug*

### Setup
- OS: Android 6.0.1
- socket.io version: 0.8.1

### Crashed Thread

0	java.lang.IllegalStateException: closed
!	1	at okhttp3.internal.ws.RealWebSocket.sendMessage(RealWebSocket.java:107)
2	at io.socket.engineio.client.transports.WebSocket$4.call(WebSocket.java:189)
3	at io.socket.engineio.parser.Parser.encodePacket(Parser.java:63)
4	at io.socket.engineio.parser.Parser.encodePacket(Parser.java:42)
5	at io.socket.engineio.client.transports.WebSocket.write(WebSocket.java:184)
6	at io.socket.engineio.client.Transport$3.run(Transport.java:108)
7	at io.socket.thread.EventThread.exec(EventThread.java:55)
8	at io.socket.engineio.client.Transport.send(Transport.java:103)
9	at io.socket.engineio.client.Socket.flush(Socket.java:615)
10	at io.socket.engineio.client.Socket.onDrain(Socket.java:606)
11	at io.socket.engineio.client.Socket.access$1100(Socket.java:31)
12	at io.socket.engineio.client.Socket$6.call(Socket.java:308)
13	at io.socket.emitter.Emitter.emit(Emitter.java:117)
14	at io.socket.engineio.client.transports.WebSocket$3$1.run(WebSocket.java:171)
15	at io.socket.thread.EventThread$2.run(EventThread.java:80)
16	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
17	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
18	at java.lang.Thread.run(Thread.java:841)

**Comment by darrachequesne** [comment]
Please open an issue here: https://github.com/socketio/socket.io-client-java. Thanks!
