### ISSUE TITLE
Autodiscovery the server's IP

### ISSUE THREAD

**Issue by giacomocerquone** [socketio/socket.io-client#1039]
### You want to:
* [x] request a *feature*

I don't know if it's already possible or it's something that still have to implemented, but I'd like to connect automatically to the server that in my LAN is running socket.io.
On the official documentation this is showed here http://socket.io/docs/#sending-and-getting-data-(acknowledgements) that just calling io(); it will auto discover the ip.
Someone know something? 😄 
Thank you all. 

### Setup
- OS: Windows 10
- Browser: No one, I'm using the node.js version of socket.io-client
- socket.io version: 1.7.1

**Comment by darrachequesne** [comment]
Hmm.. As far as I know, calling `io()` without options results in using the default ones, which should be `localhost:80` I guess. Or did I misunderstand your question?

**Comment by giacomocerquone** [comment]
No... let's say you don't know that the server is running in localhost, let's say straight away that you know completely nothing about the server's IP... how do you find it?

Thanks for the answer :)

**Comment by darrachequesne** [comment]
I'm afraid that question is not related to socket.io, please ask on Stackoverflow, thanks!

**Comment by theavijitsarkar** [comment]
@giacomocerquone  did you find anything?
