### ISSUE TITLE
Minified version breaks IE 8

### ISSUE THREAD

**Issue by johanneswuerbach** [socketio/socket.io-client#1040]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Parsing `socket.io.js` fails in IE 8 with `Expect identifier, string or number`

### Steps to reproduce (if the current behaviour is a bug)

Test the minified version in IE 8

### Expected behaviour

`socket.io.js` works in IE 8

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

The issue doesn't happen in socket.io 1.6 and also not on the non-minified version of 1.7.1.

**Comment by johanneswuerbach** [comment]
An ok solution for my use-case https://github.com/testem/testem, would also be to just have an option to serve the unminifyed version.

**Comment by darrachequesne** [comment]
Related: https://github.com/mishoo/UglifyJS2/pull/1179

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-client/pull/1042.
