### ISSUE TITLE
Client-side socket does not connect with more than 5 sockets

### ISSUE THREAD

**Issue by JasonEtco** [socketio/socket.io-client#1041]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
After declaring the socket as a a variable, the object is missing an `id`. This only occurs for the 6th socket (possibly more, but cannot  test), when there are 5 existing sockets (users accessing the page).
```
import io from 'socket.io-client';
const socket = io();
console.log(socket);
```

The output has `connected: false` and `disconnected: true` so it's seems that it isn't connecting at all, which is probably what's causing the id to not exist.

![Output](http://i.imgur.com/8zc5TMQ.png)

### Steps to reproduce (if the current behaviour is a bug)
1. In a NodeJS environment, `npm install` socket.io and socket.io-client
2. Server side as normal.
3. Client side, use the above code snippet.
4. Connect to the server in 5 different tabs; then observe the console.log on a 6th tab.

### Expected behaviour
The socket object should contain an `id` key/value pair, or if it isn't connecting, it should be clear why.

### Setup
- OS: Windows 10/Node 6.4.0
- browser:  Google Chrome
- socket.io version: 1.7.1

**Comment by thetutlage** [comment]
Shouldn't you wait until the socket connects?

```javascript
socket.on('connect', function(){
  console.log(socket.id)
})
```

**Comment by darrachequesne** [comment]
Hi! Did @thetutlage answer help you fix your issue?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
