### ISSUE TITLE
Socket IO Docs for Client API down?

### ISSUE THREAD

**Issue by mck-** [socketio/socket.io-client#1046]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Socket.io Docs for Client API is just a blank page.

### Steps to reproduce (if the current behaviour is a bug)

Go to socket.io/docs/client-api/

### Expected behaviour

Some docs? 😄 

### Setup
- browser: Chrome, Safari, Firefox

**Comment by popey456963** [comment]
In the meantime, you can use archive.org for a saved copy:

 - https://web-beta.archive.org/web/20161022042404/http://socket.io/docs/client-api

**Comment by carpii** [comment]
Still appearing as a blank page almost a month after it was reported :(

http://socket.io/docs/client-api/

**Comment by Sieabah** [comment]
RIP Socket.io

**Comment by carpii** [comment]
Maybe they just aren't aware of it yet?

@darrachequesne 
@rauchg

On the upside, the Github issue list is seeing a lot more maintenance lately, which is great (and something I was hassling them about recently)

**Comment by darrachequesne** [comment]
Please see my comment [here](https://github.com/socketio/socket.io/issues/2791#issuecomment-269749496).

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
