### ISSUE TITLE
socket.io client-api side broken

### ISSUE THREAD

**Issue by Links2004** [socketio/socket.io-client#1054]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

the client-api docs on http://socket.io are "empty".
the most data on the html file is missing, only some parts of the header are there.

last line:
```html
<script type='text/javascript' src='http://socket.io/wp-includes/js/jque
```

### Steps to reproduce (if the current behaviour is a bug)

```
curl -v "http://socket.io/docs/client-api/"
```

**Comment by csmcanarney** [comment]
See #1046 and socketio/socket.io#2791.

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
