### ISSUE TITLE
How to import an instance of "io" in socket.io-client in ES6?

### ISSUE THREAD

**Issue by crazyyi** [socketio/socket.io-client#1055]
Sorry to bring up this here. I couldn't find any information of importing it in ES6 syntax. Is it supported now? Do I have to use `require('socket.io-client')`? If I use `import * as io from 'socket.io-client'` I have to use `io.connect('localhost')`. But if I use `require('socket.io-client')` I just need to use `io('localhost')`.

**Comment by violetlight** [comment]
Doing `import io from 'socket.io-client'` will give you a direct reference to `io`.

**Comment by faizalpribadi** [comment]
```js
import ioClient from 'socket.io-client'

let io = ioClient('http://your-host')
```

**Comment by crung** [comment]
how do you pass options in this case?

**Comment by Neudson01** [comment]
Try doing something like this:

`import express from 'express';
import http from 'http';
import SocketIO from 'socket.io';
import compression from 'compression';
import {validNick, findIndex, sanitizeString} from '../shared/util';

let app = express();
let server = http.Server(app);
let io = new SocketIO(server);`

**Comment by OSG-Proj** [comment]
Importing doesnt work. It says fetch module import failed

**Comment by ushicode** [comment]
This should work.

```
import express from "express"
import http from 'http'
import {Server, Socket} from 'socket.io'

const app = express()
const server = http.createServer(app); 
const io = new Server(server)
```
