### ISSUE TITLE
is this lib available via CDN?

### ISSUE THREAD

**Issue by ORESoftware** [socketio/socket.io-client#1060]
Back on version 1.4.5, I could use this link to load socket.io into my front-end

` 'socketio': '//cdnjs.cloudflare.com/ajax/libs/socket.io/1.4.5/socket.io',`

and I could use socket.io in the browser like so

 ```js
              var socket  = io.connect('http://127.0.0.1:3400');

                socket.on('error', function (err) {
                
                });

                socket.on('connect', function () {
               
                });
```

My concern is that with versions 1.7.x and greater, I should be importing `socket.io-client` into the front-end, however, I don't see any CDN's hosting `socket.io-client`, do I need it? How can I get it via CDN?

thanks!

**Comment by darrachequesne** [comment]
https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.7.2/socket.io.js ?

**Comment by ORESoftware** [comment]
huh that's weird, I didn't see it when I searched before

**Comment by darrachequesne** [comment]
Yes it is (it wouldn't make sense to provide a server build for the browser, would it?).

Would you know how we could make it clearer in the documentation?

**Comment by ORESoftware** [comment]
hmmm, beyond naming it `socket.io-client` instead of `socket.io`, I honestly don't know :)

**Comment by darrachequesne** [comment]
It seems it's a bit too late for that :smiley: : https://github.com/cdnjs/cdnjs/pull/31/files

Related: https://github.com/cdnjs/cdnjs/issues/6738, https://github.com/cdnjs/cdnjs/pull/9791

**Comment by ORESoftware** [comment]
yeah, nbd thanks :)
