### ISSUE TITLE
Socket IO Server "connect" event is not fired, but for redis does..

### ISSUE THREAD

**Issue by xscence** [socketio/socket.io-client#1061]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

I have server setup:

```
var server = require('http').Server();

var socket = require('socket.io')(server);

var Redis = require('ioredis');

var redis = new Redis(6379, 'xxxxx.com', {
    'password': 'xxxx'
});

socket.on('connect', function(){
    console.log('io socket connection');
})


server.listen(6001);
```

and my client

```
var io = require('socket.io-client')
var socket = io.connect("http://mysite.com:6001");
```

when i access mysite.com the connect event is not fired, but if u use "redis" redis.on('connect') it works... Why ?

### Setup
- OS:
- browser: Chrome late
- socket.io version: 1.7.2

**Comment by darrachequesne** [comment]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)
