### ISSUE TITLE
Minified file has broken on IE8

### ISSUE THREAD

**Issue by gkatsev** [socketio/socket.io-client#1063]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

Load up the page in IE8 and notice the error in the console about expecing an identifier
![errors in ie8](https://cldup.com/DscjamRE5N.png)

### Expected behaviour
No errors

### Setup
- OS: Windows 7
- browser: IE8
- socket.io version: 1.7.2

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
I found this because karma 1.4.0 started failing on IE8, the investigation and error lead me to socket.io-client, though, now investigating this it seems like it's potentially deeper that the problem occurs.

This must have happened only recently since karma 1.3.0 still works fine. I tried adding `screw_ie8: false` to the uglify mangle options but it didn't seem to fix it. I'm wondering if some dependency updated to accidentally break IE8 support.

Unfortunately, I can't really investigate any longer right now but I'll try to help out as much as I can.

**Comment by darrachequesne** [comment]
Yes, that has already been reported here: https://github.com/socketio/socket.io-client/issues/1040

I can't seem to find the correct uglifyjs configuration though... (https://github.com/socketio/socket.io-client/pull/1042)

**Comment by gkatsev** [comment]
Oh,  I thought I looked but I guess I missed that.

The "correct" config is `screw_ie8: false` under `mangle`, however, when i tried it it didn't seem to help. I think there's some dependency or something that is doing something that's breaking things.

**Comment by mgol** [comment]
@darrachequesne Doesn't `--support-ie8` work for UglifyJS?

**Comment by gkatsev** [comment]
I tried it, but I think a dependency of socket.io-client is doing something a bit weird that is now failing in the minified version, even with `--support-ie8`.
I believe it worked when running it through [es3ify](https://www.npmjs.com/package/es3ify) but I'm not sure this project wants another dependency and step in the build.

**Comment by mgol** [comment]
Not sure if it helps but since you already run Babel you could try to use [babel-preset-es3](https://www.npmjs.com/package/babel-preset-es3).

**Comment by gkatsev** [comment]
I believe it didn't help either because it only runs on the current package code :(

**Comment by darrachequesne** [comment]
What's weird it that the unminified version currently passes the tests, but even with `screw_ie8: false` the minified build does not seem to pass, I get a `Error: 'document' is null or not an object` in IE7/IE8, which I can't make sense of.

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-client/pull/1042.

**Comment by gkatsev** [comment]
Sweet, I'll check it out.
