### ISSUE TITLE
Emit with Ack broken

### ISSUE THREAD

**Issue by drekka** [socketio/socket.io-client#1064]
I'm using Node.js and socket.io. I created a web pages and imported `/docket.io/socket.io.js` as per the example webpage. I then made this call from the javascript in the html.

    socket.emit('listProjects', function (data) {
            writeToScreen(data);
        });

I've debugged the server and it's `listProjects` function is being called and is returning data. However when the callback is executed, `data` is null. 

I've turned on debugging (Safari's Web Inspector) and I see this in the console logs:

    [Log] socket.io-client:manager writing packet {"type":2,"data":["listProjects"],"options":{"compress":true},"id":0,"nsp":"/"} +1ms (socket.io.js, line 416)
    [Log] socket.io-parser encoding packet {"type":2,"data":["listProjects"],"options":{"compress":true},"id":0,"nsp":"/"} +1s (socket.io.js, line 1552)
    [Log] socket.io-parser encoded {"type":2,"data":["listProjects"],"options":{"compress":true},"id":0,"nsp":"/"} as 20["listProjects"] +1ms (socket.io.js, line 1552)
    [Log] engine.io-client:socket flushing 1 packets in socket +1ms (socket.io.js, line 416)
    [Log] engine.io-client:socket socket receive: type "message", data "30[null,[{"name":"Test project"}]]" +7ms (socket.io.js, line 416)
    [Log] socket.io-parser decoded 30[null,[{"name":"Test project"}]] as {"type":3,"nsp":"/","id":0,"data":[null,[{"name":"Test project"}]]} +8ms (socket.io.js, line 1552)
    [Log] socket.io-client:socket calling ack 0 with [null,[{"name":"Test project"}]] +5s (socket.io.js, line 416) 

Which indicates to me that the client javascript is receiving the data. 

I then debugged through the socket.io.js javascript. Finding this on line 7916:

	Socket.prototype.onack = function (packet) {
	  var ack = this.acks[packet.id];
	  if ('function' === typeof ack) {
	    debug('calling ack %s with %j', packet.id, packet.data);
	    ack.apply(this, packet.data);
	    delete this.acks[packet.id];
	  } else {
	    debug('bad ack %s', packet.id);
	  }
	};

I found that `packet.data` contained an array which looked like `[null, [-my-data-]]'. So when I changed:

    ack.apply(this, packet.data);

to 

    ack.apply(this, packet.data[1]);

The Ack started receiving the data I expected to see.

I'm no expert on javascript or how socket.io has been implemented so I cannot say definitively what the problem is or what the solution should be. 

But can this be fixed please?

**Comment by darrachequesne** [comment]
Could you provide a complete test case please? (you can use the fiddle [here](https://github.com/darrachequesne/socket.io-fiddle))

**Comment by drekka** [comment]
HI

I have some more info. I created a branch of fiddle at 

https://github.com/drekka/socket.io-fiddle/tree/issue/emit-ack-issue

and replicated the issue. Look at the html document and where it calls emit. The ack works with two arguments instead of the one as suggested by the doco.

The documentation (https://github.com/socketio/socket.io-client/blob/master/docs/API.md#socketemiteventname-args-ack) indicates that emit takes a single argument in it's ack callback. I've now found that if I change that to this signature:

    socket.emit('ferret', 'tobi', function (error, data) {

Then everything works without modifying socket.io. I'm assuming here that the first argument which in my code always comes through as null, is an error argument.

Therefore all we need is an update to the doco. :-)

**Comment by darrachequesne** [comment]
```js
// server
socket.on('listProjects', function (callback) {
  // ...
  callback(null, projects) // <- two arguments here
});
// client
socket.emit('listProjects', function (error, data) { // <- two arguments here, right?
});

// the following examples should work too

// server
socket.on('listProjects-v2', function (callback) {
  // ...
  callback(projects)
});
// client
socket.emit('listProjects-v2', function (data) {
});

// server
socket.on('listProjects-v3', function (arg1, arg2, callback) {
  // ...
  callback('4', [ 5 ], 6);
});
// client
socket.emit('listProjects-v3', 1, '2', function (arg4, arg5, arg6) {
});
```

**Comment by drekka** [comment]
Ahhh. I think I get it. Looks like I made an assumption I should not have. On the server I'm using Bluebird promises so all my callbacks have the `function(error, data)` signatures. I just assumed that the acks where just giving me the data part, forgetting that socket.io does not have Promise support and therefore would not understand the context of the two arguments. I just incorrect assumed that the `function(data) {....` in the documentation was referring to the Promise data argument. Opps.
