### ISSUE TITLE
Nothing displayed under http://socket.io/docs/client-api/

### ISSUE THREAD

**Issue by BorntraegerMarc** [socketio/socket.io-client#1069]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Nothing displayed under http://socket.io/docs/client-api/

### Steps to reproduce (if the current behaviour is a bug)
Open http://socket.io/docs/client-api/ in any browser

### Expected behaviour
Should display the docs

### Setup
- OS: Windows
- browser: Chrome, firefox

**Comment by barryvdh** [comment]
See https://github.com/socketio/socket.io/issues/2791#issuecomment-269749496 and the related issues below that comment.

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
