### ISSUE TITLE
There isn't a way to remove a specific event listener

### ISSUE THREAD

**Issue by sherodtaylor** [socketio/socket.io-client#1073]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
the client has no way to remove a listener

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS:
- browser:
- socket.io version:

**Comment by darrachequesne** [comment]
Since Socket extends the [Emitter](https://github.com/component/emitter) class, you should be able to do: `socket.off('eventName');`
