### ISSUE TITLE
Auto reconnection to server not working anymore

### ISSUE THREAD

**Issue by centrual** [socketio/socket.io-client#1080]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Client not try to reconnect when socket.io server side restarted.

### Steps to reproduce (if the current behaviour is a bug)
It's simple to test. You need:
1) Most basic socket.io server
2) Most basic socket.io client

- Open server program
- Open client
- Close server program
- Open server program
- Check client program for reconnect.

### Expected behaviour
It must reconnect automatically when server restarted.

### Setup
- OS: Windows 10
- socket.io version: 1.7.2

**Comment by darrachequesne** [comment]
I'm unable to reproduce (https://github.com/darrachequesne/socket.io-fiddle), could you provide more context?

**Comment by centrual** [comment]
@darrachequesne 

Thanks for response. It's my fault.
