### ISSUE TITLE
socket.io-client keeps connecting

### ISSUE THREAD

**Issue by flarocca** [socketio/socket.io-client#1084]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

I cant connect to the server cause client socket keeps "opening"

### Client
```
let io = require('socket.io-client')
let socket = io('http://localhost:3000/api/chat/connect', { path:'/api/chat/connect' })

//socket.connected is equal to false
//socket.io.readyState is equal to opening
```

### Server

```
let restify = require('restify')
let server = restify.createServer()
let socketio = require('socket.io')

server.use(restify.bodyParser())
server.use(restify.queryParser())
server.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*')
  res.setHeader('Access-Control-Allow-Methods', 'GET, PUT, POST, DELETE, OPTIONS')
  res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With, Content-Type')

  next()
})

server.listen(3000, function () {
  console.log('%s listening at %s', server.name, server.url)
})

let websocket = socketio.listen(server.server, { path: '/api/chat/connect', origins: 'http://localhost:* http://127.0.0.1:*' });
websocket.on('connection', (socket) => {
  // I see this log when the client connects
  console.log('new client connected')
  socket.on('disconnect', () => {
    // I see this log when the client disconnects
    console.log('Client disconnected.');
  });
})

//Test connection
websocket.broadcast.emit('new-message', { message: 'Connection done!!!' })
```

[StackOverflow Question](http://stackoverflow.com/questions/42569283/reactjs-socket-io-client-does-not-connect)

### Expected behaviour

Socket should be connected.

### Setup
- OS: Windows 10 / Windows 7
- browser: Chrome last version
- socket.io version: "^1.7.3"
- socket.io-client version: "^1.7.3"

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

All code public here:
- Client: https://github.com/flarocca/react-redux-websocket
- Server: https://github.com/flarocca/node-express-websocket

**Comment by nfriacowboy** [comment]
I have the same behavior, it's only happend on windows 10, any idea about this?

**Comment by darrachequesne** [comment]
@flarocca `io('http://localhost:3000/api/chat/connect', { path:'/api/chat/connect' })` means:
- use `/api/chat/connect` path.
- connect to `/api/chat/connect` namespace (which does not exists, if I'm not mistaken)

You can either:
- create the `/api/chat/connect` namespace on the server-side:
```js
io.of('/api/chat/connect');
```
- or simply connect to the default namespace:
```js
io('http://localhost:3000', { path:'/api/chat/connect' });
```

I added an example in the documentation [here](https://github.com/socketio/socket.io-client/blob/master/docs/API.md#with-custom-path), since that point was not that clear.

**Comment by darrachequesne** [comment]
Please reopen if needed.
