### ISSUE TITLE
Module not found: require('JSON') in socket.io.slim.min.js built with Webpack

### ISSUE THREAD

**Issue by rgalus** [socketio/socket.io-client#1095]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Error:
```
ERROR in ../~/socket.io-client/dist/socket.io.slim.min.js
Module not found: Error: Can't resolve 'JSON' in '\app\node_modules\socket.io-client\dist'
 @ ../~/socket.io-client/dist/socket.io.slim.min.js 6:180-195 6:243-262
```
When:
```js
import io from 'socket.io-client/dist/socket.io.slim.min.js';
```

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour
Should import socket.io slim minified version without `JSON` package as in docs it's said:
> A slim build (without JSON3, a JSON polyfill for IE6/IE7, and debug)

### Setup
- OS: Windows 10
- Node.js: 7.8.0
- Webpack: 2.3.3 
- socket.io version: 1.7.3

**Comment by darrachequesne** [comment]
@rgalus is there a particular reason you want to import the `socket.io-client` by its minified file?
