### ISSUE TITLE
Prevent redundant events

### ISSUE THREAD

**Issue by Decapitary** [socketio/socket.io-client#1098]
### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Current behaviour
scenario : user presses a button and get some data from database.

Is there anyway to prevent calling the same function when user frequently presses a button?. Need a feature to put a cooldown on specific socket for specific "on" event.( if  request & result are the same)

**Comment by darrachequesne** [comment]
How about using [_.throttle](https://lodash.com/docs/4.17.4#throttle)?

**Comment by Decapitary** [comment]
I want to know user(not all) emitted what and when with what argument, so I can see if this event is the same event with same arguments called after 1 sec or not. I dont know how time out function can help me

**Comment by darrachequesne** [comment]
In any case, I think your question is out of scope of the project, please use stackoverflow.
