### ISSUE TITLE
when create 2 client-connections in a IE6/7 window, bug show up

### ISSUE THREAD

**Issue by doraddl** [socketio/socket.io-client#1099]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

when i create 2 (or more than 2) clients connection   in one IE6/7 window( or different tabs in one IE7 window)

i can connected firest , but  those connection ping timeout soon ,  i record some log : 

Thu Apr 20 17:38:23 UTC+0800 2017 ping
// in normal,here should show trigger a pong ,but with this bug,here  without a pong .....
Thu Apr 20 17:39:23 UTC+0800 2017 disconnect transport close

### Steps to reproduce (if the current behaviour is a bug)

create 2 (or more than 2) clients connection   in one IE6/7 window( or different tabs in one IE7 window) ,and watch the connection status

you should log when:
socket.on('ping', ...
socket.on('pong', ...
socket.on('disconnect', ...
socket.on('connect', ...

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS:Windows *
- browser: IE6  IE7
- socket.io version: many version including latest version 1.7.3

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

a unnormal log:

MSIE_7_http Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)

Thu Apr 20 17:50:59 UTC+0800 2017 connected -8t8Xl8jw2F_bYQ8ACRz
Thu Apr 20 17:52:40 UTC+0800 2017 ping 
Thu Apr 20 17:53:40 UTC+0800 2017 disconnect transport close
Thu Apr 20 17:53:41 UTC+0800 2017 connected OTh8BsqDgjJpCIlRACSA

a normal log ： 

MSIE_7_http Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)

Thu Apr 20 17:50:00 UTC+0800 2017 connected uLPoacgas1ZelDV8ACRw
Thu Apr 20 17:50:25 UTC+0800 2017 ping 
Thu Apr 20 17:50:25 UTC+0800 2017 pong 78
Thu Apr 20 17:50:50 UTC+0800 2017 ping 
Thu Apr 20 17:50:50 UTC+0800 2017 pong 31

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
