### ISSUE TITLE
Promise support

### ISSUE THREAD

**Issue by ghost** [socketio/socket.io-client#1104]
Hi,
Any plan to support async/await feature? currently socket.emit returns socket object but adding Async functions that return Promise would help a lot in writing cleaner code.

**Comment by darrachequesne** [comment]
@aryaei No plan currently. Maybe a wrapper around the current API could be provided. If anyone wants to contribute!

**Comment by emcee-ai** [comment]
[socket.io-as-promised](https://github.com/perrin4869/socket.io-as-promised) looks interesting.  Not widely used as far as I can see.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
