### ISSUE TITLE
Build a package to TypeScript

### ISSUE THREAD

**Issue by matheusmonte** [socketio/socket.io-client#1106]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [] report a *bug*
* [X] request a *feature*

### Current behaviour

To use this package on Typescript project, We have to always build .d.ts package using Typings and this spend a long time on build

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- Ionic 2 + Typescript

**Comment by ibrahimduran** [comment]
I haven't used Ionic 2 but I use typescript daily and you should be able to install type definitions from @types organization on npm and you're good to go.

```bash
$ npm install --save @types/socket.io
```

**Comment by darrachequesne** [comment]
Or `@types/socket.io-client` for the client.

**Comment by BorntraegerMarc** [comment]
@darrachequesne The typescript version still runs on version 1.4.4. Can this be updated to the latest?

**Comment by darrachequesne** [comment]
@BorntraegerMarc you should open a pull request here: https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by BorntraegerMarc** [comment]
@darrachequesne I would be happy to do so. I only have one problem: I never wrote a index.d.ts file. So I'm not sure, where the actual version of socket.io is defined. I don't see it in the code... Could you point me to the right direction, how I can define the socket.io version?

**Comment by darrachequesne** [comment]
@BorntraegerMarc you mean, the version of socket.io in the typescript definition [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/socket.io-client/index.d.ts#L1)? Or the version [here](https://github.com/socketio/socket.io/blob/2.0.3/lib/index.js#L11)?

**Comment by BorntraegerMarc** [comment]
@darrachequesne Yeah in the [typescript definition file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/socket.io-client/index.d.ts#L1)

how can I upgrade that from version 1.4.4 to 2+?
