### ISSUE TITLE
[enhancement] Reconnection module

### ISSUE THREAD

**Issue by Andarist** [socketio/socket.io-client#1107]
Im wondering if its possible to do some refactoring and modularization in this regard. Basically the whole reconnection logic from [`Manager`](https://github.com/socketio/socket.io-client/blob/ff4cb3eed04a95c9725b8aaba8b64fa9fa1ca413/lib/manager.js) could have been moved to another module.

Aint sure if worth it, but something I would personally benefit from and could help with. Is it something you would consider to be aligned with library's design?

**Comment by darrachequesne** [comment]
Hi @Andarist may I ask what your use-case is?

**Comment by Andarist** [comment]
Using reconnection module outside of socket.io itself

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
