### ISSUE TITLE
Query cannot send

### ISSUE THREAD

**Issue by burakkilic** [socketio/socket.io-client#1110]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Steps to reproduce (if the current behaviour is a bug)

    var socket = require('socket.io-client')('http://127.0.0.1:3000/printers', {
        transports: ['websocket'],
        query: "shop=123456"
});

In socket.js, I debug that and found in Socket.prototype.onpacket function:

      packet { type: 4,
          nsp: '/printservers?shop=123456',
          data: 'Invalid namespace' }

What is wrong with that?

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS:
- browser:
- socket.io version:

**Comment by matthewshirley** [comment]
I supported this issue on this [SO thread](http://stackoverflow.com/questions/43820397/socket-io-client-cannot-send-handshake-parameter/43854560#43854560), but I was not able to replicate this on the latest client release.

**Comment by burakkilic** [comment]
@matthewshirley I downgraded to 1.4.7 version and it worked as I mentioned in that [SO Thread](http://stackoverflow.com/questions/43820397/socket-io-client-cannot-send-handshake-parameter/43854560#43854560)

**Comment by darrachequesne** [comment]
@burakkilic is there a particular reason for not using `{ query: { shop: '123456' } }`?

**Comment by darrachequesne** [comment]
@burakkilic also, I am not able to reproduce: https://github.com/darrachequesne/socket.io-fiddle/tree/send-query (with v1.7.x or v2.x)

In your example, you mention both `printers` (in the url) and `printservers` (in the packet) namespaces, may that explain your issue?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
