### ISSUE TITLE
multiple reply after connecting to server

### ISSUE THREAD

**Issue by MahdiPishguy** [socketio/socket.io-client#1111]
when my device is disconnected from server or device don't have internet connection, after emitting multiple socket to server that cause of  reply all sockets after connecting to server

for example:

**1-** client disconnected from server, i multiple click on button to emit data for example 10 click as request

**2-** after connecting client to server, server reply on 10 response

how can i manage this process?

**Comment by darrachequesne** [comment]
@MahdiPishguy hi, that should be covered with the `volatile` flag (not yet implemented, see https://github.com/socketio/socket.io-client/pull/821).

For now, you should be able to check whether the socket is connected before emitting:
```js
if (socket.connected) {
  socket.emit(/* */);
}
```

**Comment by MahdiPishguy** [comment]
@darrachequesne thanks to reply, 
then using `emit` without any parameter can be solve this problem?

**Comment by darrachequesne** [comment]
@MahdiPishguy no, you should just replace the `/* */` part with your code, like:

```js
if (socket.connected) {
  socket.emit('click', {});
}
```
