### ISSUE TITLE
Misleading release notice?

### ISSUE THREAD

**Issue by vincentwoo** [socketio/socket.io-client#1112]
The release that went out 10 minutes ago says that it updates the engine-io client to 1.8.4, but the version that was actually released seems to peg to 3.1.0:

`"engine.io-client": "~3.1.0"`

https://github.com/socketio/socket.io-client/blob/d30914d11b13e51ce1c1419d5cc99a74df72c2a7/package.json#L23

Was this intentional?

**Comment by darrachequesne** [comment]
I think you are referring to `1.7.4` release note: https://github.com/socketio/socket.io-client/releases/tag/1.7.4.

`engine.io-client` was actually updated to `3.1.0` in [2.0.0](https://github.com/socketio/socket.io-client/releases/tag/2.0.0). Or am I missing something?

**Comment by vincentwoo** [comment]
I was confused, I think because the new release note hadn't made it. Can you speak to whether the 1.7x -> 2.x bump is breaking? Do I need to synchronously update the client and server? I couldn't find it in the docs but the semver bump is a bit scary.

**Comment by nuclearace** [comment]
I think it bumped for the double-encoding of unicode change, correct?

**Comment by darrachequesne** [comment]
I'll update the release note as soon as possible, but yes, the change @nuclearace is referring to is a breaking one (https://github.com/socketio/engine.io-parser/pull/81).

**Comment by darrachequesne** [comment]
Please see https://github.com/socketio/socket.io/releases/tag/2.0.0.
