### ISSUE TITLE
Unable to resolve module (engine.io-client) In window OS

### ISSUE THREAD

**Issue by GeekRishabh** [socketio/socket.io-client#1113]
* 
![engine io](https://cloud.githubusercontent.com/assets/23093075/26089675/4dc175f4-3a1d-11e7-8567-87abd09f7394.png)
[x] report a *bug*

### Current behaviour
When i tried to run the React native project with socket.io-client as dependency . Error is shown in Window OS .while In MAC and in Linux the app works fine without any issue .

### Expected behaviour

App should work fine in Windows  Os too .

### Setup
- OS:  Android/IOS
-project Type: React Native (CRNA)
- "socket.io-client": "^1.7.3"
- "react": "~15.4.0",
- "react-native": "0.42.0",

**Comment by dazich** [comment]
hey! i just met the same problem today,and i just solved it by copying the xmlhttprequest.js file in engine.io-client\lib to engine.io-client\lib\transports, and then change require('xmlhttprequest') to require('./xmlhttprequest') in all files in engine.io-client\lib\transports. Hope it works for you!

**Comment by GeekRishabh** [comment]
@dazich Thanks for the hack .but this cannot be a permanent solution to this issue .

**Comment by darrachequesne** [comment]
@GeekRishabh it seems the [browser](https://github.com/socketio/engine.io-client/blob/3.1.1/package.json#L72) field is not handled properly in react-native. Could you please open an issue in their repository?

**Comment by gavin-gmlab** [comment]
Faced this issue too! 
My version of engine.io has require ('xmlhttprequest-ssl'), so I had to change it to require ('xmlhttprequest'), but after that it says document not defined in polling-jsonp.js
(This is all in react-native)

**Comment by constantinosergiou** [comment]
guys anyone figure out a solution ?

**Comment by ThalesMatoso** [comment]
npm install engine.io-client

**Comment by constantinosergiou** [comment]
i try it before and is not working

**Comment by pdarii** [comment]
I had the similar, issue when i made checkout of existing project. 
I run npm -i, all dependency's were installed, but this error appears: 

" Can't resolve 'engine.io-client' "

Was fixed by installing socket.io-client.

npm i socket.io-client

**Comment by andikare** [comment]
umm anyone figure out a solution ?

**Comment by SahilPrabhakar7** [comment]
> npm install engine.io-client

Thanks 😄

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
