### ISSUE TITLE
XMLHttpRequest': The response type cannot be set after the request has been sent

### ISSUE THREAD

**Issue by wangzhiqiang1975** [socketio/socket.io-client#1114]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

When I use React-Native 0.4.4 and socket.io-client  testing  remote message ,program can be connected server and get json string ,but system error  "XMLHttpRequest': The response type cannot be set after the request has been sent
### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS:Mac os 10.12.5
- browser: IOS10.1 Simulator
- socket.io version:2.0.1
<img width="841" alt="2017-05-16 22 15 33" src="https://cloud.githubusercontent.com/assets/20923217/26110541/3fce4f2c-3a85-11e7-8608-090edefa83e9.png">

**Comment by wangzhiqiang1975** [comment]
I down version from 2.0.1 to 1.7.4  fix it Thanks lots

**Comment by darrachequesne** [comment]
I think that is linked to https://github.com/socketio/engine.io-client/pull/562, but it shouldn't throw an error.

=> https://github.com/facebook/react-native/issues/13991

**Comment by colorfulberry** [comment]
@wangzhiqiang1975 I down the version also works for me.

**Comment by marceloch2** [comment]
Adding { transports: ['websocket'] } works for me as well.
