### ISSUE TITLE
[help wanted] socket is not connected to the live WebSocet API (using local react app).

### ISSUE THREAD

**Issue by YUzhva** [socketio/socket.io-client#1116]
Hey hi.

I created react new react project using `create-react-app` and would like to implement some API fetching from third party API server (API from another web app).

I installed `yarn add socket.io-client`, and my next steps are:

```javascript
import io from 'socket.io-client';

class App extends Component {
  constructor(props) {
    super(props);

    this.socket = io.connect(`wss://${HIDDEN_DOMAIN}/ws/`, { reconnect: true, transports: ['websocket', 'polling'] });
  }
  componentWillMount() {
    console.log('this.socket', this.socket);
    this.socket.on('connect', () => console.log('Socket is connected'));
  }
```

Expected behavior: I would like to see log `Socket is connected` in my browser, but there only one log message with `this.socket` object, which looks like that:
```json
acks: Object
connected: false
disconnected: true
ids: 0
io: Manager
json: Socket
nsp: "/ws/"
receiveBuffer: Array(0)
sendBuffer: Array(0)
subs: Array(3)
_callbacks: Object
```

But in the network tab of the develper console, I could see the response from the server with the next message:
```
{"e":"connected"}
```

Who is right? Server response or `this.socket`object and why I can't catch events like `connect` and can't emit some functions?

Thanks.

**Comment by darrachequesne** [comment]
Hi! Is the endpoint a Socket.IO server, or a classic Websocket one? (for Socket.IO is **not** a Websocket implementation)

**Comment by YUzhva** [comment]
Looks like that API is using socket.io, because when I'm trying to establish the connection with `websocket.org`:
```javascript
this.socket = io.connect('wss://echo.websocket.org', {
    reconnect: true, transports: ['websocket', 'polling']
});
```
I'm receiving `Error during WebSocket handshake`:
```
websocket.js:112 WebSocket connection to 'wss://echo.websocket.org/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 404
```

The solution with fix for that issues [already opened here](https://github.com/socketio/socket.io/issues/1942#issuecomment-299764672)

So, `websock.org` is not running a socket.io server - I'm receiving handshake error.
And those API which I'm using are using socket.io, because there is not any issue during establishing the connection with the server.

**Comment by YUzhva** [comment]
Could it be because of I'm using socket.io-client in the browser?

**Comment by YUzhva** [comment]
[websockets/ws](https://github.com/websockets/ws) library has interesing note:

> Note: This module does not work in the browser. The client in the docs is a reference to a back end with the role of a client in the WebSocket communication. Browser clients must use the native WebSocket object.

I think there was the same issue:
I was trying to use socket.io-client in the browser by telling URL to the already hosted server `ws://domain_url` instead of using my own running server at localhost `ws://localhost:port`.

So I decided to use [the native WebSocket API](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) for communication and it works.
