### ISSUE TITLE
ERROR in ./~/socket.io-client/~/socket.io-parser/~/debug/src/browser.js

### ISSUE THREAD

**Issue by Tasemu** [socketio/socket.io-client#1117]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

When bundling with webpack after installing socket.io-client I receive the following error:

ERROR in ./~/socket.io-client/~/socket.io-parser/~/debug/src/browser.js
Module build failed: Error: ENOENT: no such file or directory, open '/Users/monty/fuse_frontend/node_modules/socket.io-client/node_modules/socket.io-parser/node_modules/debug/src/browser.js'
 @ ./~/socket.io-client/~/socket.io-parser/index.js 6:12-28
 @ ./~/socket.io-client/lib/index.js
 @ ./src/store.js
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./src/index.jsx

ERROR in ./~/engine.io-client/~/debug/src/browser.js
Module build failed: Error: ENOENT: no such file or directory, open '/Users/monty/fuse_frontend/node_modules/engine.io-client/node_modules/debug/src/browser.js'
 @ ./~/engine.io-client/lib/socket.js 7:12-28
 @ ./~/engine.io-client/lib/index.js
 @ ./~/engine.io-client/index.js
 @ ./~/socket.io-client/lib/manager.js
 @ ./~/socket.io-client/lib/index.js
 @ ./src/store.js
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./src/index.jsx

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour

I was hoping to be able to use it to be honest. Or at least be able to get a more meaningful error.

### Setup
- OS: OSX
- browser: Chrome
- socket.io version: Latest

**Comment by wa05** [comment]
Hi! How did you solve this error? I dont have \debug\browser.js inside of the package folder..

**Comment by qwertywelch** [comment]
@wa05 I got the same issue after updating my Socket.IO client from 1.x to 2.x. Restarting my npm webpack watch build task resolved the problem for me.
