### ISSUE TITLE
Room Support

### ISSUE THREAD

**Issue by cemsbr** [socketio/socket.io-client#1119]
I tried the slack channel, but had no answer about rooms

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
```
socket.join('test');
TypeError: socket.join is not a function
```

### Steps to reproduce (if the current behaviour is a bug)
1. Connect and make sure socket.connected returns true (something like ``var socket = io();``
1. (Try to) join a room like written in the [docs](https://socket.io/docs/rooms-and-namespaces/#joining-and-leaving) ``socket.join("a room")``.

https://github.com/cemsbr/socket.io-fiddle/tree/room

### Expected behaviour
Successfully join a room.

### Setup
- OS: Archlinux
- browser: Firefox/Chromium
- socket.io version: 2.0.1

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
If join and leave have not been implemented yet, the docs should warn that.

**Comment by darrachequesne** [comment]
@cemsbr room can only be joined / left on the server-side ([ref](https://github.com/socketio/socket.io/blob/master/docs/API.md#socketjoinroom-callback)).

Please do not hesitate if you have suggestions to make the documentation clearer!

**Comment by cemsbr** [comment]
Thanks for clarifying that. It is working.

**Comment by cemsbr** [comment]
Maybe it would help writing in the beginning of the "Room" section that it is part of the Server API and that the client should send regular events to join/leave rooms.
