### ISSUE TITLE
Socket.IO client  NOT following 30X redirection

### ISSUE THREAD

**Issue by nybbs2003** [socketio/socket.io-client#1120]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
<img width="421" alt="wx20170525-133354 2x" src="https://cloud.githubusercontent.com/assets/4301252/26437303/d7d719b4-414e-11e7-9970-d8f2c3c3a271.png">

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour
following the redirection, and request with new URI

### Setup
- OS:
- browser:
- socket.io version:

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
