### ISSUE TITLE
specifying websocket as the only transport clobbers extraHeaders

### ISSUE THREAD

**Issue by efx** [socketio/socket.io-client#1127]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Given the following config:
``` javascript
		const socket = io({
			transports: ['websocket'],
			transportOptions: {
				polling: {
					extraHeaders: {
						'x-custom': 'somevalue'
					}
				}
			},
			path: '/mypath',
			reconnectionAttempts: 1
		});
```
The `x-custom` header does not get attached to the initial GET. When I remove the `transports` key the header is correctly attached.

### Steps to reproduce (if the current behaviour is a bug)
Given a socket.io stack, navigate to an HTML page with `socket.io-client` loaded with the above configuration.
**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour
I expect the header to be attached when I specify `transports: ['websocket']`.

### Setup
- OS:
- browser: Any
- socket.io version: https://github.com/socketio/socket.io-client/blob/master/dist/socket.io.slim.js

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
I would submit a PR to fix, but it appears the `transportOptions` code only exists in `dist/`. Do you know where the logic handling this is?

**Comment by darrachequesne** [comment]
I think that's because Websocket does only support `Authentication` and `Sec-WebSocket-Protocol` headers.

Links:
- Websocket specification: https://tools.ietf.org/html/rfc6455
- Websocket reference on MDN: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket
- Stackoverflow question: https://stackoverflow.com/a/4361358/5138796

**Comment by efx** [comment]
ah, interesting. I think we need to document the client options better to indicate this behavior. The way the current docs read made me think this was possible. I'll get a PR for this later.

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-client/pull/1128.

**Comment by glenvollmer** [comment]
this is over two years late, but this worked for me.

`const socket = io(SOCKET_ENDPOINT, {
      query: 'b64=1',
      transports: ['websocket'],
      extraHeaders: {
        'state': state,
      }
    })`

**Comment by hanric** [comment]
Hi @glenvollmer, can you explain any extra step you took or can you recheck it's actually working? I've tried and it doesn't, and for the explanations given above I don't think it should.
