### ISSUE TITLE
Cannot find module 'socket.io-client/dist/socket.io.min.js'

### ISSUE THREAD

**Issue by sridkdhar** [socketio/socket.io-client#1130]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS:
- browser:
- socket.io version:

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

after sudo npm install socket.io-client
and run a simple chat app pschat giving error
Cannot find module 'socket.io-client/dist/socket.io.min.js'
and didnot find socket.io.min.js in the respective directory.

**Comment by darrachequesne** [comment]
Could you please share some code? Are you using webpack?

**Comment by sridkdhar** [comment]
[nodejs-pub-sub-chat-demo-master.zip](https://github.com/socketio/socket.io-client/files/1081467/nodejs-pub-sub-chat-demo-master.zip)


Thank you for asking.
I tried this demo and followed the instructions in the README file.

as per the readme file I tried to install socket.io.js
and got the above error.

FYI. 

Sridhar DK

**Comment by darrachequesne** [comment]
I can't reproduce with the example you provided. Which version of socket.io are you using? Please try with `2.0.3`.

**Comment by sridkdhar** [comment]
OK, I got it. If it is version issue, please update the documention
accordingly.

Thank you for the reply.

With best regards
Sridhar dk
Founder and CEO
Claytrix Management Services LLP
+91-9490457590
www.claytrix.com

I can't reproduce with the example you provided. Which version of socket.io
are you using? Please try with 2.0.3.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/socketio/socket.io-client/issues/1130#issuecomment-309136125>,
or mute the thread
