### ISSUE TITLE
Bad handshake method (only when using extra headers!)

### ISSUE THREAD

**Issue by JohnCoding94** [socketio/socket.io-client#1140]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
I get a 400 with the message `{"code":2,"message":"Bad handshake method"}` when trying to connect my server with an extra header (works fine if i don't try to add it).

### Steps to reproduce (if the current behaviour is a bug)
I try to connect my server with the following configuration:

      const options = {
        transportOptions: {
          polling: {
            extraHeaders: {
              Authorization: "Bearer test"
            }
          }
        }
      };

I also noticed that an OPTIONS request is made when i add this extra header (instead of a GET when i don't add it)

### Expected behaviour

A get GET request (to preserve cookies) with the extra headers that don't break the handshake.

### Setup
- OS: Mac
- browser: Chrome 58
- socket.io version: 2.0.3

**Comment by ghostfreak3000** [comment]
Same Issue, here.. totally works with the nodejs version of socket.io-client though not the browser

* OS: Win
* browser: Chrome 59
* socket.io version: 2.0.3

**Comment by darrachequesne** [comment]
Hi! I think you have to add the proper headers on the server-side (it seems you're in a CORS situation):

```js
const io = require('socket.io')(3000, {
  handlePreflightRequest: function (req, res) {
    var headers = {
      'Access-Control-Allow-Headers': 'Content-Type, Authorization',
      'Access-Control-Allow-Origin': 'http://localhost:3001',
      'Access-Control-Allow-Credentials': true
    };
    res.writeHead(200, headers);
    res.end();
  }
});
```

I added an example there: https://github.com/darrachequesne/socket.io-fiddle/tree/extra-headers

**Comment by DaVincii** [comment]
@darrachequesne how to specify multiple domains for origin,  following ways are not working:

1. 'Access-Control-Allow-Origin': 'http://localhost:3001, http://localhost:3002'
2. 'Access-Control-Allow-Origin': ['http://localhost:3001, http://localhost:3002']
3. 'Access-Control-Allow-Origin': 'http://localhost:3001 http://localhost:3002'

**Comment by stalinb87** [comment]
@DaVincii  you cannot use multiple domains, you need to read the client header origin and check agains your whitelist.

see [this](https://stackoverflow.com/questions/25309318/best-method-access-control-allow-origin-multiple-origin-domains) and [this](https://stackoverflow.com/questions/1653308/access-control-allow-origin-multiple-origin-domains) on stackoveflow

**Comment by roberto-souza-dbc** [comment]
@DaVincii i defined as null, but gets freed to any domain.

`const headers = {
    'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    'Access-Control-Allow-Origin': null,
    'Access-Control-Allow-Credentials': true
};`

**Comment by corescript** [comment]
**For CORS Use**
{
  handlePreflightRequest: function (req, res) {
    var headers = {
      'Access-Control-Allow-Headers': 'Content-Type, Authorization',
      'Access-Control-Allow-Origin': req.headers.origin ,
      'Access-Control-Allow-Credentials': true
    };
    res.writeHead(200, headers);
    res.end();
  }
}

**Comment by miguelsantos500** [comment]
> **For CORS Use**
> {
> handlePreflightRequest: function (req, res) {
> var headers = {
> 'Access-Control-Allow-Headers': 'Content-Type, Authorization',
> 'Access-Control-Allow-Origin': req.headers.origin ,
> 'Access-Control-Allow-Credentials': true
> };
> res.writeHead(200, headers);
> res.end();
> }
> }

'Access-Control-Allow-Origin': req.headers.origin 
This just saved my day! When I used:
'Access-Control-Allow-Origin': '*',
It would give me the following error:
"The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute."

**Comment by supertiger1234** [comment]
This does not seem to work anymore with the latest socket.io. Typescript does not like it. Anyway to fix?
![image](https://user-images.githubusercontent.com/8193841/84758350-3e78b800-afbd-11ea-8950-641762524082.png)

**Comment by pixochi** [comment]
> This does not seem to work anymore with the latest socket.io. Typescript does not like it. Anyway to fix?

@supertiger1234 `handlePreflightRequest` has a different interface in the latest version

![Screenshot 2020-07-20 at 20 16 00](https://user-images.githubusercontent.com/7315105/87971647-f110ce80-cac5-11ea-8b13-c0b1031ea708.png)

So in your case it should be:

...
handlePreflightRequest: function(server, req, res) {
  var headers = {
    "Access-Control-Allow-Headers": "Content-Type, Authorization",
    "Access-Control-Allow-Origin": config.allowedOrigins,
    "Access-Control-Allow-Credentials": true,
  };

  res.writeHead(200, headers);
  res.end();
...

**Comment by rttolipas** [comment]
I have some issues here. Hope someone could shed a light here.

![Screen Shot 2020-08-10 at 3 01 03 PM](https://user-images.githubusercontent.com/25500525/89758396-3ef38200-db1a-11ea-8da2-4093def3ad7d.png)

![Screen Shot 2020-08-10 at 2 59 27 PM](https://user-images.githubusercontent.com/25500525/89758287-05227b80-db1a-11ea-8013-0a3af52b8127.png)

**Comment by pA1nD** [comment]
> @supertiger1234 handlePreflightRequest has a different interface in the latest version

⚠️ If you install socket.io right now from npm you will have an old version, but if you install typings (via @types) it will have new typings! Which can be super misleading.

**Comment by supertiger1234** [comment]
How do I install the latest socket up?

**Comment by lovasoa** [comment]
For future reference: this issue also occurs when using a post-3.0 server with a pre-3.0 client. This may be caused by a misconfigured cache that makes the clients use an older version of `socket.io.js` .

**Comment by darrachequesne** [comment]
For future readers, please see:

- CORS documentation for v2: https://socket.io/docs/v2/handling-cors/
- CORS documentation for v3: https://socket.io/docs/v3/handling-cors/
