### ISSUE TITLE
docs bug - no port specified

### ISSUE THREAD

**Issue by ORESoftware** [socketio/socket.io-client#1141]
In the readme, the documentation for Node.js does not seem to specify a port for the client to connect to.

```
Node.JS (server-side usage)

Add socket.io-client to your package.json and then:

var socket = require('socket.io-client')('http://localhost');
socket.on('connect', function(){});
socket.on('event', function(data){});
socket.on('disconnect', function(){});
```

it seems to me like a major oversight to not demonstrate how to properly include a port to connect to. I frankly don't know the answer and just have to guess.

**Comment by kd8lvt** [comment]
+1
I'm having issues with being unable to connect with any port but the default, so it's human error (not knowing how to specify a port) It was working a while ago, but I refactored my code and now it's not working. Ah well. My repo is [on GitHub here](https://github.com/kd8lvt/node-remote-cmd) so if anyone wants to check it out and explain to me what I broke, that'd be awesome ^-^ (And yes, I am port forwarding properly haha.)

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
