### ISSUE TITLE
Add main property inside the bower.json file

### ISSUE THREAD

**Issue by felixrigorii001** [socketio/socket.io-client#1142]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Current behaviour
Can add in your bower.json file the main properties for e.g. 

> **"main": "dist/socket.io.js"**

so that it will be retrieved by the wiredep and gulp libraries.

### Setup
- OS:OSX
- browser:Chrome
- socket.io version:2

**Comment by darrachequesne** [comment]
We do not plan to support bower (which is now more or less deprecated if I'm not mistaken), please see https://github.com/socketio/engine.io-client/issues/289#issuecomment-40621081 for more information.
