### ISSUE TITLE
Firefox 54 - hangs for around 15 seconds when debug console is open

### ISSUE THREAD

**Issue by Kamil93** [socketio/socket.io-client#1144]
Firefox 54.0.1 (64 bit)
Windows 8.1
Socket.io: 2.0.3
Socket.io-client: 2.0.3

After connection to server and after around 25 seconds (measured) socket.io causes lag of whole firefox tab. Script is not executing. Then you need to wait next 15 seconds for normal browser work.

It happens only when debug console is open.

Why is that?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
