### ISSUE TITLE
Update Typescript Socket.Io version

### ISSUE THREAD

**Issue by BorntraegerMarc** [socketio/socket.io-client#1145]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [] report a *bug*
* [x ] request a *feature*

### Current behaviour
The version for the typescript version is very old. It's 1.4.4 -> https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/socket.io-client

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour
Update it please to the latest version.

### Setup
- OS: All
- browser: All
- socket.io version: latest

**Comment by kidkkr** [comment]
Is there anyone who handles this issue?

**Comment by BorntraegerMarc** [comment]
No. Never had the time to do it :(

There is an open PR that includes some change requests and did some updates. But it never got merged.

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16619

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18127

**Comment by MickL** [comment]
`@types/socket.io-client` was last updated 4 years ago on version `1.4.32` but latest is `2.3.0` :(

**Comment by MickL** [comment]
@darrachequesne Could you please update the typings? You are probably the most familiar with all existing functions and types.

**Comment by radinmoradi** [comment]
در تاریخ سه‌شنبه ۲۴ مارس ۲۰۲۰،‏ ۲۳:۱۱ Mick Lawitzke <
notifications@github.com> نوشت:

**Comment by darrachequesne** [comment]
For future readers:

As of Socket.IO v3, the typings are now included in the `socket.io-client` package.

The types from`@types/socket.io-client` are not needed anymore and may in fact cause errors like:

```
Object literal may only specify known properties, and 'extraHeaders' does not exist in type 'ConnectOpts'
```
