### ISSUE TITLE
Socket with IP & PORT

### ISSUE THREAD

**Issue by cedche99** [socketio/socket.io-client#1147]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [] report a *bug*
* [x] request a *feature*

### Current behaviour

Not tested

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour

i would like to create a socket with IP and PORT, like as :  

io(IP,port)

It's possible ?

### Setup
- OS:
- browser:
- socket.io version:

**Comment by mrvik** [comment]
### No

> `io(IP,port)` 

According to the [docs](https://socket.io/docs/client-api/#io-url-options) you can only specify the port as `io("https://myhostname:myport")`
The second argument on io function is reserved to an obejct with options (port is **not** included on this options)

**Comment by scottmont** [comment]
specifying port doesn't work
