### ISSUE TITLE
Unify connection event name on client and server

### ISSUE THREAD

**Issue by slykar** [socketio/socket.io-client#1150]
### You want to:

* [x] request a *feature*

### Current behaviour

When client is connected, a `connect` event is emitted.

### Expected behaviour

When client is connected, a `connect` and `connection` event is emitted.
OR
When client is connected, a `connection` event is emitted.

### Setup
- socket.io-client version: ^2.0.3

### Other information

I was working with both client and server at the same time and the event name difference caused me quite an headache, because I was confusing both strings in my tests and spent a good amount of time figuring out what's the problem.

I believe the event name could be unified or at least aliased in the client.

**Comment by darrachequesne** [comment]
Both a `connection` and a `connect` event are emitted on the server-side, so you should be able to use `connect` on both sides.

That behavior was set a very long time ago (< 1.x version I think), but I don't know what were the reasons back then.

**Comment by slykar** [comment]
Indeed, it's even in the docs https://socket.io/docs/server-api/#event-connect
Must have overlooked it.
