### ISSUE TITLE
[docs/build] remove json3 related comments

### ISSUE THREAD

**Issue by amitport** [socketio/socket.io-client#1156]
If I understand correctly, since https://github.com/socketio/socket.io-parser/pull/64, `json3` is no longer used.
Can it be removed from comments and slim build? (it's just misleading/redundant/inconvenience)

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-client/commit/f08b9338004fc8f72ae39e389399ca261431af95
