### ISSUE TITLE
React Native 47 gets xhr poll error with https server that has self signed certificate

### ISSUE THREAD

**Issue by HessiPard** [socketio/socket.io-client#1157]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
with react-native 0.47 in client and https node server with self signed certificate, i get xhr poll error even with rejectUnauthorized: false ... while i test it on node client with rejectUnauthorized: false and it works.
is it a problem with android?

### Setup
- socket.io version: 2.0.3

**Comment by jimji1005** [comment]
having same issue as above. ios is working fine with cert encrypted via lets encrypt. however does not work on android.

**Comment by Schachte** [comment]
Same issue here

**Comment by qdieppeEpitech** [comment]
same issue

**Comment by diegolaciar** [comment]
try last version from github, like this, solved my issues with RN android:

```npm i socketio/engine.io-client#3.3.2 -S ```

**Comment by darrachequesne** [comment]
For future readers:

Unfortunately, I was not able to achieve connection with a self-signed certificate, I keep getting `java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.` or `Hostname xxx not verified` errors.

`AndroidManifest.xml`

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest>

    <application
        android:networkSecurityConfig="@xml/network_security_config"
    />
</manifest>
```

`network_security_config.xml`

```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <debug-overrides>
        <trust-anchors>
            <certificates src="@raw/mycert" />
        </trust-anchors>
    </debug-overrides>
</network-security-config>
```

One should be able to completely disable the SSL check with a custom OkHttp client, but in that case I guess you can also use plain HTTP.

See also: https://socket.io/how-to/use-with-react-native
