### ISSUE TITLE
make messge cache is a options if client connection lost

### ISSUE THREAD

**Issue by tc1989tc** [socketio/socket.io-client#1158]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [] report a *bug*
* [x] request a *feature*

### Current behaviour
if the connection is lost, client will push message to cache buffer.

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour
make messge cache is a options if client connection lost.
For example:
  new Socket({cache_msg: true or false, .... })

### Setup
- OS:
- browser:
- socket.io version:

**Comment by darrachequesne** [comment]
Would volatile messages (pending feature: https://github.com/socketio/socket.io-client/pull/821) cover the use case?

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-client/commit/7ddad2c09dea0391b20378ef03b40040f0230d3e.

Syntax (similar to the server):

```js
socket.volatile.emit("volatile event", "might or might not be sent");
```
