### ISSUE TITLE
Cookie-based sticky sessions (reopen)

### ISSUE THREAD

**Issue by turpault** [socketio/socket.io-client#1159]
Our project is composed of a set of nodejs micro services, communicating through socket.io. Some of those micro services are running behind an amazon ALB load balancer. The only available session stickiness available to ALB target groups is cookie-based and the connections are allocated using a round-robin algorithm when the session cookie is not specified in the http request.

This effectively breaks the handshake protocol occurring when the socket.io connection is established, leading to the dreaded xhr poll error 400 response.

A workaround consists in disabling the xhr polling altogether in the client and only rely on the actual websocket. This is perfect in a controlled environment, but does not work when some of the services are developed and hosted by third parties.

Another hack also exists, which consists in overriding the base require('http').request function call, and issuing a pre-flight request in order to fetch those session cookies. Further http requests would then reinsert the cookies in the request. At best, I call that a hack.

See [ALB Sticky Sessions](http://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html#sticky-sessions)
Another request for the same feature #775

**Comment by DaVincii** [comment]
Any updates on this?

**Comment by AndyGOBrien** [comment]
anyone ever solve this?

**Comment by gabmontes** [comment]
@AndyGOBrien one workaround is to get your cookies from the server first and then open the socket connection specifying the `extraHeaders.Cookie` option as this:

```js
const socket = io(url, {
  extraHeaders: {
    Cookie: cookiesString
  }
})
```

**Comment by darrachequesne** [comment]
@turpault there's an `io` cookie set during the handshake: https://github.com/socketio/engine.io#methods-1

![image](https://user-images.githubusercontent.com/13031701/40054535-74918cf4-5845-11e8-87b2-ddc71cc1f3be.png)

**Comment by AndyGOBrien** [comment]
Yes, i got this to work. Thanks guys

**Comment by anderoonies** [comment]
@AndyGOBrien were you doing this in browser or in node? i'm able to get it working in node, but in browser i'm unable to set the `cookie` header

**Comment by 59naga** [comment]
[socket.io-client-v2.1.1](https://github.com/socketio/socket.io-client/tree/2.1.1) currently `extraHeaders.Cookie` option works only on NodeJS

<img width="804" alt="2018-08-17 0 49 07" src="https://user-images.githubusercontent.com/1548478/44219760-ce7a2a80-a1b7-11e8-9190-650327c570a7.png">

<img width="675" alt="2018-08-17 0 51 46" src="https://user-images.githubusercontent.com/1548478/44219789-de920a00-a1b7-11e8-8317-68edce7ed2b0.png">

at [Webpack 3.11.0](https://github.com/webpack/webpack/tree/v3.11.0/package.json) / Mac 10.13.6 / Google Chrome 67.0.3396.87

**Comment by Seldonm** [comment]
> @AndyGOBrien one workaround is to get your cookies from the server first and then open the socket connection specifying the `extraHeaders.Cookie` option as this:
> 
> ```js
> const socket = io(url, {
>   extraHeaders: {
>     Cookie: cookiesString
>   }
> })
> ```
> 
> Docs: https://github.com/socketio/engine.io-client#nodejs-with-extraheaders

**Comment by Seldonm** [comment]
> @AndyGOBrien one workaround is to get your cookies from the server first and then open the socket connection specifying the `extraHeaders.Cookie` option as this:
> 
> ```js
> const socket = io(url, {
>   extraHeaders: {
>     Cookie: cookiesString
>   }
> })
> ```
> 
> Docs: https://github.com/socketio/engine.io-client#nodejs-with-extraheaders

Any working example? Thanks

**Comment by cyrusmg** [comment]
Warning: The solution above does not handle AWSALB timeout. If the socket tries to reconnect after stickiness-timeout (i.e. 24hrs), it will throw `transport error`.

**Comment by ceciliazcx** [comment]
> [socket.io-client-v2.1.1](https://github.com/socketio/socket.io-client/tree/2.1.1) currently `extraHeaders.Cookie` option works only on NodeJS
> 
> <img alt="2018-08-17 0 49 07" width="804" src="https://user-images.githubusercontent.com/1548478/44219760-ce7a2a80-a1b7-11e8-9190-650327c570a7.png">
> 
> <img alt="2018-08-17 0 51 46" width="675" src="https://user-images.githubusercontent.com/1548478/44219789-de920a00-a1b7-11e8-8317-68edce7ed2b0.png">
> 
> at [Webpack 3.11.0](https://github.com/webpack/webpack/tree/v3.11.0/package.json) / Mac 10.13.6 / Google Chrome 67.0.3396.87

I got same problem. any luck it got fixed already?

**Comment by ceciliazcx** [comment]
@Seldonm @gabmontes @59naga any luck that anyone ever get a successful case with extraHeaders?
I am not able to do it at all.

**Comment by HighSoftWare96** [comment]
Any update on this? There are load balancer that do work only with Cookie sticky session, like Traefik...

**Comment by darrachequesne** [comment]
For future readers: cookie-based session affinity is definitely supported

I updated the documentation to make it clearer:

- example with Traefik: https://socket.io/docs/v3/using-multiple-nodes/#Traefik
- note about the `withCredentials` option: https://socket.io/docs/v3/using-multiple-nodes/#Sticky-load-balancing

The latter should fix the initial issue with the `AWSALB` cookie not being sent if the `withCredentials` is not set to `true`:

```js
// server
const io = require("socket.io")(httpServer, {
  cors: {
    origin: "https://front-domain.com",
    methods: ["GET", "POST"],
    credentials: true
  }
});

// client
const io = require("socket.io-client");
const socket = io("https://server-domain.com", {
  withCredentials: true
});
```

**Comment by sandeep-svg** [comment]
using 

// server
const io = require("socket.io")(httpServer, {
  cors: {
    origin: "https://front-domain.com",
    methods: ["GET", "POST"],
    credentials: true
  }
});

// client
const io = require("socket.io-client");
const socket = io("https://server-domain.com", {
  withCredentials: true
});

it's throwing below error

Failed to load http://localhost:9292/socket-api/?EIO=4&transport=polling&t=OW6kkXe: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:3001' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
