### ISSUE TITLE
Bump engine.io-client module to 3.1.2

### ISSUE THREAD

**Issue by roccomuso** [socketio/socket.io-client#1160]
`Regular Expression Denial of Service` Affecting an old `parsejson` dependency of `engine.io-client`.

Because of this, it prevents all the modules using express and `nsp check` to pass the security checks.

Just bump the engine.io-client to the latest v3.1.2

**Comment by chrisdothtml** [comment]
Looks like this was fixed by https://github.com/socketio/socket.io-client/pull/1109

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-client/pull/1109.
