### ISSUE TITLE
Unminified source code

### ISSUE THREAD

**Issue by pensnarik** [socketio/socket.io-client#1161]
Where can I get unminified socket.io-client JS code? Repository contains only minified JS files and source map files.

Thank you.

**Comment by darrachequesne** [comment]
@pensnarik you should be able to build the file yourself, please see the webpack configuration here: https://github.com/socketio/socket.io-client/blob/master/support/webpack.config.js

You'll have to comment the `UglifyJsPlugin` part.

**Comment by robsdedude** [comment]
I liked it better the way it was before 2.0 when one could choose between minified and unminified sources.

**Comment by slaughter550** [comment]
@rauchg is this something that could be included again? We'd prefer to minify the code ourselves to have a standard convention especially since we do not use closure compiler.
