### ISSUE TITLE
Socket.io was passed 1 argument. 0 was expected. 

### ISSUE THREAD

**Issue by nmolkeri** [socketio/socket.io-client#1162]
![microsoftteams-image](https://user-images.githubusercontent.com/10701840/31637509-e28bdfa6-b283-11e7-849d-5b33cf8638be.png)

Has anyone used socket.io-client with react-native. I am getting this error. Any help will be appreciated.

**Comment by darrachequesne** [comment]
For future readers, please check the example here: https://github.com/socketio/socket.io/tree/master/examples/react-native
