### ISSUE TITLE
SocketIOClient('http://localhost:3000'); is not working.

### ISSUE THREAD

**Issue by varunajmera0** [socketio/socket.io-client#1167]
In ur doc, u mentioned SocketIOClient('http://localhost:3000'); but unfortunately it doesn't work. I have to mention ip instead of localhost.

**Comment by vahid263** [comment]
If you want use IP Address, You must use https , Example = https://Your_IP_Address:3000

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
