### ISSUE TITLE
cannot unsubscribe from event

### ISSUE THREAD

**Issue by pmbanugo** [socketio/socket.io-client#1172]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
`socket.off(eventname)` does not remove the listener. It doesn't work. When I call socket.listeners(eventname) I get all the listeners even after calling socket.off()

### Steps to reproduce (if the current behaviour is a bug)
- initialise the client
- subscribe to an event -> socket.on(event, () => console.log('event called'))
- unsubscribe from event -> socket.off(event)
- get all listeners for event -> socket.listeners.forEach(listener => console.log(listner))

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour
Should remove all listeners after socket.off is called

### Setup
- OS: Mac
- browser: Firefox Quantum, Chrome 55
- socket.io version: 2.0.4

**Comment by pmbanugo** [comment]
my bad :( it works. It's a problem on my own end.

**Comment by sprengerst** [comment]
@pmbanugo what was your problem?

**Comment by laurencefass** [comment]
subscribing. i have two socket.on("event") calls in my code and I want to unsubscribe from only one of them. is there a way to do that?

**Comment by pmbanugo** [comment]
> subscribing. i have two socket.on("event", function(){}) calls on the same socket object and I want to unsubscribe from only one of them. is there a way to do that?

@laurencefass this might help you https://stackoverflow.com/questions/9418697/how-to-unsubscribe-from-a-socket-io-subscription/19384514#19384514
