### ISSUE TITLE
Can't use basic auth with websocket transport mode

### ISSUE THREAD

**Issue by jussirantala** [socketio/socket.io-client#1173]
### Current behaviour
Apache reads _Authorization_ header if using basic authentication. With socket.io-client you can't set custom headers without using _polling_ mode. Therefore you can't use _websocket_ mode with basic auth. https://socket.io/docs/client-api/#with-extraheaders

### Expected behaviour
Allow setting _extraHeaders_ even if the headers can't be used in _websocket_ handshake method.

**Comment by Oliv4945** [comment]
Hi, I just encountered the same issue.

Thank you

**Comment by jussirantala** [comment]
My pull request to fix this problem has been merged.

**Comment by beneuto** [comment]
Would like to mention that Authorization header is also used for CORS resolution.   Query workaround for authorization of websockets does not work when you are blocked for CORS reasons.   So even if the JS Websocket spec doesn't allow for headers, these headers are still required to get past CORS.

**Comment by darrachequesne** [comment]
The problem is that you can't add additional headers to the WebSocket connection in the browser (it will work in Node.js / React native though).

Please see the documentation here: https://socket.io/docs/v3/client-initialization/#extraHeaders
