### ISSUE TITLE
Verision in comment

### ISSUE THREAD

**Issue by robsdedude** [socketio/socket.io-client#1177]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Wanted behaviour
I think it was quite helpful if the version number of the lib was written in a comment at the top of the dist files. Many other libs do this as well and it helps debugging applications that server the libs rather than using a CDN.

**Comment by darrachequesne** [comment]
Done starting from version 2.1.0 (https://github.com/socketio/socket.io-client/blob/master/support/webpack.config.js).

Thanks for the heads-up!
