### ISSUE TITLE
Automatic reconnect stopped after explicit connection attempt

### ISSUE THREAD

**Issue by DuBistKomisch** [socketio/socket.io-client#1179]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Calling `connect` while the client is reconnecting stops any further reconnection attempts, even after connecting and disconnecting again.

### Steps to reproduce (if the current behaviour is a bug)

- Connect to a server
- Stop the server, the client will begin reconnecting automatically
- Call `connect` on the client
- No more reconnect attempts will occur

### Expected behaviour

A reconnect attempt will happen immediately and reset the backoff, and start over again if it fails or disconnects again later.

### Setup
- OS:
- browser:
- socket.io version:

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

Same as https://github.com/socketio/socket.io-client/issues/836 and https://github.com/socketio/socket.io-client/issues/849 which were supposedly fixed, so maybe this is a regression?

Maybe a new `reconnect` method needs to be added with this behaviour.

**Comment by DuBistKomisch** [comment]
Here's a quick fiddle to reproduce it: https://github.com/viviedu/socket.io-fiddle

Just start server, start client, stop server, and wait for the explicit `connect` to fire. The client process actually exits, which is a symptom of it no longer trying to reconnect.

**Comment by DuBistKomisch** [comment]
Managed to come up with a workaround:

```
socket.io.reconnecting = false;
socket.io.onclose();
```

This simulates it disconnecting again, clearing out the current reconnection process. I've just wrapped it in a check that the socket is currently disconnected.

This is good enough I guess, but would be nice to have a method which does this for you more safely.

**Comment by floriantraber** [comment]
I can confirm this bug. @DuBistKomisch workaround did not work for me. The following seems to do the trick: 
```
    // remove the old queued reconnect attempt
    socket.io.cleanup();
    socket.io.reconnecting = false;
    // reconnect immediately
    socket.io.backoff.reset();
    socket.io.reconnect();
```

**Comment by DuBistKomisch** [comment]
@floriantraber `onclose` basically calls all of those methods itself which is why I used it, not sure why it didn't work for you. One problem I noticed with my workaround is that it actual waits one backoff period (~2s by default) before trying, instead of immediately like yours, but that's fine for my use case.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
