### ISSUE TITLE
CANNOT EMIT DATA IN UTF-8 FORMAT TO ANDROID SOCKET

### ISSUE THREAD

**Issue by arfbrkdmr** [socketio/socket.io-client#1180]
### You want to:

* [x] report a *bug*

### Current behaviour

I am trying to build an app in android with socket.io. But when I try to emit data that include 'ö','ü','ş','ğ', 'ç' character from server side to client side (android), socket disconnect. It works on with browser client but with android as I said socket disconnect immediately.

### Setup
- Android:

**Comment by darrachequesne** [comment]
Hi! Which client are you using? [socket.io-client-java](https://github.com/socketio/socket.io-client-java)?

**Comment by meefik** [comment]
I confirm the problem in Chrome 64.0.3282.119 (64 bit). Socket was disconnected after send unicode symbols..

**Comment by mjarkk** [comment]
Encode the string in base64 or transform it to a uint8array

**Comment by grafikri** [comment]
I had same problem and i was using socket.io client `0.3.0` of author nkzawa on Android. 
When i send this chars(ş, ç, ö) from server side(Node) to client(Android), they not received by client or my client received chars but they changed. 
For example; when i send this word to server side "Şimdi" and i received on client side like this "^simdi"
I was using socket.io library `v2.0.3` on server side  and my nodejs was `v11.3.0.`
i updated my android socket library from `v0.3.0`  to `v1.0.0` then it fixed.

Sorry for my english.

**Comment by qqaimh** [comment]
The same to "github.com/googollee/go-socket.io",send json to web client, the recived data is base64 , not utf-8

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

Compatibility table: https://socketio.github.io/socket.io-client-java/installation.html
