### ISSUE TITLE
Namespace mixed up with query parameters

### ISSUE THREAD

**Issue by nicgirault** [socketio/socket.io-client#1181]
The original issue is https://github.com/socketio/socket.io/issues/3020 but it seems to me that it's more a socket.io-client issue than socket.io issue.

### You want to:

* [x] report a *bug*

### Current behaviour

When connecting to a namespace with query params, the namespace name contains the query params. Although the node socket.io librairy works with it, other librairies do not such as Flask Socket.io.

### Steps to reproduce

```javascript
import io from 'socket.io-client'

const socket = io.connect(
  'api.example.com/reading',
  { query: 'locale=en_US' }
)
```

Associated debug logs:

```
socket.io-client:manager writing packet {"type":0,"query":"locale=en_US","nsp":"/reading"}
socket.io-parser encoding packet {"type":0,"query":"locale=en_US","nsp":"/reading?language=en_US"}
```

### Expected behaviour

The logs should be:

```
socket.io-client:manager writing packet {"type":0,"query":"locale=en_US","nsp":"/reading"}
socket.io-parser encoding packet {"type":0,"query":"locale=en_US","nsp":"/reading"}
```

### Setup
- OS: OSX
- browser: Chrome 61
- socket.io version: 2.0.4

**Comment by nicgirault** [comment]
This is due to https://github.com/socketio/socket.io-client/blob/ebb0596ab03cc97e26d3847794c296693f02eca8/lib/manager.js#L416
But I can't understand why for the packet type 0 (CONNECT) there is this condition

**Comment by devmsg** [comment]
Hi
query question how do you solve it?

**Comment by energizer77** [comment]
@nicgirault thanks for the finding, seems to still be the case in 2.2.0, I commented the line and now my namespace + query connection works fine.

**Comment by darrachequesne** [comment]
In Socket.IO v2, the Socket `query` option was sent when connecting to a custom namespace but not for the main namespace, which was indeed a weird and unexpected behavior. 

This was fixed in Socket.IO v3: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#Add-a-clear-distinction-between-the-Manager-query-option-and-the-Socket-query-option
