### ISSUE TITLE
Please add the missing tag for version 1.7.3

### ISSUE THREAD

**Issue by sschuberth** [socketio/socket.io-client#1184]
Version 1.7.3 is not tagged in the Git repository. According to `gitHead` the [registry](https://registry.npmjs.org/socket.io-client), the tag should point to https://github.com/socketio/socket.io-client/commit/dc76b53805eeecc84fd5c07952baa842369e59fe, which is not on any branch, making it hard to fetch that commit otherwise.

**Comment by sschuberth** [comment]
Or should tag 1.7.3 point to this (rebased?) commit on the `1.7.x` branch instead? https://github.com/socketio/socket.io-client/commit/70f88881b845fcc7684eed85c4973d6b5cb6805d

**Comment by darrachequesne** [comment]
Done! https://github.com/socketio/socket.io-client/releases/tag/1.7.3
