### ISSUE TITLE
Socket status remains disconnected

### ISSUE THREAD

**Issue by divye11** [socketio/socket.io-client#1185]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
On checking this.socket object in console the status shows disconnected: true and connected: false

### Steps to reproduce (if the current behaviour is a bug)
Create a react native app with "react": "16.0.0", "react-native": "0.49.5", "socket.io-client": "^2.0.4" and try to write following

    import SocketIOClient from 'socket.io-client';
    this.socket = SocketIOClient('http://5aa3657a.ngrok.io/', { transports: ['websockets'] });
    console.log(this.socket);

    this.socket.onopen = () => {
      console.log('sending');
      this.socket.emit('senddata', { userid:1, userName: 'john'});
    }

### Expected behaviour
Server side should receive events rather a 400 status code is shown

### Setup
- OS: MacOS sierra 10.12.6
- browser: Chrome v63.0339
- socket.io version: "^2.0.4"

**Comment by darrachequesne** [comment]
For future readers, I think that's because `websocket` is misspelled.

Documentation: https://socket.io/docs/v3/client-initialization/#transports
