### ISSUE TITLE
Not receiving new data without page reload

### ISSUE THREAD

**Issue by arinhere** [socketio/socket.io-client#1186]
Hi,

In my application, I want to receives all new messages from server. But that only works, while the page is being reload. If there is any incoming messages, the event is not getting it. Here is my Angular code (I dont have access on the server code)

SocketService
==========

`var sock = io('xxx.xxx.xxx.xxxx:xxxx',{'multiplex': false});

            
            sock.on('connect', function(){
              sock.emit('register', {token: acctoken});                 
            }); 

            let observable = new Observable(observer => {
              sock.emit('new_messages');

              sock.on('new_messages', function (data) {
                console.log("running");
                observer.next(data);            
              });
            
              return () => {
                console.log("disconnected");
                sock.disconnect();
              };  
            });

          return observable;`

Then in my app.component.ts
====================

`this._socketService.socketConnect()
        .subscribe(response=>{
              console.log(response);
         });`

I am only receiving output, on page reload. I want to get notified, when there is a new message. Please suggest.

Thanks

**Comment by darrachequesne** [comment]
Hi! Did you fix your issue? (for future readers)
