### ISSUE TITLE
Socket client sending twice the connection event on Firefox

### ISSUE THREAD

**Issue by Ncifra** [socketio/socket.io-client#1187]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Steps to reproduce (if the current behaviour is a bug)
- Open a web socket server that serves also as an API server
- Request data from the API on the client with the "[request](https://github.com/request/request)" module 
- Render the pug template inside the "request" callback
- The socket client (only when refreshing or going from one page to the other inside the same client server) sends the polling request twice, and in the server it connects twice, one after the other.

### Expected behaviour
The connection event should be fired once per page navigation

### Setup
- OS: Windows
- browser: Firefox 58.0.1
- socket.io version: 2.0.4

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
On Chrome and Edge the problem doesn't show.

Edit:
It is as if we are on a page where the socket client is active, and also navigate to another page where it is active, it does the sending twice. 
For example:
I am in the login page, and this one is rendered without any requests to the API where also the Socket server resides. As soon as I am logged in and go to the home dashboard, the double polling happens (because this time I did also "request" data from the API). Also in every other page that I navigate, since all of these have the Javascript socket client code in them, the strange behaviour appears. If I render the inside pages without any pulling from the API, some times the strange behaviour continues (maybe some caching), and then it disappears.

Edit 2:

Disabling caching in the developer tools seems to make the bug appear less, and not always.

![socket bug on firefox](https://user-images.githubusercontent.com/16958850/35927082-12e5e4a8-0c2a-11e8-8603-20a747713f11.png)

**Comment by tony-gutierrez** [comment]
Anyone confirmed this?

**Comment by aprilmintacpineda** [comment]
Negative. I don't see this happening to my hobby project with React-Dom. https://github.com/aprilmintacpineda/chat-with-people-backend

The steps to reproduce is quite unclear because there are many ways to do that. Can you create a reproduce repository for this?

One possible reason is that, the script to connect to the server gets called more than once, and does not check if there is already an existing connection.

**Comment by Ncifra** [comment]
Sorry, didn't get an email about this reply.

I don't think this is related to code logic, since as I mentioned, (1) it shows only on Firefox and (2) it happens on "random" refreshes, or at least it seems so, while on the other hand, there isn't a lot of combinations on the backend for this randomness.

Also, the script is just part of the main layout file, and is only called once on initialization like so:

```
script(src='/components/socket.io-client/dist/socket.io.js')
                script.
                    var socket = io(constants.serverAPIUrl, {
                        query: {
                            token: readCookie('token')
                        }
                    });
                    socket.on('refresh', function () {
                        location.reload();
                    });
```

I also added a gif while refreshing the browser. You can notice that the polling number is different on the refreshes (I don't know why by default there are 3 polls, and there are additional abnormal ones, it's been some time since the last test so maybe those three may be something on my end). But after the third refreshs you may notice what I talk about, the default polls go first, even before the page has finished fully loading, and then there's the additional ones.

![ice_video_20180705-105202](https://user-images.githubusercontent.com/16958850/42313110-3afb25b6-8042-11e8-956c-083a249004fd.gif)

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
