### ISSUE TITLE
Shared websocket on node

### ISSUE THREAD

**Issue by mlucool** [socketio/socket.io-client#1190]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Using socket.io-client on in node does not allow for sharing a physical socket when adding new namespaces.

### Steps to reproduce (if the current behaviour is a bug)
```
const io = require('socket.io');
const ioc = require('socket.io-client');

let server = io(3000);

server.on('connection', (socket) => {
    console.log('connected default');
});

server.of('/bar').on('connection', (socket) => {
    console.log('connected bar');
});

ioc('http://localhost:3000', {secure: true}).on('connect', () => console.log('def connected'));
ioc('/bar').on('connect', () => console.log('bar connected')); // TypeError: Cannot read property 'host' of undefined
// Using below works because it is a unique socket
// ioc('http://localhost:3000/bar').on('connect', () => console.log('bar connected'));
```

### Expected behaviour
The above does not throw and works as it does on browsers as documented by [initialization-examples](https://socket.io/docs/client-api/#initialization-examples). This is likely due to the lack of a global.location.

### Setup
- OS: Linux
- browser: N/A
- socket.io version: 1.7.4

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://socket.io/docs/v3/client-initialization/
