### ISSUE TITLE
Firefox gives connection error yet triggers no events

### ISSUE THREAD

**Issue by tony-gutierrez** [socketio/socket.io-client#1199]
When using autoconnect false, and initiating a connection sometime after page load (in angular) we are seeing this console error:

`Firefox can’t establish a connection to the server at ws://localhost/socket.io/?EIO=3&transport=websocket.
vendor.bundle.js%20line%20821%20%3E%20eval:112:88
The connection to ws://localhost/socket.io/?EIO=3&transport=websocket was interrupted while the page was loading.`

Yet non of the socket events (error, connect_error) etc get fired. 

Same behavior in 2.03 and latest.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
