### ISSUE TITLE
socket.io can not hit multiple ip address 

### ISSUE THREAD

**Issue by connect2robiul** [socketio/socket.io-client#1200]
I run socketio on the raspberry pi.  

`
192.168.1.88 - - [12/Apr/2018 20:15:45] "GET /socket.io/?EIO=3&transport=polling&t=1523542543047-14 HTTP/1.1" 200 381 0.003272`
It can work in single ip. when another ip hit it can not load. 

My background server is python flask 

`(1917) wsgi starting up on http://0.0.0.0:4545`

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
