### ISSUE TITLE
restart socket.io server cause socket reconnect, but emit fail when connect event

### ISSUE THREAD

**Issue by zyf0330** [socketio/socket.io-client#1205]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
I use socket.io client in Chrome, socket.io server at nodejs.
I write `emit` action in `connect` and `reconnect` event.
When I restart server, client will reconnect, but `emit` action doesn't actually affect. If I `setTimeout` about 100ms, it does.

### Steps to reproduce (if the current behaviour is a bug)
This is my client code.
``` 
socket.on('connect', ()=>{
          setTimeout(onConnect, 100) // success
          setTimeout(onConnect, 1) // fail
          // onConnect() // fail
        })
function onConnect(){
socket.emit(...)
}
```

### Setup
- OS: Ubuntu 17.10
- browser: Chrome  66.0.3359.139 
- socket.io version: server 2.1.0, client 2.1.0

**Comment by ZODIAC3K** [comment]
Did you get the solution?
