### ISSUE TITLE
Library socket.io-client is not compatible with latest Angular 6

### ISSUE THREAD

**Issue by jameskentTX** [socketio/socket.io-client#1206]
### I want to:

* [x] report a *bug*  - solved, look last two lines for workaround

Library socket.io-client is not compatible with latest Angular 6. There is error at execution time:

ReferenceError: global is not defined at Object../node_modules/socket.io-client/node_modules/socket.io-parser/is-buffer.js (is-buffer.js:4)

Please read comment below to know more:
https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814

If you want to see this error for yourself, add to angular 6.0 app simple service like that below:

```js
import { Injectable } from 'angular/core';
import * as socketIo from 'socket.io-client';

@Injectable()
export class SocketService {
    private socket;

    constructor() {}

    public initSocket(): void {
        this.socket = socketIo();
    }
}
```

Error disappears when you remove initSocket function.

********************************************************************************
********************************************************************************

Ok, there is workaround in Angular 6 to work with socket.io-client.
Add (window as any).global = window; to polyfills.ts

**Comment by jessycormier** [comment]
@darrachequesne Would it be possible to have these changes added to a fork of the project until properly resolved?

**Comment by darrachequesne** [comment]
@jessycormier what do you mean by "a fork of the project"?

A first side-effect, it seems removing the global in https://github.com/darrachequesne/has-binary/pull/4 breaks some Electron apps: https://github.com/darrachequesne/has-binary/issues/5...

**Comment by realshaft** [comment]
Hi. Is here any progress? Any solution? Any recommended workaround?

**Comment by datumgeek** [comment]
@realshaft - the above work-around worked for me in Ionic 4 / Angular 6 web app

> Ok, there is workaround in Angular 6 to work with socket.io-client.
Add `(window as any).global = window;` to `polyfills.ts` (located in `src` folder)

**Comment by LabinotAvdiu** [comment]
@realshaft  thank you , it works in angular6 ;)

**Comment by iampeters** [comment]
hello @all,
please help me out.
so i created a service to handle my websocket connection and injected it a component.
the connection to the socket is fine as i get the <code> a user connected </code> in the server console.
but when i tried to send a message from the component nothing is sent.
here are my files:
socketService.ts
<pre>
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { Subject } from 'rxjs/Subject';
import * as io from 'socket.io-client';

@Injectable({
  providedIn: 'root'
})
export class SocketService {

  private url = 'http://localhost:3000';
  private socket = io(this.url);

  // send a message to socket
  message( msg ) {
    // send msg
    this.socket.emit('chat', msg);
  }

  chat(msg) {
    this.socket$.emit('chat', msg);

    // let observable
  }
}

</pre>

and the component file

<pre>
import { Component, OnInit } from '@angular/core';
import { SocketService } from '../../socket.service';

@Component({
  selector: 'app-socket',
  templateUrl: './socket.component.html',
  styleUrls: ['./socket.component.scss']
})
export class SocketComponent implements OnInit {

  constructor(
    private socket: SocketService
    ) { }

  ngOnInit() {
  }

  send() {
    const msg = 'hello';
    this.socket.message(msg);
  }

}
</pre>

here is my socket server connection. i used MVC
<pre>
const gameModel = require('../models/game')
const userModel = require('../models/users')
const wsModel = require('../models/socket')
const socket = require('socket.io')

module.exports = (server) => {

const io = socket(server);

// WebSocket handler
io.on('connection', (socket) => {
    console.log('a user connnected')
})

// get the chat msg
io.on('chat', (msg) => {
    // io.emit('res', json.stringify(msg))
    console.log(msg);
})

}

</pre>

**Comment by mjarkk** [comment]
here a quit hacky way to get it working but it works:  
Download [socket.io-client from a cdn](https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.1.1/socket.io.js) And place it in the `src` folder  

Inside the `main.ts` add these lines:
```
import * as io_ from './socket.io-client.js';
window['io'] = io_;
```

Inside `polyfills.ts` add:
```
(window as any).global = window;
```

Now you can use call `socket.io-client` using:
```
window['io']('localhost')
```

**Comment by pcnate** [comment]
mine started working by simply adding the following

> Inside `polyfills.ts` add:
> 
> ```
> (window as any).global = window;
> ```

**Comment by edgexie** [comment]
it help me, but why?

**Comment by sagarbhamre** [comment]
> @realshaft thank you , it works in angular6 ;)

It worked for me on Angular 7.x also, thanks.

**Comment by fromage9747** [comment]
`(window as any).global = window;`
This worked for me as well on Angular 7.

**Comment by mahmoud-ibn-samy** [comment]
same solution works with angular 8

**Comment by jusfeel** [comment]
God Can't believe I say this. Same solution @mjarkk provided. Works in angular10!

**Comment by mjarkk** [comment]
After 3 versions this hack stil works lmao, i bet it works the same in angular 11.  
But seeing this issue popup again i would no just advice to use native javascript [WebSockets](https://caniuse.com/?search=WebSocket) as they are supported in all majoir browsers.

**Comment by darrachequesne** [comment]
For future readers: this issue was fixed in `socket.io-client@2.2.0`, there is no reference to the `global` object anymore.

Related commits:
- https://github.com/socketio/socket.io-client/commit/eeafa44
- https://github.com/socketio/socket.io-parser/commit/b47efb270d959e7456d8d44b4f3c386a884542b8 (included in `engine.io-client@3.3.0`)
- https://github.com/socketio/engine.io-client/commit/99bcc622cb2cda123a2653c7d031e232ee6789e9 (included in `socket.io-parser@3.3.0`)

Besides: an example with Angular 11 was added here: https://github.com/socketio/socket.io/tree/master/examples/angular-todomvc

Thanks!
