### ISSUE TITLE
Trouble while connect different uris.

### ISSUE THREAD

**Issue by zotille** [socketio/socket.io-client#1209]
### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Current behaviour

Firstly, thanks for the package peovide really nice function on socket manage.  I am a wxApp developer -- https://developers.weixin.qq.com/miniprogram/introduction/index.html   

For one manager,  only one uri is supported. Sometimes, we need connect more than one uri at same time.    
I tried instant 2 managers, and this case, the managers often meet errors, eg. one of the two sockets can not emit. Or sometimes no error was reprted but neither of them have ping-pong.   
    
So, I wanna know if there is any way can better solve the problem

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
