### ISSUE TITLE
C# Client?

### ISSUE THREAD

**Issue by rustybrick** [socketio/socket.io-client#1210]
I'm having a hard time finding a C# client powerful enough to handle private channels and auth.  Any recommendations?  I am needing this to interop with a serial device (yes, I know).  Merging the old and the new.

**Comment by lst94** [comment]
Have you found the c# client? I'm using one,but I have encountered one problem.So do you hava any suggestions?

**Comment by darrachequesne** [comment]
For future readers:

Please check https://github.com/doghappy/socket.io-client-csharp
