### ISSUE TITLE
websocketmoudle.close got 1 arguments expected 3

### ISSUE THREAD

**Issue by sendroid-laonan** [socketio/socket.io-client#1211]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
when i trigger this.socket.disconnect();
Report error：**websocketmoudle.close got 1 arguments expected 3**

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Expected behaviour
No mistake in closing success

### Setup
- OS: Android7.0
- browser: react-native
- socket.io version: ^2.1.0

**Comment by xuho** [comment]
Same issue with you, any idea?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
