### ISSUE TITLE
Socket.io-client

### ISSUE THREAD

**Issue by cdang1234** [socketio/socket.io-client#1216]
It seems that socket.io-client isn't supported on android devices. Would anyone have any recommendations for other socketio.io libraries that work for react-native android devices? Or are there any workarounds to get socket.io-client to be compatible with android?

**Comment by darrachequesne** [comment]
Hi! Did you try https://github.com/socketio/socket.io-client-java?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
