### ISSUE TITLE
Constant 400s from same Opera client

### ISSUE THREAD

**Issue by franza** [socketio/socket.io-client#1217]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Currently we see a lot of repeating disconnects and 400s from clients with Opera 53 on Windows 10. Since we are adding unique hash to the handshake payload we can always tell that most of requests come from the same user.

The logic on client side is to send `connected` event with some user data right after user is connected.

For socket.io's HTTP server we see a lot of 400s for the same user with Opera 53. In messages level we observe that `connected` event is sent properly, and in almost 10 seconds server logs the `disconnect` event.

This is repeating constantly for the past several days without any breaks for lunch and sleep.

Since it's hard to reproduce on demand so am are missing the body of 400 response. I am currently working on logging the body, so any advices on that will be appreciated.

### Expected behaviour
No 400s and repeating disconnects.

### Setup
Mostly we observe it on Opera 53, Windows 10. Sometimes in Android browsers.

- socket.io version: ^2.1.0
- socket.io-client: 2.0.4

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
