### ISSUE TITLE
extraHeaders not working in client when using polling

### ISSUE THREAD

**Issue by beneuto** [socketio/socket.io-client#1218]
* [x] report a *bug*

My understanding is that custom headers should be able to be attached to polling calls but as per my example below, this does not seem to work.   My application is on AngularJS with socket.io-client v2.1.1.

### CLIENT CODE:

                  var token = sessionStorage.getItem( 'adal.access.token.key' + appId),
                      socket = io.connect(host,
                         {
                              forceJSONP: true,  // Required for CORS
                              transports: ['polling'],
                              transportOptions: {
                                   polling: {
                                          extraHeaders: {
                                                'Authorization': 'Bearer ' + token
                                                }
                                          }
                                    },
                              reconnectionDelay: 10000,
                              path: '/socket.io/ws/iothub',
                              secure: true             
                         });  

### FIDDLER

	GET /socket.io/ws/iothub/?EIO=3&transport=polling&j=0&t=MHxxxxv&b64=1 HTTP/1.1
	Host: myapi.azurewebsites.net
	Connection: keep-alive
	Pragma: no-cache
	Cache-Control: no-cache
	User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
	Accept: */*
	Referer: https://myapp.azurewebsites.net/release/
	Accept-Encoding: gzip, deflate, sdch, br
	Accept-Language: en-AU,en-GB;q=0.8,en-US;q=0.6,en;q=0.4
	Cookie: Nonce=9X9xrdoo++HSPsdZFuKBOetcetc

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.

Documentation: https://socket.io/docs/v3/client-initialization/#extraHeaders
