### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by razzorre** [socketio/socket.io-client#1220]
While using socket.io.js I am getting this error in the browser console.
Please help

**Comment by jaredharris** [comment]
There is a closed issue where people had the same issue.

https://github.com/socketio/socket.io-client/issues/839

Although it doesn't help me since I install the library using npm

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
