### ISSUE TITLE
development is not defined

### ISSUE THREAD

**Issue by santhoshRaju9122** [socketio/socket.io-client#1221]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
unable to load the app, due to development is not defined ReferenceError

### Steps to reproduce (if the current behaviour is a bug)
Upgraded the socket.io-client to version 2.1.1 and I started getting this issue.

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS:
- browser:
- socket.io version: 2.1.1

**Comment by guidolodetti** [comment]
I could fix all my errors by instantiating the socket after application startup:

```javascript
import SocketIOClient from 'socket.io-client'

let socket

export function initSocket() {
  if (!socket) {
    socket = SocketIOClient(SOCKET_URL)
  }
}

// ...in my React Component class:
componentDidMount() {
  initSocket()
}
```

**Comment by darrachequesne** [comment]
For future readers: there is no reference to `development` in the Socket.IO codebase, it must surely come from another dependency.
