### ISSUE TITLE
ReactNative Android takes main thread when stream is used >5 times/second

### ISSUE THREAD

**Issue by newah** [socketio/socket.io-client#1223]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:
Have a stream that fires many times/second.

* [x] report a *bug*

### Current behaviour
Works fine with iOS. 
On Android it gives warning "Setting a timer for a long period of time, i.e. multiple minutes" - in reality from what I've read, setTimeout isn't handled well in RN Android and I think creating/clearing so many timeouts simply floods the thread.

The problem seems to be resetting clreaing/setting timeout for heartbeat every time we receive an event.

### Steps to reproduce (if the current behaviour is a bug)
If we flood this example with events, the app responds extremely slowly while receiving stream of events https://github.com/vinnyoodles/react-native-socket-io-example .

I'm not sure I can share our stream link publicly with which the lagging is visible in provided example. But if this problem appears severe enough, we can try to share it privately.

### Expected behaviour
Receiving stream of events without lagging the whole thread.

### Setup
- OS: Android (RN 0.55.4, React 16.4.0)
- socket.io version: 2.1.1

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
I've seen comments about using AlarmManager on Android for correct timeouts handling.

Has anyone else experienced such a problem? Is there a better solution? 

Probably using socket.io natively would solve such problems, but there's no supported RN wrapper.

**Comment by darrachequesne** [comment]
Did you try with various values of `pingInterval` / `pingTimeout` ? Any effect?

It seems to be a recurring problem with React Native:

- https://github.com/facebook/react-native/issues/9030
- https://github.com/facebook/react-native/issues/4470

Not sure how we could improve that..

**Comment by newah** [comment]
In the end we simply filtered the stream to send events at most every second and this solved the problem.

Release build was working better (naturally)
Smaller ping interval/timeout didn't seem to have obvious effect.

Also tried https://github.com/ocetnik/react-native-background-timer which tries to use AlarmManager rather than RN defined timeouts - didn't seem to have any effect.

Have you tested client performance with a high frequency data stream yourself?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
