### ISSUE TITLE
always disconnected

### ISSUE THREAD

**Issue by bamaarintoko** [socketio/socket.io-client#1227]
cant connect server, always disconnected on react native

**Comment by maykl4iv** [comment]
Do you guys find any solution?
I can not connect to the server. Do not have any error. Any idea how I can get some logs, or maybe connect to server?

**Comment by darrachequesne** [comment]
For future readers, please check https://socket.io/docs/v3/troubleshooting-connection-issues/

See also: https://github.com/socketio/socket.io/tree/master/examples/react-native
