### ISSUE TITLE
fire disconnect event correctly 

### ISSUE THREAD

**Issue by skyitachi** [socketio/socket.io-client#1229]
### You want to:

* [x] report a *bug*

### Current behaviour

'/' namespace call `socket.disconnect` can not disconnect client which connects to custom namespace
```
// server
io.use(async (socket, next) => {
    try {
      await auth(socket); // just sample code
    } catch (err) {
      next(err);
      socket.disconnect(); // when error happens, disconnect the socket is reasonable
    }
   
})
// client
const socket = io("/42");
socket.on("disconnect", () => {
// never called
});
```

### Expected behaviour
`disconnect` event can be fired, if we meet error in middleware then disconnect

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
