### ISSUE TITLE
if randomizationFactor === 0, that will not work!

### ISSUE THREAD

**Issue by hookex** [socketio/socket.io-client#1231]
### You want to:

* [x] report a *bug*

### Current behaviour

this.randomizationFactor(opts.randomizationFactor || 0.5);

### Expected behaviour

if (opts.randomizationFactor === undefined) {
    opts.randomizationFactor === 0.5
}

this.randomizationFactor(opts.randomizationFactor);

### Setup
- OS: OSX
- browser: chrome
- socket.io version: 2.1.1

**Comment by jamesst20** [comment]
This bug is still present as of latest.

The docs says 

```
0 <= randomizationFactor <= 1
```

But the code does `opts.randomizationFactor || 0.5` which makes 0 become 0.5

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by si458** [comment]
sorry to tag onto this @darrachequesne, but im having this exact issue 
if i set randomizationFactor to 0, its being ignore and reset back to 0.5?
my code is as follows
```
const server = "http://localhost:3000"
const mysocket = io(server, { randomizationFactor: 0, reconnectionDelay: 1000, reconnectionDelayMax: 1000 });
```
mysocket output is as follows
```
<ref *1> Socket {
  receiveBuffer: [],
  sendBuffer: [],
  ids: 0,
  acks: {},
  flags: {},
  io: Manager {
    nsps: { '/': [Circular *1] },
    subs: [
      [Function: subDestroy],
      [Function: subDestroy],
      [Function: subDestroy]
    ],
    opts: {
      randomizationFactor: 0,
      reconnectionDelay: 1000,
      reconnectionDelayMax: 1000,
      path: '/socket.io',
      hostname: 'localhost',
      secure: false,
      port: '3000'
    },
    _reconnection: true,
    _reconnectionAttempts: Infinity,
    _reconnectionDelay: 1000,
    _reconnectionDelayMax: 1000,
    _randomizationFactor: 0.5,
    backoff: Backoff { ms: 1000, max: 1000, factor: 2, jitter: 0.5, attempts: 0 },
    _timeout: 20000,
    _readyState: 'opening',
    uri: 'http://localhost:3000',
    encoder: Encoder {},
    decoder: Decoder {},
    _autoConnect: true,
    engine: Socket {
      secure: false,
      hostname: 'localhost',
      port: '3000',
      transports: [Array],
      readyState: 'opening',
      writeBuffer: [],
      prevBufferLen: 0,
      opts: [Object],
      id: null,
      upgrades: null,
      pingInterval: null,
      pingTimeout: null,
      pingTimeoutTimer: null,
      transport: [XHR],
      _callbacks: [Object]
    },
    skipReconnect: false,
    _callbacks: {
      '$open': [Array],
      '$packet': [Array],
      '$error': [Array],
      '$close': [Array]
    }
  },
  nsp: '/',
  connected: false,
  disconnected: true,
  subs: [
    [Function: subDestroy],
    [Function: subDestroy],
    [Function: subDestroy],
    [Function: subDestroy]
  ]
}
```

**Comment by si458** [comment]
i think i found the issue
https://github.com/socketio/socket.io-client/blob/7326bd50dfdd0329efe47cf686a460040284767a/lib/manager.ts#L365
whats happening is when you set the value to 0, Javascript is deciding 0 is FALSE so revering back to 0.5
proof if you set value to 0.1 that works fine but 0 doesnt work

**Comment by si458** [comment]
Also setting `reconnectionDelayMax` and `reconnectionDelay` to 0 both also revert to the default values

**Comment by si458** [comment]
have submitted patch #1483
