### ISSUE TITLE
`Uint8Array` throws errors of undefined under IE8

### ISSUE THREAD

**Issue by aleen42** [socketio/socket.io-client#1234]
### You want to:

* [x] report a *bug*

### Current behaviour

*What is actually happening?*

Since `socket.io-client@1.4.5` upgraded `base64-arraybuffer` to `1.0.5` during the commit https://github.com/socketio/socket.io-client/commit/e97f9048a8e533faa2ad32309c7a343361dce066, there have been an error thrown when using IE8 as `base64-arraybuffer` as it directly called `Uint8Array` which has not been defined under IE8 (https://github.com/niklasvh/base64-arraybuffer/commit/1616895ea14ed71f6e629501215512aa97f3b9c3).

### Steps to reproduce (if the current behaviour is a bug)

Just import `socket.io-client@1.4.5+` under IE8

### Expected behaviour

*What is expected?*

Solving the script error

### Setup
- OS: Windows NT 10.0
- browser: MSIE 8.0
- socket.io version: 1.4.5

**Comment by aleen42** [comment]
Any progress?

**Comment by lwr** [comment]
seems duplicated with #979

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/engine.io-parser/commit/11e956399cefc16442b6d60c7fc03746eb4b8e77 and released in [2.3.1](https://github.com/socketio/socket.io-client/releases/tag/2.3.1).
