### ISSUE TITLE
net::ERR_INTERNET_DISCONNECTED

### ISSUE THREAD

**Issue by luisAzcuaga** [socketio/socket.io-client#1236]
I'm currently working on an app that I managed to store the needed response from the server, altho, whenever I turn off wifi (or disconnect from the current WiFi network) I get this annoying `net::ERR_INTERNET_DISCONNECTED`. I know It's obious It's trying to connect to the server, but how to I set the socket to ignore that fact?

I'm using Ionic 3.20 and this cordova plugin socket.io-client.

**Comment by BigEEE** [comment]
just use cordova events for `online` and `offline`, and stop connecting when the device is offline

**Comment by darrachequesne** [comment]
For future readers: `ERR_INTERNET_DISCONNECTED` errors are emitted by the browser itself, and there is unfortunately nothing that we can do to silence them.

Added in the documentation here: https://socket.io/docs/v3/logging-and-debugging/#Error-logs-in-the-browser-console
