### ISSUE TITLE
Channels not private..

### ISSUE THREAD

**Issue by acegilz** [socketio/socket.io-client#1238]
I want to make a uni-direccional **private** channel from where server can communicate with the individual clients, each client is subscribing to a specific channel to get updates of sensible information from the server (eg balance).

The issue with this approach is that anyone on the namespace can see them. Although the client is not directly subscribing to that channel, anyone can see all the messages / channels from the Socket  / Resources on safari for example.

**Backend:**

```javascript
var io = require('socket.io').listen(process.env.PORT || 3001);

var redis = require('redis').createClient();
redis.subscribe('balance');

io.on('connection', function(socket) {

	console.log('connected socket')

	socket.on('disconnect', function(){
	 console.log('client disconnected')
	 socket.disconnect();
	});
	
});


redis.on('message', function(channel, message){

	//I get the info from a redis subscription
	data = {balance: info.balance, locked: info.locked}
	let room = 'balance_'+info.uid;
	io.emit(room, data);
}
```

**Frontend:**

```javascript
import * as io from 'socket.io-client';

export class SocketioService {

   getBalance(uid) {
     
    let observable = new Observable(observer => {
      this.socket = io.connect(this.url, {secure: true});

      let room = 'balance_'+uid;

      this.socket.on(room, (data) => {

        var datax = JSON.stringify(data);
        observer.next(datax);   
      });

      return () => {
        this.socket.disconnect();
      };

    });
    return observable;
  }
}
```

<img width="740" alt="screenshot 2018-10-08 02 00 20" src="https://user-images.githubusercontent.com/4284362/46589138-597fee80-ca9e-11e8-866a-eacc3067a17e.png">

**Comment by cetindogu** [comment]
i think you need to you 
"io.in(room).emit(room, data);" instead of "io.emit(room, data);"

**Comment by acegilz** [comment]
> i think you need to you
> "io.in(room).emit(room, data);" instead of "io.emit(room, data);"

That was the problem..
Thanks @cetindogu !
