### ISSUE TITLE
Custom err loging ? Disable err log ?

### ISSUE THREAD

**Issue by izchie** [socketio/socket.io-client#1239]
Can I disable err loging or change it to something else ?
for example "net::ERR_CONNECTION_REFUSED" to "Error : can't establish io"

**Comment by darrachequesne** [comment]
For future readers: `ERR_CONNECTION_REFUSED` errors are emitted by the browser itself, and there is unfortunately nothing that we can do to silence them.

Added in the documentation here: https://socket.io/docs/v3/logging-and-debugging/#Error-logs-in-the-browser-console
