### ISSUE TITLE
Non-English Character Problem

### ISSUE THREAD

**Issue by cetindogu** [socketio/socket.io-client#1240]
when i broadcast "çetin doğu" i see the response below. what i need to do? HELP PLZ

![image](https://user-images.githubusercontent.com/7325611/46853499-f330fe00-ce06-11e8-9573-550c53650df5.png)

**Comment by cetindogu** [comment]
> Transform the data on the server side to base64 or to a unit8 array
> And on the client side transform it back to a string

is it the BEST PRACTICE?

**Comment by darrachequesne** [comment]
For future readers:

I was not able to reproduce the issue, all unicode characters should be supported by default. Please reopen if needed.
