### ISSUE TITLE
How to use middleware in socket.io-client

### ISSUE THREAD

**Issue by JaLe29** [socketio/socket.io-client#1244]
How can I print every payload in outgoing/ingoing requests through socket.io-client?

I don't want to use any third party library, it is possible? And how?

I didn't find any examples of this.

I am using socket.io-client 

```
import io from 'socket.io-client'
const socket = io('http://localhost:4200')
```

**Comment by darrachequesne** [comment]
For future readers, catch-all listeners were added in Socket.IO v3:

```js
socket.onAny((eventName, ...args) => {
  // ...
});
```


Documentation: https://socket.io/docs/v3/listening-to-events/#Catch-all-listeners

**Comment by RixInGithub** [comment]
> For future readers, catch-all listeners were added in Socket.IO v3:
> 
> ```js
> socket.onAny((eventName, ...args) => {
>   // ...
> });
> ```
> 
> Documentation: https://socket.io/docs/v3/listening-to-events/#Catch-all-listeners

What if I'm using lower versions than v3? I'm using v2 due to an outdated server Socket.IO version.

**Comment by darrachequesne** [comment]
@RixInGithub unfortunately, the feature was not backported to v2, which is in maintenance mode.
