### ISSUE TITLE
HEAD request from socket.io-client javascript

### ISSUE THREAD

**Issue by fcbflying** [socketio/socket.io-client#1247]
Sometimes the nginx server receives a 'HEAD' request like this:
"HEAD /socket.io/?EIO=3&transport=polling&j=6&t=MS6bMKe&b64=1&sid=1f9d8476-d5e7-4770-9fec-8dcebb40f2d1 HTTP/1.1"

But the server side doesn't handle this method of request, so error happens when the sever receives this HEAD request.
I want to know, if it is a right way to send a HEAD request from socket.io-client js side, and when it may happen?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
