### ISSUE TITLE
i cant set extraheaders help please!

### ISSUE THREAD

**Issue by fakirpic** [socketio/socket.io-client#1248]
i am using plain nodejs script it works! but while using in a nwjs app it doesnt work! it thinks is a browser

[https://stackoverflow.com/questions/53440246/extraheaders-doesnt-work-in-socket-io-client](https://stackoverflow.com/questions/53440246/extraheaders-doesnt-work-in-socket-io-client)

**Comment by ayozebarrera** [comment]
Hi

I was using version `2.1.1`and it was working. 
Yesterday I updated the package and suddenly, extraHeaders didn't work anymore!

Is this a bug? or is this feature deleted on newer versions?

Thanks!

**Comment by darrachequesne** [comment]
For future readers, please see the documentation here: https://socket.io/docs/v3/client-initialization/#extraHeaders
