### ISSUE TITLE
Namespace does not work in node.js client app

### ISSUE THREAD

**Issue by akontsevich** [socketio/socket.io-client#1249]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Namespace on web page client work fine for me:

    // Browser side JS: processed by browserify
    var io = require('socket.io-client')('/namespace');
    io.emit("message", data);

Server receives connect and the message without any problem. However if I try to make client app with node.js name space does not work. Code is following:
# test.js

    var io = require('socket.io-client');
    var socket = io.connect('http://localhost:3000', {
        reconnect: true,
        path: '/namespace'
    });
    
    // Add a connect listener
    socket.on('connect', function(socket) {
        console.log('Test connected!');
    });
    
    socket.emit('message', data);

In this case running `node test.js` client never connects to the server and can't emit any message. On server side console I see following output:

```GET /namespace/?EIO=3&transport=polling&t=MT0IoBp&b64=1 404 22.327 ms - 1423```

Any ideas? Bug or need to setup namespace in a different way?

### Setup
- OS: Linux
- socket.io-client version: 2.1.1

**Comment by akontsevich** [comment]
Changed node.js client code to 

    var socket = io.connect('http://localhost:3000/namespace', {
        reconnect: true
    });

works fine!

**Comment by darrachequesne** [comment]
For future readers: the documentation has been updated to make the difference between the [path](https://socket.io/docs/v3/client-initialization/#path) and the [namespace](https://socket.io/docs/v3/client-initialization/#Custom-namespace) clearer.

```js
const socket = io("https://example.com/order", {
  path: "/my-custom-path/"
});
```

- the Socket instance is attached to the “order” Namespace
- the HTTP requests will look like: `GET https://example.com/my-custom-path/?EIO=4&transport=polling&t=ML4jUwU`
