### ISSUE TITLE
Initial connection is very slow in React Native

### ISSUE THREAD

**Issue by saeho** [socketio/socket.io-client#1256]
I noticed that in production environment, the react native app takes very long time to connect to socket.io upon opening the app first time. Afterwards, the connection seems "better".

Is this something anyone else has noticed?

**Comment by darrachequesne** [comment]
@saeho did you find a solution?

**Comment by saeho** [comment]
No, but after a lot of research, I learnt that it wasn't socket.io. It's most likely an Android + production only issue. Seems to happen only in old devices, and it seems Javascript code is somehow locking up the app despite nothing heavy going on.

I'm still searching for the fix.

**Comment by doougui** [comment]
Did you find a solution? I'm having the same issue.

**Comment by saeho** [comment]
Yeah, there could be a lot of reasons though. So it's too hard to pinpoint to anything.

For me, my app has grown in complexity over time and I just didn't do a good job noticing bad code (on my part). Once I used best practices and used socket.io as flawlessly as I can, everything became fine.

**Comment by doougui** [comment]
I solved the issue. Thank you for answering.

**Comment by TwinsOd** [comment]
How did you solve the issue?
