### ISSUE TITLE
mine started working by simply adding the following

### ISSUE THREAD

**Issue by thiagomoraesn13** [socketio/socket.io-client#1257]
mine started working by simply adding the following

> Inside `polyfills.ts` add:
> 
> ```
> (window as any).global = window;
> ```

angular 6.1.0
socket.io-client 2.1.1

_Originally posted by @pcnate in https://github.com/socketio/socket.io-client/issues/1206#issuecomment-433508682_

**Comment by thiagomoraesn13** [comment]
It work with me...

**Comment by pcnate** [comment]
why is this a new issue?

**Comment by darrachequesne** [comment]
Please see my answer [here](https://github.com/socketio/socket.io-client/issues/1206#issuecomment-747401501).
