### ISSUE TITLE
Unable to connect on React-Native (only in Debug Mode)

### ISSUE THREAD

**Issue by jr-k** [socketio/socket.io-client#1259]
### You want to:
 * [x]  report a _bug_
 * [ ]  request a _feature_
 
 ### Current behaviour
 I can't connect via socket io to my server, it times out.
 
 ### Steps to reproduce (if the current behaviour is a bug)
 In react-native:
 
 ```js
 import io from 'socket.io-client';
 
 
 const BACKEND = 'my socketio server url'
 
 const sock = io(BACKEND, { transports: ['websocket'], forceNew: true });
 sock.on('connected', () = {
   debugger;
 })
 ```
 
 The debug logs look like:
 
There is nothing only a timeout triggered
 
 ### Expected behaviour
 I expect to be able to connect to my socketio server, the same way I am able to in a web browser.
 
 ### Setup
 * OS: Android 8.0
 * browser: React-native
 * socket.io version: 2.1.1 (but tried differents verisons with same result)

**Comment by jr-k** [comment]
oops duplicate of https://github.com/socketio/socket.io-client/issues/1245

**Comment by jr-k** [comment]
I'm reopening this issue, this is slightly different.

I tried to install socket io on a fresh react-native installation 0.57.8 and I'm facing this issue again.

**Comment by anooj1483** [comment]
React Native: 0.57.8
React: 16.6.3
socket.io-client: 2.0.4

This worked for me. Also need to change the socketio js version in server side to 2.0.4

**Comment by mostafiz93** [comment]
Works well when debug mode is on, but doesn't work when Debug mode is turned off or apk is built with release mode.

**Comment by Reardonp** [comment]
Same issue as everyone else. Works perfectly if debugging. 
React Native App versions: 
    "react": "16.5.0",
    "react-native": "^0.58.4",
    "socket.io-client": "^2.1.1"

Server Version: 
"socket.io": "2.0.4"

**Comment by mostafiz93** [comment]
`socket.io-client: 2.0.4` worked for me.

**Comment by ningacoding** [comment]
2.0.4 works, thank you alot @mostafiz93  :+1:

**Comment by ningacoding** [comment]
I'm getting error on ussing 2.0.4 + ReactNative

![image](https://user-images.githubusercontent.com/17342546/53602981-e58dd200-3b75-11e9-8f22-e83921a1a1bf.png)

**Comment by ningacoding** [comment]
FIXED IT for me when i was adding host:port like next in debug mode:

const socket = io("**//domain.com:port**", opts); // this works only in debug mode

didn't worked in NO debug mode, i had to add the protocol:

const socket = io("**http://domain.com:port**", opts);

**Comment by mostafiz93** [comment]
@ningacoding are you sue it works after adding the protocol? I'd added `http` but didn't work, then downgraded the version.

**Comment by rezareact** [comment]
I have the same issue
`react-native : 0.57.8`,
`socket-io-client : 2.2.0`
only works when debug is enabled

**Comment by jaredstevick** [comment]
has anyone found a fix for this yet? i have tried several different versions of the package with no luck

**Comment by ningacoding** [comment]
there are many causes of this error/bug, mine was only one of many.

**Comment by diegolaciar** [comment]
try last version from github, like this, solved my issues with RN android:

```npm i socketio/engine.io-client#3.3.2 -S ```

Cheers

**Comment by autotrof** [comment]
> FIXED IT for me when i was adding host:port like next in debug mode:
> 
> const socket = io("**//domain.com:port**", opts); // this works only in debug mode
> 
> didn't worked in NO debug mode, i had to add the protocol:
> 
> const socket = io("**http://domain.com:port**", opts);

its works on socket.io 2.1.1 and react-native 0.59.8. love you @ningacoding 👍 👍

**Comment by Ramesh21071993** [comment]
Hi @autotrof,
I tried with react-native 0.59.8 and socket.io, but it can't connect in release build.
Am using ip and port to connect,
Can you please help me?

**Comment by ldh1428a** [comment]
Anyone not solve yet?
**in my case**
```
react-native : 0.61.5
socket.io-client: 2.3.0 (i try another version 2.1.1, 2.0.1, 2.1.0)
```

**Comment by ldh1428a** [comment]
I solved this problem change `console.dir()` to `console.log()`
`console.dir()` function is not support to release mode 😃😃

**Comment by berto6544** [comment]
try this on android it worked for me 

 <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
        android:usesCleartextTraffic="true" <-- add this

**Comment by dtembo98** [comment]
"react-native": "0.70.5",
"socket.io-client": "^4.6.1",

This how i setup my socket connection as per the docs

`import { io } from "socket.io-client"

const URL = "http://localhost:3030"
const socket = io(URL, { autoConnect: false })
socket.onAny((event, ...args) => {
  console.log("All event listener...", event, args)
})
export default socket
`
Only working in debug mode

**Comment by darrachequesne** [comment]
For future readers:

Please check our guide with React Native here: https://socket.io/how-to/use-with-react-native

Please reopen if needed.
