### ISSUE TITLE
Build library without the webpack junk code

### ISSUE THREAD

**Issue by Extarys** [socketio/socket.io-client#1261]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

The file overhead included because of webpack is a couple kb more, I need of save every bytes.

How can I build the client trimmed (not the slim version) ?
Or is it possible to provide such file?

Thanks

**Comment by darrachequesne** [comment]
Done!

Commit: https://github.com/socketio/socket.io-client/commit/0661564dc2005b95843ddb65621b7e89af702bc0
Release notes: https://github.com/socketio/socket.io-client/releases/tag/4.3.0
