### ISSUE TITLE
socket.io attempts reconnect after 401

### ISSUE THREAD

**Issue by oliverhausler** [socketio/socket.io-client#1263]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

- reconnectionAttempts: 3
- Client connects to the server which issues 401.

### Expected behaviour

RFCs require that the client does not retry in case of 401 or 403, as the error status is considered final. I would expect the reconnectionAttempts to be honored for connection problems, but not for 4xx.

### Seen:

4 connect attempts, all with the same request.

### Setup
- OS: any
- browser: any
- socket.io version: 2.2.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

N/A

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
