### ISSUE TITLE
connect_timeout: 20000

### ISSUE THREAD

**Issue by Ivorfason** [socketio/socket.io-client#1264]
### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Current behaviour

when I use socket.io-client, it went a problem like this:
connect_timeout: 20000
connect_error: timeout

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way (and by that we mean **the only way**) to get a quick answer is to provide a failing test case by forking the following [fiddle](https://github.com/socketio/socket.io-fiddle).

### Expected behaviour

connected

### Setup
- OS:
- browser:
- socket.io version:

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
`
const io = require('socket.io-client')

var options = {
  transports: ['websocket', 'xhr-polling']
}

const socket = io('ws://localhost:8888', options)

console.log('socket_id: ' + socket.id) // undefined

socket.on('connect', () => {
  console.log('connect: ' + socket.id) // 'G5p5...'
})

socket.on('connect_error', (error) => {
  console.log('connect_error: ' + error)
})

socket.on('connect_timeout', (timeout) => {
  console.log('connect_timeout: ' + timeout)
})

socket.on('error', (error) => {
  console.log('error: ' + error)
})
`

It works well on my html request:
`var ws = new window.WebSocket('ws://localhost:8888')
    ws.onopen = function () {
      console.log('connect...')
    }
    ws.onmessage = function (evt) {
      console.log('message...')
    }
    ws.onclose = function () {
      console.log('close...')
    }`

**Comment by elfelround** [comment]
nothing to do with this, but may i ask what authentication u using?
