### ISSUE TITLE
Having problem to receive Arabic data

### ISSUE THREAD

**Issue by amirzandi** [socketio/socket.io-client#1265]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way (and by that we mean **the only way**) to get a quick answer is to provide a failing test case by forking the following [fiddle](https://github.com/socketio/socket.io-fiddle).

### Expected behaviour

*What is expected?*

### Setup
- OS:
- browser:
- socket.io version:

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

@joshk @Rainmen-xia @reid @rauchg Please resolve the UTF-8 Problem in Android Component.

We need to change to base64 and then convert at client side.

Thanks.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
