### ISSUE TITLE
extraHeader return undefined !

### ISSUE THREAD

**Issue by mostafa6765** [socketio/socket.io-client#1270]
### You want to:

* [x] report a *bug*

### Current behaviour

extraheaeder return undefined

### Steps to reproduce (if the current behaviour is a bug)

* client 

```html 
var socket = io.connect('127.0.0.1:4000',{
        transports: ['websocket', 'polling', 'flashsocket'],
        //transports: ['websocket','polling'],


        transportOptions: {
          polling: {
            extraHeaders: {
              'x-clientid': 'abc'
            }
          }
        },
});
```
* server 
```js
const io = require('socket.io').listen(4000);

io.on('connection',(socket)=>{
  console.log(socket.handshake.headers['x-clientid']);
});
// return undefined
```

*What is expected?*

`abc`

### Setup
- OS: windows 10
- browser: mozilla firefox
- socket.io version: 2.2.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
N/A

**Comment by underfisk** [comment]
Websocket just allows a very limited based headers so you can't pass x-custom you'll have to pass something such as Authorization Bearer XXX
This might help you understand: https://security.stackexchange.com/questions/174349/why-cant-websockets-support-custom-headers
