### ISSUE TITLE
Include Client application domain cookie in request header of Socket connection

### ISSUE THREAD

**Issue by HegdeSach** [socketio/socket.io-client#1271]
In my application once the user is successfully authenticated, client side browser is set with proper cookie value (JWT Token).
How can I send that cookie as Request header during Socket Connection process so that server side code should be able to identify the sender of connection request.

Any configuration available in Socket IO so that browser picks the cookie available and include it in request header like below,
![image](https://user-images.githubusercontent.com/21358983/52657209-2652dd80-2f1e-11e9-86b2-24a7d4652d64.png)

**Comment by timalanfarrow** [comment]
@HegdeSach did you figure out what the issue was?

**Comment by darrachequesne** [comment]
@timalanfarrow could you please open an issue with all necessary details? Thanks.

If I understand correctly, the author was missing `credentials: true` on the client side.

Reference: https://socket.io/docs/v4/client-options/#withcredentials
