### ISSUE TITLE
Unexpected end of JSON input while parsing

### ISSUE THREAD

**Issue by rowe0x** [socketio/socket.io-client#1272]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
npm install --save socket.io@latest
*What is actually happening?*
```
npm ERR! Unexpected end of JSON input while parsing near '...537,"npm-signature":"'
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rowe/.npm/_logs/2019-02-16T05_40_43_392Z-debug.log
```
### Steps to reproduce (if the current behaviour is a bug)
npm install --save socket.io@latest
**Note**: the best way (and by that we mean **the only way**) to get a quick answer is to provide a failing test case by forking the following [fiddle](https://github.com/socketio/socket.io-fiddle).

### Expected behaviour

*What is expected?*

### Setup
- OS: macos
- browser:
- socket.io version:

**Comment by rowe0x** [comment]
use cnpm instead of npm, problem solved.

**Comment by darrachequesne** [comment]
It seems like the NPM installation failed. Did you try to remove the `node_modules` folder and run install again?
