### ISSUE TITLE
Proposal: refactor code

### ISSUE THREAD

**Issue by frank-dspeed** [socketio/socket.io-client#1273]
I Would love to refactor this to es6 and transpil it with rollup to produce iife cjs and esm builds i would even do the refactoring but i need to know if you will merge that as i don't want to do a fork and maintain that.

# Current state
- [x] Refactored to TS
- [ ] Need to Apply ES6 Patterns example no reexports no named exports when default is exported.

**Comment by darrachequesne** [comment]
@frank-dspeed that's a great idea! I'll be happy to merge your pull request :ok_hand:

**Comment by dj-fiorex** [comment]
@frank-dspeed do you refactor this repo? i need ASM build to work with angular 10

**Comment by frank-dspeed** [comment]
@dj-fiorex ASM? You mean ESM maybe and no you do not need it to work with angular but i will produce types that is probally what you mean.

**Comment by dj-fiorex** [comment]
Yes, sorry i mean ESM, because Angular 10 warns me that using CommonJS or AMD dependencies increase my build size

**Comment by frank-dspeed** [comment]
@dj-fiorex you can ignore that as false positiv that statement is in general wrong. but i will not waist my valueable time to imrpove that error message of them.

**Comment by darrachequesne** [comment]
@frank-dspeed hi! with the rewrite to TypeScript and the release of Socket.IO v3, is this issue still valid?

**Comment by frank-dspeed** [comment]
@darrachequesne yes it is but it is now near done i updated the list at the top of the issue we need a little bit of refactoring now i think i have even sarted doing that only need to find that will create a PR soon i like to test everything before i do it so that we do not jump around.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
