### ISSUE TITLE
Code Works in Browser but not in JS Node

### ISSUE THREAD

**Issue by kcontabil** [socketio/socket.io-client#1275]
The code is quite simple, however it runs perfectly in the browser but is not working via Node JS.

**What works normally in the browser:**
`<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js"></script>
<script>
    var socket = io('wss://pay.hotmart.com/',{transport:['websocket']});
    socket.on('connect', function(){
        console.log('connected');
        socket.emit('checkout-load', {
            urlCheckout:"https://pay.hotmart.com/R6078449E?checkoutMode=10&bid=1550675960048",
            callbackEvent:"checkoutLoaded",
            affiliationReference:[{amount:1,affiliationReference:"R6078449E"}]
        });
    });
    socket.on('checkoutLoaded', function(data){
        console.log('event received');
        console.log(data);
    });
</script>`

**What is not working via Node JS:**
 `#!/usr/bin/env nodejs
var socket = require('socket.io-client')('wss://pay.hotmart.com/',{transports: ['websocket']});
socket.on('connect', function(data){
    console.log('connected');
    socket.emit('checkout-load', {
        urlCheckout:"https://pay.hotmart.com/R6078449E?checkoutMode=10&bid=1550675960048",
        callbackEvent:"checkoutLoaded",
        affiliationReference:[{amount:1,affiliationReference:"R6078449E"}]
    });
});

socket.on("checkoutLoaded", function(data){
    console.log('event received');
    console.log(data);
});`

**Comment by hari19831** [comment]
I'm facing this same issue, any fix for this??
While connecting from client it is working but when connection made from server side I get transport error. Previously this worked fine .....
