### ISSUE TITLE
Unable to establish socket connection in react-native?

### ISSUE THREAD

**Issue by harleenarora** [socketio/socket.io-client#1276]
I have integrated socket.io-client latest version("2.2.0") with my React Native application. Using this version socket io connection is not establish.

How can I do this using this code, the code I have written is listed below::

```
import io from 'socket.io-client';
var URL;
var socket;
var user_id;

export const connectSocket = () => {
   if (this.user_id !== null) {
      this.socket = io.connect(this.URL, {
         query: 'user_id=' + this.user_id
      });
      this.socket.on('connect', () => {
         this.socketConnected = true;
      });
      this.socket.on('connect_error', (err) => {
         this.socket.disconnect();
         this.socketConnected = false;
      });
   }
}
```

Here my Express Server Version: "socket.io": "1.7.2"

**Comment by maxkomarychev** [comment]
@harleenarora we managed to get this working by using this comment: https://github.com/socketio/socket.io-client/issues/1193#issuecomment-393542923

- we have "transports" declared in options
- and we downgraded to 2.1.1

**Comment by harleenarora** [comment]
Is there need to same socket version react-native app and  Express Server?

**Comment by lionbur** [comment]
I tried with Expo SDK v34 and v35 (RN 0.59) and had to downgrade socket.io-client to 1.7.2 (`yarn add socket.io-client@1.7.2`) as other versions (2.1.1, 2.1.0, 2.2.0) did NOT work.

**Comment by darrachequesne** [comment]
For future readers:

Please find an example with React Native here: https://github.com/socketio/socket.io/tree/master/examples/react-native
