### ISSUE TITLE
There is no documentation for  socket.io.dev.js

### ISSUE THREAD

**Issue by devmi** [socketio/socket.io-client#1277]
### You want to:

* [x] report a *documentation bug*
* [ ] request a *feature*

### Current behaviour

There is no documentation on how to use the **socket.io.dev.js**

### Expected behaviour

One of the [documentation pages](https://github.com/socketio/socket.io-client/tree/master/docs) would describe how to use the **socket.io.dev.js** to debug it on the client side.

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
https://stackoverflow.com/questions/54821391/how-to-debug-within-the-unminified-socket-io-client-library-on-the-browser#

**Comment by darrachequesne** [comment]
Documentation added here: https://socket.io/docs/v3/client-installation/#Installation
