### ISSUE TITLE
emit during connection lost, REsends data randomly

### ISSUE THREAD

**Issue by ghost** [socketio/socket.io-client#1279]
Hey there, 
I am developing a chat app in nodeJS and ReactJS.

Server:
```
socket.on("new message", data => {
  console.log(data);
})
```

Client: 
```
const message = {content: "hello"}
socket.emit("new message", message);
```

However when the client has a **connection problem** and then gets back online, it **sometimes** **resends** the previous emit and sometimes it doesn't. Can anyone tell me why this is happening **randomly**?

**Comment by lst94** [comment]
Have you solved the problem?

**Comment by andredoering** [comment]
No I did not. I switched to native Websockets and ws (for node). Socket.io has a bad documentation and no support at all. So I am glad I got rid of it.

**Comment by lst94** [comment]
> No I did not. I switched to native Websockets and ws (for node). Socket.io has a bad documentation and no support at all. So I am glad I got rid of it.
I want use it in C# ,but I have encountered the problem,so I have no idea solving it.Do you have any suggestions?

**Comment by darrachequesne** [comment]
Documentation added here: https://socket.io/docs/v3/client-offline-behavior/#Buffered-events
