### ISSUE TITLE
Using emit throw error: Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by rico345100** [socketio/socket.io-client#1283]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*
Using emit throws error: Uncaught TypeError: Cannot read property 'apply' of undefined.

### Steps to reproduce (if the current behaviour is a bug)
First, import Socket.io-client and use:

```javascript
import io from 'socket.io-client';
const socket = io('http://localhost:3000');
```

Second, try emit:

```javascript
socket.emit(`${this.evPrefix}::sync_upload_settings`);
```

It throws this error:
```text
index.js:133 Uncaught TypeError: Cannot read property 'apply' of undefined
    at Socket.push../node_modules/component-emitter/index.js.Emitter.emit (index.js:133)
    at Socket.push../node_modules/socket.io-client/lib/socket.js.Socket.emit (socket.js:138)
    at Socket.push../node_modules/socket.io-client/lib/socket.js.Socket.onconnect (socket.js:335)
    at Socket.push../node_modules/socket.io-client/lib/socket.js.Socket.onpacket (socket.js:232)
    at Manager.<anonymous> (index.js:21)
    at Manager.push../node_modules/component-emitter/index.js.Emitter.emit (index.js:133)
    at Manager.push../node_modules/socket.io-client/lib/manager.js.Manager.ondecoded (manager.js:345)
    at Decoder.<anonymous> (index.js:21)
    at Decoder.push../node_modules/component-emitter/index.js.Emitter.emit (index.js:133)
    at Decoder.push../node_modules/socket.io-parser/index.js.Decoder.add (index.js:251)
```

It actually coming from here(source from socket.io.dev.js):

```javascript
Emitter.prototype.emit = function(event){
	this._callbacks = this._callbacks || {};
	var args = [].slice.call(arguments, 1)
		, callbacks = this._callbacks['$' + event];

	if (callbacks) {
		callbacks = callbacks.slice(0);
		for (var i = 0, len = callbacks.length; i < len; ++i) {
			callbacks[i].apply(this, args);    // ------> HERE!!!!
		}
	}

	return this;
};
```

### Expected behaviour

*What is expected?*
I want to send event to server, but it doesn't.

### Setup
- OS: macOS 10.13.1
- browser: Chrome 72.0.3626.121
- socket.io version: 2.2.0
- socket.io.client version: 2.2.0
- node version: 11.0.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
I used Webpack for bundling.

**Comment by johanelbg** [comment]
I'm experiencing the same issue as you.
Did you find a solution ?

**Comment by Ektoplasme** [comment]
Got this issue too, still no solution?

**Comment by Osmiogrzesznik** [comment]
For Anybody Searching for this error. 
I had similar problem.
It can be caused by providing variable as a second parameter in ```.on``` method that is undefined. Internal code of socket.io tries to call ```.apply``` method to pass arguments into your event handler. If function registered is not existing and therefore ```undefined```, this error occurs since undefined values have no such property .  It often may be the case of the typo in the name of the function 

i.e

```
socket.on('next_player', this.nextplayer)
```
should be :
```
socket.on('next_player', this.next_player)
```

make sure that 
```
${this.evPrefix}::sync_upload_settings
```
exists in the moment when the event happens

**Comment by matiaslopezd** [comment]
This happens to me with `disconnect(true)` and event `disconnect` trigger error. I found that if you make a reference to `this`, on callback return this error. So to avoid them need to use the classic hack `const self = this;`.

If you see `Emitter.prototype.emit = function(event)` is function, now arrow function, that provoke the property `apply` throw error because not find the reference `this.yourFunction`.

```js
// Bad
socket.on('my-event', this.myFunction);

// Good
const self = this;
socket.on('my-event', self.myFunction);

// Also caution with this
socket.on('disconnect'); // Not pass function
```

Also, this is a bug. I believe need trigger an error when the callback is not set, and change `.emit` to arrow function.

**Comment by darrachequesne** [comment]
@matiaslopezd I am not able to reproduce the problem you are describing:

```js
const io = require("socket.io-client");

class Listener {
  constructor(socket) {
    socket.on("connect", this.onconnect);
    socket.on("disconnect", this.ondisconnect);
  }
  onconnect() {
    console.log("connect");
  }
  ondisconnect() {
    console.log("disconnect");
  }
}

const socket = io("http://localhost:3000");
const listener = new Listener(socket);
```

The only way I could reproduce the initial problem was by using `on()` without a second argument:

```js
const Emitter = require("component-emitter");
const e = new Emitter();

e.on("test"); // TypeError: Cannot read property 'apply' of undefined
e.emit("test");
```

But I'm not sure we have something to fix here.

Note: it throws an error with Node.js EventEmitter: `TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received undefined`

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by WaylayOvercast** [comment]
I actually was stuck on this, although it make be for a different reason I had run into this issue trying to create my own form of "authentication" (if you can call it that.) - and I found my issue...although I don't understand it. see below.
![image](https://user-images.githubusercontent.com/86576382/162090531-ff1ce315-2deb-41f9-82a8-0c5f4ad94750.png)
So I was returning a listener for the servers response and checking in an if statement to see if the return of that function had the ".connected" attribute.... yes I know quite hacky but.. my problem came up later when I had tried to return "socket.on("allgood")" without the empty anon function.. basically returning socket.on without its second argument caused it for me... 


not sure this is helpful for anyone as if you use the library correctly it is very well put together and I definitely don't suggest doing what I did here lol
