### ISSUE TITLE
WebSocket Client handshake headers (Authorization)

### ISSUE THREAD

**Issue by supar** [socketio/socket.io-client#1286]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Current behaviour

According to the [documentation](https://socket.io/docs/client-api/#With-extraHeaders) websocket transport will not append header cause the WebSocket handshake does not honor custom headers. (For background see the [WebSocket protocol RFC](https://tools.ietf.org/html/rfc6455#section-4))

### Expected behaviour

It seems to me this is not exactly what RFC explains. Let's read item 12 in the section 4:

> The request MAY include any other header fields, for example,
        cookies [RFC6265] and/or authentication-related header fields
        such as the |Authorization| header field [RFC2616], which are
        processed according to documents that define them.

Please, add handshake headers overwrite support for websocket transport

### Setup
- OS:
- browser:
- socket.io version:

**Comment by SergeyCherman** [comment]
I'm encountering the same thing, would be happy to try to put together a PR for this if owners approve.

**Comment by Arshardh** [comment]
The limitation I see for using headers for auth is that javascript does not support custom headers for the websocket handshake. I haven't come across any material that mentions auth via headers in websockets is not recommended. In fact even the spec mentions:

> The request MAY include any other header fields, for example, cookies [RFC6265] and/or authentication-related header fields such as the |Authorization| header field [RFC2616], which are processed according to documents that define them.

**Comment by darrachequesne** [comment]
For future readers, please see https://stackoverflow.com/a/4361358

I'm afraid there is nothing we can at the Socket.IO level.

Slightly related: the `auth` option has been added in Socket.IO v3:

```js
// client
const socket = io({
  auth: {
    token: "abcd"
  }
});

// server
io.use((socket, next) => {
  const token = socket.handshake.auth.token;
  // check token, then
  next();
});
```

Documentation: https://socket.io/docs/v3/client-initialization/#auth
