### ISSUE TITLE
TypeError: io is not a function 

### ISSUE THREAD

**Issue by SwitchedToGitlab** [socketio/socket.io-client#1287]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

socket.io does not work, throws obtuse error message when trying to implement. Issue is most likely in documentation, code quality (code comments are helpful here, these are useless), poor answers in issue tracker. 

Basically a duplicate of #873, but that was never really answered to we get to do this all over again. 

### Steps to reproduce (if the current behaviour is a bug)

My code stub (I've tried all kinds of permutations of this):

const io = require('socket.io.slim.js');

var socket = io('http://localhost:9990'); // TIP: io() with no args does auto-discovery
socket.on('connect', function () { 
  socket.emit('ferret', 'tobi', 'woot', function (data) { console.log(data); // data will be 'tobi says woot' });
});

// error message:

2019-04-09 13:08:46.166650 [ERR] undefined:6 Exception: TypeError: io is not a function (near: "var socket = io('http://localhost:9990'); // TIP: io() with no args does auto-discovery")

### Expected behaviour

It to work as shown in the example.

### Setup
- OS: debian 9
- browser: chrome v8 engine
- socket.io version: commit 9c1e73c752aec63f48b511330a506d037783d897

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

See issue #873 for a whole bunch of other people all asking the same question.

**Comment by kapi2289** [comment]
If you downloaded this as a file, you need to add `./` before the name and you don't need to add `.js` extension
```js
const io = require('./socket.io.slim');
```

**Comment by SwitchedToGitlab** [comment]
Tried that, same behavior.

**Comment by kapi2289** [comment]
Try using this `.js` file in a `<script>` tag
```html
<script src="/socket.io.slim.js"></script>
<script>
	var socket = io('http://localhost:9990');
</script>
```
OR
```js
require('./socket.io.slim');
var socket = io('http://localhost:9990');
```

**Comment by SwitchedToGitlab** [comment]
I am not launching this script via HTML. I've tried that exact block of code listed and got the exact same error message I gave to start with.

**Comment by kapi2289** [comment]
If you're using `npm` it would be better to install this lib using it
```bash
$ npm i socket.io-client
```
and then
```js
const io = require("socket.io-client");
```

**Comment by SwitchedToGitlab** [comment]
I am not using NPM. I am using the Chrome V8 engine - straight.

**Comment by kapi2289** [comment]
Is this for sure the client, not server script? I've tried to reproduce your code, I've downloaded `socket.io.slim.js` from https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.slim.js and the only error I got was missing `document` ('cause I didn't run this in a browser)
```js
> const io = require("./socket.io.slim");
> io("http://localhost:8888");
ReferenceError: document is not defined
```

**Comment by SwitchedToGitlab** [comment]
It's a client, as in it is connecting to a socket as a client.

**Comment by davidwitten** [comment]
I'm running into this same issue. Were you able to find a solution @SwitchedToGitlab?

**Comment by darrachequesne** [comment]
For future readers, please see the documentation here: https://socket.io/docs/v3/client-initialization/

**Comment by adiswordfish** [comment]
Has anybody found the solution?

**Comment by mmirann** [comment]
This causes an error `TypeError: io is not a function`
```js
const io = require("socket.io-client");
```
Solve it by using it like this:
```js
const { io } = require("socket.io-client");
```
or
```js
const io = require("socket.io-client").io;
```

**Comment by aliparsa** [comment]
same here by using npm -> TypeError: io is not a function
