### ISSUE TITLE
RegEx issue with parsing packets

### ISSUE THREAD

**Issue by alesmenzelsocialbakers** [socketio/socket.io-client#1289]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Packets are being cropped off by issue in used regex.

### Steps to reproduce (if the current behaviour is a bug)

Send this special character from the socket.io server back to socket.io-client.
The message will be cut of on the special character.
```js
`before${String.fromCharCode(8232)}after`.match(/.*/)[0]

// https://github.com/socketio/socket.io-client/blob/81089a2723770d5b32753485d1e5a160a72abab6/lib/parser.js#L210
var data = '5+{"text":"before\nafter"}'
data.match(/^([0-9]+)(\+)?(.*)/)[3]; // {"text":"before << invalid JSON

var data = `5+{"text":"before${String.fromCharCode(8232)}after"}`
data.match(/^([0-9]+)(\+)?(.*)/)[3]; // {"text":"before << invalid JSON
```
_(Note that i used template literal because github strips the special character from the text)_

**Here is a workaround:** 
```js
`before${String.fromCharCode(8232)}after`.match(/[^]*/)[0]
```

### Expected behaviour

The message is correctly parsed.

### Setup
- OS: Windows 10
- browser: Chrome 73
- socket.io-client version: 0.9.17 (cant upgrade this unfortunately)

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
This should fix the issue: fix: http://prntscr.com/nazjn9

**Comment by alesmenzelsocialbakers** [comment]
This also solves the issue of not matching new lines in the regex (e.g. if the json contains any \n the packet will be cut of on the first new line).
As the regex spec. declares -  **"(The decimal point) matches any single character except the newline character, by default."** (without the multiline /m flag)

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
