### ISSUE TITLE
Unrecognized WebSocket connection option(s) `agent`, `perMessageDeflate`, `pfx`, `key`, `passphrase`, `cert`, `ca`, `ciphers`, `rejectUnauthorized`. Did you mean to put these under `headers`?

### ISSUE THREAD

**Issue by JuAlexandre** [socketio/socket.io-client#1290]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

When I install `socket.io-client` on a blank React Native Expo project I have a yellow message with:
```
Unrecognized WebSocket connection option(s) `agent`, `perMessageDeflate`, `pfx`, `key`, `passphrase`, `cert`, `ca`, `ciphers`, `rejectUnauthorized`. Did you mean to put these under `headers`?
```

### Steps to reproduce (if the current behaviour is a bug)

`yarn add socket.io-client`

In App.js in the React Native project:
```javascript
import React from 'react';
import { YellowBox } from 'react-native';
import io from 'socket.io-client';

YellowBox.ignoreWarnings(['Remote debugger']);

import AppContainer from './config/routing';

export default class App extends React.Component {
    constructor(props) {
        super(props);
    }

    componentWillMount() {
        const socket = io('http://10.0.60.26:3000', {
            forceNew: true
        });
        socket.on('connect', () => console.log('Connection'));
    }

    render() {
        return <AppContainer />;
    }
}
```

**Comment by bogoslavskiy** [comment]
Same problem :(

**Comment by orhanoksuzz** [comment]
Debug mode solved my problem with this line of code
`import SocketIOClient from 'socket.io-client';
const socketURL = 'serveradress';
const socket = SocketIOClient(socketURL, { transports: ['websocket'], forceNew: true }); `

> 


of course, no warning message for now. I'll share here if I get an error in the following stages or if I get an error in release mode

  "dependencies": {
    "react": "16.8.3",
    "react-native": "^0.59.6",  
    "socket.io-client": "^2.2.0"
  },

**Comment by Luomusha** [comment]
+1

**Comment by evaleirasclapps** [comment]
+1

**Comment by nsafai** [comment]
+1

**Comment by Hakim-Bou** [comment]
+1

**Comment by wx962464** [comment]
+1

**Comment by maxgfr** [comment]
+1

**Comment by Vietvantue** [comment]
+1

**Comment by marcinczenko** [comment]
I am still getting this warning when using socket.io (2.2.0) on React-Native. I can silence the yellow box on the device screen with:

```javascript
import { YellowBox } from 'react-native'

YellowBox.ignoreWarnings([
  'Unrecognized WebSocket connection option(s) `agent`, `perMessageDeflate`, `pfx`, `key`, `passphrase`, `cert`, `ca`, `ciphers`, `rejectUnauthorized`. Did you mean to put these under `headers`?'
])
```

but I still get this annoying warning on the console...

**Comment by samuelgoldenbaum** [comment]
downgrade to "socket.io-client": "2.1.0" and all OK

**Comment by GrillAndChill** [comment]
+1

Didn't work after downgrading to 2.1.0 and 2.1.1

**Comment by cdiezmoran** [comment]
For me it worked when I downgraded to 2.1.1 I did:
`yarn add socket.io-client@2.1.1`
At first it didn't work because I was adding the `^` symbol before the version `socket.io-client@^2.1.1` which I believe accepts newer minor versions of the package.

**Comment by FrederickEngelhardt** [comment]
Still an issue.

**Comment by emin9422** [comment]
the downgrade to @2.2.0 didn't help   , still an issue

**Comment by Andrielson** [comment]
Still an issue @^2.3.0

**Comment by muhammadwafa** [comment]
Still and issue `v2.3.0`

**Comment by emclab** [comment]
@2.1.1 is OK. But 2.3.0 throws the warning message on RN 0.61.1

**Comment by ashadnasim52** [comment]
any solution till now

**Comment by jhoanborges** [comment]
Still an issue v2.3.0 with react-native

**Comment by canaanites** [comment]
Hey guys! We have fixed this issue by downgrading to **v2.1.1**

Make sure you completely remove the older version and clear the cache.

1. remove socket.io-client from package.json & better delete your package-lock/yarn.lock files.
2. delete your entire **node_modules** folder (start fresh)
3. npm install **socket.io-client@2.1.1** --save

Done! This should work with react-native & react-native-web!

**Comment by Jnlbr** [comment]
I have this same issue with `react-native: 0.61.4` but somehow the app is crashing, I don't know if it's happening because of the warning or if is another socket-related thing, but when I tried to connect to the socket the app closes.

**Comment by Jnlbr** [comment]
Does `socket.connect` crashes if the the socket is already connected?

**Comment by Jnlbr** [comment]
> Does `socket.open` crashes if the socket is already connected?

**Comment by ptboyer** [comment]
This warning is raised here by [`ReactNative/WebSocket.js:117`](https://github.com/facebook/react-native/blob/master/Libraries/WebSocket/WebSocket.js#L117) because EngineIO (used by SocketIO under the hood) will reference the exposed ReactNative WebSocket implementation via [`EngineIO/websocket.js:121`](https://github.com/socketio/engine.io-client/blob/master/lib/transports/websocket.js#L121) which is passed `opts` which contains the properties that the warning message mentions. Curiously enough, these added properties described by the EngineIO maintainers via comment are "SSL options for Node.js client".

By inserting something like the code below at [`EngineIO/websocket.js:114`](https://github.com/socketio/engine.io-client/blob/master/lib/transports/websocket.js#L114) to manipulate the `opts` given to the WebSocket constructor we remove all the extraneous keys in `opts` to successfully stop the warning from appearing in the first place ([`omit`](https://lodash.com/docs/4.17.15#omit) is imported from Lodash, can be reworked out).

```js
// lib/transports/websocket.js
...
if (this.isReactNative) {
  // prettier-ignore
  opts = omit(opts, ['agent', 'perMessageDeflate', 'pfx', 'key', 'passphrase', 'cert', 'ca', 'ciphers', 'rejectUnauthorized']);
}
...
```

If you're looking for a solution that doesn't involve simply muting the warning via `YellowBox.ignoreWarnings` then you could completely override the `doOpen` as defined  [`EngineIO/websocket.js:87`](https://github.com/socketio/engine.io-client/blob/master/lib/transports/websocket.js#L87) by adding something like this below, to the entry point of your ReactNative project, typically `index.js`.

```js
// index.js
...
+ import 'patches/EngineIOHeaderWarning';
...
```

```js
// patches/EngineIOHeaderWarning.js
const WS = require('engine.io-client/lib/transports/websocket');

var WebSocketImpl = WebSocket; // eslint-disable-line no-undef

WS.prototype.doOpen = function() {
  if (!this.check()) {
    // let probe timeout
    return;
  }

  var uri = this.uri();
  var protocols = this.protocols;
  var opts = {};

  if (this.extraHeaders) {
    opts.headers = this.extraHeaders;
  }
  if (this.localAddress) {
    opts.localAddress = this.localAddress;
  }

  try {
    this.ws = new WebSocketImpl(uri, protocols, opts);
  } catch (err) {
    return this.emit('error', err);
  }
};
```

Overall, if we create a pull request for EngineIO to exclude these extra `opts` that aren't needed when used in ReactNative via `this.isReactNative` then we could suppress this warning for all using the SocketIO Client in their ReactNative projects.

**Comment by jzambrano12** [comment]
> ### You want to:
> * [x]  report a _bug_
> * [ ]  request a _feature_
> 
> ### Current behaviour
> When I install `socket.io-client` on a blank React Native Expo project I have a yellow message with:
> 
> ```
> Unrecognized WebSocket connection option(s) `agent`, `perMessageDeflate`, `pfx`, `key`, `passphrase`, `cert`, `ca`, `ciphers`, `rejectUnauthorized`. Did you mean to put these under `headers`?
> ```
> 
> ### Steps to reproduce (if the current behaviour is a bug)
> `yarn add socket.io-client`
> 
> In App.js in the React Native project:
> 
> ```js
> import React from 'react';
> import { YellowBox } from 'react-native';
> import io from 'socket.io-client';
> 
> YellowBox.ignoreWarnings(['Remote debugger']);
> 
> import AppContainer from './config/routing';
> 
> export default class App extends React.Component {
>     constructor(props) {
>         super(props);
>     }
> 
>     componentWillMount() {
>         const socket = io('http://10.0.60.26:3000', {
>             forceNew: true
>         });
>         socket.on('connect', () => console.log('Connection'));
>     }
> 
>     render() {
>         return <AppContainer />;
>     }
> }
> ```

My Solution:

Just save the socket in a useState like this:

import io from 'socket.io-client';
// ...

const [socket] = useState(() => io('SERVER_URL'));

Problem solved.

**Comment by creditcoder** [comment]
In my case, v2.3 is ok when I connect to the local socket.io server.
But it occurs errors when I connect to the remote socket.io server.
The server source is the same.
So I downgrade the socket.io client version to 2.1.1, and it works fine.

**Comment by JamesMahy** [comment]
> This warning is raised here by [`ReactNative/WebSocket.js:117`](https://github.com/facebook/react-native/blob/master/Libraries/WebSocket/WebSocket.js#L117) because EngineIO (used by SocketIO under the hood) will reference the exposed ReactNative WebSocket implementation via [`EngineIO/websocket.js:121`](https://github.com/socketio/engine.io-client/blob/master/lib/transports/websocket.js#L121) which is passed `opts` which contains the properties that the warning message mentions. Curiously enough, these added properties described by the EngineIO maintainers via comment are "SSL options for Node.js client".
> 
> By inserting something like the code below at [`EngineIO/websocket.js:114`](https://github.com/socketio/engine.io-client/blob/master/lib/transports/websocket.js#L114) to manipulate the `opts` given to the WebSocket constructor we remove all the extraneous keys in `opts` to successfully stop the warning from appearing in the first place ([`omit`](https://lodash.com/docs/4.17.15#omit) is imported from Lodash, can be reworked out).
> 
> ```js
> // lib/transports/websocket.js
> ...
> if (this.isReactNative) {
>   // prettier-ignore
>   opts = omit(opts, ['agent', 'perMessageDeflate', 'pfx', 'key', 'passphrase', 'cert', 'ca', 'ciphers', 'rejectUnauthorized']);
> }
> ...
> ```
> 
> If you're looking for a solution that doesn't involve simply muting the warning via `YellowBox.ignoreWarnings` then you could completely override the `doOpen` as defined [`EngineIO/websocket.js:87`](https://github.com/socketio/engine.io-client/blob/master/lib/transports/websocket.js#L87) by adding something like this below, to the entry point of your ReactNative project, typically `index.js`.
> 
> ```js
> // index.js
> ...
> + import 'patches/EngineIOHeaderWarning';
> ...
> ```
> 
> ```js
> // patches/EngineIOHeaderWarning.js
> const WS = require('engine.io-client/lib/transports/websocket');
> 
> var WebSocketImpl = WebSocket; // eslint-disable-line no-undef
> 
> WS.prototype.doOpen = function() {
>   if (!this.check()) {
>     // let probe timeout
>     return;
>   }
> 
>   var uri = this.uri();
>   var protocols = this.protocols;
>   var opts = {};
> 
>   if (this.extraHeaders) {
>     opts.headers = this.extraHeaders;
>   }
>   if (this.localAddress) {
>     opts.localAddress = this.localAddress;
>   }
> 
>   try {
>     this.ws = new WebSocketImpl(uri, protocols, opts);
>   } catch (err) {
>     return this.emit('error', err);
>   }
> };
> ```
> 
> Overall, if we create a pull request for EngineIO to exclude these extra `opts` that aren't needed when used in ReactNative via `this.isReactNative` then we could suppress this warning for all using the SocketIO Client in their ReactNative projects.

After the try catch statement, I had to add

```
 if (this.ws.binaryType === undefined) {
    this.supportsBinary = false;
  }

  if (this.ws.supports && this.ws.supports.binary) {
    this.supportsBinary = true;
    this.ws.binaryType = 'nodebuffer';
  } else {
    this.ws.binaryType = 'arraybuffer';
  }

  this.addEventListeners();
```

Else it wouldn't connect

**Comment by ioness** [comment]
> downgrade to "socket.io-client": "2.1.0" and all OK

This worked for me.

**Comment by soullivaneuh** [comment]
If I well understand the issue, is this a related dependencies issue introduce in https://github.com/socketio/socket.io-client/commit/06e9a4ca2621176c30c352b2ba8b34fa42b8d0ba?

**Comment by soullivaneuh** [comment]
The downgrade to 2.1.1 works indeed, but we are stuck on a two years old releases.

Can @ptboyer be applied and release on the project?

**Comment by schumannd** [comment]
Does this warning affect the functionality of the package? Just setting it up and don't want to be held back by this. Happy to ignore if it has no other consequences

**Comment by ptboyer** [comment]
@schumannd This issue is purely about muting the error/warning message. Functionally, this warning is inconsequential. :)

**Comment by MrCheater** [comment]
+1

**Comment by BassemN** [comment]
I am very worried about if the socket.io library is still maintained or not because of no official reply about a fix or an upcoming update.

**Comment by rburson** [comment]
+1

**Comment by rasool707** [comment]
+1

**Comment by isthaison** [comment]
`    const _io = ioClient.connect(socketurl, { forceNode: true });
`
It's work

**Comment by BassemN** [comment]
@isthaison Also, it worked for me

**Comment by BassemN** [comment]
@isthaison It doesn't work for me

**Comment by marcorm** [comment]
@isthaison for me it works... but every other http request becomes very slow... I don't know how it's related to the workaround... but it is...

**Comment by dayaki** [comment]
> { forceNode: true }

Thank you. this work for me.

**Comment by BassemN** [comment]
This is the only solution that worked for me.

> > This warning is raised here by [`ReactNative/WebSocket.js:117`](https://github.com/facebook/react-native/blob/master/Libraries/WebSocket/WebSocket.js#L117) because EngineIO (used by SocketIO under the hood) will reference the exposed ReactNative WebSocket implementation via [`EngineIO/websocket.js:121`](https://github.com/socketio/engine.io-client/blob/master/lib/transports/websocket.js#L121) which is passed `opts` which contains the properties that the warning message mentions. Curiously enough, these added properties described by the EngineIO maintainers via comment are "SSL options for Node.js client".
> > By inserting something like the code below at [`EngineIO/websocket.js:114`](https://github.com/socketio/engine.io-client/blob/master/lib/transports/websocket.js#L114) to manipulate the `opts` given to the WebSocket constructor we remove all the extraneous keys in `opts` to successfully stop the warning from appearing in the first place ([`omit`](https://lodash.com/docs/4.17.15#omit) is imported from Lodash, can be reworked out).
> > ```js
> > // lib/transports/websocket.js
> > ...
> > if (this.isReactNative) {
> >   // prettier-ignore
> >   opts = omit(opts, ['agent', 'perMessageDeflate', 'pfx', 'key', 'passphrase', 'cert', 'ca', 'ciphers', 'rejectUnauthorized']);
> > }
> > ...
> > ```
> > 
> > 
> > If you're looking for a solution that doesn't involve simply muting the warning via `YellowBox.ignoreWarnings` then you could completely override the `doOpen` as defined [`EngineIO/websocket.js:87`](https://github.com/socketio/engine.io-client/blob/master/lib/transports/websocket.js#L87) by adding something like this below, to the entry point of your ReactNative project, typically `index.js`.
> > ```js
> > // index.js
> > ...
> > + import 'patches/EngineIOHeaderWarning';
> > ...
> > ```
> > 
> > 
> > ```js
> > // patches/EngineIOHeaderWarning.js
> > const WS = require('engine.io-client/lib/transports/websocket');
> > 
> > var WebSocketImpl = WebSocket; // eslint-disable-line no-undef
> > 
> > WS.prototype.doOpen = function() {
> >   if (!this.check()) {
> >     // let probe timeout
> >     return;
> >   }
> > 
> >   var uri = this.uri();
> >   var protocols = this.protocols;
> >   var opts = {};
> > 
> >   if (this.extraHeaders) {
> >     opts.headers = this.extraHeaders;
> >   }
> >   if (this.localAddress) {
> >     opts.localAddress = this.localAddress;
> >   }
> > 
> >   try {
> >     this.ws = new WebSocketImpl(uri, protocols, opts);
> >   } catch (err) {
> >     return this.emit('error', err);
> >   }
> > };
> > ```
> > 
> > 
> > Overall, if we create a pull request for EngineIO to exclude these extra `opts` that aren't needed when used in ReactNative via `this.isReactNative` then we could suppress this warning for all using the SocketIO Client in their ReactNative projects.
> 
> Your code wouldn't allow me to connect to the server and changed the intended behaviour of EngineIO so I've just wrapped those options in an if statement but used the same patch mechanism you suggested
> 
> ```
> // patches/EngineIOHeaderWarning.js
> const WS = require('engine.io-client/lib/transports/websocket');
> 
> var WebSocketImpl = WebSocket; // eslint-disable-line no-undef
> 
> WS.prototype.doOpen = function() {
>     if (!this.check()) {
>         // let probe timeout
>         return;
>     }
> 
>     var uri = this.uri();
>     var protocols = this.protocols;
>     var opts = {};
> 
>     if(!this.isReactNative){
>         opts.agent = this.agent;
>         opts.perMessageDeflate = this.perMessageDeflate;
> 
>         // SSL options for Node.js client
>         opts.pfx = this.pfx;
>         opts.key = this.key;
>         opts.passphrase = this.passphrase;
>         opts.cert = this.cert;
>         opts.ca = this.ca;
>         opts.ciphers = this.ciphers;
>         opts.rejectUnauthorized = this.rejectUnauthorized;
>     }
> 
> 
>     if (this.extraHeaders) {
>         opts.headers = this.extraHeaders;
>     }
>     if (this.localAddress) {
>         opts.localAddress = this.localAddress;
>     }
> 
>     try {
>         this.ws =
>             this.usingBrowserWebSocket && !this.isReactNative
>                 ? protocols
>                 ? new WebSocketImpl(uri, protocols)
>                 : new WebSocketImpl(uri)
>                 : new WebSocketImpl(uri, protocols, opts);
>     } catch (err) {
>         return this.emit('error', err);
>     }
> 
>     if (this.ws.binaryType === undefined) {
>         this.supportsBinary = false;
>     }
> 
>     if (this.ws.supports && this.ws.supports.binary) {
>         this.supportsBinary = true;
>         this.ws.binaryType = 'nodebuffer';
>     } else {
>         this.ws.binaryType = 'arraybuffer';
>     }
> 
>     this.addEventListeners();
> };
> ```

**Comment by SaveYourTime** [comment]
> ` const _io = ioClient.connect(socketurl, { forceNode: true });`
> It's work

It works with me, Thanks!

Version ` "socket.io-client": "^2.3.0"`

**Comment by dommangetnicolas** [comment]
> > ` const _io = ioClient.connect(socketurl, { forceNode: true });`
> > It's work
> 
> It works with me, Thanks!
> 
> ` "socket.io-client": "^2.3.0"`
> 
> ```js
> const socket = io(host, { forceNode: true });
> ```

It worked for me too! Big thanks

**Comment by vigneshwaran-dev** [comment]
You can simply add some headers and it works!
`    socket = io.connect('SOCKET_URL_HERE', {
      jsonp: false,
      agent: '-',
      pfx: '-',
      cert: '-',
      ca: '-',
      ciphers: '-',
      rejectUnauthorized: '-',
      perMessageDeflate: '-'
    });`

**Comment by AlexandruCalinica** [comment]
> const _io = ioClient.connect(socketurl, { forceNode: true });

This resolves the warning but makes my socket connection really really slow(timeout actually), so its unusable for me.

**Comment by darrenkeenfanduel** [comment]
Downgrading, `forceNode:true`, not doing anything other than latest installs - all leads to timeout. I can't connect at all.

**Comment by lrondanini** [comment]
> > const _io = ioClient.connect(socketurl, { forceNode: true });
> 
> This resolves the warning but makes my socket connection really really slow(timeout actually), so its unusable for me.

same here: connection timeout!

**Comment by darrenkeenfanduel** [comment]
I got rid of froceNode and downgraded to `2.1.0` and it worked fine. I also had the issue where I was using localhost and not the IP to my emulator device.

**Comment by isthaison** [comment]
The same @SaveYourTime , I'm using `"socket.io-client": "^2.3.0"`
refer here https://socket.io/docs/client-api/.
I why add `forceNode` option

**Comment by BassemN** [comment]
This issue should be fixed on `engine.io-client` v3.4.3 so all you need to do is to delete the `yarn.lock` file and the `node_modules` directory then run `yarn install`

**Comment by ptboyer** [comment]
@BassemN Perhaps instead of deleting your yarn.lock file, you could use `yarn upgrade-interactive` to bump the version safely?

It seems a bit counter-intuitive to the idea of a "lock" file if you completely destroy it every time you want to upgrade your packages. 😅

**Comment by darrachequesne** [comment]
It should be fixed by https://github.com/socketio/engine.io-client/commit/e5bc1063cc90a7b6262146c7b5338ffff1ff9e5b (included in `engine.io-client@3.4.3` and `socket.io-client@2.3.0`).

Regarding the `forceNode` option, it seems React Native actually supports WebSocket ([ref](https://reactnative.dev/docs/network.html#websocket-support)), so `forceNode: true` should not be needed. Isn't that the case?

**Comment by umitayt** [comment]
Proxying WebSockets is working for me.
I am using node HTTP-proxy to allow 'ws'  on the local machine, on a remote server configured Nginx proxy.

Server Side:
const io = require("socket.io")(server.listener, {
    log: true,
    pingInterval: 60000,
    pingTimeout: 600000,
    cors: {
      origin:   "http://localhost:3000",
      methods: ["GET", "POST"]
    }
  });
  const proxy = HttpProxy.createProxyServer({ ws: true });
  io.on("upgrade", function(req, socket, head) {
    proxy.ws(req, socket, head);
  });
 
Front Side:
 import {Manager} from "socket.io-client";
  socketInstance =  new Manager('ws://localhost:1342/',
     { transports: ["websocket"] , 
     protocols:["http"], 
     port:1342,
     auth:{ token: xxxxxx}
  });
