### ISSUE TITLE
Access to XMLHttpRequest at 'http://localhost:8080/socket.io/?EIO=3&transport=polling&t=MgBuvgw' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by imarun577** [socketio/socket.io-client#1299]
I am trying to connect a angular with laravel web socket . is it possible ?

**Comment by knoxcard** [comment]
are you in a development environment or production?  In development, dont use localhost, create a domain name.

https://sangams.com.np/setup-web-server-domain-xampp/

**Comment by harshan89** [comment]
same issue no solution

**Comment by alexisqc92** [comment]
Did someone was able to find a solution?

**Comment by darrachequesne** [comment]
Please see my answer here: https://github.com/socketio/socket.io-client/issues/641#issuecomment-723353502

**Comment by darrachequesne** [comment]
For future readers, please see the documentation here: https://socket.io/docs/v3/handling-cors/
