### ISSUE TITLE
Socket.IO shows inconsistent activity while connecting to AWS , sometimes connection will happen successfully and sometimes connection will not happen from client side to AWS(server)

### ISSUE THREAD

**Issue by vasanthhr** [socketio/socket.io-client#1301]
Hello Team,

I used below code to connect from Client Side to AWS (ELB). (AWS load balancer with Auto-Scaling Instance).

It connecting successfully  sometimes , but sometimes Client side wouldn't able to connect AWS.

(Sometimes means: Whenever users open browsers and trying to click on a button then client/front-end able to connect AWS successfully)

(Some other times whenever users trying after few minutes or later with fresh or new browser  : Same or different users trying to do the same operations then Socket.IO won't connect to AWS).

**Please guide me why this inconsistent behavior happening here, please guide me If I am doing anything wrong here.** 

Please find front-end code.

```
      const url_soc = "https://apiml.ourwebsite.com/namepose"
      const param_soc = {'reconnect': true,'reconnection delay': 100,'max reconnection attempts' : 'Infinity', 'try multiple transports':   true,
        'transports': [
        'websocket',
        'flashsocket',
        'htmlfile',
        'xhr-multipart',
        'xhr-polling',
        'jsonp-polling']
      }
      const domain= "coming_host"
      const key= "unique_key_code"
      const msg={query:"key="+key+"&domain="+domain}


      var socket = io.connect(url_soc, msg, param_soc);
```

Backend(AWS, ELB), Python flask_socketio

```
@socketio.on('connect', namespace='/namepose')
def test_connect():
    emit('test_connect', {'data': 'Connected'})
```

**Comment by darrachequesne** [comment]
For future readers, please see the documentation here:

- https://socket.io/docs/v3/handling-cors/
- https://socket.io/docs/v3/using-multiple-nodes/
