### ISSUE TITLE
Cannot send message from iOS devices

### ISSUE THREAD

**Issue by interpol2006** [socketio/socket.io-client#1302]
Hi guys, we are using socket io with react native to build chat . We got an issue when user on some iOS devices cannot send messages with android/iOS users but when they switch to use android devices they can send messages normally. We trace the issue and it related to socket io but we still not find the root cause. Have you ever met the issue before please advise . TIA.

**Comment by emdotem** [comment]
Up

**Comment by m-ricca** [comment]
same problem for our ios chat app: the emit never ends and does not call our callback
