### ISSUE TITLE
Proxy config

### ISSUE THREAD

**Issue by augustoeliezer** [socketio/socket.io-client#1307]
### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Current behaviour

Not implemented.

### Expected behaviour
Please add a config option to use with proxy.
```javascript
var proxy = {
  host: '192.168.0.1',
  port: 8080,
  user: '',
  password: '',
  protocol: 'http:'
};

var socket = require('socket.io-client')('http://localhost', {proxy});
socket.on('connect', function(){});
socket.on('event', function(data){});
socket.on('disconnect', function(){});

```
### Setup
- OS: Any
- browser: Any
- socket.io version: Next

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
Old project with socket.io@2.0.4: https://github.com/stbrenner/socket.io-proxy

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by binarybaron** [comment]
Has there been an update on this?

**Comment by darrachequesne** [comment]
@binarybaron no, no work has been done on this subject. Could you please explain your use case?

**Comment by binarybaron** [comment]
I want to allow users to route their traffic through TOR (The onion router) and that includes the socket.io connection to the backend.

I have made this work by using the `socks-proxy-agent` npm package and then passing that in as the `agent`
