### ISSUE TITLE
Socket doesn't connect when React Native remote debugger is on

### ISSUE THREAD

**Issue by haitaox** [socketio/socket.io-client#1308]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*socket doesn't connect when react native remote debugger is turned on.
The error is always timeout.
Socket does connect if debugger is turned off.*

### Expected behaviour

*socket should connect regardless of RN debugger being on or off*

### Setup
- iOS: 12.4
- react native: 0.59.8
- socket.io version: 2.2.0

**Comment by parth-koshta** [comment]
I'm having the same problem
Did you find any solution?

**Comment by LucasHimelfarb** [comment]
@haitaox  @parth-koshta  ¿Has encontrado una respuesta para resolver esto?

**Comment by iarif4u** [comment]
hey bro, get any solution

**Comment by TaiPhamDuc** [comment]
I think it because different time of device and pc :)

**Comment by ofgowtham** [comment]
> I think it because different time of device and pc :)
> so, try to set your pc time same as device time or later than device time.

It worked. But this is atrocious. :/

**Comment by ofgowtham** [comment]
> That sounds weird, the time of the device should not affect the Socket.IO connection... Does somebody have an explanation?

And also socket connects as new client multiple times even when socket.connect() was not called. After I synced the time for both pc and device especially working with debugging mode this happened. While on production even if the time is different, socket was working. IMO this has to be with debugging mode. 
PS: I was using chrome debugger.

**Comment by darrachequesne** [comment]
For future readers:

Please check our guide with React Native here: https://socket.io/how-to/use-with-react-native

Please reopen if needed.
