### ISSUE TITLE
Extra Headers not working in Angular

### ISSUE THREAD

**Issue by NoSoup4you2** [socketio/socket.io-client#1310]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

When trying to use extra header element in socket client in an angular app it does not set / show the value on the socket server site. Using the same method on a basic web client will create header and show on server.  Based on all docs i found i used the below code

### Steps to reproduce (if the current behaviour is a bug)
This is the code i use on the angular client. The same code works just fine on a Webrowser and JavaScript
```
this.client = io(`${environment.socketUrl}`,  {
    transportOptions: {
      polling: {
        extraHeaders: {
          Authorization: "Bearer authorization_token_here"
        }
      }
    }
  });
```

### Expected behaviour
 to be able to access the extra header on my server

*What is expected?*

### Setup
- OS: Win 10
- browser: Chrome
- socket.io version: "socket.io-client": "^2.1.1"

**Comment by ceciliazcx** [comment]
@NoSoup4you2  any luck you got it work?
My case is to try pass 'Cookie' and chrome does not allowed reset Cookie

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

Documentation about `extraHeaders` option: https://socket.io/docs/v3/client-initialization/#extraHeaders
