### ISSUE TITLE
Socket 400 bad request error for multiple clusters in nodejs

### ISSUE THREAD

**Issue by vipul8131** [socketio/socket.io-client#1311]
I'm facing the 400 Bad Request error on the socket on the client side. On Frontend, I am using reactjs with socket and on the backend is nodejs. But on the nodejs I am using 3 clusters so the socket connection is disconnected repeatedly.

I have used the openSocket package on the reactjs side(Front-end):

```
import openSocket from 'socket.io-client';
let socket = openSocket(server url);
```
And on the backend side nodejs:

`var io = require('socket.io')(server);`
Please help me out. Thanks!

**Comment by GriFlo** [comment]
have you read this? https://socket.io/docs/using-multiple-nodes/

**Comment by GrillAndChill** [comment]
+1 same issue!

We are using Redis to sync all instances of our nodejs app, but it spams our backhand log with 400 Bad Request errors for like 30seconds, and then it connects.

**Comment by darrachequesne** [comment]
Please check https://socket.io/docs/using-multiple-nodes/
