### ISSUE TITLE
channel name from laravel

### ISSUE THREAD

**Issue by arbabi2010** [socketio/socket.io-client#1313]
Hi, I'm using from socket.io-client for react native and server data is from laravel event
in laravel i send from event broadcast with channel name "new_notif" but a cant receive in socket io
 this is my laravel code
```
class NotifOrderEvent extends Event implements ShouldBroadcast
{
    public $message;

    use Dispatchable, InteractsWithSockets;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct($message)
    {
        $this->message = $message;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return Channel|array
     */

    public function broadcastOn()
    {

        return new Channel('notif_channel');
    }
}


```
how can i define channel  in socket

**Comment by adhenrique** [comment]
@arbabi2010 what your Laravel version?

**Comment by adhenrique** [comment]
@arbabi2010  Anyway, the Laravel broadcast has a prefix on the channels. Some time ago, i finding a problem like yours, and this is not documented. Look here:

https://github.com/laravel/framework/issues/28210

**Comment by arbabi2010** [comment]
@adhenrique  Thank you.
But in laravel 5.4 i haven't prefix for redis database. 
Should i use channel_name:App\\Event\\EventName ?

**Comment by adhenrique** [comment]
Maybe. Are u using a container, or standalone redis server?

U can use *redis-cli monitor* command to see the return, and so, identify channel name.

**Comment by arbabi2010** [comment]
I have standalone redis server.
Thanks . It's a good idea. I'll check it.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
