### ISSUE TITLE
can't connect python server

### ISSUE THREAD

**Issue by mtalhagaoglu** [socketio/socket.io-client#1314]
hi. i have to connect python socketio server from reactnative app. i was able to connect socketio server in ubuntu server ( http://remoteip:8080 ). so the server is working properly but react native couldn't connect. this is the code: const socket = SocketIOClient("http://remoteip:8080"); socket.on("connect", () => { console.warn("connected") });

are there anyone know how can i connect?

i used this library for python server: https://github.com/miguelgrinberg/python-socketio

before that i used another python server but it didn't work also: https://stackoverflow.com/questions/57036652/cant-send-data-from-react-native-app-to-python-server/57044788#57044788

**Comment by lionbur** [comment]
I tried with Expo SDK v34 and v35 (RN 0.59) and had to downgrade socket.io-client to 1.7.2 (yarn add socket.io-client@1.7.2) as other versions (2.1.1, 2.1.0, 2.2.0) did NOT work.
