### ISSUE TITLE
query token not connecting

### ISSUE THREAD

**Issue by ran-j** [socketio/socket.io-client#1316]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

I'm trying to connect with my server with query token : 

![image](https://user-images.githubusercontent.com/17410205/63100983-8dddfa00-bf4e-11e9-8eff-e9b00154b3ca.png)

But the events like connected or error did not come.

In a web browser works normally the same code.

The connection Its even in my server.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

Documentation for the `query` option: https://socket.io/docs/v3/client-initialization/#query
