### ISSUE TITLE
Connect to Server With IPV6 Address

### ISSUE THREAD

**Issue by harshkoralwala** [socketio/socket.io-client#1319]
Hello,

I want to connect my client with **IPV6** python server which is in local connection.

My node Client code looks like...
`
const socket = io('ws://[fe80::899d:6463:7c8c:5af2]:2499', {
    reconnection: false,
    secure: true,
    transports: ['websocket'],
    rejectUnauthorized: false,
 );
`
But this not works...

Python server on Another system (in local connection) created with code...
`
import socketio
from aiohttp import web
sio = socketio.AsyncServer(cors_allowed_origins="*",logger=True,json=json)
app = web.Application()
sio.attach(app)

@sio.event
async def connect(sid, environ):
    print('>>>> connect <<<<< ')
    print(sid)

ourSocket = socket.socket(socket.AF_INET6)

ourSocket.bind(('::1', 2499))

ourSocket.listen(5)      
ssl_context=ctx,sock=ourSocket)
web.run_app(app,sock=ourSocket)

`
So how can I connect to this server?

Thanks in advance

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by wesleydarnell** [comment]
Ever figure this out?
Running into similar headaches getting socket.io-client to connect to a link-local IPV6 address.
Server side seems properly listening.
