### ISSUE TITLE
Broken ES5 support in v2.3.0

### ISSUE THREAD

**Issue by subzey** [socketio/socket.io-client#1325]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

socket.io-client now depends on debug@4.x.x which is not ES5 compatible.

After socket.io-client is built with Webpack, the resulting file contains several `const` declarations. As a result, the built file is not an ES5.

That sudden drop of ES5 is very surprising for a minor version release.

### Steps to reproduce (if the current behaviour is a bug)

Build something with webpack importing `socket.io-client` as a dependency, without Babel transcompilation.

### Expected behaviour

Built files are ES5.

### Setup
- OS: <any>
- browser: <n/a>
- socket.io version: 2.3.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

The `const` statement is actually in the dependency, `debug@4`. The 2.2.0 had `debug@3` dependency.

**Comment by fmagaldea** [comment]
Same here

**Comment by Perlets9** [comment]
Same issue here when starts building app with Create React App

**Comment by goto-bus-stop** [comment]
You can pin to an ES5 version using:
```json
"socket.io-client": "~2.2.0"
```

https://github.com/transloadit/uppy/commit/5839b655f093edaa778d49b719f7dda063ef79cb

**Comment by hellivan** [comment]
Despite [debug](https://github.com/visionmedia/debug) dependency, [engine.io-client](https://github.com/socketio/engine.io-client) was also updated to version ~3.4.0 in this release. 
Since engine.io-client@3.4.0 also depends on debug@~4.1.0, that change seams to be problematic too.

**Comment by Schweinepriester** [comment]
+1

On a related note, v2.3.0 does not seem to have a git tag in this repo nor a changelog… :/

**Comment by jeremylcarter** [comment]
I have actually done the inverse, pinned to a specific debug version. eg.
`"debug": "~3.2.6"`
I have this listed above the `socket.io-client dependency` - although it shouldnt matter what order they are listed.

**Comment by goto-bus-stop** [comment]
the package.json in socket.io-client@2.3.0 lists debug 4.1.0, so if you pin the debug dependency in your _own_ package.json, npm will install both debug v3 (for you) and v4 (for socket.io). you can do `npm ls debug` to check if this is the case.

**Comment by darrachequesne** [comment]
This was fixed in `socket.io-client@2.3.1`: https://github.com/socketio/socket.io-client/releases/tag/2.3.1
