### ISSUE TITLE
HTTPS connection issue

### ISSUE THREAD

**Issue by rameshmonad** [socketio/socket.io-client#1326]
# You want to:
* [x] report a *bug*

### Current behaviour
Case 1: message-center.js:3382 Uncaught TypeError: _vueSocket2.default is not a constructor
    at Object.85../components/MessageCenter.vue (message-center.js:3382)
    at s (message-center.js:1)
    at e (message-center.js:1)
    at message-center.js:1

Case 2: WebSocket connection to 'wss://hostname:80/socket.io/?EIO=3&transport=websocket&sid=0ByZrlpBAZ8Kug5KAAAH' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR

### Steps to reproduce (if the current behaviour is a bug)
I've elabled ssl from node server side and its working fine, but from client side it gives below error. 
Can anybody help me to fix that.

Case 1:

import socketio from 'socket.io-client'; // "socket.io-client": "^2.0.4"
import VueSocketIO from 'vue-socket.io'; // "vue-socket.io": "^2.1.1-a"

export const SocketInstance = socketio(store.getters.resourcePath, {
	secure: true,
	rejectUnauthorized: false
});

Vue.use(new VueSocketIO({
    debug: true,
    connection: socketio(store.getters.resourcePath, { secure: true, rejectUnauthorized: false })
  })
);

message-center.js:3382 Uncaught TypeError: _vueSocket2.default is not a constructor
    at Object.85../components/MessageCenter.vue (message-center.js:3382)
    at s (message-center.js:1)
    at e (message-center.js:1)
    at message-center.js:1

Case 2: 

import socketio from 'socket.io-client'; // "socket.io-client": "^2.0.4"
import VueSocketIO from 'vue-socket.io'; // "vue-socket.io": "^2.1.1-a"

export const SocketInstance = socketio(store.getters.resourcePath, {
	secure: true,
	rejectUnauthorized: false
});

Vue.use(VueSocketIO, SocketInstance);

WebSocket connection to 'wss://hostname:80/socket.io/?EIO=3&transport=websocket&sid=0ByZrlpBAZ8Kug5KAAAH' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR

### Expected behaviour
It should connect with https

### Setup
- OS:Linux
- browser:Chrome - Version 74.0.3729.157 (Official Build) (64-bit)
- socket.io version:

import socketio from 'socket.io-client'; // "socket.io-client": "^2.0.4"
import VueSocketIO from 'vue-socket.io'; // "vue-socket.io": "^2.1.1-a"

**Comment by besserwisser** [comment]
Hey, I have the same issue. Could you fix it?

**Comment by darrachequesne** [comment]
For future readers:

`wss://` (SSL) and `:80` (non-SSL) sounds weird. Maybe an invalid configuration?

Closed due to inactivity, please reopen if needed.
