### ISSUE TITLE
Error using nodejs v12.

### ISSUE THREAD

**Issue by tuphampro** [socketio/socket.io-client#1327]
var socket = socketIO(`wss://localhost:8000/plugin`, {
      rejectUnauthorized: false,
      transports: ['websocket'],
      upgrade: false,
      reconnectionDelay: 1000,
      reconnection: true,
      reconnectionAttempts: 4,
    });

Error: **write EPROTO 3127633848:error:100000f0:SSL routines:OPENSSL_internal:UNSUPPORTED_PROTOCOL:../../third_party/boringssl/src/ssl/handshake_client.cc:569**

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
