### ISSUE TITLE
Still using socket.io-parser 3.3.0

### ISSUE THREAD

**Issue by daveisfera** [socketio/socket.io-client#1329]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
2.3.0 is using `socket.io-parser` 3.3.0 even though [`socket.io` 2.3.0 is using `socket.io-parser` 3.4.0
](https://github.com/socketio/socket.io/blob/47161a65d40c2587535de750ac4c7d448e5842ba/package.json#L32)

### Steps to reproduce (if the current behaviour is a bug)
1) Install `socket.io` and `socket.io-client`
2) Observe that 2 versions of `socket.io-parser` are installed

### Expected behaviour
Both versions use the same version of `socket.io-parser`

### Setup
- OS: 10.14.6
- browser: Chrome 77.0.3865.90
- socket.io version: 2.3.0

**Comment by darrachequesne** [comment]
Yes, that is expected, because `socket.io-parser@3.3.x` relies on `debug@3`, while `socket.io-parser@3.4.x` relies on `debug@4`, which now needs to be transpiled to ES5.

Related: https://github.com/socketio/socket.io-client/issues/1325
