### ISSUE TITLE
yarn build error

### ISSUE THREAD

**Issue by kenneth** [socketio/socket.io-client#1330]
yarn run v1.19.1
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/socket.io-client/node_modules/debug/src/browser.js:155

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Malik-Adil** [comment]
Facing same issue

**Comment by jadok** [comment]
Facing same issue using npm and react-script

**Comment by victoria100** [comment]
Facing same issue.. any idea? I upgraded version to latest version. but still no luck

**Comment by anotheri** [comment]
Same here

**Comment by guixiao417** [comment]
I got same issue

**Comment by guixiao417** [comment]
Please try to downgrade socket.io-client version to 1.7.0, then above issue will be gone away

**Comment by victoria100** [comment]
oh my gosh @guixiao417 thanks, it worked for me! Thank you!

**Comment by aliriomendezjr** [comment]
@guixiao417 it works!

**Comment by hscspring** [comment]
@guixiao417 works for me.

**Comment by krzywiecki** [comment]
Is it possible to keep using the newest stable version of the socket.io-client with react-scripts? Downgrading is not really a solution for me.

**Comment by mahshid22** [comment]
thre is a way insted of downgrade? all of my modual are update to the laste verion.

**Comment by guixiao417** [comment]
I tried but it was not working for last version

**Comment by Gauthamjm007** [comment]
@guixiao417 you saved my day thanks a lot

**Comment by guixiao417** [comment]
My pleasure

**Comment by chenbrian** [comment]
I updated react-script to latest (3.4.1 at this time) and followed the instructions from yarn build. Ended up removing babel-eslint and eslint and was able to build successfully.

**Comment by tmaximini** [comment]
Also not happy with the approach of downgrading to an old version, but it's the only thing that works for us at the moment.

**Comment by lovefengruoqing** [comment]
This bug messed me up. The downgrading way is a good solution. 
I can only use the latest version through script which annoys me.

**Comment by tmaximini** [comment]
What I ended up doing was, download socket.io-client latest 2.3.0 and save it in `./client/scripts/vendor`, then use a webpack alias:

```
  resolve: {
    alias: {
      'socket-io.client': __dirname + '/client/scripts/vendor/socket.io-client.2.3.0'
    }
  },
```

This compiled fine and did not produce any yarn build errors.

**Comment by jxooi00** [comment]
> Please try to downgrade socket.io-client version to 1.7.0, then above issue will be gone away

Thx bro u da best!!! It works thank you!!

**Comment by Pedroxam** [comment]
I complete remove socket.io and my problem was fixed. thanks!

**Comment by darrachequesne** [comment]
Hi! I'm not able to reproduce: https://github.com/socketio/socket.io/tree/master/examples/create-react-app-example

```
$ yarn build
yarn run v1.22.4
$ react-scripts build
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  66.34 KB (+1 B)  build/static/js/2.333cb71d.chunk.js
  783 B            build/static/js/runtime-main.4d1b81e4.js
  718 B (-2 B)     build/static/js/main.c951bd20.chunk.js
  547 B            build/static/css/main.5f361e03.chunk.css

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s build

Find out more about deployment here:

  bit.ly/CRA-deploy

Done in 9.16s.

$ npx serve -s build
npx: installed 78 in 4.816s

   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   Serving!                                      │
   │                                                 │
   │   - Local:            http://localhost:5000     │
   │   - On Your Network:  http://192.168.0.2:5000   │
   │                                                 │
   │   Copied local address to clipboard!            │
   │                                                 │
   └─────────────────────────────────────────────────┘
```

**Comment by muayKenny** [comment]
I had the issue aswell except the token error was for index, downgraded to 1.7.0 and saw success

**Comment by dradeng** [comment]
Worked for me thanks!

**Comment by ghostal** [comment]
FWIW, I was experiencing this exact error with npm/webpack, using the Node 14.x Docker image. Upgrading to the Node 15.x image solved the problem. In both instances (failing and building) I was using the same `socket.io-client` package version - `2.3.1`.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
