### ISSUE TITLE
Must socket.io-client and socket.io be used together

### ISSUE THREAD

**Issue by guozhenqianga** [socketio/socket.io-client#1334]
Must socket.io-client and socket.io be used together
"socket.io-client": "^2.3.0",

Must socket.io-client and socket.io be used together
![image](https://user-images.githubusercontent.com/23112360/67448239-fdf0b680-f648-11e9-8966-9aabb608894d.png)

java:spring-boot-starter-websocket
client:"socket.io-client": "^2.3.0",
error:
![image](https://user-images.githubusercontent.com/23112360/67448189-dd286100-f648-11e9-9c93-9d13a26fa575.png)

**Comment by darrachequesne** [comment]
Please see the documentation here: https://socket.io/docs/v3/
