### ISSUE TITLE
NPM show 2.3.0 yet I  don't see a 2.3.0 release in the codebase

### ISSUE THREAD

**Issue by gregors** [socketio/socket.io-client#1338]
The code says `2.2.0` 
https://github.com/socketio/socket.io-client/blob/master/package.json#L3 . 
So where is the code for `2.3.0` that NPM is reporting? Are releases no longer from master?

**Comment by darrachequesne** [comment]
For future readers: please see https://github.com/socketio/socket.io-client/releases/tag/2.3.0
