### ISSUE TITLE
Requires attribute to be set not to cache packets

### ISSUE THREAD

**Issue by hua1995116** [socketio/socket.io-client#1347]
### You want to:

* [] report a *bug*
* [x] request a *feature*

### Current behaviour

*What is actually happening?*

When it went offline, I sent a message. Socket-io puts the information in the cache, and when it reconnects, it sends the cached data.
On my client, I made the cache myself. When I reconnect, I need the user to actively control the resend.

### Expected behaviour

*What is expected?*

I need an attribute to set not to cache packets.

### Setup
- socket.io version: 2.3.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

https://github.com/socketio/socket.io-client/blob/master/lib/socket.js#L161

**Comment by darrachequesne** [comment]
Please see the documentation here: https://socket.io/docs/v3/client-offline-behavior/#Buffered-events
