### ISSUE TITLE
Not work on React Native version 0.61.5 and socket.io-client 2.3.0 version

### ISSUE THREAD

**Issue by sonalip2** [socketio/socket.io-client#1350]
React native modules versions
1. react-native: 0.61.5,
2. react: 16.9.0,
3. socket.io-client: 2.3.0

Node versions

1. "socket.io": "^2.3.0"

**In react**

 I'm using this version on react-native and following for connect nodeserver socket
const io = require('socket.io-client');

module.exports = (ns) => {
    // ns will be "game/gameId"
    return io(`http://192.168.1.80:4040/${ns}`, {
        query: `ns=${ns}`,
        resource: 'socket.io',
        transports: ['websocket'],
        pingTimeout: 60000,
        pingInterval: 60000
    });
}

every single time when i go for connect socket, it will always gives **connection timeout** error and it try to connect multiple times to server.
On server side I'm getting complete response but not able to connect with server.
The same code working in website, but not in react-native. I tried with different version but not working.

**Comment by Lizhooh** [comment]
me too

**Comment by sbsujith** [comment]
Is there a fix? I get the same timeout error in mac for both android device and ios simulator. However i can connect to the server using restfull. So its some thing to do with socket.io-client
socket.io-client@3.0.4
engine.io-client@4.0.5 
react-native@0.63.3

**Comment by sbsujith** [comment]
> Is there a fix? I get the same timeout error in mac for both android device and ios simulator. However i can connect to the server using restfull. So its some thing to do with socket.io-client
> socket.io-client@3.0.4
> engine.io-client@4.0.5
> react-native@0.63.3

It worked for me with below versions
socket.io-client@2.3.0
engine.io-client@3.4.4 ( installs along with socket.io-client)
react-native@0.63.3

**Comment by sonalip2** [comment]
Issue resolved, issue was from system side.
