### ISSUE TITLE
possible to revise header during handshake?

### ISSUE THREAD

**Issue by ceciliazcx** [socketio/socket.io-client#1355]
I read the following article already
https://github.com/socketio/socket.io-client/issues/648

It looks like extra header is allowed. My question is : is it possible to revise header? I need to append sth to a cookie, due to chorme's new change of Samesite.

Thanks.

**Comment by darrachequesne** [comment]
For future readers:

Please find the documentation here: https://socket.io/docs/v3/client-initialization/#extraHeaders
