### ISSUE TITLE
Handle sending/recieving messages while disconnected better

### ISSUE THREAD

**Issue by matej-svejda** [socketio/socket.io-client#1358]
### You want to:
* request a *feature*

### Current behaviour
It isn't possible to configure whether the client buffers sent/recieved messages while disconnected. When using socket.io to sync state between server and client, this makes reasoning harder in a lot of cases.

### Expected behaviour
It should be configurable how sending/recieving messages should be handled. For sending messages the workaround is easy (just check that the client is connected before sending, otherwise don't send). For recieving there's no way of knowing if the message was recieved while disconnected or not.

**Comment by darrachequesne** [comment]
For future readers:

- messages emitted by the client are indeed buffered when the client is disconnected, and sent upon reconnection. You can indeed control this behavior with:

```js
if (socket.connected) {
  socket.emit( /* ... */ );
} else {
  // ...
}
```

More information here: https://socket.io/docs/v3/client-offline-behavior/#Buffered-events

- messages received by the client while disconnected are lost. Upon reconnection, a new session is created and any message sent to the previous session is lost.

Actually, I'm not sure what the usage of the `receiveBuffer` ([here](https://github.com/socketio/socket.io-client/blob/3.1.0/lib/socket.ts#L41)) is. Maybe in case the socket receives a packet before the actual connection?

For reference, it was added in https://github.com/socketio/socket.io-client/commit/d523a25cc036556e649d4cb8df937e6d6395992e and then edited in https://github.com/socketio/socket.io-client/commit/8e76ec1717c906214ab24552225ce5b5f06a6098.
