### ISSUE TITLE
The socket client produces a massive amount of get request. Some of them failing

### ISSUE THREAD

**Issue by SecretUnicorn** [socketio/socket.io-client#1361]
### You want to:

* [x] report a *bug*

### Current behaviour

*What is actually happening?*
![grafik](https://user-images.githubusercontent.com/24612112/81300995-c2fc2080-9078-11ea-8528-e8eb89f34825.png)

Is this a normal behavior? Everytime it gets a Bad Request it reconnects after it but I imagine thats bad if my application has 200 active users simultaneously.

### Steps to reproduce

`this.socket = io(socketUrl);`

### Expected behaviour

Dont get so many Bad Requests?

### Setup
- OS: Windows 10
- browser: Firefox
- socket.io version: ^2.3.0

**Comment by SecretUnicorn** [comment]
Every request that failed had the transport type websocket instead of polling

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
