### ISSUE TITLE
unable to run the SioChatDemo application

### ISSUE THREAD

**Issue by poojapowar** [socketio/socket.io-client#1363]
When I am trying to run this application only starting wondow is appearing which ask to enter the name. After entring name not getting any further ouput.
Also in the XCode output window getting errors as :
Network is unreachable 
socket is not connected

Whats the correct way to run this application? Do I need to make any changes on MAC machine settings?

Here is the error messages in output window : 
 [devel] asio::init_asio
[devel] set_open_handler
[devel] set_close_handler
 [devel] set_fail_handler
[devel] set_message_handler

 [devel] connection constructor
[devel] transport::asio::init
[devel] starting async DNS resolve for 192.168.4.108:8080
[devel] Async DNS resolve successful. Results: 192.168.4.108:8080 
 [devel] Starting async connect
 [devel] asio handle_resolve_timeout timer cancelled
[info] asio async_connect error: system:51 (Network is unreachable)
[devel] connection terminate
[info] Error getting remote endpoint: system:57 (Socket is not connected)
[fail] WebSocket Connection Unknown - "" /socket.io/?EIO=4&transport=websocket&t=1589458470 0 websocketpp.transport.asio:3 Underlying Transport Error
[devel] asio connection async_shutdown
[devel] connection handle_terminate
Connection failed.
Reconnect for attempt:0
[error] handle_connect error: Underlying Transport Error
[devel] asio handle_connect_timeout timer cancelled
[devel] asio socket shutdown timer cancelled
Reconnecting..[devel] connection constructor
 [devel] transport::asio::init
 [devel] starting async DNS resolve for 192.168.4.108:8080
[devel] Async DNS resolve successful. Results: 192.168.4.108:8080 
[devel] Starting async connect
[devel] asio handle_resolve_timeout timer cancelled
[info] asio async_connect error: system:51 (Network is unreachable)
[devel] connection terminate
 [info] Error getting remote endpoint: system:57 (Socket is not connected)
[fail] WebSocket Connection Unknown - "" /socket.io/?EIO=4&transport=websocket&t=1589458470 0 websocketpp.transport.asio:3 Underlying Transport Error
[devel] asio connection async_shutdown
[devel] connection handle_terminate
Connection failed.
Reconnect for attempt:0
[error] handle_connect error: Underlying Transport Error
 devel] asio handle_connect_timeout timer cancelled
[devel] asio socket shutdown timer cancelled
Reconnecting..

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
