### ISSUE TITLE
Not Working in react native android app getting Error: xhr poll error

### ISSUE THREAD

**Issue by Venukom** [socketio/socket.io-client#1367]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*
"react-native": "0.62.2",
"socket.io-client": "^2.3.0",

getting Error: xhr poll error, while connect with https.

### Steps to reproduce (if the current behaviour is a bug)

I have the following code in my react native app for chat bot functionality, trying to make https connection with my server, I have pass the same cert using in my server ,tried different options to pass the cert and tried with/without vpn but it is not working, I am always getting Error: xhr poll error.

If I run my server with http and make a call from client it is working, could you please help with this, I am not sure it will support https, all the examples was with http. Thank you!

import io from 'socket.io-client';
let socket = io('https://10.0.2.2:3000', {
query: {
                    botmasterUserId: 'rwer3423hghg', //random string
                    clientid: 'rwer3423hghg', //random string
               },
reconnectionAttempts: 1,
path: '/chat',
upgrade: false,
ca: caCert
});
this.socket.connect();

this.socket.on('connect', () => {
               console.log(this.socket.id);
        });
this.socket.on('connect_error', (err) => {
            console.error(err);
        });

### Expected behaviour

I was expecting that it would make a secure connection with server.

### Setup
- OS: Android 10
- browser:
- socket.io version:2.3.0

**Comment by fe80Grau** [comment]
Hello,
just now I have fixed the same error with a certificate from Let's Encrypt. Before Android 28, self-signed certificates worked, but after that, every connection requires an authority certificate.

I have the same version of socket.io on both the RN client and the nodejs server. ^ 2.3.0

Let's Encrypt certificates configuration on my socket.io server in nodejs:

> var express = require('express');
> var app = express();
> var fs = require('fs');
> const https = require('https');
> const secureServer = https.createServer({
>       key: fs.readFileSync('..\\ssl\\private.key'),
>       cert: fs.readFileSync('..\\ssl\\certificate.crt'),
>       ca: fs.readFileSync('..\\ssl\\ca_bundle.crt'),
>       requestCert: false,
>       rejectUnauthorized: false
> },app)

> var io = require('socket.io')(secureServer);

And in my client in RN:

> 
> import io from 'socket.io-client'
> 
> componentDidMount(){
> const socket = io("https://....",{transports:['websocket'], reconnectionDelay:1000, reconnection:true, reconnectionAttempts:10, rejectUnauthorized: false, agent: false, upgrade:false, jsonp:false, forceNew:true})
> ...
> }


If u wan't Let's Encrypt, can get a free certificate in ZeroSSL, I have a test in RN with them and work fine.

**Comment by darrachequesne** [comment]
@Venukom did you find a solution? I guess it is related to the SSL connection that cannot be established, and not Socket.IO itself. Are you using a self-signed certificate?

**Comment by Venukom** [comment]
@darrachequesne yes It is working after adding the ca cert to the network config, latest version of Android is blocking HTTPS calls without proper cert.
https://developer.android.com/training/articles/security-config
