### ISSUE TITLE
Behaviour of reconnect after connect_timeout

### ISSUE THREAD

**Issue by kirankumar-ravuri** [socketio/socket.io-client#1368]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*
- Reconnection attempt after dissconnect is immediate, where as reconnection attempt after connect_timeout is taking maximum of 5 secs.

### Steps to reproduce (if the current behaviour is a bug)
After socket.io client is connected block the socket.io port
 `sudo iptables -A OUTPUT -p tcp --destination-port <sockt.io-port> -j DROP`
**Note**: the best way (and by that we mean **the only way**) to get a quick answer is to provide a failing test case by forking the following [fiddle](https://github.com/socketio/socket.io-fiddle).

### Expected behaviour

*What is expected?*
Reconnection attempt is supposed to happen just after connect_timeout.
### Setup
- OS:Fedora
- browser:chrome
- socket.io version:2.3.0
- client configuration
{
  "timeout" : 5000,
  "reconnectionDelay" : 1000,
  "reconnectionDelayMax" : 5000,
}
### Other information (e.g. stacktraces, related issues, suggestions how to fix)

console output from browser:

connected ::Wed Jun 03 2020 13:34:56 GMT+0530 (India Standard Time)
disconnected               ::Wed Jun 03 2020 13:35:18 GMT+0530 (India Standard Time)
reconnect_attempt1    ::Wed Jun 03 2020 13:35:19 GMT+0530 (India Standard Time)
connect_error              ::Wed Jun 03 2020 13:35:24 GMT+0530 (India Standard Time)
connect_timeout          ::Wed Jun 03 2020 13:35:24 GMT+0530 (India Standard Time)
reconnect_attempt2    ::Wed Jun 03 2020 13:35:26 GMT+0530 (India Standard Time)
connect_error              ::Wed Jun 03 2020 13:35:31 GMT+0530 (India Standard Time)
connect_timeout          ::Wed Jun 03 2020 13:35:31 GMT+0530 (India Standard Time)
reconnect_attempt3     ::Wed Jun 03 2020 13:35:35 GMT+0530 (India Standard Time)
connect_error              ::Wed Jun 03 2020 13:35:40 GMT+0530 (India Standard Time)
connect_timeout          ::Wed Jun 03 2020 13:35:40 GMT+0530 (India Standard Time)
reconnect_attempt4    ::Wed Jun 03 2020 13:35:45 GMT+0530 (India Standard Time)
connected                   ::Wed Jun 03 2020 13:35:46 GMT+0530 (India Standard Time)

**Comment by darrachequesne** [comment]
For future readers:

The `connect_timeout` event was removed in version 3.0.0, you can now use the `connect_error` event:

```js
socket.on("connect_error", (error) => {
  // ...
});
```

Reference: https://socket.io/docs/v4/client-socket-instance/#connect_error
