### ISSUE TITLE
let connect_timeout triggered before connect_error

### ISSUE THREAD

**Issue by zyf0330** [socketio/socket.io-client#1371]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Current behaviour

`connect_error` is triggered before `connect_timeout`
### Steps to reproduce (if the current behaviour is a bug)

Nothing

### Expected behaviour
`connect_timeout` is triggered before `connect_error`
### Setup
- OS: linux
- browser: chrome
- socket.io version: 2.3.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

I want to know if `connect_error` is caused by `connect_timeout`

**Comment by zyf0330** [comment]
Is there anybody here?

**Comment by darrachequesne** [comment]
For future readers: `connect_timeout` has been removed in `socket.io-client@3.0.0`.

Documentation: https://socket.io/docs/v4/migrating-from-2-x-to-3-0/
