### ISSUE TITLE
there is no disconnect reason "transport close" in client doc

### ISSUE THREAD

**Issue by zyf0330** [socketio/socket.io-client#1373]
There is no doc to describe disconnect reason "transport close" in client doc https://socket.io/docs/client-api/#Event-%E2%80%98disconnect%E2%80%99 , it just exists in server doc.

**Comment by matiaslopezd** [comment]
Yes, currently this is not documented, and is highly important to know it.

I send PR for [v2](https://github.com/socketio/socket.io-website/pull/197) and [v3](https://github.com/socketio/socket.io-website/pull/196).

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-website/commit/5cbc8d186490db80dde854845a6ae5f3c9ede3d3.
