### ISSUE TITLE
Incompatibility with angular 10

### ISSUE THREAD

**Issue by justvamp** [socketio/socket.io-client#1375]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Error in console after upgrading to Angular 10. It says `TypeError: Cannot assign to read only property 'exports' of object '#<Object>'`. Errors goes deep to `debug` dependency.

Downgrading to version 1.7.4 **helps**.
Downgrading within version 2 doesn't help.

### Steps to reproduce

* Having angular 9 app with installed socket.io-client. Everything works ok.
* Upgrade angular to version 10.
* Get an error in console. Page in browser is blank. 

### Expected behaviour

Everything should work as it worked before in angular 9.

### Setup
- OS: Ubuntu 20.04
- browser: Chromium 83.0.4103.61
- socket.io-client version: 2.0.0 - 2.3.0 affected, 1.7.4 works ok

### Minimal reproduce example

https://stackblitz.com/edit/angular-ivy-qzhmby?file=package.json

I'm facing another issue here (`Import error, can't find file: ./common`), but I believe they have the same root, because downgrading to 1.7.4 also helps.

**Comment by alcfeoh** [comment]
+1, I have a similar issue. 
This has to do with CommonJS exports syntax vs ES Modules syntax (as explained here: https://flaviocopes.com/cannot-assign-readonly-property-export/). Any chance socket.io could use the modern ES Modules syntax?

**Comment by depyronick** [comment]
+1

**Comment by depyronick** [comment]
https://www.npmjs.com/package/@depyronick/socket.io-client.ng10-fix this works for me

**Comment by jeremylcarter** [comment]
@depyronick Could you explain what you did to the package and it's dependencies?

**Comment by depyronick** [comment]
@jeremylcarter nvm about it, its hard to maintain. 

instead i added `socket.io.js` which socket.io server provides like at `https://domain.ltd/socket.io/socket.io.js` to index.html and put `declare var io;` to the place i had to import socket.io-client.

**Comment by darrachequesne** [comment]
As a workaround, you should be able to ignore the `debug` module:

- create a file named `noop.js`:

```js
module.exports = () => () => {}; // empty function
```

- add the following line in your `package.json` file:

```json
{
  "browser": {
    "debug": "./noop.js"
  }
}
```

I'm not sure what's the best way to deal with that issue though.

**Comment by MaciejWWojcik** [comment]
have the same issue  😢

**Comment by wangta69** [comment]
have the same issue

**Comment by sid69330** [comment]
Have the same issue :(

**Comment by jeremylcarter** [comment]
Current workaround (and its not a good one so don't complain)
Include the `socket.io.slim.js` file in your index.html. You can get it from a CDN or local resource.
Eg from https://cdnjs.com/libraries/socket.io:
`<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.slim.js"></script>`

Then in your socket io client service/file reference it as the any type.
Eg:
`declare var io // This was instantiated in socket.io.slim`

Then use the `@types/socket.io-client` types to bring back type hints.
Eg:
`private socket: SocketIOClient.Socket`

**Comment by Aris1404** [comment]
Some edits to `tsconfig.base.json` will fix this issue.
Here is my tsconfig file:
```
{
    "compileOnSave": false,
    "compilerOptions": {
        "baseUrl": "src",
        "outDir": "./dist/out-tsc",
        "sourceMap": true,
        "declaration": false,
        "downlevelIteration": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "module": "esnext",
        "moduleResolution": "node",
        "importHelpers": true,
        "resolveJsonModule": true,
        "target": "es2015",
        "typeRoots": [
            "node_modules/@types"
        ],
        "lib": [
            "es2017",
            "es5",
            "es6",
            "dom",
            "dom.iterable"
        ],
    }
}
```
As you can see i use `esnext ` to `module`, `es2015 ` to `target` and i add `dom ` and `dom.iterable`  to lib array.
After these changes i cleared my node modules, i runned a fresh `npm install` and the issue solved.

P.S. Special creds to @Giorgospago for his help.

**Comment by justvamp** [comment]
Seems like the Angular team has fixed the issue.
Everything works ok now, no workaround required.

Latest angular:
* @angular/cli - v10.0.5
* @angular/core - v10.0.8

Closing the issue.
