### ISSUE TITLE
How to resolve the Delay issue

### ISSUE THREAD

**Issue by forevereffort** [socketio/socket.io-client#1377]
I would like to allow the socket connection only for the logged-in users. for this, I used the code like the following

```
socket = io.connect(WS_BASE)

if (socket) {
      socket.emit(SOCKET_EVENTS.LOGIN, { token: userToken })
}
```

but SOCKET_EVENTS.LOGIN wasn't calling. **(SOCKET_EVENTS.LOGIN didn't work)**

when I add some **time delay code over 3 sec**, SOCKET_EVENTS.LOGIN worked.

```
socket = io.connect(WS_BASE)

if (socket) {
     setTimeout(() =>  socket.emit(SOCKET_EVENTS.LOGIN, { token: userToken }), 3000)
}
```

**for this, I have a question, after socket connect, do we need much delay time over 3 sec? I am not clear about this**

how can I sovle this problem looks like professional? if anyone tell me the best solution, I am thankful.

PS : if you let me know about using socket RECONNECT and using sample, I am thankful, too :)

**Comment by darrachequesne** [comment]
You can listen to the `connect` event:

```js
socket = io.connect(WS_BASE)

socket.on('connect', () => {
  socket.emit(SOCKET_EVENTS.LOGIN, { token: userToken });
});
```

Your first example should work though, as the packet will be buffered until the socket is connected. Are you able to reproduce in the [fiddle](https://github.com/socketio/socket.io-fiddle)?

**Comment by forevereffort** [comment]
thank you very much. I will clone the fiddle, again. your answer was very helpful.
