### ISSUE TITLE
cors error

### ISSUE THREAD

**Issue by mer30boy** [socketio/socket.io-client#1379]
hi there 
I'm trying to connect an angular socket client and esp8266 socket server to each other.
But when I try to connect to server through Angular, I get the following error:

> Access to XMLHttpRequest at 'http://192.168.1.161/socket.io/?EIO=3&transport=polling&t=NG0T6Hx' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

how can i solve this problem ?

**Comment by darrachequesne** [comment]
That's weird, the server should send the necessary `Access-Control-Allow-xxx` headers by default.

What does `curl "http://192.168.1.161/socket.io/?EIO=3&transport=polling"` gives (headers/http status)?

**Comment by StTronn** [comment]
This is not working by default in v3 for me I have to pass explicitly pass an object with cors on instantiating `io`  

```
const app = express();
app.use(cors());
const server = http.createServer(app);

const io = socketio(server, {
  cors: {
    origin: true,
  },
});

```

You can look at the [doc](https://socket.io/docs/v3/migrating-from-2-x-to-3-0/index.html#CORS-handling) for more info.

**Comment by darrachequesne** [comment]
@StTronn you're absolutely right, my comment above was indeed referring to Socket.IO v2, thanks for the heads-up :+1: 

For future readers:
- documentation for v2: https://socket.io/docs/v2/handling-cors/
- documentation for v3: https://socket.io/docs/v3/handling-cors/
