### ISSUE TITLE
Application crash issue with Internet Explorer

### ISSUE THREAD

**Issue by PriyaKatkade** [socketio/socket.io-client#1384]
We are using socket-io-client (Version ^2.1.1) with Angular 8. Its working fine with Microsoft Edge, Google chrome, but not working with Internet Explorer (Version 11.508.19041.00).
Whenever I start my angular application and access it on IE, automatically application crashes with following error:

```
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on TLSSocket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
```

Here is my code snippet-

```
import * as ClientSocket from 'socket.io-client';
const socket = ClientSocket({
     path: '/api/ns/socket.io',
     transports: ['websocket']
});
 socket.on('error', error => {
    console.error(error);
 });
 socket.on('testEvent', () => {
    alert('Test');
});
```
I am not getting why this is happening? It will be really helpful for me if anybody have some workaround for this.

Thanks.

**Comment by darrachequesne** [comment]
That's weird. Which version of the client are you using exactly?

According to the stacktrace you provided, it may be related to TLS connection. Are you using a self-signed certificate? Or TLS 1.3 which may not be supported by IE?

**Comment by PriyaKatkade** [comment]
socket-io-client version - 1.4.32

Yes, we are using SSL certificate.

Is there any workaround as I need this to work with IE.

**Comment by darrachequesne** [comment]
> We are using socket-io-client (Version ^2.1.1) with Angular 8

> socket-io-client version - 1.4.32

So... which one :smile: ?

More seriously, are there any information in the network tab of your web console? Any request that gets cancelled/with an uncommon HTTP status code?

**Comment by PriyaKatkade** [comment]
Sorry, I just mentioned wrong version.
We are having socket-io-client 2.1.1

As far talking about network tab, I don't see any uncommon HTTP status code. All request returns 200.

**Comment by darrachequesne** [comment]
The exception that you included in your first comment

```
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on TLSSocket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
```

looks like a Node.js exception. Is it really thrown by your browser?

**Comment by PriyaKatkade** [comment]
I am getting this error on Angular CLI.

**Comment by Sumishu** [comment]
I am getting this error from vue-js too.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
