### ISSUE TITLE
import error when build for production

### ISSUE THREAD

**Issue by krishnaTORQUE** [socketio/socket.io-client#1385]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
`Uncaught SyntaxError: Unexpected token '*'`

### Setup
- OS: Ubuntu 20.04
- browser: Firefox, Chrome (All Browser)
- socket.io version: 
-- "socket.io": "^2.3.0"
-- "socket.io-client": "^2.3.1"

in development its working find, Once I build for production its showing error in all browsers.

I tried to do:
- import io from 'socket.io-client
- import io from 'socket.io-client/dist/socket.io'
- import io from 'socket.io-client/dist/socket.io.slim'

all are same error

**Comment by darrachequesne** [comment]
Hi! We will need a lot more information to help you. Are you using webpack? Another bundler? Which version? Which configuration?

**Comment by krishnaTORQUE** [comment]
I am using `create-react-app` I did not install or configure webpack or babel directly. It is all default by react js

**Comment by darrachequesne** [comment]
@krishnaTORQUE I'm not able to reproduce with the following example: https://github.com/socketio/socket.io/tree/master/examples/create-react-app-example

**Comment by krishnaTORQUE** [comment]
sorry my bad. I had another minify script which ruin the production code. I fixed it & working like charm.
thank you for your quick response.

however I have a question
Can I use `socket.io` package like `socket.io/lib/client` instead of this `socket.io-client` or this package is more optimize of client ?

**Comment by darrachequesne** [comment]
Good news!

No, the `socket.io/lib/client` file is a server-side part, though I agree that the name is a bit misleading.

**Comment by krishnaTORQUE** [comment]
Thank you for your time and reply.
I really appreciate that.
