### ISSUE TITLE
Manger uri parser can not parse right `//localhost:4000`

### ISSUE THREAD

**Issue by perymimon** [socketio/socket.io-client#1388]
it looks like the parser uri of `io()` function and the one for `Manger(uri, opt)` are different. 
the last one can not parse right `//localhost:4000` because the leading `//`

Manger parser use module `parseruri` that use the complex regex that not work:

/^(?:(?![^:@]+:[^:@\/]*@)(http|https|ws|wss):\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?((?:[a-f0-9]{0,4}:){2,7}[a-f0-9]{0,4}|[^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
