### ISSUE TITLE
emit msg trigger the socket disconnection and lost the msg

### ISSUE THREAD

**Issue by mathias22osterhagen22** [socketio/socket.io-client#1389]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*

After checking if the socket is connected I send an emit event, but then the socket disconnect:
![image](https://user-images.githubusercontent.com/60438474/97710433-09788800-1abc-11eb-914b-53393c575b6d.png)

This is the connectionSocket method: 
![image](https://user-images.githubusercontent.com/60438474/97710551-2c0aa100-1abc-11eb-8565-0a14bf614b8e.png)

This is the logs: 
![image](https://user-images.githubusercontent.com/60438474/97710692-5f4d3000-1abc-11eb-94ae-75cbcc2ef673.png)

### Steps to reproduce (if the current behaviour is a bug)

Check the code here: [https://github.com/mathias22osterhagen22/socket.io-fiddle]( https://github.com/mathias22osterhagen22/socket.io-fiddle)

> I add an "execSync" call to the windows cmd to be the closest of my current use case

As you can see the "hello" message never emit to the server: 
![image](https://user-images.githubusercontent.com/60438474/97717569-39785900-1ac5-11eb-8c56-92d04e9f1ed8.png)

### Expected behaviour

*What is expected?*
The "socket.connected" should be false or the socket should emit the package after re-connect.

### Setup
- OS: Windows 10 Pro x64bit
- browser: node.js
- socket.io version: 2.3.1

**Comment by mathias22osterhagen22** [comment]
(To avoid this problem I added a "queue" system. If after connection the queue is not empty, the socket emit the payload from the queue, probably this should be managed internally)

**Comment by darrachequesne** [comment]
For future readers:

I think this is due to the `maxHttpBufferSize` value, which defaults to 1MB. The client gets disconnected if it sends a payload above this limit.

Reference: https://socket.io/docs/v4/server-options/#maxhttpbuffersize

Might be related to https://github.com/socketio/engine.io-client/commit/46fdc2f0ed352b454614247406689edc9d908927.

Please reopen if needed.
