### ISSUE TITLE
Uncaught TypeError: encodedPayload.split is not a function

### ISSUE THREAD

**Issue by vadimka123** [socketio/socket.io-client#1391]
### You want to:

* [x] report a *bug*

### Current behaviour

Exception: Uncaught TypeError: encodedPayload.split is not a function

### Steps to reproduce
Simple polling 

### Expected behaviour

No exceptions

### Setup
- OS: linux
- browser: chrome
- socket.io version: 3.0.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
Uncaught TypeError: encodedPayload.split is not a function
    at Object.decodePayload (index.js?2a85:24)
    at XHR.onData (polling.js?0949:105)
    at Request.eval (polling-xhr.js?d33e:101)
    at Request.Emitter.emit (index.js?7297:145)
    at Request.onData (polling-xhr.js?d33e:262)
    at Request.onLoad (polling-xhr.js?d33e:329)
    at XMLHttpRequest.xhr.onreadystatechange (polling-xhr.js?d33e:217)

**Comment by shay-te** [comment]
also happens to me

**Comment by PolarBearAndrew** [comment]
also happens to me

**Comment by darrachequesne** [comment]
That's weird, the `decodePayload()` method should always be called with a String...

It might be fixed by https://github.com/socketio/engine.io-client/commit/ec3f677e9240a8947b6a12e15e3fd77e9bbb51d5 though.

**Comment by vadimka123** [comment]
@darrachequesne , new exception in 3.0.1 release 

`Uncaught DOMException: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'arraybuffer').`

**Comment by TrayserCassa** [comment]
Any workaround for this issue? Currently we are developing a new site, so i could downgrade. For now it should be fine to downgrade, but maybe someone has a better idea?

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/engine.io-client/commit/ec3f677e9240a8947b6a12e15e3fd77e9bbb51d5 and https://github.com/socketio/engine.io-client/commit/89cb771cf0d26426bda603ee01d3b5a225e9f3c0, which are included in `engine.io-client@4.0.4` and `socket.io-client@3.0.3`.
