### ISSUE TITLE
cannot read 'sid' of undefined on linux in windows its working fine

### ISSUE THREAD

**Issue by Warrior-hound** [socketio/socket.io-client#1392]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way (and by that we mean **the only way**) to get a quick answer is to provide a failing test case by forking the following [fiddle](https://github.com/socketio/socket.io-fiddle).

### Expected behaviour

*What is expected?*

### Setup
- OS:
- browser:
- socket.io version:

**Comment by petersaints** [comment]
This report is rather uncomplete, but I'm having the same issue.

**Comment by lcherone** [comment]
Check both client and server versions are the same if you're trying to connect to v3.0.0 server with an older client 2.x.x it wont work

**Comment by darrachequesne** [comment]
I think you must be trying to connect to a v2 server with a v3 client, which are not compatible.

Since the v2 server doesn't send a `sid` in the CONNECT packet, it will throw here: https://github.com/socketio/socket.io-client/blob/3.0.0/lib/socket.ts#L227-L229

@Warrior-hound could you please confirm the analysis? Or give additional details about the error? Thanks!

**Comment by Warrior-hound** [comment]
Thank actually vps installed latest v3 version and i downgraded it to v2 and it worked fine. TYSM

**Comment by Warrior-hound** [comment]
Thank actually vps installed latest v3 version and so i downgraded it to v2 and it just worked fine. TYSM for help.

**Comment by petersaints** [comment]
Ok. That seems to be the problem. I wrongly assumed that the new client was backwards compatible with Socket.io v2 server.
