### ISSUE TITLE
Unrecognized WebSocket connection option(s) `localAddress`. Did you mean to put these under `headers`?

### ISSUE THREAD

**Issue by TalhaZubair21521** [socketio/socket.io-client#1397]
I am getting this error and warning when connecting in react native with node js.
Warning : Did you mean to put these under `headers`?
Error : TypeError: undefined is not an object (evaluating 'packet.data.sid'

**Comment by darrachequesne** [comment]
This should be fixed in `engine.io-client@4.0.3` (which is included in `socket.io-client@3.0.x`). Could you please confirm?

**Comment by ivorcho** [comment]
I am testing with socket.io-client@3.0.3 with react-native on android and I also see `[TypeError: undefined is not an object (evaluating 'packet.data.sid')]`

**Comment by darrachequesne** [comment]
@ivorcho this might mean that you are trying to reach a Socket.IO server in v2 with a client in v3, which is not possible.
