### ISSUE TITLE
client disconnected after emit a event with big data

### ISSUE THREAD

**Issue by cenfun** [socketio/socket.io-client#1399]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*

client will disconnect after client emit a event with big data

### Steps to reproduce (if the current behaviour is a bug)

client:
clientSocket.emit("data", "some string")  => works well

clientSocket.emit("data", window.__coverage__)  => failed, server never get event and client will disconnect

window.__coverage__ is a report which generated by Mocha, but it works before ("socket.io": "^2.3.0")

### Expected behaviour

*What is expected?*
emit event well

### Setup
- OS: Windows
- browser: Chrome
- socket.io version: 3.0.1

**Comment by darrachequesne** [comment]
What do you see in the network panel? Is there any error logged in the console? Any failing HTTP request?

Are you able to reproduce in the https://github.com/socketio/socket.io-fiddle project?

**Comment by cenfun** [comment]
@darrachequesne  thanks for your comments.
there is no error in the console, but I got some debug logs here

browser.js:183 socket.io-parser encoded {"type":2,"data":["data",{"type":"onMessage","data":"test in debug mode: refresh page to test it again"}],"options":{"compress":true},"nsp":"/"} as 2["data",{"type":"onMessage","data":"test in debug mode: refresh page to test it again"}] +0ms
browser.js:183 socket.io-client:manager writing packet ... +1ms
browser.js:183 socket.io-parser encoding packet ... +62ms
browser.js:183 socket.io-parser encoded ... +83ms
browser.js:183 engine.io-client:socket flushing 3 packets in socket +254ms
browser.js:183 engine.io-client:socket socket close with reason: "transport close" +35ms
browser.js:183 socket.io-client:manager onclose +286ms
browser.js:183 socket.io-client:manager cleanup +1ms
browser.js:183 socket.io-client:socket close (transport close) +27s
browser.js:183 socket.io-client:manager will wait 1393ms before reconnect attempt +1ms
browser.js:183 socket.io-client:manager attempting reconnect +1s
browser.js:183 socket.io-client:manager readyState closed +0ms
browser.js:183 socket.io-client:manager opening http://localhost:9878/ +0ms
...

after emit a event with big data, the socket close with reason "transport close", any idea?
browser.js:183 engine.io-client:socket flushing 3 packets in socket +254ms
browser.js:183 engine.io-client:socket socket close with reason: "transport close" +35ms

**Comment by cenfun** [comment]
more test

case worked (send 1000 kB data):

var getData = function(size) {
var list = [];
for (var i = 0; i < size; i ++) {
    list.push("123456789");
}
return list;
}
socket.emit("data", getData(**83300**))

engine.io-client:socket flushing 1 packets in socket +10s
Socket {ids: 0, acks: {…}, receiveBuffer: Array(0), sendBuffer: Array(0), flags: {…}, …}
browser.js:183 engine.io-client:socket socket receive: type "ping", data "undefined" +15s

case failed (send 1.0 MB data):

var getData = function(size) {
var list = [];
for (var i = 0; i < size; i ++) {
    list.push("123456789");
}
return list;
}
socket.emit("data", getData(**83400**))

engine.io-client:socket flushing 1 packets in socket +19s
Socket {ids: 0, acks: {…}, receiveBuffer: Array(0), sendBuffer: Array(0), flags: {…}, …}
browser.js:183 engine.io-client:socket socket close with reason: "transport close" +22ms
browser.js:183 socket.io-client:manager onclose +167ms


the only difference is data size, any data limit in new version socket.io?

**Comment by darrachequesne** [comment]
>  any data limit (guess 1024 kb?) in new version socket.io?

Yes, the `maxHttpBufferSize` has indeed been decreased to `1MB` by default: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#Saner-default-values

You can adjust the value when creating the server:

```js
const io = require("socket.io")(httpServer, {
  maxHttpBufferSize: 1e8
});
```

**Comment by cenfun** [comment]
@darrachequesne  got it, thanks for your help

**Comment by joacub** [comment]
same here
