### ISSUE TITLE
Multiple connection occours while initializing in React Native

### ISSUE THREAD

**Issue by ledmago** [socketio/socket.io-client#1402]
I am currently developing a project in React Native. In the version of 3.0.1 socket.io-client, I am trying to connect to a server, it connects multiple times maybe 5 times when the app is opening. I fixed this issue by downgrading the version to 2.1.1.

`Client connected -> ASkjAS35USD
Client connected -> WEIAUHB98
Client connected -> KALSKF876
Client connected -> LKKJHJSDNB90

Client disconnected (time out)-> ASkjAS35USD
Client disconnected (time out) -> WEIAUHB98
Client disconnected (time out) -> KALSKF876
`

**Comment by ved-numeroeins** [comment]
I am facing the same issue with an angular project. I am using version ```v3.0.3``` of ```socket.io-client```. It connects around 7 times and then starts disconnecting them automatically.

**Comment by guiseek** [comment]
it's also happening to me in version 3, i'm looking forward to using it due to the new features, but i had to limit myself to 2. because the problem doesn't happen

Angular Project also, like the @ved-numeroeins  project

**Comment by darrachequesne** [comment]
Hi! I'm not able to reproduce:

- https://github.com/socketio/socket.io/tree/master/examples/react-native
- https://github.com/socketio/socket.io/tree/master/examples/angular-todomvc

Which version of Socket.IO server are you using? (because you cannot reach a v2 server with a v3 client, and vice-versa).

**Comment by Hatko** [comment]
@darrachequesne was my issue - NestJS uses v2

**Comment by darrachequesne** [comment]
For future readers, I suspect this is due to a version incompatibility. I added a note here: https://socket.io/docs/v4/troubleshooting-connection-issues/#The-client-is-not-compatible-with-the-version-of-the-server-1
