### ISSUE TITLE
connect_error callback doesn't get called

### ISSUE THREAD

**Issue by binkoni** [socketio/socket.io-client#1404]
* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

connect_error callback doesn't get called

### Steps to reproduce (if the current behaviour is a bug)
client.js
```javascript
var io = require('socket.io-client');
var socket = io.connect('http://localhost:9000');

// Add a connect listener
socket.on('connect', function (socket) {
    console.log('Connected!');
});
socket.on('connect_error', () => console.log('connect error!!!'))
socket.emit('CH01', 'me', 'test msg');
```
```console
# none of servers is running on localhost:9000
curl localhost:9000
curl: (7) Failed to connect to localhost port 9000: Connection refused
node client.js
# prints nothing
```
### Expected behaviour

connect_error callback should be called

### Setup
- OS: Ubuntu 20.04 with kernel 5.4.67
- browser: None
- socket.io-client version: 3.0.1

**Comment by malsatin** [comment]
Same issue for me even in version 3.0.4

**Comment by darrachequesne** [comment]
Hi. That is due to that fact that in v3 the events emitted by the Manager are not forwarded to the Socket anymore (described in the migration guide [here](https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#The-Socket-instance-will-no-longer-forward-the-events-emitted-by-its-Manager)).

```js
socket.io.on("error", () => console.log('connect error!!!'));
```

It is not really intuitive though...

**Comment by malsatin** [comment]
In the migration guide, that you referred to, it is said that `connect_error` should still be emitted by the Socket and not the Manager

**Comment by darrachequesne** [comment]
@malsatin you are absolutely right. This should be fixed by https://github.com/socketio/socket.io-client/commit/53c73749a829b2c98d9a5e45c48f0ae5a22c056c (included in `socket.io-client@3.0.5`).
