### ISSUE TITLE
[types] SocketOptions whould include withCredentials

### ISSUE THREAD

**Issue by erwanv** [socketio/socket.io-client#1405]
According to the documentation:

```
// client-side
const io = require("socket.io-client");
const socket = io("https://api.example.com", {
  withCredentials: true,
  extraHeaders: {
    "my-custom-header": "abcd"
  }
});
```

However the types are not set accordingly:

```
Argument of type '{ withCredentials: boolean; }' is not assignable to parameter of type 'Partial<ManagerOptions> | Partial<SocketOptions>'.
  Object literal may only specify known properties, and 'withCredentials' does not exist in type 'Partial<ManagerOptions> | Partial<SocketOptions>'.

86     this.adminSocket = io(':8443/admin', { withCredentials: true });
```

**Comment by justLuiz** [comment]
extraHeaders too

`Argument of type '{ withCredentials: true; extraHeaders: { MyHeader: string; }; }' is not assignable to parameter of type 'Partial<ManagerOptions> | Partial<SocketOptions> | undefined'.
  Object literal may only specify known properties, and 'extraHeaders' does not exist in type 'Partial<ManagerOptions> | Partial<SocketOptions>'.`

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-client/commit/719307801a2170f02d3a16ab52752ac219ca4b6e (included in `socket.io-client@3.0.2`)
