### ISSUE TITLE
v3 disconnection of socket seems to close underlying connection.

### ISSUE THREAD

**Issue by david-fong** [socketio/socket.io-client#1406]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

After I upgraded to v3, when I call `socket.disconnect()` on either of the client or server sides, it seems that the Manager's underlying connection is also being closed- all other sockets using the same manager / underlying connection also get disconnected.

I don't know where to file this issue. Maybe it has root in engine.io v4?

[Here's a diff of my project during the upgrade](https://github.com/david-fong/snakey3/compare/f1b2f57...8802589). I apologize that it contains some unrelated changes as well. The main thing I mean to highlight is that I didn't make any changes to how I setup and manage connections (you can cmd+F for "disconnect", "close", "io.socket").

### Steps to reproduce (if the current behaviour is a bug)

Please see [this jsfiddle](https://github.com/david-fong/socket.io-fiddle).

### Expected behaviour

The v2 behaviour is that calling `socket.close()` on the clientside and on the serverside should only close that socket when a manager has multiple namespaces- it should not close every multiplexed socket under that socket's manger.

### Setup

- OS: Windows 10
- browser: Chrome 86.0
- socket.io version: 3.0.0

Observe behaviour difference when using socket.io v2 instead.

**Comment by david-fong** [comment]
I spent a bunch of time debugging my own code thinking I broke something :')

Looking forward to the fix! And thanks again for your hard work in starting v3.

**Comment by alextenev** [comment]
The "connecting" event is never fired on socket connection and doesn't fill the `connecting` array in manager:
https://github.com/socketio/socket.io-client/blame/master/lib/manager.ts#L599

When _destroy is called `if (this.connecting.length) return; this._close();` will always close the connection.

I don't see an issue in the client code. Maybe some bug on server side? In the server code I couldn't find any event named "connecting". Maybe that's the issue?

**Comment by darrachequesne** [comment]
@david-fong I could indeed reproduce the issue, thanks a lot for the detailed steps :+1:

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-client/commit/f8f60fc860f51aa6465fc32dd9275a8e1d22f05d (included in `socket.io-client@3.0.4`).

Again, thanks for the detailed report, that really helps!
