### ISSUE TITLE
Syntax error on IE11

### ISSUE THREAD

**Issue by cenfun** [socketio/socket.io-client#1407]
### You want to:

* [x] report a *bug*

### Current behaviour

*What is actually happening?*

SCRIPT1002: Syntax error
socket.io.js (15,8)

https://github.com/socketio/socket.io-client/blob/master/dist/socket.io.js#L15
`
})((() => {
`

arrow function is not supported by IE11, could you please fix it?

**Comment by darrachequesne** [comment]
That is really weird indeed, the arrow function is part of the webpackBootstrap code.

Note: It is correctly transpiled by babel in the [socket.io.min.js](https://github.com/socketio/socket.io-client/blob/master/dist/socket.io.min.js) bundle.

**Comment by cenfun** [comment]
@darrachequesne  thanks for your note, the socket.io.min.js bundle works for me.

BTW, did you used webpack 5? try following webpack option may fix this issue:
webpack.config.js
module.exports = {
    target: ["web", "es5"]
    ...
}
see more detail here: https://webpack.js.org/configuration/target/

**Comment by vsamotskiy** [comment]
Any updates here?

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-client/commit/8c08c5d5c3bd6dd5477ca11a2625314da57724cc (included on `socket.io-client@3.0.5`).
