### ISSUE TITLE
socket.io doesn't work with es6 imports

### ISSUE THREAD

**Issue by vedantroy** [socketio/socket.io-client#1409]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*

socket.io with es6 imports doesn't work / doesn't have a clear guide. Example:

```js
import io from 'socket.io'
```

In the above example, `io` has 3 fields: `Server`, `Socket`, `Namespace` (according to the TS types). It is not a function that accepts a http server as described here: https://socket.io/get-started/chat/

### Steps to reproduce (if the current behaviour is a bug)

The above line of code is all that is needed to reproduce.

### Expected behaviour

`io` should be a function that accepts a http server, or, there should be documentation detailing how to use ES6 imports with socket.io.

*What is expected?*

### Setup
- OS:
- browser:
- socket.io version: 3.0.3

**Comment by darrachequesne** [comment]
You are right! I added an example here: https://socket.io/docs/v3/server-initialization/#ES-modules
