### ISSUE TITLE
Connection shutdown throwing Uncaught TypeError: Cannot read property 'sid' of undefined

### ISSUE THREAD

**Issue by otaviobarros** [socketio/socket.io-client#1413]
[x] report a *bug*
[ ] request a *feature*

### Current behaviour

When initiating a connection, if there's a rejection (I.E.: WebSocket is closed before the connection is established), the connection is shut down and the following error message is shown:

```
Uncaught TypeError: Cannot read property 'sid' of undefined
 at Socket.onpacket (socket.js:189)
    at Manager.<anonymous> (index.js:21)
    at Manager.Emitter.emit (index.js:145)
    at Manager.ondecoded (manager.js:209)
    at Decoder.<anonymous> (index.js:21)
    at Decoder.Emitter.emit (index.js:145)
    at Decoder.add (index.js:117)
    at Manager.ondata (manager.js:201)
    at Socket.<anonymous> (index.js:21)
    at Socket.Emitter.emit (index.js:145)
```

### Steps to reproduce

I have simply instantiated a new connection with a WebSocket server with default settings passing a custom namespace.

### Expected behaviour

I expected this variable to have some check to see if it's undefined to prevent this error.

### Setup
- OS: Linux Mint 19
- browser: Tested in Google Chrome Version 87.0.4280.66 (Official Build) (64-bit)
- socket.io version: 3.0.3

### Other information

To fix, change the following code on socket.ts file on line 227, adding the optional chaining operator to validate the object:

```
// socket.ts - line 227

 case PacketType.CONNECT:
        const id = packet?.data?.sid;
        this.onconnect(id);
        break;
```

**Comment by s-light** [comment]
i encountered the same bug during my [experiments with quasar (vue) and featherjs](https://github.com/s-light/quasar_with_featherjs/blob/main/app/src/api.js#L4).
the error output i got:
``` 
11:42:30.196 Uncaught TypeError: packet.data is undefined
    onpacket socket.js:189
    exports index.js:21
    emit index.js:145
    ondecoded manager.js:209
    exports index.js:21
    emit index.js:145
    add index.js:117
    ondata manager.js:201
    exports index.js:21
    emit index.js:145
    onPacket socket.js:388
    setTransport socket.js:197
    emit index.js:145
    onPacket transport.js:103
    onData transport.js:96
    onmessage websocket.js:108
    addEventListeners websocket.js:107
    doOpen websocket.js:90
    open transport.js:43
    open socket.js:170
    Socket socket.js:94
    exports index.js:3
    open manager.js:111
    Manager manager.js:43
    lookup index.js:40
    mounted Index.vue:29
    VueJS 18
    init vue-router.esm.js:2795
    init vue-router.esm.js:2794
    updateRoute vue-router.esm.js:2223
    transitionTo vue-router.esm.js:2086
    confirmTransition vue-router.esm.js:2208
    step vue-router.esm.js:1892
    step vue-router.esm.js:1899
    step vue-router.esm.js:1899
    runQueue vue-router.esm.js:1903
    confirmTransition vue-router.esm.js:2203
    step vue-router.esm.js:1892
    step vue-router.esm.js:1896
    iterator vue-router.esm.js:2188
    resolve vue-router.esm.js:1935
    once vue-router.esm.js:2011
    promise callback*resolveAsyncComponents/</< vue-router.esm.js:1958
    flatMapComponents vue-router.esm.js:1979
    flatMapComponents vue-router.esm.js:1979
    flatMapComponents vue-router.esm.js:1978
    resolveAsyncComponents vue-router.esm.js:1914
    iterator vue-router.esm.js:2169
    step vue-router.esm.js:1895
    step vue-router.esm.js:1899
    step vue-router.esm.js:1899
    runQueue vue-router.esm.js:1903
    confirmTransition vue-router.esm.js:2196
    transitionTo vue-router.esm.js:2083
    init vue-router.esm.js:2786
    beforeCreate vue-router.esm.js:1242
    VueJS 4
    start client-entry.js:71
    async* client-entry.js:82
    js app.js:1019
    __webpack_require__ app.js:854
    fn app.js:151
    0 app.js:1173
    __webpack_require__ app.js:854
    checkDeferredModules app.js:46
    <anonymous> app.js:994
    <anonymous> app.js:997
socket.js:189

```

i just *hot-patched* `quasar_with_featherjs/app/node_modules/socket.io-client/build/socket.js` Line 188
```
case socket_io_parser_1.PacketType.CONNECT:
    const id = packet.data.sid;
    this.onconnect(id);
    break;
```
to
```
case socket_io_parser_1.PacketType.CONNECT:
    if (packet.data) {
        const id = packet.data.sid;
        this.onconnect(id);
    } else {
        console.log(packet);
    }
    break;
```
this way i get the log output
```
Object { type: 0, nsp: "/" }
```

has the check some other side impacts?
[link to lib/socket.ts#L228](https://github.com/socketio/socket.io-client/blob/master/lib/socket.ts#L228)

**Comment by darrachequesne** [comment]
Hi, it seems you are trying to reach a Socket.IO server in v2 with a client in v3, but they are not compatible.

We will add a check for this, as this is a common question: https://github.com/socketio/socket.io-client/commit/dddd63a48f52d558a96accfc7025e9a25b2bfc6a

**Comment by otaviobarros** [comment]
> Hi, it seems you are trying to reach a Socket.IO server in v2 with a client in v3, but they are not compatible.
> 
> 
> 
> We will add a check for this, as this is a common question: https://github.com/socketio/socket.io-client/commit/dddd63a48f52d558a96accfc7025e9a25b2bfc6a
> 
> 
> 
> 

Hi, @darrachequesne

The websocket server is using a NestJS package that is built in with SocketIO, so a must check if it's using v2 or v3, I really don't know.

When I have this information I'll come back here to add a new comment.

I think that's the issue tho, since I've downgraded the client version to v2 and it's working correctly.

Thank you!

**Comment by s-light** [comment]
you are right - with an downgraded client it works :-)

**Comment by darrachequesne** [comment]
An error will now be emitted when reaching a v2.x server: https://github.com/socketio/socket.io-client/commit/ec1f8c3474b54600420487a0554cb195cc78f2bc (included in `socket.io-client@3.0.4`).

I think this issue can now be closed.
