### ISSUE TITLE
Uncaught ReferenceError: Cannot access 'XMLHttpRequest' before initialization

### ISSUE THREAD

**Issue by takoyaro** [socketio/socket.io-client#1415]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

When importing the client in a React or Svelte project I'm getting the `Uncaught ReferenceError: Cannot access 'XMLHttpRequest' before initialization` error.

Issue is coming from engine.io-client:
```js
const hasXHR2 = (function() {
  const XMLHttpRequest = require("xmlhttprequest-ssl"); //<---- Devtools says the problem is here
  const xhr = new XMLHttpRequest({ xdomain: false });
  return null != xhr.responseType;
})();
```

### Steps to reproduce (if the current behaviour is a bug)

I can't provide a REPL because I keep getting:
`Could not find module in path: 'xmlhttprequest-ssl' relative to '/node_modules/engine.io-client/lib/transports/index.js'`
which somehow seems to be related to the issue described in **Current behaviour**.

The `Uncaught ReferenceError: Cannot access 'XMLHttpRequest' before initialization` will show up by simply importing the package like so: `import io from 'socket.io-client`.

_It doesn't matter what code you have after that line, it'll crash with the error._

### Expected behaviour
I'm expecting to be able to import the package.

### Setup
- OS: macOS & Windows give the issue
- browser: Edge, Chrome, Firefox and Safari give the issue.
- socket.io version: Client is 3.0.3 - Server is N/A

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
```
polling-xhr.js:18 Uncaught ReferenceError: Cannot access 'XMLHttpRequest' before initialization
    at polling-xhr.js:18
    at polling-xhr.js:21
    at main.ts:5
```

**Comment by dionysiusmarquis** [comment]
`socket.io-client/dist/socket.io.msgpack.min.js` works I guess 🤔

**Comment by takoyaro** [comment]
> `socket.io-client/dist/socket.io.min.js` and `socket.io-client/dist/socket.io.msgpack.min.js` works I guess 🤔

It does "work" in the sense that the error disappears but it does not work as Client<=>Server communication never establishes.
Simply importing Socket.io v2 "fixes" my issue...

**Comment by dionysiusmarquis** [comment]
@takoyaro `socket.io-client/dist/socket.io.min.js` is working for me, I can connect as expected. I think `msgpack` might also need additional server config.
Maybe you have also a server/client version mismatch? It's still an issue anyways, though

**Comment by llanas** [comment]
Hello, for SEO research I am adding the error message from Firefox that is slightly different : 
```
Uncaught ReferenceError: can't access lexical declaration 'XMLHttpRequest' before initialization
    hasXHR2 polling-xhr.js:18
    app polling-xhr.js:21
    <anonymous> bundle.js:6402
```

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/engine.io-client/commit/c22681542cc4b0acf2dc5ac2923fa3faa33b6008 (included in `engine.io-client@4.0.5`).
