### ISSUE TITLE
multiple connections react js

### ISSUE THREAD

**Issue by skyredmilad** [socketio/socket.io-client#1416]
Hi
I have a problem !!!

When io connect to the server, 
Server log over and over:
Like this:
New client connected
Client disconnected
New client connected
Client disconnected
Client disconnected
New client connected
Client disconnected
New client connected
New client connected
Client disconnected
Client disconnected
New client connected
New client connected
Client disconnected
New client connected
Client disconnected
New client connected
Client disconnected
New client connected
Client disconnected
Client disconnected
New client connected
Client disconnected
New client connected
New client connected
Client disconnected
Client disconnected
Client disconnected
Client disconnected
Client disconnected
Client disconnected

Server Code:
`io.origins('*:*');`
`io.on('connection', (socket) => {`
`  console.log('New client connected');`
`  socket.on('disconnect', () => {`
`    console.log('Client disconnected');`
`  });`
`});`

Client Code:
`import io from 'socket.io-client';`
`const socket = io.connect('http://192.168.1.34:3000');`

What is wrong in my code???
Please help me

**Comment by sajadgm** [comment]
I have this issues too

**Comment by sajadgm** [comment]
install socket.io-client@2.3.1

**Comment by huynhduc280519999** [comment]
> install socket.io-client@2.3.1

thanks. I had the same problem, but using it my problem was solved

**Comment by ZaidQ797** [comment]
I've the same issue in react-native even I'm using  `socket.io-client@2.3.1`

**Comment by vashajin** [comment]
Thanks Lod Solved..

**Comment by emericspiroux** [comment]
I don't think this is a good think to do. Downgrad version can be counter productive... 🤔 Any maintainer to understand what going wrong ?

**Comment by quammy** [comment]
> I don't think this is a good think to do. Downgrad version can be counter productive, typescript and babel-core are not up-to-date... 🤔 Any maintainer to understand what going wrong ?

socket.io-client now is 4.1.2
downgrade it to 2.3.1 is illogical.

**Comment by darrachequesne** [comment]
Hi all! It looks like a version incompatibility. Could you please check https://socket.io/docs/v4/client-installation/#Version-compatibility ?

**Comment by emericspiroux** [comment]
Yes @darrachequesne, I upgrading my server version to 4.1.2 after find a weird timeout on server socket.io's debug logs and it's work properly. 🎉 (I was into 2.x socket.io 🤦)

Conclusion beware of your server and client socket.io versions 😅 

If @skyredmilad confirm, we can close this issue.

**Comment by jassirahmed** [comment]
const [socket,setSocket]=useState()
useEfect(()=>{
   const socket = io.connect('Backend URL')
   setSocket(socket)
return()=>{
  socket.disconnect()
 }
})
