### ISSUE TITLE
fix typescript definitions

### ISSUE THREAD

**Issue by AndreyMiloserdov** [socketio/socket.io-client#1419]
v.3.0.3
1. SocketIO client options

What happen with old one SocketIOClientOptions?

At this moment works only:
```javascript
import io, { ManagerOptions } from 'socket.io-client;

const IOOptions: Partial<ManagerOptions> = {
  path: '/seacher',
  autoConnect: false,
  transports: ['websocket'],
};
```

Write `Partial<ManagerOptions>` is not good way.

2. Type of `io` now unknown

If write
```javascript
import io from 'socket.io-client';
...
this._socket = io(url, IOOptions);
````
There are will be an TS error for `io` like

```
import io
This expression is not callable.
  Type 'typeof import("/mnt/hdd/Projects/home/searcher/node_modules/socket.io-client/build/index")' has no call signatures.ts(2349)
```

Works only 'classic' way:
```javascript
import io from 'socket.io-client';
...
this._socket = (io as any)(url, IOOptions);
```

**Comment by keyyuki** [comment]
change to 
```
import {io} from 'socket.io-client';
```
and must (importance) update your server to socket.io 3.0.3, it take all day of my T_T

**Comment by darrachequesne** [comment]
Hi! Sorry to hear that the migration to v3 has not been as straightforward as we would like it to be.

Did you check https://socket.io/docs/v3/migrating-from-2-x-to-3-0/ (and especially the part about TypeScript [here](https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#The-Socket-IO-codebase-has-been-rewritten-to-TypeScript))? Is there something we could improve/make clearer?

> Write `Partial<ManagerOptions>` is not good way.

The other solution would be to make all fields optional, right? I didn't find any guidelines in the TypeScript in favor of Partial or optional fields.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by kmirojo** [comment]
Those documentation links worked for me, thank a lot! @darrachequesne

**Comment by edorgeville** [comment]
> Did you check https://socket.io/docs/v3/migrating-from-2-x-to-3-0/ (and especially the part about TypeScript [here](https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#The-Socket-IO-codebase-has-been-rewritten-to-TypeScript))? Is there something we could improve/make clearer?

@darrachequesne The import instruction for Typescript could be added here as well: https://socket.io/docs/v3/client-installation/#From-NPM
