### ISSUE TITLE
Support multiple protocol versions

### ISSUE THREAD

**Issue by kohtala** [socketio/socket.io-client#1424]
### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Current behaviour

If I upgrade client to version 3, it will fail to connect to a group of servers that I am unable to upgrade at the same time. If I upgrade server, the clients that I am unable to upgrade at the same time will fail.

I use Socket.IO between many different clients and servers. I can not upgrade everything at the same time, because I do not have all under my control and they have maintenance breaks at different times over many months.

Thus I have clients that need to be able to talk to many different versions of servers (and I have servers that are connected by clients of different versions).

### Expected behaviour

Client and server discover common protocol version and use that. Should be possible at least over two consecutive versions, or what ever span of versions is needed to cover possibly a maintenance period of a year.

### Setup
- OS: N/A
- browser: N/A
- socket.io version: 2 -> 3

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

I also wrote socketio/socket.io-protocol#21.

**Comment by fmagaldea** [comment]
👍 
A temporary compatibility with just previous version 2 would help migrations (could be with some warning message about deprecation) for projects than can't migrate both servers & clients at exactly the same moment.

**Comment by darrachequesne** [comment]
The v3 server is now able to communicate with v2 clients:

```js
const io = require("socket.io")({
  allowEIO3: true // false by default
});
```

Included in [socket.io@3.1.0](https://github.com/socketio/socket.io/releases/tag/3.1.0).
