### ISSUE TITLE
Node.js (typescript) with extraHeaders

### ISSUE THREAD

**Issue by majordo** [socketio/socket.io-client#1425]
* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
I've a socket.io-client running in a nodejs back-end and connecting to a socket.io server in another machine. I need the client to use the extraHeaders option but the typescript compiler return an error:
"Object literal may only specify known properties, and 'extraHeaders' does not exist in type 'ConnectOpts'"

```
const socket = io(
    "/",
    {
        extraHeaders: { "x-origin": "......" }
    });
```
The decumentation says extraHeaders is a node.js-only option, so what's wrong?
Thanks in advance

**PS** Without typescript it's working as supposed

### Setup
- OS: macOS 
- browser: node.js / typescript
- engine.io version: 3.0.4

**Comment by darrachequesne** [comment]
It seems the `@types/socket.io-client` package is indeed missing the `extraHeaders` option: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/socket.io-client/index.d.ts

Could you please open an issue over there?

Note: it should properly work with `socket.io-client@3` / `engine.io-client@4`

**Comment by darrachequesne** [comment]
Documentation: https://socket.io/docs/v3/client-initialization/#extraHeaders
