### ISSUE TITLE
socket.io.opts should not be private readonly

### ISSUE THREAD

**Issue by mhintzke** [socketio/socket.io-client#1427]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

I took a look at the [Migration Guide outlined here](https://socket.io/docs/v3/migrating-from-2-x-to-3-0/) and it looked pretty straightforward but I am beginning to think this will be more work than I thought.

There is some documentation that outlines how to deal with transports and reconnects [that exists here](https://socket.io/docs/v3/client-api/index.html#With-websocket-transport-only), but due to [this change here](https://github.com/socketio/socket.io-client/commit/697bea2d81735c4ecde42c80402e2e7abfb5fb10)
 the `Manager.opts` field is now private and so I cannot use the same strategy and I didn't see any obvious replacement API.

Is the best way to bypass for now just to bypass the type-system with some casts to `any`? I'd rather not do that but will if there is no immediate way to fix this.

### Steps to reproduce (if the current behaviour is a bug)

No need to reproduce as its a build error not a runtime error.

### Expected behaviour

That the same API is exposed in some way or the documentation and Migration guides are updated to reflect the changes to the API.

### Setup
- OS: any
- browser: any
- socket.io version: 3.0.4

**Comment by MickL** [comment]
Same error. To clearify:

As stated in the [documentation](https://socket.io/docs/v3/client-api/#With-query-option) query options can be set by setting `socket.io.opts` but `opts` is private and readonly.

Workaround @mhintzke : Just add `// @ts-ignore` above that:

```
// @ts-ignore
this.socket.io.opts.query = {token};
```

Could you rename the issue to "socket.io.opts should not be private readonly"?

**Comment by mhintzke** [comment]
Ok updated the title.

**Comment by MickL** [comment]
PR is merged. Waiting for it to be published to npm :)

**Comment by darrachequesne** [comment]
Fixed by https://github.com/socketio/socket.io-client/commit/fe97243fab02cd80fc1116e8f4aeca02951dac75 and included in `socket.io-client@3.1.0`. Thanks!
