### ISSUE TITLE
io函数解析url错误

### ISSUE THREAD

**Issue by zhangguanyin** [socketio/socket.io-client#1428]
https://127.0.0.1:443/im/user?userid=36f8798d65ff4248b1df2caa0222e80e&orgi=cskefu&session=b7591462-fdb9-414c-a9d7-01531a4f3643

解析出的uri.path值为空字符串

导致建立连接失败
WebSocket connection to 'wss://163.com%26email%3Dhttp/socket.io/?EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
![9999999999](https://user-images.githubusercontent.com/41132383/102862709-7846e180-446c-11eb-95ae-d089bae06535.png)

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
