### ISSUE TITLE
[HOWTO] Simulate or manually fire all disconnection reasons

### ISSUE THREAD

**Issue by matiaslopezd** [socketio/socket.io-client#1431]
Hi! How is possible to simulate or fire the five reasons for the disconnection event? I'm working on automated testing of disconnection behavior, but I can't manually fire disconnection event, passing the reason.

**I'm working only with websocket transport, not long-polling.**

The first two reasons are obvious, but the rest I'm trying using [http-proxy](https://github.com/http-party/node-http-proxy) to connecting through him and then closing the port. But not works :disappointed: 

Finally, the only way to get a `ping timeout` is blocking the port I'm using in the socket.io app, directly in iptables, then unblocking to reconnect.

All of this modifying the network of the websocket connection.

Exist something in `socket.io-client` that can I use to force that disconnection reasons? 
Like `socket.manager.events.disconnect`?

Reason | How to fire |
------ | ----------- | 
`io server disconnect` | Using [socket.disconnect()](/docs/v3/server-api/#socket-disconnect-close) :heavy_check_mark: 
`io client disconnect` | Using [socket.disconnect()](/docs/v3/client-api/#socket-disconnect) :heavy_check_mark: 
`ping timeout` | :question: 
`transport close` | :question:
`transport error` | :question: 

Thanks!

**Comment by hyperknot** [comment]
I found no way to actually simulate these in a browser. The only reliable approach to simulate a real disconnect is to use a Virtual Machine and disconnect network over there.

**Comment by matiaslopezd** [comment]
Mmmh the thing is when I want to automate testing of this, use VM is too complex and slow. Currently, I'm using mocha but can't simulate a `ping timeout`, `transport close`, and `transport error`. I'll try to simulate the next week in codesandbox with [http-proxy](https://github.com/http-party/node-http-proxy) but with another approach.

Now I'm doing this:

**disconnection.test.js**
```js
const proxy = require('../utils/proxy-server')(port);

describe('Check disconnection behavior', function () {

    before('Start proxy server', function (done) {
      this.internet = proxy.server.listen(3535);
      this.internet.on('close', () => console.log('"Internet" is down.'));
      this.internet.once('listening', done);
    });

    it('Check disconnection', async function (){
      return new Promise(async (resolve) => {
        const id = await createACall(this.token);
        const options = {...wsParams};
        options.query.accessToken = this.token;
        options.query.id = id;
        const socket = io(hostname(URL, 3535), options);
        console.log(socket);
        socket.on('connect', () => console.log('connected'));
        socket.on('status:ready', () => {
          proxy.proxy.close();
          proxy.server.close();
        });
        socket.on('disconnect', (reason) => {
          console.log(reason);
          resolve();
        });
      });
    }).timeout(timeoutWs);
});
```

**proxy-server.js**
```js
const http = require('http'), httpProxy = require('http-proxy');

module.exports = function (port = 3030, host = 'http://localhost') {
  const options = { target: `${host}:${port}` };
  const proxy = httpProxy.createProxyServer({});
  const server = http.createServer(function (req, res){
    proxy.web(req, res, options);
  });
  server.on('upgrade', (req, socket, head) => proxy.ws(req, socket, head, options));
  proxy.on('close', () => console.log('Websocket disconnected'));
  return { server, proxy };
}
```

**Comment by darrachequesne** [comment]
Hi!

- `transport close` errors can happen when the active transport (either HTTP long-polling or WebSocket) is closed, for example when:
  - the user looses connectivity
  - the user switches from Wifi to 4G
  - the server is stopped/restarted

The last case can be simulated with:

```js
const io = require("socket.io")(3000);
const socket = require("socket.io-client")("http://localhost:3000", {
  transports: ["websocket"]
});

socket.on("connect", () => {
  io.close();
});

socket.on("disconnect", (reason) => {
  console.log(`disconnect because ${reason}`); // disconnect because transport close
});
```

In the source code, it means the [Transport#onClose](https://github.com/socketio/engine.io-client/blob/4.0.6/lib/transport.js#L111) method is called.

- `transport error` is a bit similar to `transport close`, but it's when the active transport (either HTTP long-polling or WebSocket) is closed unexpectedly

It can be simulated by enabling the HTTP long-polling transport only (the HTTP request is cancelled when the server is closed, hence the error).

```js
const io = require("socket.io")(3000);
const socket = require("socket.io-client")("http://localhost:3000", {
  transports: ["polling"]
});

socket.on("connect", () => {
  io.close();
});

socket.on("disconnect", (reason) => {
  console.log(`disconnect because ${reason}`); // disconnect because transport error
});
```

In the source code, it means the [Transport#onError](https://github.com/socketio/engine.io-client/blob/4.0.6/lib/transport.js#L27) method is called.

- `ping timeout` errors should be rarer, it might mean that:
  - the connection is in an unknown state (not really closed, but not valid either)
  - the user has left the page between two HTTP long-polling requests
  - one side is overloaded and becomes unresponsive

You can simulate it by ignoring the ping packets on the client side:

```js
const io = require("socket.io")(3000, {
  pingInterval: 2500,
  pingTimeout: 500
});

const socket = require("socket.io-client")("http://localhost:3000");

socket.on("connect", () => {
  socket.io.engine.onPacket = () => {};
});

socket.on("disconnect", (reason) => {
  console.log(`disconnect because ${reason}`); // disconnect because ping timeout
});
```

**Comment by matiaslopezd** [comment]
@darrachequesne Nice! This would be excellent to add to the documentation! :clap: :clap:
