### ISSUE TITLE
Network disconnect / offline mode not detected

### ISSUE THREAD

**Issue by hyperknot** [socketio/socket.io-client#1433]
**Describe the bug**
When turning off the wireless network on my MacBook, the client does not detect the disconnect event. It waits a possibly long time until the ping detects it. Using Websockets.

**To Reproduce**
Any basic example will replicate it, for example https://socket.io/demos/chat/ replicates it.

*Server*
Does not matter, it is disconnected on the client.

Socket.IO client version: `3.0.4`

*Client*

Default options, only `auth` is specified in options.

**Expected behavior**

When disconnecting the network, the socket should detect a disconnect event.
The browser correctly recognizes such event, the following triggers immediately.
```
window.addEventListener('offline', () => {alert('offline')});
```
`navigator.onLine` is also correctly showing false.

However SocketIO client believes it is still connected, the WS connection is sending messages like everything was connected. Only after the next ping event it recognizes that something is wrong and fires the disconnect event.

**Platform:**
 - Device: Macbook Pro
 - OS: macOS 10.15.7
 - Browser: latest Chrome and Firefox

**Comment by hyperknot** [comment]
As a workaround, is there a way to force-send a ping event?

**Comment by hyperknot** [comment]
So far I came up with this workaround, this seems to work.

```
    window.addEventListener('offline', () => {
      if (
        this.socket &&
        this.socket.io &&
        this.socket.io.engine &&
        this.socket.io.engine.transport
      ) {
        this.socket.io.engine.transport.close()
      }
    })
```

How do everyone else handle this problem?

**Comment by dverzolla** [comment]
Fixed in 3.0.5: https://github.com/socketio/socket.io-client/commit/bcdd3bef855313c5a252cfc8eb80aeeb834a99f9#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed

**Comment by darrachequesne** [comment]
@dverzolla I don't think this is fixed yet.

@hyperknot I could indeed reproduce, thanks. That's really weird, one could expect that the TCP connection would be closed when the network is turned off, but that does not seem to be the case.

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/engine.io-client/commit/c361bc691f510b96f8909c5e6c62a4635d50275c, included in `socket.io-client@4.0.0`.

Thanks for the detailed bug report :+1:
