### ISSUE TITLE
Socket.io-client - auth object does not exist in type ConnectOpts (Typescript)

### ISSUE THREAD

**Issue by mason5991** [socketio/socket.io-client#1438]
From the documentation, it said I can use the `auth` object inside options when using manager or io. However, It reports the types does not contain `auth` object inside `ConnectOpts`.

```
const socket = io(`${process.env.REACT_APP_BACKEND_URL!}`, {
  auth: {
    token: "123"
  },
  query: {

  }
});

```
![image](https://user-images.githubusercontent.com/18270432/105118980-5cd20380-5b0a-11eb-9ef1-568c9a12052e.png)

Current package:
"@types/node": "^14.14.22",
"socket.io-client": "^3.1.0"

**Comment by darrachequesne** [comment]
I think you are importing `@types/socket.io-client`, which is useless in v3 since the types are included in the `socket.io-client` package.

**Comment by darrachequesne** [comment]
I added a note at the bottom here: https://socket.io/docs/v3/client-installation/#From-NPM
