### ISSUE TITLE
How to pass cookie header from react native application

### ISSUE THREAD

**Issue by ursnj** [socketio/socket.io-client#1441]
**Describe the bug**
I want to pass cookie header from react native application as both my web and mobile is using same backend.

can someone help me on how to pass this ??? 

**To Reproduce**

Please fill the following code example:

Socket.IO server version: `2.3.1`

**Comment by darrachequesne** [comment]
It seems you need to explicitly set `withCredentials` to `false`:

```js
import { io } from 'socket.io-client';

const socket = io("your url", {
  withCredentials: false,
  extraHeaders: {
    cookie: 'test=1234'
  }
});
```

(tested with `react-native@0.61.4` and `socket.io-client@2.3.0`)

**Comment by Sunil16202** [comment]
@darrachequesne am doing the same things but I am not able to get the extraHeaders in the server side(nodejs).

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
