### ISSUE TITLE
Accept `port` as `number`

### ISSUE THREAD

**Issue by aghArdeshir** [socketio/socket.io-client#1444]
**Is your feature request related to a problem? Please describe.**
I believe defining `port` on `io` client library seems a better suit if it's type was a number. Probably most people using `socket.io` on frontend and backend use a common variable for port, e.g. `export const SERVER_PORT = 3000` in my case. And with current implementation and TypeScript definitions I am not allowed to pass `SERVER_PORT` directly to `io` and need to do a manual `.toString()` on it. (or keep my server port in two places)

**Describe the solution you'd like**
I think it's best for `socket-io.client`'s exported property `io` to accept `port` as both `number` and `string` and convert number to string underneath if necessary.

**Describe alternatives you've considered**
 When developers think of `port`, they think of `number`s. I even believe a breaking change wouldn't be bad at all

**Additional context**

![image](https://user-images.githubusercontent.com/5755214/108438177-f7397a00-7263-11eb-87d3-3335ca8ccd53.png)

**Comment by saurabhmehta1601** [comment]
I am new to open source and  I want to give my contribution  ❤. Maybe I can fix this bug .Is someone else working on it ??

**Comment by Ardeshir81** [comment]
@saurabhmehta1601 I believe if the issue gets accepted as a valid issue, meaning a change that the library would embrace, someone will say something here. As nobody's said something yet, there may be a chance of the library not willing to accept such a change at all, meaning your work would be of no use. But still, no, nobody's working on it.

I appreciate your interest in this.

**Comment by darrachequesne** [comment]
Hi! Yes I believe the typings are incorrect, it should be a number, like [here](https://nodejs.org/api/http.html#http_http_request_options_callback).

@saurabhmehta1601 I'll be happy to merge your pull request, if you have the time :+1:

**Comment by Ardeshir81** [comment]
Thanks @darrachequesne  That's good news :newspaper:

Thanks @saurabhmehta1601  for working on it

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/engine.io-client/commit/8f68f77825af069fe2c612a3200a025d4130ac0a, which is included in `socket.io-client@4.4.0`.
