### ISSUE TITLE
HttpOnly cookie is not getting set on the handshake request in Jest

### ISSUE THREAD

**Issue by marnixhoh** [socketio/socket.io-client#1445]
**Describe the bug**
I am using the React socket.io-client package to connect to a socket.io websocket. The authentication of the entire application is based on httpOnly cookies (i.e. these cookies can not be accessed through clientside Javascript).

When running the app in developement, everything works as expected: the socket client sets the httpOnly cookie on the handshake request and the server authenticates this.

But when running the Jest test suite, the httpOnly cookie no longer gets set on the handshake.

Note that when making http requests (using fetch) in Jest, the httpOnly cookie DOES get set as expected. So for whatever reason, the socket.io-client is not setting the httpOnly cookie on the handshake request in Jest...

Any help or suggestions would be greatly appreciated! Thank you

Socket.IO server version: `^3.1.0`
Socket.IO client version: `^3.1.1`

**Comment by marnixhoh** [comment]
For a minimal reproducible example, please see https://github.com/socketio/socket.io/issues/3812#issuecomment-783493953

**Comment by darrachequesne** [comment]
This was added in the documentation here: https://socket.io/how-to/deal-with-cookies#nodejs-client-and-cookies

Please reopen if needed.
