### ISSUE TITLE
Cookie header not set

### ISSUE THREAD

**Issue by Rc85** [socketio/socket.io-client#1449]
**Describe the bug**

Using `express-session` and the cookie header is not set when I do a `socket.emit` from client.

**To Reproduce**

Please fill the following code example:

Socket.IO server version: 3.1.2

Socket.IO client version: 3.1.2

**Expected behavior**

**Platform:**
 - Device: Desktop Chrome
 - OS: Windows 10

**Additional context**

Reverted back to `socket.io@2.4.1` and `socket.io-client@2.4.0` and the cookie is in the request header.

**Comment by darrachequesne** [comment]
For future readers:

Please check the documentation here: https://socket.io/how-to/use-with-express-session
