### ISSUE TITLE
Plain vanilla JS approach not working anymore

### ISSUE THREAD

**Issue by neilyoung** [socketio/socket.io-client#1452]
Hi,

could you please help me to understand, why a "plain vanilla JS approach" stopped working with version 3.0.0? Need to say, that my Node JS socket.io server is of version 2.2.0.

I'm just taking the `socket.io.js` file out of the `dist` repo, having a simple `index.html`, which loads it, and a js file which tries to open a Node JS socket.io server.

./socket.io.js

Content of https://github.com/socketio/socket.io-client/blob/4631ed6ab38a7760a983571d36e83ad5294b52fc/dist/socket.io.js

index.html

```html
<script src="./socket.io.js"></script>
<script defer  src="./index.js" charset="utf-8"></script>
```

./index.js

```js
const socket = io("https://webrtcdemo.ddns.net/licensed")
socket.on('connect', () => {
    console.log("connected")
    debugger
});
```

This works, the breakpoint is hit and the console log is printed.

The same does not work anymore starting with https://raw.githubusercontent.com/socketio/socket.io-client/b7e07ba633ceb9c1dc94cc894c10b9bfca536c7a/dist/socket.io.js 

The connection is not established anymore and an endless reconnect happens.

**Comment by neilyoung** [comment]
The problem seems to be the "outdated" server (well, the version change has happened 2020) and the no-CORS support of it.  https://socket.io/docs/v3/handling-cors/

I find this a bit problematic, because it means, you will not be able to connect from > 3.0 clients to < 3.0 servers anymore. Please confirm that this is intended.

**Comment by darrachequesne** [comment]
> you will not be able to connect from > 3.0 clients to < 3.0 servers anymore

Yes, this is expected.

Please see the documentation here: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/

**Comment by neilyoung** [comment]
Thanks for the confirmation and the link.
