### ISSUE TITLE
The visibility of the "auth" property prevents it from being updated 

### ISSUE THREAD

**Issue by knona** [socketio/socket.io-client#1453]
**auth** property is set as private and readonly.
Therefore, we can't update it as the documentation show us.

**To Reproduce**

Socket.IO client version: `4.0.0`

*Client*

I get a Typescript error here :
```ts
socket.auth.token = "efgh";
socket.disconnect().connect();
```

**Expected behavior**
We should have at least a setter to update this property.

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-client/commit/c15022347c662dc31ee0a3d89cde23641f029783.
