### ISSUE TITLE
`sendBuffer` should be emptied before `emit`

### ISSUE THREAD

**Issue by dwelle** [socketio/socket.io-client#1458]
**Describe the bug**

Right now it's possible to `emit` a message before `sendBuffer` is emptied after reconnection. This will result in out-of-order messages arriving on the server.

**To Reproduce**

Upon `disconnect`, `emit` a message `A`, and upon `connect`, emit a message `B`. The messages will be sent in this order: `B`, `A`.

Consider a case where `A` is a `roomLeave` message and `B` is a `roomJoin` message, in which case the order is significant.

This is because the `onconnect` handler notifies event subscribers before emptying the buffer:

https://github.com/socketio/socket.io-client/blob/2edf0f308c8b969928124d02e81e21c456f736a7/lib/socket.ts#L387-L388

While currently this seems to be the only code path in which this behavior manifests, it may also affect other code paths in the future so I think the problem generalizes to this issue's title.

Socket.IO client version: 4.x.x

**Expected behavior**

`emit()` should check if `sendBuffer` contains messages and send those beforehand.

**Comment by darrachequesne** [comment]
I could indeed reproduce, thanks. It seems that this is very old bug: https://github.com/socketio/socket.io-client/commit/d523a25cc036556e649d4cb8df937e6d6395992e

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-client/commit/34f822f783c6985039c0733a96d1fab8f01b1edf, included in `socket.io-client@4.0.2`.

Thanks for the report :+1:
