### ISSUE TITLE
Hability to reconnect with a different base url

### ISSUE THREAD

**Issue by LeonardoRick** [socketio/socket.io-client#1466]
It's pretty hard to reconnect from a client to a different url if you have multiple listeners already working. All of them stop working since nowadays we need to redefine the `socket` variable and for them to work, we need to call them again.

**Solution**
``` javascript
const myAnotherUrl = "http://localhost:8080"
this.ioSocket =  socketio.io(config.url, config.options);
this.ioSocket.connect() // connecting with config.url
this.ioSocket.url = myAnotherUrl
this.ioSocket.disconnect()
this.ioSocket.connect() // connecting with myAnotherUrl
```

then, when I call

**Comment by darrachequesne** [comment]
You should already be able to do that:

```js
this.ioSocket.io.uri = myAnotherUrl;
```

I don't think this is properly documented though.

**Comment by LeonardoRick** [comment]
Wish all issues were solve like that. Thanks a lot!
