### ISSUE TITLE
open tow browser,first is ok,but second is 400 bad request

### ISSUE THREAD

**Issue by bizhen-yang** [socketio/socket.io-client#1470]
socket.io-client 2.3.0
flask_socketio 4.3.1

when I open one  browser, request is ok, but open second,request is `{"sid":"4c47129b0dca4d6988d458fe3caf0b06","upgrades":[],"pingTimeout":60000,"pingInterval":25000}`,when first browser,second browser can connect

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
