### ISSUE TITLE
Inconsistent use of closeOnBeforeunload and closeOnBeforeUnload

### ISSUE THREAD

**Issue by hkremss** [socketio/socket.io-client#1472]
**Describe the bug**
The new 'closeOnBeforeUnload' feature introduced in Socket.io 4.1.0 (socket.io-client@3.1.1) does not work as expected, because its implemented as 'closeOnBefore[u]nload' in the code. Note the 'U' vs. 'u'.

**To Reproduce**
The value of closeOnBeforeUnload (with capital U) will just have no effect with Socket.io 4.1.0

**Expected behavior**
Code and documentation (and [release note](https://socket.io/blog/socket-io-4-1-0/#Add-a-way-to-ignore-the-beforeunload-event)) should be consistent. 

**Platform:**
Any

**Additional context**
-

**Comment by darrachequesne** [comment]
@hkremss you're absolutely right, there was indeed a typo in the release notes. Thanks!
