### ISSUE TITLE
reconnect event fails to emit

### ISSUE THREAD

**Issue by ngot** [socketio/socket.io-client#1473]
**Describe the bug**

`reconnect` event does not trigger.

**To Reproduce**

Turn off wifi, wait a while, then turn on. The `reconnect` event dose not trigger. It triggers in version **2**.

Socket.IO server version: `4.1.2`

*Server*

```js
import { Server } from "socket.io";

const io = new Server(3000, {});

io.on("connection", (socket) => {
  console.log(`connect ${socket.id}`);

  socket.on("disconnect", () => {
    console.log(`disconnect ${socket.id}`);
  });
});
```

Socket.IO client version: `4.1.2`

*Client*

```js
import { io } from "socket.io-client";

const socket = io("ws://localhost:3000/", {});

socket.on("connect", () => {
  console.log(`connect ${socket.id}`);
});

socket.on("reconnect", () => {
  console.log(`reconnect`);
});
```

**Expected behavior**

`reconnect` should be triggered as expected.

**Comment by ngot** [comment]
To help reproduce locally:
- set transports: ['polling'] in client.
- use Chrome dev tool's network throttle to offline the page.

**Comment by darrachequesne** [comment]
The `reconnect` event was indeed removed in v3.

Please check https://socket.io/docs/v4/migrating-from-2-x-to-3-0/#The-Socket-instance-will-no-longer-forward-the-events-emitted-by-its-Manager

You can either:

- listen to the `reconnect` event on the Manager

```js
socket.io.on("reconnect", () => { /* ... */ });
```

- or listen to the `connect` event on the Socket

```js
socket.on("connect", () => { /* ... */ });
```

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
