### ISSUE TITLE
Socket.io no longer work with version 4 (400 Bad Request)

### ISSUE THREAD

**Issue by romain-neil** [socketio/socket.io-client#1474]
**Describe the bug**
socket.io was upgraded from version 3.x to 4.1.2 and when I try to launch my demo chat site, the developer console dosen't stop to show 400 bad request when trying to reach http://localhost:8080/socket.io/?EIO=4&transport=polling&t=Ne6LT_E

**To Reproduce**

Please fill the following code example:

Socket.IO server version: `4.1.2`

Socket.IO client version: `4.1.2`

*Client*

```js
let socket = io('ws://localhost:8080');

socket.on("connect", () => {
  console.log(`connect ${socket.id}`);
});

socket.on("disconnect", () => {
  console.log("disconnect");
});
```

**Expected behavior**
The code work, and there is no 400 error

**Platform:**
 - OS: Windows 10

**Additional context**
![image](https://user-images.githubusercontent.com/3512803/121816277-f39a8a80-cc7a-11eb-8927-3c7648a74a21.png)

Note: I am unable to find any informations about error code 3 on the website

Thanks !

**Comment by darrachequesne** [comment]
A "Bad request" response means there was an issue during the handshake.

You can gather more details with:

```js
io.engine.on("connection_error", (err) => {
  console.log(err);
});
```

Reference: https://socket.io/docs/v4/server-instance/#Server-engine

Could you please provide the code you are using on the server side?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by HazemNB** [comment]
i have been experiencing that same issue

**Comment by HazemNB** [comment]
code: 5, message: "Unsupported protocol version"}
code: 5
message: "Unsupported protocol version"

**Comment by saicharanreddythummala** [comment]
#Error
![image](https://user-images.githubusercontent.com/95035414/209575283-c3085b8b-900f-4b63-9112-4a9d924767aa.png)

##Client
![image](https://user-images.githubusercontent.com/95035414/209575347-7b71f4b8-d35e-4134-8c60-1b33a4a4c15e.png)

##Server
![image](https://user-images.githubusercontent.com/95035414/209575417-eeac53f1-3859-4ee4-953b-fa2eaab862d7.png)

I am not able to figure out the error. This only happens when the server is hosted on Vercel/Heroku. But when I run it locally there is no error. Kindly help me out!!!

Thanks

**Comment by al1ych** [comment]
Any updates on the issue?

**Comment by darrachequesne** [comment]
@al1ych could you please detail your issue? It seems this thread contains various issues:

- "Unsupported protocol version" means that versions of the client and the server do not match. Compatibility with previous versions of the client (2.x) can be enabled with the `allowEIO3` option

Reference: https://socket.io/docs/v4/server-options/#alloweio3

- Vercel does not support WebSocket

Reference: https://vercel.com/guides/do-vercel-serverless-functions-support-websocket-connections

See also: https://socket.io/docs/v4/troubleshooting-connection-issues/

**Comment by moxpatwa** [comment]
Hello,

I am getting HTTP Error 400 around.

I am using socket-io 4.7.2 and socket-io-client 4.7.2 and I am using react for front end this is my client side settings
<img width="834" alt="Test png" src="https://github.com/socketio/socket.io-client/assets/64414384/15aadc73-174b-42c6-a673-9e858212923d">

in server side using node is which setting describe below:
![Test02 png](https://github.com/socketio/socket.io-client/assets/64414384/5e404092-5664-4ea5-b68a-34a1a9b06c22)

Can you suggest me solutions for that?

**Comment by moxpatwa** [comment]
@darrachequesne any sugesstions?

**Comment by moxpatwa** [comment]
@romain-neil  any update ?

**Comment by alok-mishra143** [comment]
[GET] /api/socket/io?EIO=4&transport=polling&t=P3mzKcY status=400


i am facing the same error running on localhost it working find but on vercel it show that log 
![image](https://github.com/user-attachments/assets/6ec3e795-af96-4a1e-9b93-b3d348f5979b)
