### ISSUE TITLE
Event:'ping' not firing on Manager on 4.1.2

### ISSUE THREAD

**Issue by tonymccallie** [socketio/socket.io-client#1475]
We are needing to programmatically catch the 'ping' event. The documentation indicates this is possible here:
https://socket.io/docs/v4/client-api/#Event-%E2%80%98ping%E2%80%99
But we are unable to do this. All other Manager events are working fine. 

Socket.IO client version: `4.1.2`

*Client*

```js
    this.socket.io.on('{error|reconnect|etc}', (error) => {
      //all work great
    });

    this.socket.io.on('ping', () => {
      console.warn('ping');
      //never fires on 4.1.2
    });
```

I couldn't find any know issues with this. Is it a known bug?

**Comment by darrachequesne** [comment]
I could indeed reproduce the issue, we'll publish a fix as soon as possible.

**Comment by tonymccallie** [comment]
Thanks!

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/engine.io-client/commit/589d3ad63840329b5a61186603a415c534f8d4fc, included in `engine.io-client@5.1.2` / `socket.io-client@4.1.3`.

Replit: https://replit.com/@socketio/socketio-minimal-example-ping-issue

Thanks!
