### ISSUE TITLE
socket.io.js(3.x,4.x) can't  interact with servesocketio server(netty-socketio)

### ISSUE THREAD

**Issue by jmbkeyes** [socketio/socket.io-client#1476]
**Describe the bug**
I start netty-socketio server, try to use socket.io.js(3.x,4.x) to connect the server.  The connection is established between client and server, but amazing things has happened as follows.
1. server received two connection events.
2. server can't receive message from client, and client can't receive message from server.

But when I downgrade to version under version 3.0(e.g. 2.4.0), all things works as excepted.

**Comment by darrachequesne** [comment]
`netty-socketio` is only compatible with Socket.IO v2.

See also:

- https://github.com/mrniko/netty-socketio/issues/805
- https://github.com/mrniko/netty-socketio/issues/810

**Comment by jmbkeyes** [comment]
thanks for your reply.
