### ISSUE TITLE
Android Socket keeps disconnecting

### ISSUE THREAD

**Issue by nikesh8** [socketio/socket.io-client#1478]
I have implemented a socket in my chat application and I have implemented room subscription on one-to-one messages but unfortunately, it won't work for android apps but it works fine for iOS apps.

"socket.io-client": "2.2.0",
"react": "16.13.1",
"react-native": "0.63.3",

**Comment by darrachequesne** [comment]
For future readers:

Please check our guide with React Native here: https://socket.io/how-to/use-with-react-native

Please reopen if needed.
