### ISSUE TITLE
websocket logs not showing

### ISSUE THREAD

**Issue by pankajgupta1** [socketio/socket.io-client#1480]
**Describe the bug**

My project is in React JS. In that socket is working fine. Some days before the logs were showing, but now stopped showing in ws tab of network tab of chrome devtools. But this thing happening for not all pc. on some pc those logs are showing but on some not. 

On the PCs for which the logs are not showing, for other website their websocket logs are showing. 

Not able to understand where is the problem. Please help.

**Comment by darrachequesne** [comment]
For future readers:

Please check our troubleshooting guide here: https://socket.io/docs/v4/troubleshooting-connection-issues/

Please reopen if needed.
