### ISSUE TITLE
Vulnerabilities High/Critical for engine.io-client > xmlhttprequest-ssl

### ISSUE THREAD

**Issue by dotMortis** [socketio/socket.io-client#1484]
The dependent package "engine.io-client" has a high and a critical vulnerability in its own dependent package "xmlhttprequest-ssl".
 
![image](https://user-images.githubusercontent.com/29275165/128184827-dd791fcd-bba9-4ce6-92b8-5721c53fc05a.png)

**Comment by darrachequesne** [comment]
Hi! This issue should be fixed now. Which version of `socket.io-client` is affected?

**Comment by dotMortis** [comment]
Hey, oh sry I missed the update. Was on "4.1.2".
