### ISSUE TITLE
bug(typings): async event listeners

### ISSUE THREAD

**Issue by roikoren755** [socketio/socket.io-client#1486]
**Describe the bug**
Trying to update `socket.io-client` from v3.1.3 to v4.1.3 in one of my typescript projects. I have async event listeners defined at the client side. This code worked fine in v3, and might be the same in v4, but the `@typescript-eslint/no-misused-promises ` rule started reporting that the `socket.on` callback parameter should be a function returning `void`, and not `Promise<void>`.

According to at least [one place](https://socket.io/docs/v4/listening-to-events/#Error-handling) in the documentation, it should be possible for listeners to return `Promise<void>`, and not only `void`.

If I use the `Socket` class' generics to defined possible listen and emit events, I can return whatever I want in the listener, provided it fits the return type I define.

**To Reproduce**
Simply use an async listener anywhere. The typescript compiler will be ok with it, but `@typescript-eslint/no-misused-promises` flags it as an issue.

**Expected behavior**
The default listener type, provided by `FallbackToUntypedListener`, should accept `Promise<void>` as a return type.

**Comment by darrachequesne** [comment]
Hi! I could reproduce the issue, I'm working on this.

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-client/commit/66e00b7dd7c4a09072cfd84c78e6e15ec52039f5 and https://github.com/socketio/socket.io/commit/ccfd8caba6d38b7ba6c5114bd8179346ed07671c.

Thanks for the detailed report :+1:
