### ISSUE TITLE
Does not work with Vite.js and vue 3.  

### ISSUE THREAD

**Issue by Taykavol** [socketio/socket.io-client#1492]
**Describe the bug**
The same code with webpack works. But Vite.js + Vue 3 is not. There is even no requests. Probably it's not problem of socket.io-client package but something wrong with socket.io-client. 

**To Reproduce**

Socket.IO server version: `4.2.0`

*Server*

```js
import { Server } from "socket.io";

const io = new Server(3000, {});

io.on("connection", (socket) => {
  console.log(`connect ${socket.id}`);

  socket.on("disconnect", () => {
    console.log(`disconnect ${socket.id}`);
  });
});
```

Socket.IO client version: `4.2.0`

*Client*

```js
import { io } from "socket.io-client";

const socket = io("ws://localhost:3000/", {});

socket.on("connect", () => {
  console.log(`connect ${socket.id}`);
});

socket.on("disconnect", () => {
  console.log("disconnect");
});
```

**Expected behavior**
Expected to see console.log messages on server and client. But it's not working at all.

**Platform:**
 - OS: [e.g. Windows 10]

**Comment by darrachequesne** [comment]
Could you please provide a complete example reproducing the issue? Thanks!

**Comment by Taykavol** [comment]
I am sorry, not expert in programming explaining. So the problem is the simplest code above works with webpack(vue-cli) but not work with vite.js +vue.  

 I created full repo example, [https://github.com/Taykavol/socket.io-vite-and-vue-cli-example](url)

Client
`import {io} from 'socket.io-client'
// io is works with webpack but not working with vite
const socket = io("ws://localhost:4000/", {});
socket.on("connect", () => {
  // Works great! with webpack
  alert(`connect ${socket.id}`)
});

socket.on("disconnect", () => {
  console.log("disconnect");
});
`

**Comment by Taykavol** [comment]
> Could you please provide a complete example reproducing the issue? Thanks!

I am sorry, not expert in programming explaining. So the problem is the simplest code above works with webpack(vue-cli) but not work with vite.js +vue.

I created full repo example, https://github.com/Taykavol/socket.io-vite-and-vue-cli-example

Client
`import {io} from 'socket.io-client'
// io is works with webpack but not working with vite

const socket = io("ws://localhost:4000/", {});

socket.on("connect", () => {
// Works great! with webpack
alert(connect ${socket.id})
});

socket.on("disconnect", () => {
console.log("disconnect");
});

**Comment by Taykavol** [comment]
Also, now I checked that the versons 4.1.x works great but something wrong with 4.2.0

**Comment by philippdormann** [comment]
can confirm.
v4.1.3 works fine
v4.2.0 breaks.

not sure how to debug this

also see https://github.com/vitejs/vite/issues/4798

**Comment by darrachequesne** [comment]
Please see my answer here: https://github.com/vitejs/vite/issues/4798#issuecomment-924620798

**Comment by darrachequesne** [comment]
It should be fixed now:

- https://github.com/socketio/engine.io-client/commit/c557707fb694bd10397b4cd8b4ec2fbe59128faa included in `engine.io-client@6.1.1` and `socket.io-client@4.4.x`
- https://github.com/socketio/engine.io-client/commit/9fcaf58d18c013c0b92fdaf27481f0383efb3658 included in `engine.io-client@6.0.3` and `socket.io-client@4.3.x`

Please reopen if needed.
