### ISSUE TITLE
Documentation error: removeAllListeners does not exist

### ISSUE THREAD

**Issue by LaurensRietveld** [socketio/socket.io-client#1496]
**Describe the bug**
The v4 documentation on [this page](https://socket.io/docs/v4/listening-to-events/) says:
> On the client-side, the Socket instance uses the event emitter provided by the component-emitter library, which exposes a subset of the EventEmitter methods.

In a [later section](https://socket.io/docs/v4/listening-to-events/#socketremovealllistenerseventname) the documentation describes how to remove all event listeners.

The `removeAllEventListeners` function however is not part of the component-emitter library, and also does not exist in the socket.io-client typescript interface. 

*Client*
```ts
import { io } from "socket.io-client";

const socket = io("ws://localhost:3000/", {});

// This line errors
socket.removeAllListeners()
```

**Expected behavior**

The documentation should not include references to function that are not supported.

**Comment by darrachequesne** [comment]
The `removeAllEventListeners` method does actually exist [here](https://github.com/component/emitter/blob/6bd7817e8a444cb16e8abdf7dd2d7f04d5ca3dc8/index.js#L85).

It does not appear in the typings though: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/component-emitter/index.d.ts

Could you please open a PR over there?

**Comment by LaurensRietveld** [comment]
Thanks, will do :+1:
