### ISSUE TITLE
Socket.io client dont receive binary buffer in react native

### ISSUE THREAD

**Issue by joelzavala** [socketio/socket.io-client#1500]
**Describe the bug**
When the server emit some event with binary payload the react native socket io client receive the event but the payload or data is empty

**To Reproduce**
1. Create a React Native App with react-native-cli
2. Copy and paste the following code in your server or react-native project

Please fill the following code example:

Socket.IO server version: 4.2.0

*Server*

```js
import { Server } from "socket.io";

const io = new Server(3000, {});

io.on("connection", (socket) => {
  console.log(`connect ${socket.id}`);

  socket.emit("binary_test", Uint8Array.from([0, 1, 2, 3])

  socket.on("disconnect", () => {
    console.log(`disconnect ${socket.id}`);
  });
});
```

Socket.IO client version: 4.2.0

*Client*

```js
import React , { useEffect } from 'react'
import { io } from "socket.io-client";

const socket = io("ws://localhost:3000/", { autoConnect: false });

const App = () => {

  useEffect(() => {
   socket.on("connect", () => {
       console.log(`connect ${socket.id}`);
   });

    socket.on("disconnect", () => {
        console.log("disconnect");
    });

    socke.on("binary_test", data => {
       console.log("Binary data", data)
    })
  })

   return <View>
      <Text>Hello word</Text>
   </View>
}
```

**Expected behavior**
LOG: Binary data <Buffer 00 01 02 03 >

**Current behavior**
LOG: Binary data []

**Platform:**
 - Device: Samsung A9 2018
 - OS: android 10

**Additional context**
I´m trying to receive the binary data from a camera ( esp32 cam ) and display it in an Image in react-native

**Comment by guoyw** [comment]
> **描述这个错误**当服务器发出一些带有二进制有效负载的事件时，反应本机套接字io客户端接收事件，但有效负载或数据是空的
> 
> **复制**
> 
> 1. 使用react-native-cli创建React Native应用程序
> 2. 将以下代码复制并粘贴到您的服务器或react-native项目中
> 
> 请填写以下代码示例：
> 
> Socket.IO服务器版本：4.2.0
> 
> _服务器_
> 
> ```js
> import { Server } from "socket.io";
> 
> const io = new Server(3000, {});
> 
> io.on("connection", (socket) => {
>   console.log(`connect ${socket.id}`);
> 
>   socket.emit("binary_test", Uint8Array.from([0, 1, 2, 3])
> 
>   socket.on("disconnect", () => {
>     console.log(`disconnect ${socket.id}`);
>   });
> });
> ```
> 
> Socket.IO客户端版本：4.2.0
> 
> _客户_
> 
> ```js
> import React , { useEffect } from 'react'
> import { io } from "socket.io-client";
> 
> const socket = io("ws://localhost:3000/", { autoConnect: false });
> 
> const App = () => {
> 
>   useEffect(() => {
>    socket.on("connect", () => {
>        console.log(`connect ${socket.id}`);
>    });
> 
>     socket.on("disconnect", () => {
>         console.log("disconnect");
>     });
> 
>     socke.on("binary_test", data => {
>        console.log("Binary data", data)
>     })
>   })
> 
>    return <View>
>       <Text>Hello word</Text>
>    </View>
> }
> ```
> 
> **预期行为**日志：二进制数据<缓冲区00 01 02 03>
> 
> **当前行为**日志：二进制数据 []
> 
> **平台：**
> 
> * 设备：三星A9 2018
> * 操作系统：安卓10
> 
> **附加上下文**我试图从相机（esp32凸轮）接收二进制数据，并将其显示在图像中

Is this problem solved? I have the same problem.

**Comment by guoyw** [comment]
> **Describe the bug** When the server emit some event with binary payload the react native socket io client receive the event but the payload or data is empty
> 
> **To Reproduce**
> 
> 1. Create a React Native App with react-native-cli
> 2. Copy and paste the following code in your server or react-native project
> 
> Please fill the following code example:
> 
> Socket.IO server version: 4.2.0
> 
> _Server_
> 
> ```js
> import { Server } from "socket.io";
> 
> const io = new Server(3000, {});
> 
> io.on("connection", (socket) => {
>   console.log(`connect ${socket.id}`);
> 
>   socket.emit("binary_test", Uint8Array.from([0, 1, 2, 3])
> 
>   socket.on("disconnect", () => {
>     console.log(`disconnect ${socket.id}`);
>   });
> });
> ```
> 
> Socket.IO client version: 4.2.0
> 
> _Client_
> 
> ```js
> import React , { useEffect } from 'react'
> import { io } from "socket.io-client";
> 
> const socket = io("ws://localhost:3000/", { autoConnect: false });
> 
> const App = () => {
> 
>   useEffect(() => {
>    socket.on("connect", () => {
>        console.log(`connect ${socket.id}`);
>    });
> 
>     socket.on("disconnect", () => {
>         console.log("disconnect");
>     });
> 
>     socke.on("binary_test", data => {
>        console.log("Binary data", data)
>     })
>   })
> 
>    return <View>
>       <Text>Hello word</Text>
>    </View>
> }
> ```
> 
> **Expected behavior** LOG: Binary data <Buffer 00 01 02 03 >
> 
> **Current behavior** LOG: Binary data []
> 
> **Platform:**
> 
> * Device: Samsung A9 2018
> * OS: android 10
> 
> **Additional context** I´m trying to receive the binary data from a camera ( esp32 cam ) and display it in an Image in react-native

Is this problem solved? I have the same problem.

**Comment by smfunder** [comment]
Here I have the same problem!

**Comment by guoyw** [comment]
> Here I have the same problem.

I found that the problem was caused by base64-js decoding failure

**Comment by darrachequesne** [comment]
I was not able to reproduce the issue: https://github.com/socketio/socket.io/tree/main/examples/react-native

Does it happen on some specific platforms (phone, android version)?

**Comment by guoyw** [comment]
> I was not able to reproduce the issue: https://github.com/socketio/socket.io/tree/main/examples/react-native
> 
> Does it happen on some specific platforms (phone, android version)?

https://github.com/guoyw/Example/tree/main/Socket

**Comment by darrachequesne** [comment]
For future readers:

I was not able to reproduce the issue, the client should properly receive the binary data as a `ArrayBuffer`.

See also: https://socket.io/how-to/use-with-react-native

Please reopen if needed.

**Comment by ramyodev** [comment]
This issue still exists in socket.io-client@4.8.1 with RN 0.76.6 with expo@52.0.25 @darrachequesne
