### ISSUE TITLE
Better `socket.off` events name type.

### ISSUE THREAD

**Issue by AbdUlHamedMaree** [socketio/socket.io-client#1501]
**Describe the bug**
when I start using `socket.io-client` with typescript, I initilized my socket with the following code:
```javascript
const socket:Socket<ListenerEvents, EmitEvents> = io('URL');
```
so if I use `socket.on` it will help me with `ListenersEvents` types, but when using `socket.off` it will not.

**To Reproduce**
the above code.

**Expected behavior**
the function `socket.off` be better in types.

**Platform:**
 - Device: Lenovo
 - OS: Ubuntu

**Additional context**
I looked at the `typed-events.d.ts` file and it looks like `StrictEventEmitter` extends from the `Emitter` interface without passing the names of the events, but on the other hand, the `StrictEventEmitter` class has implements the same functions that exist in the `Emitter` interface _(why?!)_ so implement the `off` function and that's it!.

I think this is enough to explain the bug and the solution.

**Comment by darrachequesne** [comment]
Fixed by https://github.com/socketio/socket.io-client/issues/1501
