### ISSUE TITLE
TypeError: Object(n.default) is not a function

### ISSUE THREAD

**Issue by blackisnotcool** [socketio/socket.io-client#1506]
Not sure if it's related to an already opened "Buffer is not defined" issue, so creating a new one just in case. 4.3.0 works fine locally, and production build is successful but I get "TypeError: Object(n.default) is not a function" error.
Production is on AWS using webpack

4.2.0 works fine

<img width="1076" alt="Screenshot 2021-10-15 at 14 47 22" src="https://user-images.githubusercontent.com/14161444/137454702-633931c6-2e14-4162-888b-218f1efdc6a5.png">

**Comment by ericman314** [comment]
I noticed that this appears to be fixed in 4.3.2.

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-client/commit/f0aae8457a8bdf7e2f2286b4b7d34d2798419456, included in `socket.io-client@4.3.1`. Thanks for the heads-up :+1:
