### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'flags')

### ISSUE THREAD

**Issue by icastillejogomez** [socketio/socket.io-client#1512]
**Describe the bug**

In this line of this file (https://github.com/socketio/socket.io-client/blob/master/lib/socket.ts#L163) I'm getting this error:

```
Cannot read properties of null (reading 'flags')
    at emit (socket.js?d640:111)
    at runCallEffect (redux-saga-core.esm.js?42a9:524)
   ....
```

I'm not doing anything weird, Only connect with my local server and doing some concepts probes. The stack you can see above ends in socket.js file. When I click on my devtools they follow me to this line that is the link I put.

```js
packet.options.compress = this.flags.compress !== false;
```

**To Reproduce**

Nothing special, send a event to the server from the frontend.

**Expected behavior**
Don't go to error 

**Platform:**
 - Device: Desktop 
 - OS: Hackintosh

**Additional context**
The socket client does strange things. I'm sorry if the publications does not follow any rule

**Comment by darrachequesne** [comment]
According to the error message, the `this` reference is null, which is a bit weird. Did you modify the `emit` function? I think this could happen with something like:

```js
const emit = socket.emit;

emit.call(null, "hello");
```

Could you please provide a reproducible example?

**Comment by icastillejogomez** [comment]
This was weird. I will close the issue because that won't happen anymore. Im going to explain to you what I could deduced this days...

I was calling socket.emit function inside a redux saga (generator function). I suppose that JS engine "play" with the context after call something with `yield` reserved word. Something in my code logic was failing and in my socket.emit function I have a callback function with error check. If my code logic response with error, I'll throw it. 

The point is... something between yield call context switching and my error throwing (on my callback function) was blowing up.

May the code of this repo should handle it but this looks like an unusual error case.
