### ISSUE TITLE
Incompatible with @microsoft/api-extractor (maybe pnpm?).

### ISSUE THREAD

**Issue by rogerleung0411** [socketio/socket.io-client#1513]
**Describe the bug**
![image](https://user-images.githubusercontent.com/42612758/140273460-a3bf98ba-de28-4dbe-b4e1-8a97ddb423f4.png)

In my project, i use @microsoft/api-extractor to rollup all d.ts into a single d.ts per package（like what vue 3.0 does). 

However, when i migrate yarn to pnpm, and build my project once again, the error(snapshot above) occurs. 
It it obvious that api-extractor ([code here](https://github.com/microsoft/rushstack/blob/master/libraries/node-core-library/src/PackageJsonLookup.ts#L237)) tries to read meta info from esm/package.json (or cjs/package.json), while no `name` field found.

It is neccessary not only provide `type` field but merge with the root package.json in postcompile.sh?

**To Reproduce**

- clone [vue next repo](https://github.com/vuejs/vue-next)
- access an arbitrary package under `/packages/`, add socket.io-client to dependencies, then `exports * from 'socket.io-client'` in index.ts
- build the package, error will log in terminal.

im not sure it is actually a bug of socket.io-client, or the build tools / package manager tools i used, or even it is not a bug and has walkaround?

**Comment by rogerleung0411** [comment]
FYI: i confirm that 4.2.0 works fine, and broke since this commit(https://github.com/socketio/socket.io-client/commit/16b65698aed766e1e645c78847f2e91bfc5b6f56) released.

**Comment by darrachequesne** [comment]
Hmm, OK, so it seems the parent `package.json` is not read. I'm wondering whether copying the name would be enough, or if we also need `version` and other fields.

**Comment by rogerleung0411** [comment]
I think in this specific case, providing `name`, `version`, `type` is enough ('cause api-extractor mark only `name` and `version` required and throw error if field not found. see https://github.com/microsoft/rushstack/blob/master/libraries/node-core-library/src/PackageJsonLookup.ts). But more fields we exposed (targeting to align with root package.json), higher compatibility we have.

The `./package.json` fields after `exports` field in https://github.com/socketio/socket.io-client/blob/master/package.json#L20 only works in node 12+ and reading files using  syntax below:
```js
// import
import packageJson from 'socket.io-client/package.json';
// or
const packageJson = require('socket.io-client/package.json');
```
However, in tools like api-extractor, they just tryna read package.json under the same directory once they encountered an entry file, seems like it's a quite common case.
