### ISSUE TITLE
Creating new connections with multiplexing after disconnection

### ISSUE THREAD

**Issue by samuel-olivier** [socketio/socket.io-client#1514]
**Describe the bug**
Two many websocket connections are created if we connect to namespaces that we have previously disconnected.

**To Reproduce**

Socket.IO server version: `4.4.0`

*Server*

```js
import { Server } from "socket.io";

const io = new Server(3000, {});

io.of('/namespace1')
io.of('/namespace2')
```

Socket.IO client version: `4.4.0`

*Client*

```js
const { io } = require("socket.io-client");

// We connect to 2 different namespaces
const socket1a = io("ws://localhost:3000/namespace1", {});
const socket2a = io("ws://localhost:3000/namespace2", {});

socket1a.on("connect", () => {
  console.log('socket1a', socket1a.io.engine.id) // a random id
  setTimeout(() => socket1a.disconnect(), 500)
});
socket2a.on("connect", () => {
  console.log('socket2a', socket2a.io.engine.id) // same id as socket1a because of multiplexing
  setTimeout(() => socket2a.disconnect(), 500)
});

setTimeout(() => {
  // After disconnection of the 2 namespaces, we reconnect to the same namespaces
  const socket1b = io("ws://localhost:3000/namespace1", {});
  const socket2b = io("ws://localhost:3000/namespace2", {});

  socket1b.on("connect", () => {
    console.log('socket1b', socket1b.io.engine.id) // a random id
  });
  socket2b.on("connect", () => {
    console.log('socket2b', socket2b.io.engine.id) // a random id instead of reusing the manager of socket1b
  });
}, 1000)
```

**Expected behavior**
The `socket2b` should not create a new connection because it can reuse the manager of `socket1a`. Could it even reuse the manager of `socket1a` and `socket2a` for both `socket1b` and `socket2b` ? 

**Platform:**
 - Device: Macbook Pro
 - OS: MacOs 11.5.2

**Additional context**
This behavior is due to manager cache system found here :
https://github.com/socketio/socket.io-client/blob/71e34a38261d4c52f60c153e5f492e7304d802eb/lib/index.ts#L8-L11
https://github.com/socketio/socket.io-client/blob/71e34a38261d4c52f60c153e5f492e7304d802eb/lib/index.ts#L49-L67
 
Because the manager is never destroyed (even if it is in closed state) and so the manager is never removed from the cache or neither is `manager.nsps['{disconnected namespace id}]` removed on namespace disconnection, then we will never be able to reuse an existing alive manager when connecting to a namespace we previously connected then disconnected.

**Comment by darrachequesne** [comment]
Hi. I think this is the correct behavior, as documented here: https://socket.io/docs/v4/namespaces/#client-initialization

```js
const socket1 = io();
const socket2 = io(); // no multiplexing, two distinct WebSocket connections
```

If you really want the same manager, you can manually create it:

```js
const { Manager } = require("socket.io-client");

const manager = new Manager("ws://localhost:3000");

const socket1a = manager.socket("/namespace1");
const socket2a = manager.socket("/namespace2");
```

**Comment by samuel-olivier** [comment]
Hi,

Thanks for your answer ! I knew indeed that calling `io` twice for the same namespace was creating a new connection each time, but I didn't though that it would apply if the previous connection was closed. Do you think the documentation should mention that as well ?

By the way, why do we wan't to keep in the cache some managers that have been closed ? In case they are reused somehow ?

Thank you for the solution you provided, I'll implement this.

**Comment by darrachequesne** [comment]
> Do you think the documentation should mention that as well ?

Sure! Would you have the time to open a pull request [here](https://github.com/socketio/socket.io-website)?

> By the way, why do we wan't to keep in the cache some managers that have been closed ? In case they are reused somehow ?

Managers can indeed be reopened, with either `manager.open()` or `socket.connect()`, so I don't think we should remove them from the cache.

I think we can close this now, please reopen if needed.
