### ISSUE TITLE
A way for the client to figure out if the payload is too large

### ISSUE THREAD

**Issue by andre4i** [socketio/socket.io-client#1518]
**Is your feature request related to a problem? Please describe.**

I noticed the behavior when the client sends a large payload, which exceeds the server configured `maxHttpBufferSize`. In this situation, the client will get disconnected and the reason supplied to the event handler is `transport error`.

Any resilience mechanism which would try to reconnect and resend the message will be oblivious to the underlying `'Max payload size exceeded` error and enter a costly (for both client and server) loop of retries. `transport error` being generic enough to cover a set of error scenarios which are (eventually) recoverable, while the payload size being larger than configured would not.

**Describe the solution you'd like**
- One possibility would be to extend the disconnect event handler to provide a full error object which can be inspected and reasoned about (something which may have a flag related to whether or not a reconnect would be futile).
- Another possibility would be for the client to have an `error` event raised in this situation instead of the disconnect, again with an object holding more information.

**Describe alternatives you've considered**

A workaround would be possible for the client to know the `maxHttpBufferSize` configuration of the server, measure each message and self-govern its payload size. However, this is again costly, as messages are already measured in the `socket.io` stack where another set of identical validations take place.

**Additional context**

See this resilience behavior [here](https://github.com/andre4i/socket.io/compare/master...andre4i:transport-error). The server is configured with an impossible `maxHttpBufferSize` value, which makes the client enter an endless loop of reconnects:

![image](https://user-images.githubusercontent.com/84357545/146097104-32aa4b51-894b-4fdd-8648-35d0a6ba3953.png)

**Comment by darrachequesne** [comment]
That sounds like a good improvement :+1:

Currently, the HTTP request or the WebSocket connection get closed if any message is bigger than the `maxHttpBufferSize` value:

- https://github.com/socketio/engine.io/blob/b04967b52eb1574cfaa6e24bdf164096322be96a/lib/transports/polling.ts#L157-L160
- https://github.com/websockets/ws/blob/c82b08737fbe142dd910fc7e429399e23b95c6d6/lib/receiver.js#L372-L381

But the client indeed does not have the reason for the "transport close" error.

**Comment by andre4i** [comment]
Hi @darrachequesne, thanks for the input. What is your opinion about a proper way to improve this experience? Should this be a new `reason` for the disconnect event at https://socket.io/docs/v3/client-socket-instance/#disconnect?

**Comment by darrachequesne** [comment]
The `disconnect` event will now provide additional details:

```js
socket.on("disconnect", (reason, details) => {
  console.log(reason); // "transport error"

  // in that case, details is an error object
  console.log(details.message); "xhr post error"
  console.log(details.description); // 413 (the HTTP status of the response)

  // details.context refers to the XMLHttpRequest object
  console.log(details.context.status); // 413
  console.log(details.context.responseText); // ""
});
```

Implemented in https://github.com/socketio/socket.io-client/commit/b862924b7f1720979e5db2f0154906b305d420e3 and included in version `4.5.0`.

**Comment by TechAkayy** [comment]
It would be good to know the payload size that triggered the disconnect, so that we can dynamically calculate a chunkSize and relay the data across. Without the payload size, it's not possible to make any calculations and keep the comms stable & reliable. Thanks in advance.

**Comment by darrachequesne** [comment]
@TechAkayy that's a good idea. We might even include it in the library, which might prevent the socket from disconnecting during a big emit. What do you think?
