### ISSUE TITLE
`connect` events are triggered too early

### ISSUE THREAD

**Issue by SimonMARTIN87** [socketio/socket.io-client#1527]
**Describe the bug**
`connect` events are triggered too early by the server, i.e. before the complete `on('connection',...)` callback has been run.
If a client connects and immediately emits an event while the server is still running the callback, the event is lost, never catched.

**To Reproduce**

Socket.IO server version: `4.4.1`

*Server*

```js
import { Server } from "socket.io";

const io = new Server(3000, {});

// this factor depends on your workmachine.
const POW =  10;

io.on("connection", (socket) => {
  /* 1. make something slow... */
  // this loop here is useless, it's just for taking time.
  // but imagine making a call to a database, an api, or something like that !
  for (let index = 0; index < 10**POW; index++) {
    // do nothing. Just take some time...
  }

  /* 2. then add the listener */
  socket.on('test', () => {
    socket.emit('response', 'Hello !');
  });
});
```

Socket.IO client version: `4.4.1`

*Client*

```js
import { io } from "socket.io-client";

const socket = io("ws://localhost:3000/", {});

socket.on("connect", () => {
  socket.emit('test'); // this will never be caught...
});

// ...and therefore this will never happen
socket.on('response', (data) => {
  console.log('response : ', data);
});
```

Complete example here : https://github.com/SimonMARTIN87/socket-io-latency

**Expected behavior**
`connect` events should be triggered server-side only after the callback is completed.

**Platform:**
 - Device: Dell Optiplex 5090
 - OS: Windows 10

**Additional context**
It seems there is a similar bug in the swift version ([link](https://github.com/socketio/socket.io-client-swift/issues/1194))

**Comment by darrachequesne** [comment]
Hi! I'm not sure that is a bug. Why would you not register the event listeners at the top of the connection handler?

If you need to delay the connection, you can use a middleware:

```js
io.use(async (socket, next) => {
  await fetchSomethingFromDB();
  
  next();
});
```

Reference: https://socket.io/docs/v4/middlewares/

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
