### ISSUE TITLE
Client disconnects when cookie is set

### ISSUE THREAD

**Issue by malavshah-9** [socketio/socket.io-client#1532]
**Describe the bug**

In my application, there are some cookies been set for authentication which is not related to this socket connection.

But after setting this cookies, when i try to do socket connection to same domain, than all request are been failed.

On ther server side, there is Python fast api with socket io is implemented, where logs are been

400 - Bad request when this happens,

If i try to open the same page in incognito tab where there no cookies is been set, than it works fine.

**To Reproduce**

Socket Io client version: 4.3.2

**Expected behavior**

Connection should happen regardless of what cookies is been set for that domain.

**Platform:**
 - Device: All
 - OS: All

**Additional context**

Currently I have patched this issue by changing TLD for socket server so that those cookies not been set,

Thanks for any help

**Comment by darrachequesne** [comment]
This seems like an issue on the server side, but we would need some way to reproduce the issue in order to help.

Please reopen if needed.
