### ISSUE TITLE
Poll Error in node js but works fine in browser

### ISSUE THREAD

**Issue by White2001Offl** [socketio/socket.io-client#1534]
**Describe the bug**
The Socket.io-client works fine when I connect from browser, but when I try the same thing in node js it fails and gives xhr poll error Status Code 403

**To Reproduce**

Socket.IO server version: `idk`

*Server*

I connect to a third party socket.io server which I don't have any idea what's their configuration

Socket.IO client version: `4.4.1`

*Client*

*Node JS*

```js
const { io } = require('socket.io-client');
const socket = new io('wss://site.com/', {
    pingInterval: 25000,
    pingTimeout: 10000
});

socket.on('open', () => {
    socket.on('message', (data) => console.log(data));
    socket.on('close', () => {});
});

socket.on("error", (err) => {
    console.error(err)
})


socket.on("connect", () => {
    console.log(socket.connected);
});

socket.on("disconnect", () => {
    console.log(socket.connected);
});

socket.on("connect_error", (err)=>{
    console.log(err)
})
```

*Browser*

```
<script type="module">
    import { io } from "https://cdn.socket.io/4.4.1/socket.io.esm.min.js";
    const socket = new io('wss://site.com/', {
        pingInterval: 25000,
        pingTimeout: 10000
    });

    socket.on('open', () => {
        socket.on('message', (data) => console.log(data));
        socket.on('close', () => {});
    });

    socket.on("error", (err) => {
        console.error(err)
    })


    socket.on("connect", () => {
        console.log(socket.connected);
    });

    socket.on("disconnect", () => {
        console.log(socket.connected);
    });

    socket.on("connect_error", (err)=>{
        console.log(err)
    })
</script>
```

**Expected behavior**
It should connect successfully to the server in node js

**Platform:**
 - Device: MacBook Pro M1 Pro
 - OS: MacOS Monterey 12.3

If you want the site details, please send the email ID / Discord and I'll text you there I don't want the site details to get indexed on google

**Comment by darrachequesne** [comment]
That sounds weird. Maybe the Socket.IO server requires some authentication? An 'Origin' header? I don't think that comes from the Socket.IO client itself.

**Comment by leoderigo** [comment]
> **Describe the bug** The Socket.io-client works fine when I connect from browser, but when I try the same thing in node js it fails and gives xhr poll error Status Code 403
> 
> **To Reproduce**
> 
> Socket.IO server version: `idk`
> 
> _Server_
> 
> I connect to a third party socket.io server which I don't have any idea what's their configuration
> 
> Socket.IO client version: `4.4.1`
> 
> _Client_
> 
> _Node JS_
> 
> ```js
> const { io } = require('socket.io-client');
> const socket = new io('wss://site.com/', {
>     pingInterval: 25000,
>     pingTimeout: 10000
> });
> 
> socket.on('open', () => {
>     socket.on('message', (data) => console.log(data));
>     socket.on('close', () => {});
> });
> 
> socket.on("error", (err) => {
>     console.error(err)
> })
> 
> 
> socket.on("connect", () => {
>     console.log(socket.connected);
> });
> 
> socket.on("disconnect", () => {
>     console.log(socket.connected);
> });
> 
> socket.on("connect_error", (err)=>{
>     console.log(err)
> })
> ```
> 
> _Browser_
> 
> ```
> <script type="module">
>     import { io } from "https://cdn.socket.io/4.4.1/socket.io.esm.min.js";
>     const socket = new io('wss://site.com/', {
>         pingInterval: 25000,
>         pingTimeout: 10000
>     });
> 
>     socket.on('open', () => {
>         socket.on('message', (data) => console.log(data));
>         socket.on('close', () => {});
>     });
> 
>     socket.on("error", (err) => {
>         console.error(err)
>     })
> 
> 
>     socket.on("connect", () => {
>         console.log(socket.connected);
>     });
> 
>     socket.on("disconnect", () => {
>         console.log(socket.connected);
>     });
> 
>     socket.on("connect_error", (err)=>{
>         console.log(err)
>     })
> </script>
> ```
> 
> **Expected behavior** It should connect successfully to the server in node js
> 
> **Platform:**
> 
> * Device: MacBook Pro M1 Pro
> * OS: MacOS Monterey 12.3
> 
> If you want the site details, please send the email ID / Discord and I'll text you there I don't want the site details to get indexed on google

Did you solved? Getting the same behavior.
