### ISSUE TITLE
Make socket.io including dependencies esm compatible

### ISSUE THREAD

**Issue by Artur-** [socketio/socket.io-client#1536]
**Is your feature request related to a problem? Please describe.**
`@web/test-runner` only supports ESM imports: https://github.com/modernweb-dev/web/issues/1439. It is currently not possible to use socket.io with that.

**Describe the solution you'd like**
All dependencies of socket.io-client should be ESM modules. Right now there are problems with at least
- @socket.io/component-emitter
- parseuri
- parseqs
- yeast
- ws (shouldn't be loaded at all as far as I understand)

**Comment by Artur-** [comment]
In practice you likely need to mock socket.io in most tests which makes this a not that major issue for this use case

**Comment by darrachequesne** [comment]
That sounds reasonable :+1: 

Here is the list of the dependencies for the Socket.IO client:

| Dependency | Repository | ESM? |
| --- | --- | --- |
| @socket.io/component-emitter | https://github.com/socketio/emitter/ | |
| backo2 | https://github.com/mokesmokes/backo | |
| debug | https://github.com/debug-js/debug | |
| ms | https://github.com/vercel/ms | |
| engine.io-client | https://github.com/socketio/engine.io-client/ | :heavy_check_mark: |
| engine.io-parser | https://github.com/socketio/engine.io-parser | :heavy_check_mark: |
| @socket.io/base64-arraybuffer | https://github.com/socketio/base64-arraybuffer | :heavy_check_mark: |
| has-cors | https://github.com/component/has-cors | |
| parseqs | https://github.com/galkn/querystring | |
| parseuri | https://github.com/galkn/parseuri | |
| yeast | https://github.com/unshiftio/yeast | |
| socket.io-parser | https://github.com/socketio/socket.io-parser | :heavy_check_mark: |

Both `ws` and `xmlhttprequest-ssl` are only needed for Node.js, so I think they can be ignored in that case.

From: https://socket.io/docs/v4/client-installation/#dependency-tree

**Comment by Waxolunist** [comment]
Actually it would make it simpler for example in conjunction with esbuild or build less execution if they would be esm compatible.

**Comment by darrachequesne** [comment]
OK, so starting from `socket.io-client@4.5.0` we only include ESM compatible dependencies!
