### ISSUE TITLE
Connection timeout errors caused by Webpack

### ISSUE THREAD

**Issue by Quovadisqc** [socketio/socket.io-client#1537]
**Describe the bug**
Webpack version 5.71.0 causes an issue with this library.
It causes statements such as ""__initialize" in WebSocket" in [this function](https://github.com/socketio/engine.io-client/blob/master/lib/transports/websocket.ts#L238) to be changed to true.
https://github.com/webpack/webpack/issues/15633

**Expected behavior**
This is obviously not an issue with this library but I though it would help others to have it documented.
Perhaps error handling could be improved for transports detection.

**Comment by jayarjo** [comment]
@Quovadisqc @darrachequesne any ideas on why would Webpack evaluate `"__initialize" in WebSocket` condition into a literal `true`?

**Comment by Quovadisqc** [comment]
@jayarjo From my understanding, Webpack had an issue when processing "property in object" statements on imported tokens which made Webpack always evaluate and transform the statement to "true". The issue was introduced in version 5.70 and fixed in version 5.72.

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/engine.io-client/commit/f158c8e255be9e849313e53201adf1642c60345a.

@Quovadisqc thanks a lot for the detailed explanation :+1:
