### ISSUE TITLE
socket.handshake.query cannot handle Multi-depth Objects

### ISSUE THREAD

**Issue by Krypt0n36** [socketio/socket.io-client#1538]
**Describe the bug**
Front-end: React, Back-end: Node.js.
This unexpected behavior appears when I try to send a Multi-Depth Object as the "query" param when initializing the socket.io connection.

**To Reproduce**

Socket.IO server version: `4.5.0`

*Server*

```js
io.on('connection', (socket) => {
if(socket.handshake.query){
        console.log(typeof socket.handshake.query.headers)
        console.log(socket.handshake.query.headers)
        console.log(socket.handshake.query.headers.length)
}});
```

Socket.IO client version: `4.5.0`

*Client*

```js
const socket = io('ws://localhost:4000', {
		query:{
			token:'xxx',
			headers:{
				from:'kry',
				to:'none'
			}
		}
});
```

**Server Output :** 
string
[object Object]
15

Note: I console logged the length to show that the printed headers's value is literally  "[object Object]" not a logging mistake.

**Expected behavior**
Full depth object sending and appropriate parsing.

**Platform:**
 - Device: WEB

**Comment by darrachequesne** [comment]
Hi! Yes, multi-depth object cannot be sent currently in the query parameters. But maybe you are looking for the `auth` option?

```js
const socket = io('ws://localhost:4000', {
		auth:{
			token:'xxx',
			headers:{
				from:'kry',
				to:'none'
			}
		}
});
```

Reference: https://socket.io/docs/v4/client-options/#auth

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
