### ISSUE TITLE
ReferenceError: exports is not defined (Vue)

### ISSUE THREAD

**Issue by XeraFiu-YTB** [socketio/socket.io-client#1543]
**Describe the bug**
When i import socket.io-client in my component data, this error appear.

**To Reproduce**

Following the socket.io-client documention, i've done this on the client side :

```js
const { io } = require("socket.io-client");

function data() {
    return {
        messages: [],
        socket : io("localhost:3000")
    }
}

module.exports = {
    data,
    async created() {
        console.log("Page loaded")
        this.socket.on("listFromBack", data => {
            this.messages = data
        })
    }
}
```

**Versions:**
- Node 16.0.1
- Npm 7.21.1
- Vue 3.2.37
- socket.io-client 4.5.1

**Additional context**
The Vue config was created by the vue-cli.

Thanks for the help, have a nice day :p

**Comment by darrachequesne** [comment]
Hi! Sorry for the delay.

For future readers, I think you need to use the ESM syntax:

```js
import { io } from "socket.io-client";

function data() {
    return {
        messages: [],
        socket : io("localhost:3000")
    }
}

export default {
    data,
    async created() {
        console.log("Page loaded")
        this.socket.on("listFromBack", data => {
            this.messages = data
        })
    }
}
```

Please reopen if needed.
