### ISSUE TITLE
fix types socket has no property of on

### ISSUE THREAD

**Issue by guyue88** [socketio/socket.io-client#1547]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `socket.io-client@3.1.3` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/socket.io-client/build/socket.d.ts b/node_modules/socket.io-client/build/socket.d.ts
index b23b738..71c3841 100644
--- a/node_modules/socket.io-client/build/socket.d.ts
+++ b/node_modules/socket.io-client/build/socket.d.ts
@@ -1,5 +1,5 @@
 import { Packet } from "socket.io-parser";
-import Emitter = require("component-emitter");
+import Emitter from "component-emitter";
 import { Manager } from "./manager";
 export interface SocketOptions {
     /**
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by darrachequesne** [comment]
That should be fixed in latest versions. Please reopen if needed.
