### ISSUE TITLE
socketInstance.timeout is not a function

### ISSUE THREAD

**Issue by nachogonzalezsibila** [socketio/socket.io-client#1563]
When I call timeout() function before emit(), I get a TypeError:

`e.socketInstance.timeout is not a function`

Socket.IO server version: `4.1.2`

Socket.IO client version: `4.1.3`

*Client*

```js
const handleMessageEmit = (message) => {
    props.socketInstance.timeout(3000).emit("NEW_MESSAGE_REC", {
      message,
      token: sessionStorage.getItem("AccessToken"),
    }, (error, serverResponse) => {
        if (error) return showSocketWarning();
        props.addMessage(message);
    });
  }
```

**Expected behavior**
It should emit the message as expected, and fail in case of a response taking too long.

**Additional context**
I know it sounds like a very silly issue so far, but here's the weird part:

If I only do this:

```js
const handleMessageEmit = (message) => {
    props.socketInstance.emit("NEW_MESSAGE_REC", {
      message,
      token: sessionStorage.getItem("AccessToken"),
    }, (error, serverResponse) => {
        if (error) return showSocketWarning();
        props.addMessage(message);
    });
  }
```

it works as expected. Also, I'm doing something very similar in a very similar project (same socket io client version and targeting the same server) and it works fine there as well.

**Comment by darrachequesne** [comment]
Hi! The `timeout()` method was added in version 4.4.0, so that should explain your issue. Could you please check?

Reference: https://socket.io/docs/v4/client-api/#sockettimeoutvalue

**Comment by nachogonzalezsibila** [comment]
Hi! Updating to 4.4.0 fixed the issue. I had some weird behaviour with npm where it would upgrade automatically in one project but not in the other by using 

`"socket.io-client": "^4.1.3",`
