### ISSUE TITLE
Add a best-practice example to use socket-io in React 18 with React.StrictMode

### ISSUE THREAD

**Issue by itayperry** [socketio/socket.io-client#1575]
`Socket.IO`'s docs have a page called _How to use with React hooks_ (https://socket.io/how-to/use-with-react-hooks) - this page shows an example of how to connect/open a socket but it doesn't show:

1) How to disconnect entirely (which makes since many times).
2) A best practice to work with **React 18 Strict Mode** - which runs `useEffect`s twice, causing weird behavior. 
For example :
**if `useEffect()` disconnects you can't connect again (socket-io example connects **once** outside the component)
![image](https://user-images.githubusercontent.com/37377389/222423511-c2b2c752-dbdc-48d1-9244-c2a5ea01d0b9.png)

**you can't immediately reconnect to a socket you just disconnected from.

**I do not wish to waste your time**, but I truly think adding/editing this guide is important and it would greatly help the community and the users of this wonderful library 🌻

**Comment by darrachequesne** [comment]
Hi! Thanks a lot for the feedback :+1: 

> How to disconnect entirely (which makes since many times).

Something like this?

```js
import React, { useState, useEffect } from 'react';
import io from 'socket.io-client';

const socket = io("http://localhost:3001");

function App() {
  const [isConnected, setIsConnected] = useState(socket.connected);
  const [lastPong, setLastPong] = useState(null);

  useEffect(() => {
    socket.on('connect', () => {
      setIsConnected(true);
    });

    socket.on('disconnect', () => {
      setIsConnected(false);
    });

    socket.on('message', () => {
      setLastPong(new Date().toISOString());
    });

    return () => {
      socket.off('connect');
      socket.off('disconnect');
      socket.off('pong');
    };
  }, []);

  const sendPing = () => {
    socket.emit('ping');
  }

  function connect() {
    socket.connect();
  }

  function disconnect() {
    socket.disconnect();
  }

  return (
    <div>
      <p>Connected: { '' + isConnected }</p>
      <p>Last pong: { lastPong || '-' }</p>
      <button onClick={ sendPing }>Send ping</button>
      <button onClick={ connect }>Connect</button>
      <button onClick={ disconnect }>Disconnect</button>
    </div>
  );
}

export default App;
```

> if `useEffect()` disconnects you can't connect again (socket-io example connects once outside the component)

I'm not sure to understand this part. Could you please explain?

**Comment by itayperry** [comment]
Hi @darrachequesne, thank you gor the response! I know how to disconnect :) but most devs disconnect in useEffect() cleanup when the component is destroyed.

Please try running the code in React 18 and you'll see what I mean (with StrictMode wrapper).

**Comment by darrachequesne** [comment]
@itayperry I have updated the guide, could you please check whether everything is clear enough?

**Comment by itayperry** [comment]
HIi @darrachequesne, 

I just read it :) You've done a lot of work! Wow.

The only thing missing (in my opinion) is to explain that `io('some-url')` immediately connects and there is no need to actually write `socket.connect()` unless in React 18 or unless the user must trigger it.
It is not entirely clear that the mere action of solely **importing** the socket file from the guide would automatically connect it, providing the user with a connect button (which is great and I think it should stay there) adds to this confusion.

Shortly, I thing that **2 small text-notes** will do, cause the code is already flawless 🚀:
1) Let them know `io()` connects automatically (but react 18 kills it) if you disconnect inside `useEffect` cleanup.
2) In this example:
<img width="688" alt="image" src="https://user-images.githubusercontent.com/37377389/224481987-c1a1db27-5980-4f9c-869b-e61a8399f9f7.png">
let the users know that the **first** call to `socket.connect() `doesn't really connect cause it's already connected.

One more thing that could be done - cancelling `autoConnect:`
```javascript
import { io } from 'socket.io-client';
// "undefined" means the URL will be computed from the `window.location` object
const URL = process.env.NODE_ENV === 'production' ? undefined : 'http://localhost:4000';

export const socket = io(URL, { autoConnect: false });
```
---

Other than that, the guide is amazing!! Leaving it as-is would also be pretty awesome.
I personally learned a few new things, and I'm gonna change my code to be written like your examples.

Thank you so much 🎆✨

P.S.
**It's currently irrelevant** but React is working on something cool called `useEffectEvent` :) And from what I saw if you have event-handlers for socket events you can put them outside of the `useEffect` hook and put them in `useEffectEvent` and then you don't have to put them in dependency array! **This will create another improvement when working with `socket.io`.**

https://beta.reactjs.org/learn/separating-events-from-effects#declaring-an-effect-event


<img width="712" alt="image" src="https://user-images.githubusercontent.com/37377389/224482937-68b5e7b4-48d7-4400-8ef8-22ff5689542c.png">

**Comment by darrachequesne** [comment]
@itayperry thanks a lot for the feedback! I've updated the guide following your advice :+1:

**Comment by itayperry** [comment]
@darrachequesne thank you so much 🎉
The guide is perfect!

**Comment by darrachequesne** [comment]
Thanks for the feedback! I guess we can close this now, please ping me if something is missing.
