### ISSUE TITLE
The front-end has received the event, but does not trigger the handler.

### ISSUE THREAD

**Issue by Qyokizzzz** [socketio/socket.io-client#1576]
**Describe the bug**
The server side calls emit('msg', xxx), but the client side doesn't trigger msg's handlers.

**To Reproduce**
egg-socket.io version: `4.1.6`

*Server*

```js
  const nsp = app.io.of('/');
  nsp.emit('msg', '1111111');
```

Socket.IO client version: `4.6.1`

*Client*

```js
  useEffect(() => {
    if (socketIns) {
      socketIns.on('msg', (msg) => {
        console.log(msg);
      });
      console.log(socketIns);
    }
  }, [socketIns]);
```

**Expected behavior**
The console shows '1111111' sent by the backend.

**Platform:**
 - windows10

**Additional context**

![do-not-support-strict-mode](https://user-images.githubusercontent.com/42693551/227765789-e434828a-5a93-4794-b3f8-4754325db001.png)

**Comment by darrachequesne** [comment]
Hi! Did you check our React guide: https://socket.io/how-to/use-with-react?

**Comment by Qyokizzzz** [comment]
> Hi! Did you check our React guide: https://socket.io/how-to/use-with-react?

Thanks, it has been resolved
