### ISSUE TITLE
Socket.on() functions can't read Jotai's atom variables

### ISSUE THREAD

**Issue by kaganAhmetOkan** [socketio/socket.io-client#1577]
**Describe the bug**
I'm using Jotai for state management in Next.js. On the client side, socket.on() functions can't read atom variables in the store, though they can write into them.

**To Reproduce**
Create an atom variable and try to read it in a socket.on() function:

`const testAtom = atom(["po","ta","toes"]);`

inside socket initializer:

`socket.onAny(() => console.log(testAtom));
// doesn't printout the expected array`

Please fill the following code example:

Socket.IO server version: `4.6.1`

*Server*

```js
import { Server } from "socket.io";

const io = new Server(3000, {});

io.on("connection", (socket) => {
  console.log(`connect ${socket.id}`);

  socket.on("disconnect", () => {
    console.log(`disconnect ${socket.id}`);
  });
});
```

Socket.IO client version: `4.6.1`

*Client*

```js
import { io } from "socket.io-client";

const socket = io("ws://localhost:3000/", {});

socket.on("connect", () => {
  console.log(`connect ${socket.id}`);
});

socket.on("disconnect", () => {
  console.log("disconnect");
});
```

**Expected behavior**
I expected socket.io-client to read the values of atom variables, since it can write them, and it has no trouble reading useState variables.

**Platform:**
 - Device: [VivoBook 15_ASUS Laptop X540UAR 1.0]
 - OS: [Arch Linux x86_64]
 - Kernel: [6.1.22-1-LTS]

**Comment by darrachequesne** [comment]
Hi! That's weird, I don't think there is something specific about Socket.IO event handlers, just plain JavaScript functions. Are you able to reproduce reliably?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
