### ISSUE TITLE
Debugging messages in Metro terminal with React Native

### ISSUE THREAD

**Issue by folin03** [socketio/socket.io-client#1578]
**Is your feature request related to a problem? Please describe.**
Hi, I use socket.io-client in react native app and in my terminal running Metro I keep getting DEBUG messages, is there a way of turning it off? 

![Screenshot 2023-04-19 at 10 58 07](https://user-images.githubusercontent.com/61707215/233039883-d8c945a6-c46d-4bef-bc3b-ffb0a0180bb2.png)

**Comment by darrachequesne** [comment]
For future readers:

Please check our guide with React Native here: https://socket.io/how-to/use-with-react-native

Please reopen if needed.
