### ISSUE TITLE
How to properly disconnect from server in tests using jest.

### ISSUE THREAD

**Issue by GreatGaryCooper** [socketio/socket.io-client#1581]
### This is not a bug, but I had no other place to report it, so feel free to close it.

I faced this issue when I was using socker.io-client in some tests, the issue was that even after calling `socket.close()`, `socket.disconnect()`, or `socket.off()`, or calling them in the `socket.io` instance, jest was complaining that some open handlers still exist, even `socket.disconnected` was saying the connection is closed.
After hours of search I found the solution, when you want to completely disconnect from the server, in a way that jest does not complain, you need to call these two function:
```
const socket = io(<some-url>);

socket.io.engine.off();
socket.io.engine.close();
```

Keep that in mind that the order is important, if you change the order it won't work.

Cheers 🍻

**Comment by darrachequesne** [comment]
Hi! That sounds weird, calling `socket.disconnect()` should be sufficient. Do you have an example of a test where jest complains about open handles?

For the record:

- `socket.close()` is an alias for `socket.disconnect()`
- `socket.off()` clears the list of event listeners, but it does not impact to the low-level connection

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
