### ISSUE TITLE
errors from node-mudules

### ISSUE THREAD

**Issue by deepakchandrawanshi1063** [socketio/socket.io-client#1582]
when I am running an angular project. it gives me errors from node-modules of socket-io-client.
------------------------
ERROR in node_modules/socket.io-client/build/esm/socket.d.ts(29,56): error TS1110: Type expected.
node_modules/socket.io-client/build/esm/socket.d.ts(30,62): error TS1110: Type expected.
node_modules/socket.io-client/node_modules/engine.io-client/build/esm/socket.d.ts(2,13): error TS1005: '=' expected.
node_modules/socket.io-client/node_modules/engine.io-client/build/esm/socket.d.ts(2,50): error TS1005: ';' expected.
node_modules/socket.io-client/node_modules/engine.io-client/build/esm/transport.d.ts(1,13): error TS1005: '=' expected.
node_modules/socket.io-client/node_modules/engine.io-client/build/esm/transport.d.ts(1,38): error TS1005: ';' expected.
--------------------------

I tried so many things to solve the issue but nothing happened. Some of are.
----------------------------------------------------------------------------------
1. change the node version through node version manager.
2. remove the socket-io-client from the package.json file and install it separately later.
3. remove node-module folder and package.lock.json file and then install.
4. clean the cache through **npm cache clear --force**.
5. set maxsockets through **npm set maxsockets 3**.
6. set the npm registry through **npm config set registry http://registry.npmjs.org/ --global**.
7. install through verbose **npm install --verbose**.

**Comment by darrachequesne** [comment]
Hi! Which version of `typescript` are you using? Could you please upgrading it?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
