### ISSUE TITLE
Getting Console Errors

### ISSUE THREAD

**Issue by mdahsanekram** [socketio/socket.io-client#1588]
WebSocketClient.js:13 WebSocket connection to 'wss://loyaltystaging.novusloyalty.com:4040/ws' failed: 
I am getting the above Errors but no package is use for a socket connection on the staging

**Comment by darrachequesne** [comment]
For future readers:

Please check our troubleshooting guide here: https://socket.io/docs/v4/troubleshooting-connection-issues/

Please reopen if needed.
