### ISSUE TITLE
more useful advice about namespace

### ISSUE THREAD

**Issue by 588q9** [socketio/socket.io-client#1590]
**Is your feature request related to a problem? Please describe.**

socketio has a default multiplexing  in front,but i think  every packet need add a flag about namespace then maybe lead namespace become more useful,in our application if has difference namespace then I always open a new namespace in front ,however,if don't close multiplexing ,open same io() and  setting  it namespace  difference each other, that every io() just join last io() that setting namespace.

**Describe the solution you'd like**
add a flag that explain what is belong namespace  in packet

**Comment by darrachequesne** [comment]
For future readers:

The namespace is indeed included in each packet.

Please check the details of the Socket.IO protocol here: https://socket.io/docs/v4/socket-io-protocol/#format

Please reopen if needed.
