### ISSUE TITLE
Next.js v14.0.0 server with socket.io client doesn't send messages with more than a few characters

### ISSUE THREAD

**Issue by njarraud** [socketio/socket.io-client#1596]
**Describe the bug**
Socket.io-client installed on a  Next.js v.14.0.0 server doesn't send messages if they are longer than a few characters.

The issue appeared between Nextjs v.13.5.7-canary11 and v13.5.7-canary12. Everything is working as expected for previous versions.

**To Reproduce**
Socket.IO server version: `4.7.2`
Socket.IO client version: `4.7.2`
Nextjs version: `14.0.0` on nodejs runtime

*Server*

```js
import { Server } from 'socket.io';

const nextNamespace: NextSocketNamespace = io.of('/next');

nextNamespace.on('connection', (socket) => {
  socket.onAny((eventName, ...args) => {
    console.log(`Received event "${eventName}" with data: ${JSON.stringify(args)}`);
  });
});
```

*Client*

Code shall be triggered in a API route for example - not in the browser

```js
import { io } from 'socket.io-client';

const websocket: NextSocketClient = io('ws://localhost:3000/next`);

websocket.emit('partLibraryIconEvent', { test: 'abcd' });
```

**Expected behavior**
The message `Received event "partLibraryIconEvent" with data: [{"test":"abcd"}]` shall be logged on the server console. However nothing is logged.

It is working if a character is removed anywhere - 

- [x] `websocket.emit('partLibraryIconEvent', { test: 'abc' });`
- [x] `websocket.emit('partLibraryIconEvent', { t: 'abcdef' });`
- [x] `websocket.emit('partLibraryIcon', { test: 'abcdefgh' });`

I guess it is serialized as `["partLibraryIconEvent",{"test":"abc"}]`
If this is the case, it seems that 39 characters is the maximum. Anything above and the message is not sent.

**Platform:**
Any

**Comment by njarraud** [comment]
With debugging - 

**Pass** (abc)
<img width="1291" alt="Capture d’écran 2023-11-03 à 14 26 47" src="https://github.com/socketio/socket.io-client/assets/45501180/e9d48f61-2d8d-4177-a8ff-6eb1a321d02e">

**Fail** (abcd)
<img width="1300" alt="Capture d’écran 2023-11-03 à 14 25 54" src="https://github.com/socketio/socket.io-client/assets/45501180/08f596c2-8950-4f77-88de-900e3e2e74c6">

The only difference is `engine.io-client:websocket` displaying `websocket closed before onclose event` at then end.

Heartbeat is still working afterwards.

**Comment by njarraud** [comment]
Here is a github repo to reproduce the error https://github.com/mecabricks/debug-socketio

**Comment by filipjnc** [comment]
Experiencing the same, had to move all server code using websockets back to pages dir api routes.

**Comment by njarraud** [comment]
I believe that NextJS is overwriting something when packing the code. We cannot figure out what.
However, the solution that I just found is to exclude the `socket.io-client` package from webpack on the server.

Here is the code to go in `next.config.js` 
```js
webpack: (config, { isServer }) => {
  isServer && config.externals = [...config.externals,  'socket.io-client'];
  return config;
},
```

**Comment by darrachequesne** [comment]
For future readers:

Please check our guide with Next.js: https://socket.io/how-to/use-with-nextjs

Please reopen if needed.

**Comment by mohammedothmanintegrant** [comment]
I have fixed this issue by identifying the Nextjs server in the same event that I emit.
example
socketio.emit("YOUR_CLIENT_IDENTIFIER","ROOM","DATA")

**Comment by Turbo0x03** [comment]
> I believe that NextJS is overwriting something when packing the code. We cannot figure out what. However, the solution that I just found is to exclude the `socket.io-client` package from webpack on the server.
> 
> Here is the code to go in `next.config.js`
> 
> ```js
> webpack: (config, { isServer }) => {
>   isServer && (config.externals = [...config.externals,  'socket.io-client']);
>   return config;
> },
> ```

this worked for me as well, my problem was similar to yours, i think it has something to do with the caching mechanism but your workaround works, thanks.
