### ISSUE TITLE
Bug: `connect` event will not fire on browser client

### ISSUE THREAD

**Issue by KillerJulian** [socketio/socket.io-client#1597]
**Describe the bug**

My socket.io-client becomes a `connect` event with NodeJS, but when I use the socket.io-client in the browser, I only get an `open` event on the manager (`socket.io.on(...)`).

**Reproduce**

```ts
import { io, Socket } from 'socket.io-client';

const socket = io('ws://localhost');

socket.on('connect', () => console.log('"connect" event was fired'));
socket.io.on('open', () => console.log('"open" event was fired'));
```

Socket.IO client version: `4.7.2`

**Expected behavior**

`connect`-Event is also fired on the browser client side

**Platform:**

 - Node: `v18.16.1`
 - OS: `Windows 10`
 - Browser: `Firefox 119.0`
 
 ---
 
 @morihofi
 @scholzi100

**Comment by darrachequesne** [comment]
Hi! Do you get a `connect_error` event instead?

```js
socket.on('connect_error', (err) => {
  console.log('"connect_error" event was fired', err)
});
```

**Comment by KillerJulian** [comment]
1. i do not get an `connect_error` event
2. for testing I used a socket.io server with Node
3. i used a Jetty server for testing with the WebClient

Could it be that the `connect` event is only thrown when connecting to a socket io server?

**Comment by darrachequesne** [comment]
> for testing I used a socket.io server with Node
> i used a Jetty server for testing with the WebClient

Which server implementation are you using, the Node.js one?

If you enable the debug logs (by setting `localStorage.debug = '*'` in your console), do you get any useful information?

**Comment by KillerJulian** [comment]
The production server is the Jetty server, on which it does not work 100 per cent. The debugging does not produce any further output in the console.

It establishes the connection and also sends data:
![network_trafic](https://github.com/socketio/socket.io-client/assets/36083682/8e1d0470-dd38-48b4-8764-276162a95b0e)

I have to do some weird workarounds to make the connection work:
```ts
socket.io.on('open', () => {
  socket.onconnect();
});

socket.onAny((data) => {
  console.log('Here comes my data', data);
});

socket.on('message', (msg) => {
  console.log('Here comes no data', data);
});
```

**Comment by darrachequesne** [comment]
After the `40...` message (which means "I want to enter the namespace named `/statistics/websocket/stat1/`"), the client should get a response from the server ("OK for namespace `/statistics/websocket/stat1/`"), which does not seem to be the case here.

It sounds like a bug. Could you please open an issue on the repository of the Jetty server?

**Comment by KillerJulian** [comment]
We can mark this issue as solved.

The implementation in the production server was incorrect. This only used the `engine.io` protocol sub-protocol. Then of course it is clear if the corresponding events are not thrown.

Sorry for the inconvenience
