### ISSUE TITLE
websockets are currently broken in Google Chrome but socket.io still chooses to use them - and hangs

### ISSUE THREAD

**Issue by x1024** [socketio/socket.io-client#16]
The test server currently doesn't run in Chrome, but runs perfectly on Firefox.
Some searching led to the discovery that websockets do not currently work in Chrome (June 22nd).

I'm not sure how to select which transports the client should try to use (i.e. "don't try with websocket").
There is either need for such a functionality, or a need for its documentation on http://socket.io/

**Comment by joeydash** [comment]
Hello Cheems

I had the same issue fixed by specifically passing the protocol string

```js
new WebSocket("wss://db.grow90.org/v1/graphql",["graphql-ws"]);
```

here you can see I have passed in the protocol name too

let me know if it works

thanks
