### ISSUE TITLE
Encountering 'TransportError' with socket.io-client in React Native Production Mode

### ISSUE THREAD

**Issue by DDarkLexs** [socketio/socket.io-client#1602]
**Issue Description:**

I'm encountering an error while using `socket.io-client` in production mode within `react-native`. When attempting to establish a connection, the following error is displayed: `{"type": "TransportError", "description":0}`. Notably, this issue doesn't occur in development mode.

**Error Details:**

- **Error Type:** `TransportError`
- **Description:** `0`

**Steps to Reproduce:**

1. Run the application in production mode.
2. Attempt to establish a connection using `socket.io-client`.

**Expected Behavior:**

The `socket.io-client` should connect without encountering any errors in production mode, similar to its behavior in development mode.

**Additional Context:**

- Version of `react-native`: 0.72.6
- Version of `socket.io-client`: 3.1.3

Potential Solutions Attempted:

Attempted installation of various versions of socket.io-client, but the issue persisted despite the version changes.

**Request for Assistance:**

I would greatly appreciate any insights or guidance to resolve this issue in production mode. Any help or suggestions on resolving this issue would be immensely helpful. Thank you in advance for your assistance!

**Comment by darrachequesne** [comment]
For future readers:

Please check our React Native guide: https://socket.io/how-to/use-with-react-native

I'm closing this now, please reopen if needed.
