### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by mehdish3022** [socketio/socket.io-client#1605]
**Describe the bug**
I am currently utilizing Socket.IO client version 4.7.3 for my application. Upon executing the socket.disconnect(); command to sever the connection with the server, I subsequently attempt to re-establish the connection utilizing socket.connect();. However, during this process, I encounter a timeout error. Following this error, the system appears to automatically attempt reconnection procedures.
**To Reproduce**

Socket.IO client version: `4.7.3`

*Client*

```js


const socket = io("ws://localhost:3000/", {autoConnect:false});

socket.on("connect", () => {
  console.log(`connect ${socket.id}`);
});

socket.on("disconnect", () => {
  console.log("disconnect");
});
socket.on("connect_error", (error) => {
    console.error('Socket error:', error);
});
```

**Expected behavior**
I had anticipated that the socket.connect() function would operate seamlessly, logging the socket.id to the console as expected. Contrary to this expectation, there appears to be a delay of approximately 10 seconds, after which the system generates and presents an error: 
```
Socket error: Error: timeout
    at manager.js:137:25

```

The socket.connect() function performs flawlessly when invoked initially. However, an issue arises when it is executed subsequent to the socket.disconnect() call, where it consistently results in an error. This discrepancy in behavior is observed only in instances where socket.connect() is used following a disconnection.

**Comment by darrachequesne** [comment]
Hi! I was not able to reproduce the issue: https://github.com/socketio/socket.io-fiddle/tree/issues/socket.io-client/1605

Could you please check?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
