### ISSUE TITLE
[BUG] building socket.io-client@4.7.4 in a typescript based nodejs docker container results in type script error

### ISSUE THREAD

**Issue by PretoPlasma** [socketio/socket.io-client#1606]
**Describe the bug**
When trying to build the docker container "RUN npm run build" (node:16-alpine) throws the exception:

```
 => ERROR [25/25] RUN npm run build                                                                                                                                                                                          3.0s
------
 > [25/25] RUN npm run build:
0.678 
0.678 > xxx@1.2.1 build
0.678 > tsc
0.678 
2.996 node_modules/engine.io-parser/build/esm/index.d.ts(6,54): error TS2304: Cannot find name 'TransformStream'.
2.996 node_modules/engine.io-parser/build/esm/index.d.ts(7,96): error TS2304: Cannot find name 'TransformStream'.
------
Dockerfile:40
--------------------
  38 |     ENV KUBECONFIG=/home/node/.kube/rancherno-p.yaml;/home/node/.kube/rancherno-t.yaml
  39 |     
  40 | >>> RUN npm run build
  41 |     
  42 |     USER 1000
--------------------
ERROR: failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 2
```

**To Reproduce**

Please fill the following code example:

*Server*
out of scope

*Client*

Socket.IO-client version: `4.7.4`

import { io } from "socket.io-client";

const socket = io("http://localhost:3000", {
   reconnection: true
 });

 socket.on("connect", () => {
   console.log('socket connected:', socket.id);
 });

 socket.on("backend", (data) => {
   console.log('data received on channel: backend, data:', data);
 })

 socket.on("disconnect", () => {
   console.log('disconnected');
 });

**Expected behavior**
I would expect to get a successful image build. The build in nodejs project outside the container fails same (node v16.14.2)

**Platform:**
- Docker

**Additional context**
A look into the labeled file node_modules/engine.io-parser/build/esm/index.d.ts shows that there is no imort for "TransformStream" (row 6, col 54) (row 7, col 96). Maybe this could be the reason and a way to fix it quickly.

**Comment by darrachequesne** [comment]
I could indeed reproduce the issue, thanks for the heads-up :+1: 

See also: https://github.com/socketio/engine.io-parser/issues/136

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/engine.io-parser/commit/0305b4a7a597e0f070ce8ea17106121f9ab369bc, included in `engine.io-parser@5.2.2`. Could you please check?

**Comment by PretoPlasma** [comment]
@darrachequesne I can confirm that this patch on `engine.io-parser@5.2.2` fixes the issue.
Many thanks for your quick action and strong support.

**Comment by darrachequesne** [comment]
Awesome, thanks for the update :+1:
