### ISSUE TITLE
socket.io-client not working on Android API 34 - iOS works normally (React Native) 

### ISSUE THREAD

**Issue by mrbinhdrt** [socketio/socket.io-client#1609]
import React, { useEffect, useState } from 'react';
import {
  StyleSheet,
  Text,
  View,
} from 'react-native';
import io from 'socket.io-client';

const socket = io('your domain socket');

function App(): React.JSX.Element {
  const [connected, setConnected] = useState(false);

  useEffect(() => {
    socket.on('connect', () => {
      console.log("Connect Socket")
      setConnected(true);
    });

    socket.on('disconnect', () => {
      setConnected(false);
    });

    return () => {
      socket.off('connect');
      socket.off('disconnect');
    };
  }, []);

  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Socket Status: {connected ? 'Connected' : 'Disconnected'}</Text>
    </View>
  );
}
export default App;
response error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found
I have configured socket.io-client on my react native project. The application runs on iOS normally but on Android there is no connection response. I use socket.io-client version 4.7.4

**Comment by darrachequesne** [comment]
Hi! It seems like there is a problem when establishing the SSL connection. Did you find the culprit?

Reference: https://developer.android.com/privacy-and-security/security-config

**Comment by darrachequesne** [comment]
@enaluz plain HTTP or HTTPS? Self-signed certificate?

If it works without `transports` and not with `transports: ['websocket']`, then this might indicates that something between the client and the server is preventing the WebSocket connection.

See also: https://socket.io/docs/v4/troubleshooting-connection-issues/
