### ISSUE TITLE
Passing an empty object as ManagerOptions causes uri to be undefined.

### ISSUE THREAD

**Issue by tomlynchRNA** [socketio/socket.io-client#1612]
**Describe the bug**
Passing an empty options object to the client options causes `uri` to be undefined in the manager, and breaks things.

I used to pass an object with a custom transport option. At some point I commented it out like this:
```js
let socketio = io({ /*transports: ['websocket']*/ });
```

See the constructor here: https://github.com/socketio/socket.io-client/blob/4f6030f2c4394bc51d63fe27ed3310d95b9e0a74/lib/manager.ts#L157-L165 if the object is empty, it will overwrite all the options, and uri becomes undefined.

If you run with e.g. `DEBUG=socket.io*` you will see logs like:
```
...
  socket.io-client:manager connect attempt will timeout after 20000 +0ms
  socket.io-client:manager attempting reconnect +0ms
  socket.io-client:manager readyState closed +0ms
  socket.io-client:manager opening undefined//undefined//undefined +0ms
  socket.io-client:manager connect attempt will timeout after 20000 +0ms
  socket.io-client:manager error +44ms
  socket.io-client:manager cleanup +0ms
  socket.io-client:manager reconnect attempt error +0ms
  socket.io-client:manager will wait 5000ms before reconnect attempt +0ms
  socket.io-client:manager error +0ms
  socket.io-client:manager cleanup +0ms
  socket.io-client:manager reconnect attempt error +0ms
  socket.io-client:manager will wait 5000ms before reconnect attempt +0ms
  socket.io-client:manager error +10ms
  socket.io-client:manager cleanup +0ms
  socket.io-client:manager reconnect attempt error +0ms
  socket.io-client:manager will wait 5000ms before reconnect attempt +0ms
  socket.io-client:manager attempting reconnect +2s
  socket.io-client:manager readyState closed +0ms
  socket.io-client:manager opening undefined//undefined//undefined +0ms
  socket.io-client:manager connect attempt will timeout after 20000 +0ms
  socket.io-client:manager error +58ms
...
```

**Comment by darrachequesne** [comment]
Hi! Could you please explain what you are trying to do?

If you call `io()` without an URI, it will uses the [window.location](https://developer.mozilla.org/en-US/docs/Web/API/Location) object to compute the URL in the browser.

If you create a Manager directly (without calling `io()`), then in that case the URL is mandatory:

```js
import { Manager } from "socket.io-client";

const manager = new Manager("http://localhost:3000");
```

Reference: https://socket.io/docs/v4/client-api/#new-managerurl-options

**Comment by tomlynchRNA** [comment]
Hey, probably this was my mistake, a side effect of it running in next.js and getting called server-side where there is no location. All good :+1:
