### ISSUE TITLE
想让他运行时可携带token

### ISSUE THREAD

**Issue by ljbhyy** [socketio/socket.io-client#1613]
https://developers.weixin.qq.com/community/develop/doc/000ae4b6320aa8b1d361d88206b400 @joshk

**Comment by darrachequesne** [comment]
Hi! `extraHeaders` will not be sent if `websocket` is the first element of the `transports` option.

Reference: https://socket.io/docs/v4/client-options/#extraheaders

If you want to send the HTTP headers, you'll need to put `polling` first:

```js
const socket = io({
  // transports: ["websocket", "polling"],
  transports: ["polling", "websocket"],
  extraHeaders: {
    "my-custom-header": "1234"
  }
});
```

**Comment by ljbhyy** [comment]
按照你上面提及的解决方案会报错，替换["polling","websocket"]



---- 回复的原邮件 ----
| 发件人 | Damien ***@***.***> |
| 日期 | 2024年04月24日 16:31 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [socketio/socket.io-client] 想让他运行时可携带token (Issue #1613) |

Hi! extraHeaders will not be sent if websocket is the first element of the transports option.

Reference: https://socket.io/docs/v4/client-options/#extraheaders

If you want to send the HTTP headers, you'll need to put polling first:

constsocket=io({// transports: ["websocket", "polling"],transports: ["polling","websocket"],extraHeaders: {"my-custom-header": "1234"}});

**Comment by ljbhyy** [comment]
按照我那个请求的话只有那个 query 那边才能携带参数吗，这会不会缺少安全隐患(｡･ω･｡)?



---- 回复的原邮件 ----
| 发件人 | Damien ***@***.***> |
| 日期 | 2024年04月24日 16:31 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [socketio/socket.io-client] 想让他运行时可携带token (Issue #1613) |

Hi! extraHeaders will not be sent if websocket is the first element of the transports option.

Reference: https://socket.io/docs/v4/client-options/#extraheaders

If you want to send the HTTP headers, you'll need to put polling first:

constsocket=io({// transports: ["websocket", "polling"],transports: ["polling","websocket"],extraHeaders: {"my-custom-header": "1234"}});

**Comment by ljbhyy** [comment]
Thank you very much author.



---- 回复的原邮件 ----
| 发件人 | Damien ***@***.***> |
| 日期 | 2024年04月25日 04:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [socketio/socket.io-client] 想让他运行时可携带token (Issue #1613) |

Google translate to the rescue!

According to the solution you mentioned above, an error will be reported, replace ["polling", "websocket"]
This is the request code I wrote and the request result screenshot
According to my request, will only the query side be able to carry parameters? Will this cause any security risks (｡･ω･｡)?

The browser WebSocket API does not allow sending additional headers, so allowing HTTP long-polling ("polling") is the only way to send the headers.

There is no additional risks compared to plain WebSocket.

**Comment by ljbhyy** [comment]
import io from 'socket.io-client';
const socket = io('http://127.0.0.1:5000/pipei', { // 添加请求头对象
 extraHeaders: headers
});
import io from 'socket.io-client';
const socket = io('http://127.0.0.1:5000/pipei', { // 添加请求头对象
 extraHeaders: headers
});


要不作者大大努力一下，网页的可以支持✧٩(ˊωˋ*)و✧



---- 回复的原邮件 ----
| 发件人 | Damien ***@***.***> |
| 日期 | 2024年04月25日 04:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [socketio/socket.io-client] 想让他运行时可携带token (Issue #1613) |

Google translate to the rescue!

According to the solution you mentioned above, an error will be reported, replace ["polling", "websocket"]
This is the request code I wrote and the request result screenshot
According to my request, will only the query side be able to carry parameters? Will this cause any security risks (｡･ω･｡)?

The browser WebSocket API does not allow sending additional headers, so allowing HTTP long-polling ("polling") is the only way to send the headers.

There is no additional risks compared to plain WebSocket.
