### ISSUE TITLE
Duplicated event responses

### ISSUE THREAD

**Issue by romancitodev** [socketio/socket.io-client#1617]
**Describe the bug**

I have created a monorepo containing a web and a server, I have set up the server with socket-io and the web with nextjs following [the guide to create a server inside nextjs](https://socket.io/how-to/use-with-nextjs) but when I emit an event, the event fires like 5 times and I only fire one. (And when I set up the server automatically 4 to 6 clients connect, but if I close the page, the 5 clients disconnect at one).

![image](https://github.com/socketio/socket.io-client/assets/84428770/468d2463-14e9-4111-9842-c9abdc65b1a7)

![image](https://github.com/socketio/socket.io-client/assets/84428770/2119100f-6669-4c1a-bfb1-4fcfb74db28e)

I don't know if this is a problem of the Nextjs side or I misconfigured the socket-io client.

**To Reproduce**
1. Open this link: https://stackblitz.com/~/github.com/romancitodev/socket.io-nextjs
or:
1. Create a nextjs monorepo.
2. Create a ws server in `apps/server`.
3. Create a client in `apps/web`.
4. Create a hook called `useSocket` with this:
```ts
import { useState, useEffect, useRef } from "react";
import { io } from "socket.io-client";

const server = io("ws://localhost:4000", { transports: ["websocket"] });

export function useSocket() {
	const [isConnected, setIsConnected] = useState(false);

	const socket = useRef(server);

	useEffect(() => {
		if (!socket.current) {
			socket.current = server;
		}

		const handleMessage = (msg: string) =>
			console.log(`🚀 The socket said: ${msg}`);

		socket.current.on("new-message", handleMessage);

		function onConnect() {
			setIsConnected(true);
		}

		function onDisconnect() {
			setIsConnected(false);
		}

		if (socket.current.connected) onConnect();

		socket.current.on("connect", onConnect);
		socket.current.on("disconnect", onDisconnect);

		return () => {
			socket.current.off("connect", onConnect);
			socket.current.off("disconnect", onDisconnect);
		};
	}, []);

	return { isConnected, socket };
}
```
5. Create a component called `Socket`:
```ts
"use client";

import { useSocket } from "@/hooks/socket";

export function Socket() {
	const { socket } = useSocket();

	if (typeof window !== "undefined") {
		socket.current.emit("message", "hi");
	}

	if (socket.current.connected) return <main>Hello {socket.current.id}</main>;

	return <main>Hello, world!</main>;
}
```
7. Call it from the `page.tsx` root.

Socket.IO server version: `4.7.5`

*Server*

```js
import { createServer } from "node:http";
import { Server } from "socket.io";
import * as e from "./ws-events";

const hostname = "localhost";
const port = 4000;

const http = createServer();
const io = new Server(http, {
	cors: {
		origin: "http://localhost:3000",
	},
});

io.on("connection", e.connect);

http
	.once("error", e.error)
	.listen(port, e.args({ hostname, port }, e.serverUp));
```

Socket.IO client version: `4.7.5`

*Client*

```js
import { useState, useEffect, useRef } from "react";
import { io } from "socket.io-client";

const server = io("ws://localhost:4000", { transports: ["websocket"] });

export function useSocket() {
	const [isConnected, setIsConnected] = useState(false);

	const socket = useRef(server);

	useEffect(() => {
		if (!socket.current) {
			socket.current = server;
		}

		const handleMessage = (msg: string) =>
			console.log(`🚀 The socket said: ${msg}`);

		socket.current.on("new-message", handleMessage);

		function onConnect() {
			setIsConnected(true);
		}

		function onDisconnect() {
			setIsConnected(false);
		}

		if (socket.current.connected) onConnect();

		socket.current.on("connect", onConnect);
		socket.current.on("disconnect", onDisconnect);

		return () => {
			socket.current.off("connect", onConnect);
			socket.current.off("disconnect", onDisconnect);
		};
	}, []);

	return { isConnected, socket };
}
```

**Expected behavior**
The logs from the console should appear one time, not 4 times.

**Platform:**
 - OS: Windows.

**Comment by romancitodev** [comment]
I forgot to clarify that I am using Nextjs 14 with the app router.

**Comment by darrachequesne** [comment]
Hi! I think that the problem comes from the fact that every time you edit the file with the `useSocket()` hook, the Next.js app hot reloads the file but the previous connection is kept alive, thus leading to multiple connections.

That's why, in our [guide](https://socket.io/how-to/use-with-nextjs), the `src/socket.js` file which creates the Socket.IO client is kept to the bare minimum:

```js
"use client";

import { io } from "socket.io-client";

export const socket = io();
```

**Comment by romancitodev** [comment]
I Fixed it, I just changed up a little bit the hook and now looks like this:
https://github.com/romancitodev/socket.io-nextjs/blob/main/apps/web/context/socket.tsx#L31-L69
