### ISSUE TITLE
> 40 means namespace join. As far as I remember.

### ISSUE THREAD

**Issue by JolianGof** [socketio/socket.io-client#1621]
> 40 means namespace join. As far as I remember.
> 
> And script is the name of the namespace

it's sending the number 40 instead of 42/rs when the connection is opened. This discrepancy is causing the connection to close with a "Connection closed: 1000" error.

To ensure the connection remains stable, it's crucial that the client sends "42/rs" as intended. Could you provide guidance on how we can correct this behavior?

@denny99

_Originally posted by @JolianGof in https://github.com/socketio/socket.io/issues/4226#issuecomment-2184021895_

**Comment by JolianGof** [comment]
read more from

[](https://dev.to/wpreble1/socket-io-namespaces-and-rooms-d5h)

**Comment by darrachequesne** [comment]
@JolianGof hi! `42/rs` is not a valid packet, the format of the packets is described there: https://socket.io/docs/v4/socket-io-protocol/#packet-encoding
