### ISSUE TITLE
This repository and its history have been merged into the Socket.IO monorepo

### ISSUE THREAD

**Issue by hongjiaherng** [socketio/socket.io-client#1624]
As this repository has already been merged into the [Socket.IO monorepo](https://github.com/socketio/socket.io), to use this on the client, do we still install and import socket.io-client package in a React project?

Do we still need to install socket.io-client on a React project?
```
npm install socket.io-client
```
Do we import socket.io or socket.io-client on a React project?
```
import io from "socket.io-client";
```

**Comment by darrachequesne** [comment]
Hi! Yes, you still need to install the `socket.io-client` package.

The migration simply means that both packages (`socket.io` on the server side, `socket.io-client` on the client side) live in the same repository.
