### ISSUE TITLE
Connect -> Disconnect -> Connect doesn't work

### ISSUE THREAD

**Issue by JonathanJonathanJonathan** [socketio/socket.io-client#251]
The following code doesn't work for me:
socket = io.connect('http://host.com:8081');socket.disconnect();socket = io.connect('http://host.com:8081');

This is a workaround I've found:
socket = io.connect('http://host.com:8081');socket.disconnect();delete io.sockets['http://host.com:8081'];io.j = [];socket = io.connect('http://host.com:8081');

**Comment by pradeep-rajpoot** [comment]
my code is working as follows : 

To connect : 
socket = window.io.connect();

To disconnect : 
socket.io.disconnect()

To reconnect : 
socket.io.reconnet()

socket.io.disconnect() does emit disconnect event so you can wire-up cleanups if needed.

**Comment by rolandhegedus** [comment]
```javascript
Client.prototype.connect = function() {
    if (!this.connection) {
        this.connection = this.socket.connect(config.host + ':' + config.port);
    }
    else {
        if (!this.connection.connected) {
            this.connection.connect();
        }
    }
};
```

**Comment by nasasutisna** [comment]
> io.connect(null,{'force new connection':true});

this solve my problem, thank you mr. milami
