### ISSUE TITLE
Sending Volatile Messages

### ISSUE THREAD

**Issue by samlown** [socketio/socket.io-client#283]
Hi,

Is there any way to send volatile messages from the client to the server? I know the reverse is possible, but from the client all the messages are buffered. The result of this is that after a failed socket becomes available again a mass of messages are sent at the same time.

At the moment, I'm checking to see if the socket is connected, which works to a certain extent but takes a while to realise the disconnect has happened.

Cheers, sam

**Comment by hunterloftis** [comment]
Any plans to ever support this?

**Comment by tracycollins** [comment]
+1   yes, please!

**Comment by tobeorla** [comment]
+1
