### ISSUE TITLE
Under node, io.transports contains duplicates

### ISSUE THREAD

**Issue by mixu** [socketio/socket.io-client#310]
If you inspect io.transports, you will find that it contains ["websocket", "xhr-polling", "websocket", "xhr-polling"] under Node.

This is because under Node, io.transports contains the names of the supported transports, as added here: 
https://github.com/LearnBoost/socket.io-client/blob/master/lib/io.js#L119

but then each transports appends it's name again when loaded, so you get duplicate transport names. I'd assume this is in part why I cannot get Node to emit connect_failed in my tests.

I'm not sure whether io.util.merge() works as intended for the transport array, if that array already contains items. Simple test case (for 0.8.4 via npm):

```
var obj = { transports: require('socket.io-client').transports };
console.log(obj); // { transports: ['websocket', 'xhr-polling', 'websocket', 'xhr-polling'] }
var result = require('socket.io-client').util.merge(obj, { transports: ['xhr-polling'] });
console.log(result); // { transports: ['xhr-polling', 'xhr-polling', 'websocket', 'xhr-polling'] }
```

For arrays like transports, it merges by replacing into the existing structure at the given position. util.merge is used to configure the sockets ( https://github.com/LearnBoost/socket.io-client/blob/master/lib/socket.js#L42 )

**Comment by plumpNation** [comment]
#322
