### ISSUE TITLE
Are multiple client connections supported?

### ISSUE THREAD

**Issue by andyuk** [socketio/socket.io-client#318]
I am writing unit tests to test my socket.io server. It would be useful to be able to test multiple client socket connections in the same script. I am running the socket.io-client server side.

I've created 2 simple test scripts that show it is currently not possible:

https://gist.github.com/1297838

Obviously multiple socket connections within the browser wouldn't make any sense, but on the server-side I don't see why this shouldn't be possible.

Am I correct with my understanding? Do I need to run multiple Node.js processes if I want to run multiple socket-clients on the server-side?

Any help would be appreciated.

Andrew

**Comment by LoganathanB** [comment]
Thanks for the config suggestion {'force new connection': true}.
