### ISSUE TITLE
Support client certificates in node

### ISSUE THREAD

**Issue by daguej** [socketio/socket.io-client#551]
In the browser, client SSL certificates are supported because the browser automatically sends the client cert that the user picked when loading the page while making a WebSocket connection.  (Although checking that cert on the server currently requires [a bit of a hack](https://github.com/LearnBoost/socket.io/issues/754).)

However, it looks like there's no way to specify a client certificate when using `socket.io-client` from node.  The client does not pass connection options to the transport (which ends up being `ws` in node) and the `ws` module does not allow you to specify cert/ca connection options anyway.

This may be related to #550 since it's a matter of passing connection options to the transport.

**Comment by adrai** [comment]
friendly reminder: not released right now
