### ISSUE TITLE
Using a custom CA in SSL for Nodejs applications

### ISSUE THREAD

**Issue by Ferk** [socketio/socket.io-client#594]
There's not much documentation about socket.io with SSL. And I couldn't find any option concerning trusted Certificate Authorities.

How can I specify the list of certificate authorities that are trusted when I create a socket from nodejs?

I need to use a custom CA for my nodejs application and I want that only authorized certificates are allowed, the ones coming from my root certificate.

I even acked through the code trying to find anything that might help me, but there's nothing, the only option that can be provided when connecting from the client is the "secure" flag, which mostly just takes care to set the right protocol string in the url in a bunch of places and to set the default port to either 443 or 80.

I assume that this feature is not implemented? where does socket.io-client obtain the list of trusted Certificate Authorities? or if it doesn't, then at which point does it delegate this job to a different layer?

**Comment by zxc23** [comment]
Is this still not possible?
