### ISSUE TITLE
Update docs with 'force new connection'

### ISSUE THREAD

**Issue by jareddlc** [socketio/socket.io-client#607]
I could not find listed in the docs `{'force new connection': true }` option for socket create. Should also specify that this option is set to `false` by default.

usage: 

``` javascript
var socket = io.connect(URL, {'force new connection': true });
```

**Comment by JohnMcLear** [comment]
+1

**Comment by AlexioVay** [comment]
I agree. One question as I'm pretty new to socket.io and nodejs: How could you find out this command without documentation anywhere?

**Comment by blented** [comment]
I happened to catch it on a [socket.io blog post](http://socket.io/blog/socket-io-1-2-0/).

[Stackoverflow question](http://stackoverflow.com/questions/31629579/correct-way-to-restart-a-socket-io-server/31632963#31632963) detailing it's use

**Comment by darrachequesne** [comment]
https://github.com/socketio/socket.io-client/blob/master/docs/API.md#iourl-options
