### ISSUE TITLE
Multiple polling requests...too many?

### ISSUE THREAD

**Issue by austinh** [socketio/socket.io-client#626]
Not sure if this is a bug or intended but if I connect, I often have 3 or 4 different XHR/JSONP requests showing up in my web debug tool with null responses when upgrading to a websocket. I am not sending any data/events, so I'm not sure why theyre there.

I understand that there should be at least one XHR/JSONP at first to first connect via polling, and then determine if one can if upgrade to websockets, but why do I have so many showing up before it switches over to websocket, and with null responses?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by Darker** [comment]
Needed indeed! This started happening to me in my project.

#Sample code:

##Server:
```
requirejs(['http', 'socket.io', 'node-static],
    function (Http, SocketIo, staticServer) {
        const staticHTTP = new staticServer.Server('./');
        var http = Http.createServer(function (request, response) {
            request.addListener('end', function () {
                staticHTTP.serve(request, response);
            }).resume();
        });
        var io = SocketIo(http);

        io.on('connection', function (socket) {
            /// Handle connection
            /// but socket IO keeps creating 5 connections per second
        });
        var port = process.env.PORT || 3000;
        http.listen(port, function () {
            console.log('listening on *:' + port);
        });
});
```
##Client:
```
requirejs(["socket.io"], function (io) {
    var socket = io(location.hostname + ":" + location.port);
})
```

**Comment by Gustaf26** [comment]
I got same problem on an event running 4 times instead of just once.

The event is under the io.on('connection', ()=>{}) function and should be started only once upon request from the front end
