### ISSUE TITLE
allow access to handshake headers

### ISSUE THREAD

**Issue by benzen** [socketio/socket.io-client#648]
When establishing the connection, i can 'access' to query string via io.connect(url, {query:'key=value'})

I expected to be able to do something similar with the headers.

I would like to use this to build webapi, with token authentication.

**Comment by mcm-ham** [comment]
So how does this work, all the examples http://socket.io/docs/#using-with-node-http-server use http and the server docs indicate we can access the headers http://socket.io/docs/server-api/#socket#request:request so I assumed it initiates an http connection and upgrades to websockets automatically. Is this not how it works?

**Comment by mcm-ham** [comment]
It looks like you did have code for it at one stage https://github.com/Automattic/socket.io-client/issues/344#issuecomment-9424237

So I'm guessing there were issues so it never made it to the main repo apart from cookies which looks like it has since been removed. In which case it'd be good to update the server documentation which is a bit misleading http://socket.io/docs/server-api/#namespace#use%28fn:function%29:namespace
```js
var io = require('socket.io')();
io.use(function(socket, next){
  if (socket.request.headers.cookie) return next();
  next(new Error('Authentication error'));
});
```
as it indicates cookies (i.e. headers) can be used for authentication. And add a replacement to the obsolete authentication wiki document on the main site on suggestions for authentication as I'm sure it's a common scenario.

**Comment by ruzz311** [comment]
+1 for some resolution to this.  The docs and examples ate up my time as I expected better access to setting headers for token auth as well.

**Comment by ktoh** [comment]
+1.  There is an upcoming release of engine.io client which enables access to headers, which should facilitate resolving this issue. 
https://github.com/socketio/engine.io-client/pull/379

**Comment by netpoetica** [comment]
Is this available from the client JS library as well?

**Comment by vvatikiotis** [comment]
+1. I've into a similar situation where I need to authenticate browser clients. socket.io-client doesn't seem to allow it.

**Comment by WestleyArgentum** [comment]
+1 any updates on this?

**Comment by letchoo** [comment]
Any updates on this?

**Comment by calidion** [comment]
Any updates on this?

**Comment by darrachequesne** [comment]
@fullstackwebdev since `2.0.0`, you can now provide an `extraHeaders` object:
```js
const socket = io({
  transportOptions: {
    polling: {
      extraHeaders: {
        'x-clientid': 'abc'
      }
    }
  }
});
```

Added to the documentation [here](https://github.com/socketio/socket.io-client/blob/master/docs/API.md#with-extraheaders).

**Comment by 4nubhav** [comment]
> Since `2.0.0`, you can now provide an `extraHeaders` object:
> 
> ```js
> const socket = io({
>   transportOptions: {
>     polling: {
>       extraHeaders: {
>         'x-clientid': 'abc'
>       }
>     }
>   }
> });
> ```
> 
> Added to the documentation [here](https://github.com/socketio/socket.io-client/blob/master/docs/API.md#with-extraheaders).

I'm getting the following CORS error with this although I'm using `cors` with `express`:
`Response to preflight request doesn't pass access control check: It does not have HTTP ok status.`

**Comment by 4nubhav** [comment]
> Since `2.0.0`, you can now provide an `extraHeaders` object:
> 
> ```js
> const socket = io({
>   transportOptions: {
>     polling: {
>       extraHeaders: {
>         'x-clientid': 'abc'
>       }
>     }
>   }
> });
> ```
> 
> Added to the documentation [here](https://github.com/socketio/socket.io-client/blob/master/docs/API.md#with-extraheaders).

I'm getting the following CORS error with this although I'm using `cors` with `express`:
> Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by neg3ntropy** [comment]
@4nubhav you have to pass a handlePreflightRequest function like this:
```
    handlePreflightRequest: (request, response) => {
        const headers = { ... };
        response.writeHead(200, headers);
        response.end();
    }
```

**Comment by rohitnishad613** [comment]
> > Since `2.0.0`, you can now provide an `extraHeaders` object:
> > ```js
> > const socket = io({
> >   transportOptions: {
> >     polling: {
> >       extraHeaders: {
> >         'x-clientid': 'abc'
> >       }
> >     }
> >   }
> > });
> > ```
> > 
> > 
> > Added to the documentation [here](https://github.com/socketio/socket.io-client/blob/master/docs/API.md#with-extraheaders).
> 
> I'm getting the following CORS error with this although I'm using `cors` with `express`:
> 
> > Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

then where I declare server URL.
I am using .of("/path") in the server then what i do.

**Comment by rohitnishad613** [comment]
> Since `2.0.0`, you can now provide an `extraHeaders` object:
> 
> ```js
> const socket = io({
>   transportOptions: {
>     polling: {
>       extraHeaders: {
>         'x-clientid': 'abc'
>       }
>     }
>   }
> });
> ```
> 
> Added to the documentation [here](https://github.com/socketio/socket.io-client/blob/master/docs/API.md#with-extraheaders).

I use .of("/path") in the Socket server then what I do where I declare URL.

**Comment by p4rse** [comment]
@4nubhav you should allow that header with `handlePreflightRequest` on the server-side.

```javascript
const options = {
	handlePreflightRequest: (req, res) => {
	 	res.writeHead(200, {
	 		'Access-Control-Allow-Headers': 'x-clientid', // <<< this
	 	});
	 	res.end();
	 },
};
const io = require('socket.io')(server, options);
```

**Comment by darrachequesne** [comment]
Update: in Socket.IO v3, the `transportOptions` is not needed anymore, you can simply use:

```js
const socket = io({
  extraHeaders: {
    'x-clientid': 'abc'
  }
});
```

Documentation for CORS:
- v2: https://socket.io/docs/v2/handling-cors/
- v3: https://socket.io/docs/v3/handling-cors/
