### ISSUE TITLE
How to differentiate events with same name emitted to multiple rooms for same socket

### ISSUE THREAD

**Issue by ismarslomic** [socketio/socket.io-client#686]
Scenario:
In my AngularJS app I have 3 controllers (sharing same socket/client) which joins their respectively room "A", "B" and "C". Server emits an event, with same name "myEvent", but different payload to each of these three rooms in different point of time.

Question:
How can my controllers differentiate which room each of these three events belongs to? Currently my Controller code looks like below, but each controller will retrieve "myEvent" no matter which room it were sent to, since they are sharing same socket. I could of course create 3 sockets, but I feel like this will be an performance issue, since number of controllers is dynamic and it could be from 1-20 for Angular view.

```
socket.on("myEvent", function (data) {
  console.log("Retrieved event myEvent")
})
```

**Comment by darrachequesne** [comment]
A bit late, but I'd suggest using different event names, since the payload is different.
