### ISSUE TITLE
Middleware error not catches

### ISSUE THREAD

**Issue by Korri** [socketio/socket.io-client#688]
I might be making a mistake, but I cannot manage to catch middleware error on client, here is server code:

``` js
(function () {
    'use strict';

    var url = require("url"),
        sio = require('socket.io')(3010);

    //Authentification required
    sio.use(function (socket, next) {
        return next(new Error('refused client'));
    });
}());
```

and client code:

``` js
(function () {
    "use strict";

    //Network
    var socket = io.connect(SOCKET_IO_SERVER);

    socket.on('error', function(){
        console.error(arguments);
    });
}());
```

So is it a bug ?

EDIT: Using network tab on chrome I do see a `polling` request containing "refused client"

**Comment by oliveiragabriel07** [comment]
+1
Error callback is not beeing called on client side When Error is passed as parametter to next on middleware.

**Comment by Korri** [comment]
@oliveiragabriel07 thanks, that seems to be the exact issue, it client is actually refused, but doesn't receive the error.

I created a small repo with a working exception https://github.com/Korri/socket.io-issue688

**Comment by shoerob** [comment]
I'm able to catch middleware errors in socket.io 1.0 w/the 'error' event handler.

**Comment by jbaez** [comment]
I have the same issue when using namespaces. @oliveiragabriel07 solution worked for me as well but I think the client should be able to receive an error thrown in the general connection middelware ( io.use ) I guess this is a socket.io server issue

**Comment by oliveiragabriel07** [comment]
I agree with jbaez.

**Comment by 8webit** [comment]
to catch error you need return after next(). i think this is bug in express.js too.
you should have like this:

```
io.use(function (socket, next) {
       next(new Error('refused client')); 
       return;
});
```




this is not  good

```
io.use(function (socket, next) {
       return next(new Error('refused client'));
});
```

**Comment by darrachequesne** [comment]
I think this is fixed in latest versions.

Please note that, as of Socket.IO v3, a middleware registered on the main namespace will not be triggered when a client tries to connect on another namespace:

```js
// server
io.use((socket, next) => {
  // middleware A
  next();
});

io.use((socket, next) => {
  // middleware B
  next();
});

io.of("/admin").use((socket, next) => {
  // middleware C
  next();
});

// client
const socket = io(); // only A and B will be triggered
const socket = io("/admin"); // only C will be triggered
```

Please find the documentation here:
- https://socket.io/docs/v3/middlewares/
- https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#No-more-implicit-connection-to-the-default-namespace
