### ISSUE TITLE
version 1.0.x is not AMD compatible but 0.9.x works

### ISSUE THREAD

**Issue by reidlai** [socketio/socket.io-client#690]
I keep on getting error when I use dojo AMD loader to load socket.io.js but no problem at branch 0.9.x. I tried both server version and GitHub version.  Please follow up

**Comment by kashifshamaz21** [comment]
I'm using r.js version 2.1.15, and when i minify the build i don't see the "too many anonymous modules issue", so the build went through fine.
But when i load the built output file of r.js in the browser, it throws up the following error:
```
Uncaught ReferenceError: module is not defined
```
The built output file after r.js optimization has the following line from index.js(of root folder),
```
module.exports = require('./lib/');
```
which i believe would result in the `module is not defined` error.

Anybody ran into this, and figured out a way to resolve it?

**Comment by maxbeatty** [comment]
I was able to work around this by upgrading to the latest `requirejs` (2.1.17) and including require.js with our main built output file like [from the optimization docs](http://requirejs.org/docs/optimization.html)

```
node ../../r.js -o baseUrl=. paths.requireLib=../../require name=main include=requireLib out=main-built.js
```

> Since "require" is a reserved dependency name, you create a "requireLib" dependency and map it to the require.js file.

**Comment by kashifshamaz21** [comment]
@maxbeatty  The issue i was facing was due to a different reason altogether.
It was a build system issue at my end, nothing to do with socket-io-client library.
Thanks for the info anyways.

**Comment by reidlai** [comment]
Dear All, finally I worked it out using third-party engine.io AMD client to talk with Socket.IO's new engine "engine.io".  I believe socket-io-client is based on CommonJS....there may be some problems when we use dojo build.

**Comment by kent78** [comment]
We are using the namespace option for our RequireJS optimize build step. And got a "Mismatched anonymous define() module" error for JSON3 and utf8 but if we changed the source code as below we got it to work (not using anonymous define calls). 

    define('utf8', [], function() {
        return utf8;
    });

...

    define('JSON3', [], function () {
        return JSON3;
    });

**Comment by radishj** [comment]
amd-optimize also has this problem 

`Error: A module must not have more than one anonymous 'define' calls.`

**Comment by darrachequesne** [comment]
That should be fixed in latest release, thanks for the heads-up.
