### ISSUE TITLE
documentation should be improved

### ISSUE THREAD

**Issue by SEAPUNK** [socketio/socket.io-client#709]
_figured I'd give this its own issue_

the current documentation is too basic and unclear, and I propose that the new documentation will look and/or feel like [javadocs](http://jd.bukkit.org/rb/apidocs/), that will describe in detail any exposed function or event.

e.g.

| returns | function | arguments | description |
| --- | --- | --- | --- |
| `Socket` | `Socket.emit()` | `string` event | emits an event without data to the socket |
| `Socket` | `Socket.emit()` | `string` event, <br>`object` data | emits an event with the data to the socket |

**Comment by darrachequesne** [comment]
The documentation has been completed: https://socket.io/docs/v3/

Still not perfect, would need some additional code examples, but it should be better now.
