### ISSUE TITLE
Doesnt connect with https from Node client

### ISSUE THREAD

**Issue by rupamkhaitan** [socketio/socket.io-client#712]
Hi

When i updated my socket.io-client to version 1.0.6 and trying to connect to my server using https its not connecting. Here is my code

var socket = require('socket.io-client')('https://localhost:8443');
//console.log('socket instance.......',socket);
socket.on( 'connect', function( socket ) {
    console.log( "Websocket connection to " + server + ":" + port + " established.".green );

});

But the same code above works with 0.9.17 version, is there anything I am missing in new version?

**Comment by JamesMGreene** [comment]
I am experiencing trouble with the Node.js client as well, and so are others it would seem.

Related: #982

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
