### ISSUE TITLE
1.0.6 ACK crashes browser

### ISSUE THREAD

**Issue by mneil** [socketio/socket.io-client#716]
Client:

```
socket.emit('somedata', null, function(data){
      console.log(data);
});
```

Server:

```
socket.on('somedata', function(data, cb){
  debug('some data received %s', data); //some data received null
  cb('I got what you're sending');
});
```

The server receives the data but the acknowledgement is never called. No errors in debugger or the console. I haven't been able to track down where or why but this exact setup works in 1.0.2 but crashes the browser in 1.0.6

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
