### ISSUE TITLE
How to set request headers when connect to server?

### ISSUE THREAD

**Issue by litgh** [socketio/socket.io-client#722]
how to set custom request headers when connect socket.io use js client

**Comment by IonicaBizau** [comment]
I also need that... Did you find any solution?

**Comment by hayksaakian** [comment]
i am also interested in this.

I've seen how to do it on the Java socket.io-client but not the JS one

**Comment by Bizarrus** [comment]
Won't Work with all transport-methods.
If you using XHR/Ajax Polling, it is possible, but not for `WebSockets` on HTML5.

http://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-apic

I'm searching for a solution to.

**Comment by peteruithoven** [comment]
What are you trying to achieve? Can't you use url parameters?

**Comment by badunk** [comment]
I'm trying to write a test to verify whether websockets can be eavesdropped on before and after authentication middleware.

In order to successfully authenticate, however, I need to send a cookie session along with the initial http upgrade request.  It works in the browser, I just want it to work in my node tests as well.

**Comment by bastianwegge** [comment]
Is there any progress on this? Or any hint how to get/set the cookie-session / sessionId within socket.io?

**Comment by badunk** [comment]
I actually got it working.  The details of the initial http handshake are available at `socket.request`.  There, you'll find the session.  For example, using the socket.io middleware:

```
io.use(function(socket, next){
    if (!socket.request.session){
      console.log('no session in socket')
      socket.disconnect();
    }
    next();
  });
```

**Comment by darrachequesne** [comment]
Since version `2.0.0`, you can now set request headers with the `extraHeaders` option:
```js
const socket = io({
  transportOptions: {
    polling: {
      extraHeaders: {
        'x-clientid': 'abc'
      }
    }
  }
});
```

**Comment by muhammadnasr** [comment]
How can I add url to this example
const socket = io({
  transportOptions: {
    polling: {
      extraHeaders: {
        'x-clientid': 'abc'
      }
    }
  }
});

**Comment by IonicaBizau** [comment]
@muhammadnasr  Pass the options in the second argument, the first one being the url:

```
const socket = io("/your-url-here", {
  transportOptions: {
    polling: {
      extraHeaders: {
        'x-clientid': 'abc'
      }
    }
  }
});
```

**Comment by muhammadnasr** [comment]
That's great.

Do you have sample code to set headers for iOS and Android SDK?

Thanks a lot.

**Comment by gtkpr** [comment]
> Since version `2.0.0`, you can now set request headers with the `extraHeaders` option:
> 
> ```js
> const socket = io({
>   transportOptions: {
>     polling: {
>       extraHeaders: {
>         'x-clientid': 'abc'
>       }
>     }
>   }
> });
> ```

how come i can't find anything about this even in socket.io's own documentation?!

**Comment by thethtun-mmds** [comment]
Android : https://github.com/socketio/socket.io-client-java/issues/226

**Comment by shuliangfu** [comment]
Can the headers be dynamically set?

**Comment by darrachequesne** [comment]
For future readers: please see https://socket.io/docs/v3/client-initialization/#extraHeaders
