### ISSUE TITLE
Emitting volatile messages to a namespaced socket fails

### ISSUE THREAD

**Issue by brod-ie** [socketio/socket.io-client#742]
``` coffeescript
io = require("socket.io").listen(server)
map = io.of "/map"
map.volatile.emit 'data'
```

This is failing with the error `TypeError: Cannot read property 'volatile' of undefined`. Can you not emit volatile messages to a namespaced socket?

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io/pull/2013
