### ISSUE TITLE
Socket.io does not close pending requests after disconnecting in polling mode

### ISSUE THREAD

**Issue by sean2449** [socketio/socket.io-client#744]
When I try to disconnect polling socket and create a new one ( by using forceNew ), the old polling GET request becomes pending permanently, and it will never be cleaned up. After I do this several times, all the polling requests are blocked by Socket.io server and never get response. Does anyone have same issue here? 

I solve this by adding timeout for every requests:
Request.prototype.create = function(isBinary, supportsBinary){
..
    xhr.timeout = 5000;
..
}
but I think it's not the right way to do so, any solution?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
