### ISSUE TITLE
IE8 json.stringify Error

### ISSUE THREAD

**Issue by mycaule** [socketio/socket.io-client#748]
I'm using `socket.io` version 1.0.6 with Internet Explorer 8.0.7601 and get the following error just by loading `socket.io.js` with `jquery-1.10.1`

```
Détails de l’erreur de la page Web

Agent utilisateur : Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; .NET CLR 1.1.4322; Tablet PC 2.0)
Horodateur : Thu, 14 Aug 2014 12:17:18 UTC


Message : Cet objet ne gère pas cette propriété ou cette méthode
Ligne : 5066
Caractère : 5
Code : 0
URI : http://localhost:8080/socket.io/socket.io.js
```

line 5066 is

```
    str += json.stringify(obj.data);
```

**Comment by liquidkey** [comment]
hi Tug, how do you upgrade to JSON3 ? I'm using the latest socket.io client js in IE 11 and I'm getting error on json.stringify()

**Comment by Tug** [comment]
Well I haven't forked socket.io for this because I have a modified version of socket.io.
This is because my app embed socket.io with require.js which does not play well with browserify. Anyway I had to edit the socket.io build by hand. Here it is if you want : https://gist.github.com/Tug/3d1c0282df796a518a5c

**Comment by everedifice** [comment]
hi. is there anyone to check this problem?
i can check this problem IE7 also.

i think problem is JSON3 dependency in socket.io-parser repository.
![2015-11-02 10 39 18](https://cloud.githubusercontent.com/assets/1061205/10883023/96738f28-81b2-11e5-97f0-074d4fc0dc05.png)

the 'json' object is empty at IE7.

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-parser/pull/31.
