### ISSUE TITLE
emit utf-8 problem

### ISSUE THREAD

**Issue by tselishev-semen** [socketio/socket.io-client#770]
I'm using `socket.io` version 1.0.3 (https://cdn.socket.io/socket.io-1.0.3.js) and `netty-socketio`1.7.3 (https://github.com/mrniko/netty-socketio)  for server. I have problem in encoding russian letters in emit, example:

```
socket.emit('some_event', { msg: 'Привет мир' });
```

But sent to the server:

```
42["some_event",{"msg":"ÃÂÃÂÃÂ¸ÃÂ²ÃÂµÃÂ ÃÂ¼ÃÂ¸ÃÂ!"}]
```

I tried to use other versions `socket.io`, but the problem remains.
I found, that problem in :

```
while(++index<length){
    codePoint=codePoints[index];
    byteString+=encodeCodePoint(codePoint)
}
```

If replace `encodeCodePoint(codePoint)` by `String.fromCharCode(codePoint)` then sent to the server:

```
42["some_event",{"msg":"ÐÑÐ¸Ð²ÐµÑ Ð¼Ð¸Ñ!"}]
```

and  it's work's fine.

<b>Is there a more elegant way to solve this problem without changing socket.io lib?</b>

**Comment by naanur** [comment]
Запускал чат комнату на flask + socketio 
Проблема возникала с кодировкой когда <script src="../static/socket.io.min.js"></script>
Если <script src="../static/socket.io.js"></script>то проблем с кодировкой нет. Socket.IO v2.2.0

**Comment by alexanderustinov** [comment]
@naanur 
Thanks.
Had same problem with cyrillic 'ыыы' getting transferred to serverside python socket.io backend as 'Ñ\x8bÑ\x8bÑ\x8b'. After changing socket.io.min.js  to socket.io.js it works as expected (recieves 'ыыы')
