### ISSUE TITLE
Query option not working

### ISSUE THREAD

**Issue by vicary** [socketio/socket.io-client#776]
I am aware of a similar case #331 back in 2011 which is still not fixed.

My case is that when I connects with
1. `io(':1337', { query: { __sid: hashed_string } })` it sends the request at the second attempt with `__sid` param.
2. `io(':8080', { query: { __sid: hashed_string } })` It skips the query option all the way.

Not sure if port number matters, but it is the only different.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
