### ISSUE TITLE
Consider removing debug on browser build

### ISSUE THREAD

**Issue by davidbau** [socketio/socket.io-client#787]
socketio.js recently grew by 5K (about 6% of its size) uglified.  That's the cost of including the debug package for the browser.

We should consider removing debug (and calls to debug) from browser builds, and also look for other opportunities to reduce size.

**Comment by darrachequesne** [comment]
Fixed by https://github.com/socketio/socket.io-client/commit/c1dd34c4eb6a1e452179c2090de321c66c0cc974 (included in `socket.io-client@1.7.0`, and still valid today: https://github.com/socketio/socket.io-client/blob/3.1.0/support/prod.config.js#L15)
