### ISSUE TITLE
Feature to use a fallback url for reconnection

### ISSUE THREAD

**Issue by oooookk7** [socketio/socket.io-client#789]
I'm trying to create a use-case whereby, if the socket.io fails to connect, it uses a new url to do a reconnection.

The fallback url maybe set in the options.

Example options:

```
var socket = io.connect('http://test.com:80', {
   reconnection: true,
   reconnectionAttempts: 5,
   reconectionDelay: 10000,
   forceNew: true,
   fallbackUrl: 'http://test-fallback.com:500'
});
```

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by smashah** [comment]
Just in case someone needs it, here is my implementation for socket fallback URL:

https://gist.github.com/smashah/8987a5f621be331e19db301643edb756
