### ISSUE TITLE
ArrayBuffer is deprecated in XMLHttpRequest.send(). Use ArrayBufferView instead. 

### ISSUE THREAD

**Issue by mrichie** [socketio/socket.io-client#794]
In my phonegap app in console , it will output this warning
It tested on android 4.4.2 devise

**Comment by rase-** [comment]
Bumped to `1.4`.

**Comment by darrachequesne** [comment]
According to this https://github.com/socketio/engine.io-client/issues/372, it should be fixed now. Please reopen if needed.
