### ISSUE TITLE
Unhanded error in response handler causes socket hang / timeout

### ISSUE THREAD

**Issue by loopingrage** [socketio/socket.io-client#795]
I have observed that the socket.io client hangs and eventually times out due to a ping timeout if an error is thrown from within a response handler.

Pretty simple to reproduce:

```js
socket.emit('some', thing, function() {
  throw new Error('this will cause the socket to hang');
});
```

After some time you will see in the debug log that the client disconnects due to a server ping timeout.

**Comment by jiangzhuo** [comment]
You should catch error in callback function +1

**Comment by nkzawa** [comment]
Closed due to inactivity.
