### ISSUE TITLE
Cannot find module socket.io-client

### ISSUE THREAD

**Issue by Pranay92** [socketio/socket.io-client#796]
Hi,

Version **1.2.1**

We're using socket.io-client via browserify and we're getting the following error 

`cannot find module socket-io-client`

when using 

`require('socket.io-client)`

I'm assuming this is because we don't have the `main` entry in the `package.json` file. I created a fork of the project and changed the filename to `socket.io-client.js` and created a new release to be able to use it in our project which ultimately resolved the issue.

Is this valid or if something I'm doing wrong? Thanks in advance.

**Comment by 3rd-Eden** [comment]
I think your confused. You mention `bower.json` and browserify in the same issue. Browserify doesn't use `bower.json` it uses `package.json`.

**Comment by Pranay92** [comment]
I've just updated the description above. Thanks!

**Comment by nkzawa** [comment]
This should not be an issue anymore since we have the `main` entry now. Feel free to reopen.
