### ISSUE TITLE
avoid use of undocumented custom `source` field in parsed uri

### ISSUE THREAD

**Issue by defunctzombie** [socketio/socket.io-client#798]
Trying to determine the origin of this field and if we can get rid of it:
https://github.com/Automattic/socket.io-client/blob/master/lib/index.js#L45

/cc @rase- @kevin-roark @rauchg 

This field is non-standard for parsed URIs and causes confusing when debugging the parsed uri object.

Related to debugging invalid url parsing when a full url string is passed to io constructor and the incorrect port is detected.

Related PR to start fixing related issue: https://github.com/Automattic/socket.io-client/pull/797

**Comment by defunctzombie** [comment]
Source started to be used here:
https://github.com/Automattic/socket.io-client/commit/99bfc07b9d9486b361b7a2046c096e2fd8fa43b2#diff-6d186b954a58d5bb740f73d84fe39073R59

But I am unclear on what was the underlying bug that this commit needed to fix.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
