### ISSUE TITLE
possible to use router on client side?

### ISSUE THREAD

**Issue by loveencounterflow** [socketio/socket.io-client#800]
I'm using `socket.io-client` in my NodeJS client side app; can i use `socket.io-events` to listen to events from there, too? Specifically, i'd like to call a function on each socket event that arrives, catching all the events. Is that possible?

**Comment by andrewda** [comment]
+1 did you figure it out?

**Comment by darrachequesne** [comment]
Please consider using [socketio-wildcard](https://github.com/hden/socketio-wildcard).

**Comment by errorx666** [comment]
It looks like socketio-wildcard is being discontinued in favor of `socket.use`, except that API is only available on the server side, not the client side.
