### ISSUE TITLE
Google Closure Compiler fails to parse socket.io client JavaScript

### ISSUE THREAD

**Issue by brianlenz** [socketio/socket.io-client#807]
The Google Closure Compiler fails to parse socket.io's client JavaScript file due to the use of the reserved words "short" and "long", which are defined as functions in the socket.io client. The specific error given for socket.io 1.3.2 is:

> Jan 23, 2015 7:46:56 AM com.google.javascript.jscomp.LoggerErrorManager println
> SEVERE: /jscript/socket.io-1.3.2.js:3983: ERROR - Parse error. identifier is a reserved word
>    ? long(val)
>      ^
> 
> Jan 23, 2015 7:46:56 AM com.google.javascript.jscomp.LoggerErrorManager println
> SEVERE: /jscript/socket.io-1.3.2.js:3984: ERROR - Parse error. identifier is a reserved word
>    : short(val);
>      ^
> 
> Jan 23, 2015 7:46:56 AM com.google.javascript.jscomp.LoggerErrorManager println
> SEVERE: /jscript/socket.io-1.3.2.js:4034: ERROR - Parse error. identifier is a reserved word
> function short(ms) {
>         ^
> 
> Jan 23, 2015 7:46:56 AM com.google.javascript.jscomp.LoggerErrorManager println
> SEVERE: /jscript/socket.io-1.3.2.js:4050: ERROR - Parse error. identifier is a reserved word
> function long(ms) {
>         ^

Those functions will simply need to be given different names (e.g. shortFormat and longFormat).

These were reserved future keywords in older versions of ECMAScript:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Future_reserved_keywords

For now, to work around the issue, we'll just use the pre-minified version off the CDN:

https://cdn.socket.io/socket.io-1.3.2.js

**Comment by CoDanny** [comment]
+1 on this for 1.3.3.

**Comment by giko** [comment]
+ 1

**Comment by vibhavsinha** [comment]
Any quick fix available before the next version?

**Comment by sterlinghirsh** [comment]
I added a pull request to address this. #886

**Comment by eneroth** [comment]
+1

**Comment by stackOverMind** [comment]
I solved this problem by add a option `--language_in=ECMASCRIPT5` to closure compiler .

**Comment by Dreaded-Gnu** [comment]
I've tried to isolate the point where the long() comes in at socket.io.js.
It can be fixed by updating the socket.io-parser dependency to 2.3.2. With that release, the debug dependency within the parser has been updated and the functions long and short disappeared.

The tests passed also without any problems.

If wanted I can also create a short pull request for the dependency update.

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-client/pull/1071.
