### ISSUE TITLE
Impossible to get the reconnecting time in ms after upgrade

### ISSUE THREAD

**Issue by leszekhanusz** [socketio/socket.io-client#809]
With socket.io 0.9.x It was possible to see when a reconnection attempt was going to be made using the reconnecting event.

Now apparently the reconnecting event is returning the same parameter as the new reconnect_attempt event. Which seems to have no sense at all.

In the docs you have:
- reconnect_attempt. Fired upon an attempt to reconnect.
- reconnecting. Fired upon an attempt to reconnect. Parameters:
  - Number reconnection attempt number

But shouldn't it be:
- reconnect_attempt. Fired upon an attempt to reconnect.
  - Number reconnection attempt number
- reconnecting. Fired upon an attempt to reconnect. Parameters:
  - **Number reconnection time (in ms)**

**Comment by darrachequesne** [comment]
I know it's been a while, but you should be able to do it with:

```js
let disconnectionTime;

socket.on("connect", () => {
  if (disconnectionTime) {
    console.log("duration", Date.now() - disconnectionTime);
  }
});

socket.on("disconnect", () => {
  disconnectionTime = Date.now();
});
```
