### ISSUE TITLE
Reconnecting to socket client with different url

### ISSUE THREAD

**Issue by gauravhanda25** [socketio/socket.io-client#815]
Hi I am using node express socket for a chatting app. I am sending request from laravel to node server
as http://192.168.1.91:8155/discussboard?token={some_token} and it connects me to node as well with socket keeping that token as session.Now whenever socket client disconnects it tries to reconnect to socket server sending request to http://192.168.1.91:8155/socket.io/?EIO=3&transport=polling&t=1423735820745-3 without that token.Question is how can I send that token repeatedly with reconnecting event request so that it will maintain session ?

**Comment by nkzawa** [comment]
It seems sockets always reconnects with the same query parameters as far as I tested. Can you post your code?

**Comment by nkzawa** [comment]
Closed due to inactivity.

**Comment by Climax777** [comment]
This is still happening to me. Changing the query field in the object doesn't work.
