### ISSUE TITLE
Tests for websocket doesn't work when using zuul with a support sever 

### ISSUE THREAD

**Issue by nkzawa** [socketio/socket.io-client#834]
When I run zuul tests on local, all tests for websocket fail because of timeout. It's the same when I try with engine.io-client.
As far as I noticed, a support server can send messages, but can't receive a message from client at all.
A workaround is to fix `bouncy/index.js` like the following. (so this may be a bug of `bouncy` module)

```js
s.pipe(dst).pipe(req.connection);
s.resume(); // add this to line 93.

```

I still don't know why this happens, so just report the issue here. I tested this on node v12.2.

**Comment by defunctzombie** [comment]
@nkzawa can we report this on the bouncy module? Possibly with a failing test.

**Comment by nkzawa** [comment]
@defunctzombie I reported the issue on https://github.com/substack/bouncy/issues/69.

Anyway I think zuul should use another proxy module like https://github.com/nodejitsu/node-http-proxy.
It looks bouncy would not be maintained anymore.

**Comment by defunctzombie** [comment]
k, I'll see what it will take to switch to the other module. IIRC last time I looked bouncy was the only one that allowed me to just pass a socket to proxy to versus requiring a target url.

**Comment by nkzawa** [comment]
The issue has already been fixed on zuul.
