### ISSUE TITLE
Calling connect manually during a reconnection breaks subsequent automatic reconnection

### ISSUE THREAD

**Issue by headlessme** [socketio/socket.io-client#836]
When `open()` or `connect()` is called during a reconnection the socket stops trying to reconnect, and if it does manage to reconnect, the next time it's disconnected it won't try to reconnect automatically (even though the options say that it should).

This appears to be because the subscriptions are destroy'd by the call to open() - so the reconnection loop gets broken when the reconnection timer is cleared. Looks like it's when the engineio socket fails to connect and emits an error event which is handled by `errorSub`, which contains a call to `cleanup()`

It doesn't start reconnecting again because the reconnecting flag has been on the manager and the backoff state isn't reset, so `maybeReconnectOnOpen()` won't trigger a new reconnect loop to start.

The behaviour I'd expect for calling connect during a reconnection is that the reconnection is immediately retried and the backoff state is reset - useful for implementing a 'reconnect now' button for users to force reconnections.

**Comment by headlessme** [comment]
I've submitted a pull request that I think fixes this behaviour, but the fix isn't ideal. It adds a flag to the public `Manager.open` / `Manager.connect` API that determines whether or not the backoff state should be reset, so might not be an acceptable fix.

Maybe someone that knows the code better can see a better solution!

**Comment by nkzawa** [comment]
Fixed in https://github.com/socketio/socket.io-client/pull/853
