### ISSUE TITLE
"Unexpected token <" when loading socket.io.js locally

### ISSUE THREAD

**Issue by zappfinger** [socketio/socket.io-client#839]
When I load the client library as follows:
<script src="js/socket.io.js"></script>
I get the above error.
It points to line 4 in the file, that starts with:
<!DOCTYPE html>

I already have defined this line earlier, could that be the  problem?

Richard

**Comment by zappfinger** [comment]
src="js/socket.io.js"

**Comment by nkzawa** [comment]
It has to be `src="/socket.io/socket.io.js"`

**Comment by barbalex** [comment]
I get the same error using this html file:

    <!doctype html>
    <html lang="en">
    <head>
      
      <meta charset="utf-8">
      
      <meta name="viewport" content="width=device-width, initial-scale=1">
      
      <link rel="manifest" href="manifest.json">
      <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/leaflet.css">
      <meta name="mobile-web-app-capable" content="yes">
      <title>AP Flora</title>
    </head>
    <body>
    
    <div id="app"></div>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Mono" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    
    <script src="/socket.io/socket.io.js"></script>
    <script>
      const socket = io()
      console.log(`socket:`, socket)
    </script>
    </body>
    </html>

What am I doing wrong?

**Comment by barbalex** [comment]
it works when I use:

    <script src="https://cdn.socket.io/socket.io-1.4.0.js"></script>

Wo what _is_ the correct url?

**Comment by moreirapontocom** [comment]
Calling socket.io.js locally, it worked when I use browserify to compile the correct required files. Another way is use the lib inside _socket.io-client_
