### ISSUE TITLE
conect_timeout never fired (Websocket)

### ISSUE THREAD

**Issue by Patatruc** [socketio/socket.io-client#843]
Hello,

socket = io(url, {transports: ['websocket']});
socket.io.on("connect_timeout", function() { alert("timeout!"); });

The listener is never fired with the default timeout value (20000). I've tried with lower values and it is the same, except when timeout < ~5000 (IE11) or < ~8000 (Chrome). This limit is not consistent..

Is it a bug, or did I missed something ?

(socket io 1.3.5)

**Comment by darrachequesne** [comment]
The `connect_timeout` event was removed in Socket.IO v3:

```js
// either listen to the "connect_error" on the Socket instance
socket.on('connect_error', (err) => {
  console.log(err);
});

// or listen to the "error" on the Manager instance
socket.io.on('error', (err) => {
  console.log('manager', err);
});
```

See also: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#The-Socket-instance-will-no-longer-forward-the-events-emitted-by-its-Manager
