### ISSUE TITLE
Wrap websocket instantiation in try/catch to catch IE security errors

### ISSUE THREAD

**Issue by mtharrison** [socketio/socket.io-client#844]
IE10/11 will throw a SecurityError when calling `new Websocket(url)`, where `url` is considered to be an intranet site.

In this situation polling would still with s.io work but it doesn't have a chance because the SecurityError isn't being caught. I propose to wrap https://github.com/Automattic/socket.io-client/blob/master/socket.io.js#L3413 in a try/catch and emit an error on the transport if there is one, causing the transport to be frozen. Polling can then continue:

```
try {
    this.ws = new WebSocket(uri, protocols, opts);
} catch (e) {
    return this.emit('error', e);
}
```

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/engine.io-client/pull/475. Thanks for the report.
