### ISSUE TITLE
Add '"main": "socket.io.js"' entry in bower.json

### ISSUE THREAD

**Issue by jake-rigby** [socketio/socket.io-client#846]
bower invalid-meta  socket.io-client is missing "main" entry in bower.json
bower invalid-meta  socket.io-client is missing "ignore" entry in bower.json

I use the main entries to concat depedencies so I have to add this each time I install. Please include it in the repository

**Comment by mhoffmeyerDC** [comment]
@rauchg This issue is resolved by https://github.com/Automattic/socket.io-client/pull/840 and should be merged in to make bower/wiredep function correctly.

**Comment by madickson** [comment]
+1

**Comment by tobiasmuecksch** [comment]
+1 +1 +1

**Comment by boogiebug** [comment]
+1 +1 +1 +1

**Comment by Hrafnkellos** [comment]
+1

**Comment by darrachequesne** [comment]
I think this can be closed now.
