### ISSUE TITLE
Reconnection not working after disconnect() -> connect()

### ISSUE THREAD

**Issue by sSeewald** [socketio/socket.io-client#849]
I think it comes from this solution: #737 

There is a problem after disconnect(). When you call connect() again the reconnection is not working anymore. The main problems are that in the method "Manager.prototype.reconnect" a variable "this.reconnecting" is tested to be true. This is set when i call socket.disconnect(). But after a socket.connect() it is never be reseted. Imho this should be initialized when a socket is opened or connect() is called because this is undefined in the first run.

What makes it tick again:
```
socket.disconnect();
socket.io.reconnecting = undefined; <- false should be the initial value
socket.io._reconnection = true;
socket.connect();
```

**Comment by nkzawa** [comment]
Fixed in 1.4.x.
