### ISSUE TITLE
How can I get passed an ERR_INSECURE_CONTENT error when using https to connect to an IP address instead of a domain name?

### ISSUE THREAD

**Issue by matthewhafner** [socketio/socket.io-client#855]
socket.io - v1.3.5
socket.io-client - v1.3.5
nodejs - v0.10.31 also occurs in v0.12.4

I have a nodejs server running socket.io. All connections to the server are through https with a certificate for *.mydomain.com. I would like to connect to the server from socket.io-client using the server's IP address. When I do, I get an ERR_INSECURE_CONTENT error. I understand that this is working as expected.

I noticed that there is an rejectUnauthorized setting. With the nodejs https server, setting rejectUnauthorized = false allows a connection to take place, even though the certificate is setup for my domain name and not the servers IP address. I tried setting rejectUnauthorized to false with my socket.io server and socket.io client. There was no change in behavior. I still received the ERR_INSECURE_CONTENT error.

Can someone please point me to some documentation for rejectUnauthorized with socket.io, or better yet, offer up a better solution.

Thank you very much.
Matt

**Comment by LuizLeite** [comment]
Hi Matthewhafner.

Did you solve your problem? I got the same around here.

**Comment by mrvik** [comment]
@matthewhafner You can take a domain (some are free) point it to your ip and generate a let's encrypt certificate

**Comment by LuizLeite** [comment]
Yeah. This is at the past. I solved this problem. Certificate wrong. Tanks.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
