### ISSUE TITLE
.emit() fails silently on objects

### ISSUE THREAD

**Issue by EvNaverniouk** [socketio/socket.io-client#857]
When I send an object using `.emit`, I get no errors or warning and nothing is sent to the server:

```
socket.emit('test', {test: true});
```

However, when I stringify it, everything works OK:

```
socket.emit('test', JSON.stringify({test: true}));
```

If sending objects is not allowed -- the library should throw an error.
If sending object is allowed -- the library isn't working correctly.

**Comment by nkzawa** [comment]
Sounds weird. Sending JSON like object is totally supported.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by programat3** [comment]
I have the same problem!!

**Comment by darrachequesne** [comment]
@programat3 could you please open a new issue, with all necessary details? Thanks in advance!
