### ISSUE TITLE
bump engine.io-client version

### ISSUE THREAD

**Issue by mathiask88** [socketio/socket.io-client#858]
Please bump the `engine.io-client` version, so that the a newer `ws` is used to build correct with iojs.

Thanks!

**Comment by chentsulin** [comment]
+1 Waiting for new version. Please upgrade. Thanks

**Comment by chentsulin** [comment]
Oh, I thought this issue could be closed. Because 1.3.6 already use `engine.io-client` 1.5.2 which is using ws `0.7.2`!
