### ISSUE TITLE
Cannot call `next()` after calling `sock.emit()`.

### ISSUE THREAD

**Issue by kawadhiya21** [socketio/socket.io-client#861]
In expressJS, I have a router like:
```
router.on(function (sock, args, next) {
    sock.emit();
    ....
    .....
    ....
    next(new Error("error"));
})
```

The `next()` function doesn't get called if `sock.emit()` is called before. Otherwise it works fine. I want to know why this functionality has been added.

**Comment by nkzawa** [comment]
:question:  `router.on(function (sock, args, next) {` where did this come from?
