### ISSUE TITLE
1.3.6: Use released zuul

### ISSUE THREAD

**Issue by vanjan** [socketio/socket.io-client#862]
Hello,

We're using this library in an environment that doesn't have access to the Internet.
Because the of this, running `npm install` on a project that depends on `1.3.6` fails with the following error:

    npm ERR! fetch failed https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz

Would it be possible to use a release version of zuul and release another patch?

**Comment by dburrows** [comment]
+1

**Comment by vladimir-ivanov** [comment]
Hello, 

Any ETA on this one please? 
Seems to have been opened for a while, and zuul package is registered on npm.
Still experiencing the issue (via karma/ webpack - requesting versions 1.3.7 and ^1.3.6) and hence failing our builds
thanks

**Comment by nkzawa** [comment]
Fixed in 1.4.x
