### ISSUE TITLE
Localhost client to Localhost server

### ISSUE THREAD

**Issue by mcallew** [socketio/socket.io-client#863]
Hi ! 

I meet an issue with your client when i try to connect a localhost client (mocha unit tests)  to my localhost server. The client seems never be connected. But if i put my api on a other machine, it works :s.

In my case (integration tests), it is very blocker.

Can you help me ?

**Comment by mcallew** [comment]
My client code : 

var io = require('socket.io-client');
var socketURL = 'http://localhost:3333';
var app = require('../app');

describe('test', function () {
    it(' socket ', function (done) {
        var socket = io(socketURL);

        io.on('connect', function (socket) {
            socket.emit('hello');
        });
    });
});

Handshake seems to be send but not connected

**Comment by comartmit** [comment]
I am running into this same issue. Enabling client logs shows that the socket opens but never 'connects'.

**Comment by nkzawa** [comment]
@mcallew the code looks weird. `io` should be socket.io-client, but used like a server as well?

**Comment by Arrow7000** [comment]
I have the same issue, but only on Ubuntu. Client never connects to server, whether local or remote. The same app on Windows does connect without a problem. 

Any update on this?

**Comment by jakobhansson** [comment]
Also having this

**Comment by darrachequesne** [comment]
For future readers, please check https://socket.io/docs/v3/troubleshooting-connection-issues/.
