### ISSUE TITLE
provide bower support

### ISSUE THREAD

**Issue by richburdon** [socketio/socket.io-client#864]
Is this package registered with bower?

I see several people cloning the project in order to register what seem to be unofficial versions: e.g.,
https://github.com/Alexandre-io/socket.io-client

**Comment by HarasimowiczKamil** [comment]
:+1:  to bower support

**Comment by alexlrobertson** [comment]
This should be resolved by #840, but that PR has stalled out

**Comment by nkzawa** [comment]
Bower wouldn't be supported. Please see https://github.com/socketio/engine.io-client/issues/289#issuecomment-40621081 for the reason.

**Comment by gaurav21r** [comment]
Bower and indeed all Package Managers can be updated easily with a `grunt-bump` . I think socket.io-client is primarily used in browsers and there would be so many client side browser projects that don't even have a package.json!

I think the effort is minimal and updation of the config file can be automated.
