### ISSUE TITLE
After manual reconnect, namespace'd sockets no longer multiplex connections

### ISSUE THREAD

**Issue by smoodiver** [socketio/socket.io-client#866]
When initially creating namespaces the client will multiplex using existing connections:

    var oldSocket = io.connect('http://127.0.0.1', {path:'/socket.io/mypath'});

    oldSocket.on('connect', function(socket){
      var newSocket = io('/mynamespace');
    });

    oldSocket.id: "vF-AmOhExV8OmkaJAABO"
    oldSocket.io.nsps: {
      '/': Socket,
      '/mynamespace': Socket.id: "vF-AmOhExV8OmkaJAABO"
    }
    newSocket.id: "vF-AmOhExV8OmkaJAABO"

However, if the socket is disconnected and re-connected again the namespace'd sockets no longer retain the ability to multiplex:

    oldSocket.disconnect();
    // Wait any amount of time
    var oldSocket = io.connect('http://127.0.0.1', {path:'/socket.io/mypath'});

    oldSocket.id: "1sw340pXhMK-sb2hAABP"
    oldSocket.io.nsps: {
      '/': Socket
    }
    newSocket.connected: false
    GET http://127.0.0.1/socket.io/?EIO=3&transport=polling&t=1438125195815-9

The newSocket no longer uses oldSocket to multiplex, instead it tries to establish its own independent connecting using default paths.

To avoid the re-connection errors I can do this:

    socket.on('connect', function(socket){
      var newSocket = io.connect('http://127.0.0.1/mynamespace', {path:'/socket.io/mypath'});
    });

This will multiplex the first time around, however after a manual disconnect/reconnect it will establish its own connection to the server. 

    oldSocket.id: "gfcMXwvb02dFDZARAABU"
    oldSocket.io.nsps: {
      '/': Socket
    }
    newSocket.id: "81oDSyjxtIklo3I1AABV"

This means upon a manual disconnect/reconnect the number of connections increases from one to the number of namespaces being used.

Note: Also tried force closing the oldSocket connection:

    oldSocket.io.close()

but this didn't change the behaviour.

**Comment by darkpssngr** [comment]
I think this because we do not remove the namespace from the manager when a namespaced socket is destroyed. because of this when you try to connect to the namespace it returns the old socket object tied to the namespace.

**Comment by nkzawa** [comment]
How do you reproduce the issue? I tried, but somehow I couldn't.

**Comment by smoodiver** [comment]
No worries! 

Note, if you're using the default socket.io path these errors will probably not manifest as 404's as they have for me (it'lll still be establishing lots of new connections though). I am running a few sites from different paths (e.g. ./mysite1/, ./mysite2/) so have Nginx routing accordingly. The non-default socket.io paths (e.g. /socket.io/mysite1/, /socket.io/mysite2/) causes the bug to reveal itself.

## Server code
The server is a modified version of the example on socket.io's site. It creates the socket server and a namespace listener. Connections to the root namespace ('/') and the 'mynamespace' namespace ('/mynamespace') will be emitted a heartbeat in 30s intervals. The server listens on 3003 and in my stack Nginx proxy-passes websocket traffic through to it:

    var self = this;

    function doStuff(){
      function handler (req, res) {
        fs.readFile(__dirname + '/index.html',
        function (err, data) {
          if (err) {
            res.writeHead(500);
            return res.end('Error loading index.html');
          }

          res.writeHead(200);
          res.end(data);
        });
      }

      var app = require('http').createServer(handler)
      var io = require('socket.io')(app);
      var fs = require('fs');

      app.listen(3003);

      io.on('connect', function(socket){
        console.log('socketone connection');
        setInterval(function(){
            socket.emit('heartbeat');
          }, 30000);
      });

      var mynamespace = io.of('/mynamespace').on('connection', function (socket) {
          console.log('mynamespace socket connection');
          setInterval(function(){
            socket.emit('heartbeat');
          }, 30000);
        });
    }

    doStuff();

## Client code

The client javascript has an index to track the number of sockets being created and a function used to create a socket. I use that function to create the first socket to the root namespace ('/') then I bind an event to it that will attempt to create a second socket to a particular namespace ('/mynamespace'). The 2nd socket should multiplex on the 1st one. I store each socket that is created in an object (sockets) so that I can catch the orphan socket that is created in the following scenario:

    var index = 0;
    sockets = {};

    function createSocket(path, options, index){
     
      var localindex = index;
      var socket = io.connect(path,options);
      socket.on('connect', function(){
        console.log('socket connected', index);
      }).on('disconnect', function(){
        console.log('socketdisconnected', index);
      }).on('heartbeat', function(data){
        console.log('heartbeat', data, index);
      }).on('connect_error', function(err){
        console.log('connect_error', index, err);
      });
      
      return socket;
    }
    
    var socketone = createSocket('http://127.0.0.1',{path:'/socket.io/mysite'},index);
    sockets[index] = socketone
    index++;
    socketone.on('connect', function(){
      var sockettwo = createSocket('/mynamespace',null,index);
      sockets[index] = sockettwo;
      index++;
    });


## Recreating

Ok, with the code out of the way here's what happens:

1. Server crashes but starts up again. 
Expected: SocketOne should reconnect and SocketTwo should also reconnect, multiplexing through SocketOne.
Actual: SocketOne reconnects. SocketTwo reconnects and multiplexes. A 3rd Socket is created but it doesn't have the correct connection parameters so continuously attempts to connect causing 404 errors. This 3rd socket is somehow related to SocketTwo attempting to reconnect.

2. Load the page and initiate the sockets:

        Navigated to http://127.0.0.1/mysite/socket.io.test.html
        XHR finished loading: GET "http://127.0.0.1/socket.io/mysite/?EIO=3&transport=polling&t=1449781881691-0".
        XHR finished loading: GET "http://127.0.0.1/socket.io/mysite/?EIO=3&transport=polling&t=1449781881711-1&sid=-k7idBQtms-MG3PvAAAC".
        socket connected 0
        socket connected 1
Both the root and namespaced socket are receiving heartbeat messages from the server. Notice also that the 2nd namespaced socket is using the 1st sockets ID so multiplexing is occurring:

        sockets[0].id
        "-k7idBQtms-MG3PvAAAC"
        sockets[1].id
        "-k7idBQtms-MG3PvAAAC"
3. We kill the server app then re-start it again. Here the sockets reconnect nicely, multiplex and begin receiving heartbeat messages.

        socketdisconnected 0
        socketdisconnected 1
        GET http://127.0.0.1/socket.io/mysite/?EIO=3&transport=polling&t=1449781968360-2 502 (Bad Gateway)
        XHR finished loading: GET "http://127.0.0.1/socket.io/mysite/?EIO=3&transport=polling&t=1449781968360-2".
        connect_error 0 Error: xhr poll error {type: "TransportError", description: 502, stack: (...), message: "xhr poll error"}
        connect_error 1 Error: xhr poll error {type: "TransportError", description: 502, stack: (...), message: "xhr poll error"}
        XHR finished loading: GET "http://127.0.0.1/socket.io/mysite/?EIO=3&transport=polling&t=1449781971087-3".
        XHR finished loading: POST "http://127.0.0.1/socket.io/mysite/?EIO=3&transport=polling&t=1449781971133-4&sid=Z_NoF6R8WaB6eXqQAAAA".
        XHR finished loading: GET "http://127.0.0.1/socket.io/mysite/?EIO=3&transport=polling&t=1449781971135-5&sid=Z_NoF6R8WaB6eXqQAAAA".
        socket connected 0
        socket connected 1

4. Now we start seeing the 404 errors being reported from a 3rd socket (index 2):

        GET http://127.0.0.1/socket.io/?EIO=3&transport=polling&t=1449781971179-6 404 (Not Found)
         XHR finished loading: GET "http://127.0.0.1/socket.io/?EIO=3&transport=polling&t=1449781971179-6".
         connect_error 2 Error: xhr poll error {type: "TransportError", description: 404, stack: (...), message: "xhr poll error"}

Looking at the sockets object we see the first two sockets having nicely reconnected and multiplexed. There is also now a 3rd socket that is trying to connect to the /mynamespace path but without multiplexing, causing the 404 errors.

    sockets[0] = {
        id: "Z_NoF6R8WaB6eXqQAAAA",
        nsp: "/"
    }

    sockets[1] = {
        id: "Z_NoF6R8WaB6eXqQAAAA",
        nsp: "/mynamespace"
    }

    sockets[2] = {
        << note no id key >>
        nsp: "/mynamespace"
    }

It seems that by doing
    
    socketone.on('connect' ...

in the client code I am creating zombie sockets when the initial sockets try to reconnect. I could solve this by using

    socketone.once('connect'

to prevent the 3rd zombie socket appearing, but here's where stuff starts to get a little funny...

## Use case

Lets say I'm building a web-app that needs to behave like this:

1. User logs in
2. Establishes socket.io connection (main connection)
3. Loads widgets
4. Each widget establishes a namespaced/multiplexed socket.io connection
5. User logs out

When logging out if only the main socket.io connetion calls 

    socket.disconnect()

each of the multiplexed connections stay connected. So in turn they need to do

    multiplexed_socket.disconnect()

And finally all of the sockets are disconnected and we're happy. But! What if the user logs in again without refreshing the page? By not refreshing the page the socket.io library is never re-loaded.

6. User logs back in without refreshing the page.
7. Establishes socket.io connection (main connection) - successful
8. Loads widgets
9. Each widget tries to establish a namespaced/multiplexed socket.io connection but fails. Each multiplexed connection doesn't multiplex through the newly created connection (7), instead it tries to create its own connection but with the /namespace path. This causes it to fail like the zombie socket identified above.

## Recreating

Lets modify the client code a little so it's easier to set things up:

## Client code

    var index = 0;
    var sockets = {};
    
    function socketInit(){
      function createSocket(path, options, index){
       
        var localindex = index;
        var socket = io.connect(path,options);
        socket.on('connect', function(){
          console.log('socket connected', index);
        }).on('disconnect', function(){
          console.log('socketdisconnected', index);
        }).on('heartbeat', function(data){
          console.log('heartbeat', data, index);
        }).on('connect_error', function(err){
          console.log('connect_error', index, err);
        });
        
        return socket;
      }
      
      var socketone = createSocket('http://127.0.0.1',{path:'/socket.io/mysite'},index);
      sockets[index] = socketone;
      index++;
      socketone.once('connect', function(){
        var sockettwo = createSocket('/mynamespace',{multiplex:true},index);
        sockets[index] = sockettwo;
        index++;
      });
    }

Now we need to call `socketInit()` to get the sockets going. So...

    window.socketInit()
    XHR finished loading: GET "http://127.0.0.1/socket.io/mysite/?EIO=3&transport=polling&t=1449786249696-0".
    XHR finished loading: GET "http://127.0.0.1/socket.io/mysite/?EIO=3&transport=polling&t=1449786249724-1&sid=H2kWoKWBF_LXZqVzAAAJ".
    socket connected 0
    socket connected 1
    sockets[0].id
    "H2kWoKWBF_LXZqVzAAAJ"
    sockets[1].id
    "H2kWoKWBF_LXZqVzAAAJ"
    2015-12-11 11:24:39.727socket.io.test.html:19 heartbeat 1 0
    2015-12-11 11:24:39.764socket.io.test.html:19 heartbeat 2 1

And now we disconnect both of the sockets:

    sockets[0].disconnect()
    socketdisconnected 0
    Socket {io: Manager, nsp: "/", json: Socket, ids: 0, acks: Object…}
    sockets[1].disconnect()
    socketdisconnected 1
    Socket {io: Manager, nsp: "/mynamespace", json: Socket, ids: 0, acks: Object…}

Looks good, heatbeats have stopped and the connection state is false.

Now we try to re-establish the connection again. This will create a new pair of sockets but that should be OK.

    window.socketInit()
    XHR finished loading: GET "http://127.0.0.1/socket.io/mysite/?EIO=3&transport=polling&t=1449786599310-2".
    XHR finished loading: GET "http://127.0.0.1/socket.io/mysite/?EIO=3&transport=polling&t=1449786599405-3&sid=yt6leCU_2se-XAlXAAAK".
    socket connected 2
    GET http://127.0.0.1/socket.io/?EIO=3&transport=polling&t=1449786599443-4 404 (Not Found)
    XHR finished loading: GET "http://127.0.0.1/socket.io/?EIO=3&transport=polling&t=1449786599443-4".
    connect_error 3 Error: xhr poll error {type: "TransportError", description: 404, stack: (...), message: "xhr poll error"}
    heartbeat 1 2

We can see that the first new socket establishes a connection and looks good (it receives heartbeats) but the 2nd new socket that multiplexes returns 404 errors as it's using some kind of busted path.

The problem occurs because socket.io caches socket managers using an id that is derived from the URL, port, paths, etc. When the socket is disconnected the manager remains in the cache and is never removed. 

Consequently, when the user re-logs in using the same path/namespaces as the first time, the logic that determines if the connection should be a new connection or multiplex an existing one identifies that the derived ID already exists so decides that this must be a new connection rather than a multiplexed one.

This means the 1st re-attempt works because it has all of the path/options needed to establish a new connection. Likewise, the 2nd namespace only socket is also incorrectly detected as requiring a new connection because of the old cache entry, however it doesn't have enough path/options details to establish a new connection so uses the default path and 404's.

**Comment by nkzawa** [comment]
Umm, I can't reproduce. What version of socket.io do you use? Can you you post a whole demo codes which we can just download and start it if possible? (sorry for being too demanding)

**Comment by nkzawa** [comment]
I could reproduce something similar by using the code of master branch. Is this your case?

**Comment by smoodiver** [comment]
Yea this was reproduced on the socket.io-client master branch. It looks like any multiplex'd sockets that existed prior to a disconnect/reconnect will reconnect using an independent socket instead of re-multiplexing. 

This will be OK and almost undetectable if you are using the default /socket.io paths in the URL as the socket will use the default path to connect successfully. However, if your socket.io server is listening on a non-default path (e.g. /socket.io/mysite) the independent sockets will fail to reconnect.

**Comment by nkzawa** [comment]
Actually, this is the expected behavior from the next release. Please see https://github.com/socketio/socket.io/issues/1956.

So you need to cache and reuse a socket in your case.

```js
var sockettwo;
socketone.on('connect', function(){
  if (!sockettwo) sockettwo = io('/mynamespace');
});
```
