### ISSUE TITLE
Win Xp IE8 Socket 1.X Not Working!

### ISSUE THREAD

**Issue by man9565** [socketio/socket.io-client#879]
Win Xp IE8 Socket 1.X Not Working!

![490921c0-541d-11e5-9c2b-68daabef1f34](https://cloud.githubusercontent.com/assets/10486692/9701871/f43f39ee-547c-11e5-96f8-be8cf34d60cd.png)

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
