### ISSUE TITLE
Install error on several node versions

### ISSUE THREAD

**Issue by nicofff** [socketio/socket.io-client#884]
The last released version has a dependency problem with nodeJS 4.0.
Trying to npm install socket.io-client fails with a build error in the utf-8-validate module which is a dependency of ws, which is a dependency of engine-io.client.

The build error of utf-8-validate is already fixed, and the latest version of ws (0.8) points to a fixed version. 
engine.io-client latest release (1.5.4) already uses ws 0.8, but the latest release of socket.io-client is still using version 1.5.2 of engine.io-client.

I can confirm that installing socket.io-client directly from the master branch installs with no problems on node 4.0.

I know I should probably wait for a release, but I couldn't a find reference to this bug anywhere, so I'm creating this bug report so a) You are aware of it (in case you weren't) and b) To have a reference for anyone with the same issue

**Comment by RIAEvangelist** [comment]
+1

**Comment by nicofff** [comment]
Trying to install on v0.10.36, and it fails either with the latest release, or with master. 
I'll report a bug on utf-8-validate and link it here.

**Comment by nicofff** [comment]
Looks like v1.3.5 installs fine on node v0.10.36. The only broken release is the last one

**Comment by RIAEvangelist** [comment]
12.7 should have been good too. that was the previous stable version

**Comment by RIAEvangelist** [comment]
REALLY a pain in the ass that socket.io and is up to date and socket.io-client is not.

**Comment by mischkl** [comment]
bump. still getting errors on node 4 when installing packages with indirect dependencies on this

**Comment by mischkl** [comment]
Actually on second look it seems this has been fixed already, my problem was due to outdated dependencies on my side. So I am closing it.
