### ISSUE TITLE
JsonP dose not work in IE 6-8 when I emit mutiple times continuously

### ISSUE THREAD

**Issue by xiukongtiao** [socketio/socket.io-client#887]
function sendMessage() {
                        var message = $('#msg').val();
                        var jsonObject = {userName: userName,message: message};
                        socket.emit('chatevent', jsonObject);
                        socket.emit('chatevent', jsonObject);
                        socket.emit('chatevent', jsonObject);
                        socket.emit('chatevent', jsonObject);
                        socket.emit('chatevent', jsonObject);
}

When I call this function in IE 8,  only 2-3 request can be sent to server every time, 2-3 message will be lost. 
In other browsers,  it works good.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
