### ISSUE TITLE
Add a minified version of socket.io client

### ISSUE THREAD

**Issue by bryce-larson** [socketio/socket.io-client#888]
Most npm and bower dependencies also include a minified version of their library, the socket.io-client should as well.  

I would like to bundle the socket.io-client with addition minified third party dependencies for my client.   When all of the vendors provide minified versions of their libraries, I can simply concatenate all of the files without having to minify the code myself.  This allows the owners of library to choose the best  minifier for their repository and more importantly it allows them to keep any comments / licence information as part of the minified code.

Thank you.

**Comment by kayz1** [comment]
+1

**Comment by gaurav21r** [comment]
+1 socket.io is to be primarily used in Browsers, so this is a natural Use Case.

**Comment by ironmig** [comment]
+1 would be a nice feature, especially for releases

**Comment by bogomips** [comment]
+1 the script itself is not so big, but search engines can evaluete these "details" for their ranking scores

**Comment by nkzawa** [comment]
I think minified version would never be supported. Please see https://github.com/socketio/socket.io/issues/1847#issuecomment-61384590 .
For keeping comments and license information, use source maps.
