### ISSUE TITLE
Difference with socket.io?

### ISSUE THREAD

**Issue by alvarotrigo** [socketio/socket.io-client#890]
What's the difference between socket.io-client and [socket.io](https://github.com/socketio/socket.io)?

Not very clear to me.

**Comment by nuclearace** [comment]
In a nutshell, socket.io is made up of a few different parts. The core of socket.io is the [socket.io-protocol](https://github.com/socketio/socket.io-protocol) which in turn is built on the [engine.io-protocol](https://github.com/socketio/engine.io-protocol). Engine.io which is what implements the engine.io-protocol. And socket.io implements the socket.io-protocol. The engine.io-client and socket.io-client are just clients that handle the respective protocols.

If that makes any sense.

**Comment by alvarotrigo** [comment]
> The engine.io-client and socket.io-client are just clients that handle the respective protocols.

So... in order to use sockets you need socket.io-client and socket.io ?

**Comment by nuclearace** [comment]
Yes, however socket.io includes all the dependencies
