### ISSUE TITLE
reconnectionAttempts doesn't work after a handshake failed

### ISSUE THREAD

**Issue by lcalvy** [socketio/socket.io-client#891]
Hi, 

It's seems that reconnectionAttempts option doesn't work when a handshake or sid error occur (400 Bad request).
If you set it on connect constructor to 5, if error occur while verifying the request, the client continue to send connection requests.

Manager test correctly 
https://github.com/socketio/socket.io-client/blob/master/lib/manager.js#L486

``` javascript
if (this.backoff.attempts >= this._reconnectionAttempts) {
```

but the value is reseted here
https://github.com/socketio/socket.io-client/blob/master/lib/manager.js#L514

``` javascript
        } else {
          debug('reconnect success');
          self.onreconnect();
        }
      });
```

Is it a normal behaviors?

**Comment by nkzawa** [comment]
It seems that no reconnection on 4XX errors is expected behavior, since 400 means a problem of client and reconnection wouldn't succeed anyway.

**Comment by OronNadiv** [comment]
+1

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by gordol** [comment]
Hello, today we had an issue where a socket.io client tried to reconnect every second after 400 error was thrown.

https://github.com/miguelgrinberg/Flask-SocketIO/issues/414
