### ISSUE TITLE
Upgrade devDependency has-cors@1.0.3 to has-cors@1.1.0

### ISSUE THREAD

**Issue by taemon1337** [socketio/socket.io-client#892]
has-cors@1.0.3 has a dependency on global with a hard link to a github url.  This breaks npm installs behind firewalls or without access directly to github.

**Comment by darrachequesne** [comment]
Done in https://github.com/socketio/socket.io-client/commit/e97f9048a8e533faa2ad32309c7a343361dce066.

Thanks!
