### ISSUE TITLE
Nothing happens...?

### ISSUE THREAD

**Issue by lookapanda** [socketio/socket.io-client#893]
```javascript
var io = require('socket.io-client');
var socket = io.connect('http://ec2-54-226-192-118.compute-1.amazonaws.com', { timeout: 5000 });
socket.on('connect', function () {
    console.log("i have connected.");
});
socket.on('event', function (data) {
    console.log("i have received some data: ");
    console.log(data);
});
socket.on('connect_timeout', function () {
    console.log("i timed out...");
});
socket.on('connect_failed', function () {
    console.log("i failed...");
});
socket.on('disconnect', function () {
    console.log("i have disconnected :(");
});
```

With the code above....Nothing happens. At all.
And I seriously have no idea why. It doesn't fire any of the events (no console.log is appearing)....Can anyone help me?

**Comment by jeremyhuang3627** [comment]
Has the server side http://ec2-54-226-192-118.compute-1.amazonaws.com set up socket.io ? If not, then that may explain why nothing happened in your code.

**Comment by lookapanda** [comment]
Did you click the link and see what it returns?
```
Welcome to socket.io
```

:P So, yes, I'm sure that it has socket.io

**Comment by nkzawa** [comment]
I guess you are using old socket.io v0.9.x. What version of socket.io do you use for client?

**Comment by lookapanda** [comment]
1.3.7

I don't know what version of socket.io is running on the servers. They are not mine, they're from Hitbox.tv

**Comment by nkzawa** [comment]
That's the reason of the issue. Actually `Welcome to socket.io` is the message of v0.9. Clients also must be 0.9 in this case.
