### ISSUE TITLE
restore compliance with 2009/136/EC

### ISSUE THREAD

**Issue by burner-account** [socketio/socket.io-client#895]
Hello!

**Background:**

In order to comply with 2009/136/EC of the European Parliament and of the Council (https://secure.edps.europa.eu/EDPSWEB/webdav/site/mySite/shared/Documents/EDPS/DataProt/Legislation/Dir_2009_136_EN.pdf) aka "EU cookie guideline" websites have to ask for explicit consent if they want to store data on the users' device..

Since the cookie guideline also has to be applied to HTML 5 storages such as sessionStorage and localStorage and it requires active consent from the user to use even such storages, the localStorage.debug flag should be implemented differently.

**Problem:**

version: socket.io-client 1.3.7

I have found no (documented) way to disable the creation of the localStorage.debug flag. It will always be present, although set to undefined. In the blood-shot eyes of the legislators this is a problem. The key 'debug' is present in localStorage, no matter the value of said key - by this you have violated the users' rights. Don't kill the messenger.

Afaik this has its source in line 1503 of socket.io.js, where

``` javascript
if (window.localStorage) debug.enable(localStorage.debug);
```

can be found. The call to debug.enable(undefined) results in

``` javascript
  try {
    localStorage.debug = name;
  } catch(e){}
```

in lines 1422 to 1424 of socket.io.js storing undefined as the value of localStorage.debug.

I would be very happy to see some sort of

``` javascript
if (name === void 0) return;
```

at the top of the debug.enable function body, line 1422.

**Benefits:**

The simple fact of using socket.io would no longer require active consent banners/popups/disturbance. 

What do you think? Is this a feasible request?

**Comment by SEAPUNK** [comment]
The maintainer hasn't worked on this repo for quite some time; if you need it removed, create a fork and use it.

**Comment by dereckson** [comment]
Is the legal interpretation correct? Contentment is not required if the object is "strictly necessary in order for the provider of an information society service explicitly required by the user to provide that service".

Reference: http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm#section_2

**Comment by burner-account** [comment]
I am not a lawyer. But i assume it would be hard to argue that debug flags in a production environment are a necessity covered by the exceptions given in the guideline.

Anyhow, i came here to state that I switched product and no longer care.

Close?
