### ISSUE TITLE
Need more clear documentation about the difference between the standalone build and the nodejs lib

### ISSUE THREAD

**Issue by jiaz** [socketio/socket.io-client#896]
I write a simple GUI application using electron and socket.io client to communicate with a socket.io server.

Initially I used the browserify style to require and initialize the socket io client. Something like:

```
// in index.html
<script>
  require('./client');
</script>

// in client.js
var io = require('socket.io-client');
var client = io('ws://localhost:3000');
client.on('connect', function() {
  // blah, blah
});
```

However this doesn't work. The socket io client hangs on upgrading to websocket transport.

I spend a lot of time to figure out what happened since I'm translating a working CLI node program to the GUI program, which has exactly the same code to connect to the socket.io server.

Then, I accidentally changed the `require` statement to including the standalone client js. Everything works smoothly. Something like this:

```
// in index.html
<script type='text/javascript' src='/socket.io.js'></script>
<script>
  require('./client');
</script>

// in client.js
var client = io('ws://localhost:3000');
client.on('connect', function() {
  // blah, blah
});
```

So I'm trying to understand the difference between the node.js one and the standalone one. Is the node.js version not supposed to be used on webpage even we have tools like browserify? If so I think the documentation should clearly document this.

**Comment by nkzawa** [comment]
The node.js version is supposed to be used on webpage with browserify. Actually, the file served as `/socket.io.js` is build with browserify.
