### ISSUE TITLE
Transport object event handlers interfere even after being replaced (socket.io-client 0.9)

### ISSUE THREAD

**Issue by prateekmr** [socketio/socket.io-client#897]
I noticed that when socket.io client decides to replace a transport object (say on connect timeout) it does not clear the transport's event handlers. Not doing this causes the swapped out transport object event handlers to interfere and cause bad behavior. 

Here is a scenario: Suppose the client initially connects through websocket but the server is slow to respond to the websocket upgrade. The client times out and is able to connect successfully through long poll. Now if the upgrade request comes back or errors out it raises the appropriate event handler on the now replaced WebSocket transport which causes the parent Socket object to disregard that it is connected through long poll. The connection sequence is repeated starting with websocket.

We have observed cases where clients make this sort of never ending oscillating connection attempts websocket-long poll-websocket. (possibly due to proxies denying the websocket upgrade and responding with an error after socket.io client times out and connects through a long poll transport variant)

Have seen this in Socket.io-client 0.8 but not verified in newer versions.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
