### ISSUE TITLE
Wrong path resolving

### ISSUE THREAD

**Issue by amurchick** [socketio/socket.io-client#900]
Version: 1.3.7
```
> io('https://site.com/ws/')
https://site.com/socket.io/?EIO=3&transport=polling&t=1447039681151-0 
```
Wrong - library go to `/socket.io/`instead of `/ws/`

Workaround (not documented option `path`):
```
io({path: '/ws/'})
```
This works fine

**Comment by nkzawa** [comment]
This is the intended behavior. In your case, `/ws` is a namespace of socket.io, not an actual request path.

**Comment by scythargon** [comment]
experiencing the same issue, but my original path is `var socket = io('http://127.0.0.1:8001/chat');`
