### ISSUE TITLE
400 Bad Request Apache 2.2 and Apache 2.4

### ISSUE THREAD

**Issue by CoryGH** [socketio/socket.io-client#906]
I came across an odd issue and I haven't been able to find the source, hoping someone here has an idea.  I have an application that has been running for years on an Ubuntu server without issue and the other week it died - the application utilizes socket.io to talk to a node.js backend, nothing on the server changed unless an update was pushed out by Ubuntu but I'm not seeing anything on the issue online.  Log files for node.js and Apache don't show any records of what is going on.  On the client side I just get a list of:
`POST https://sitename:8082/socket.io/?EIO=3&transport=polling&t=1447809989677-2&sid=LOUwLLIZQvWahhC1AAAA 400 (Bad Request)`
whenever it tries to connect while the URL itself return:
`{"code":1,"message":"Session ID unknown"}`
which as far as I've been able to determine thus far just means a session isn't built for the socket.  When connecting via websocket.org/echo.html to:
`wss://sitename:8082/socket.io/?EIO=3&transport=websocket`
in the same browser in which I receive errors I get:

    CONNECTED
    RESPONSE: 0{"sid":"dqJQzWfgPIvn1C5eAAAA","upgrades":[],"pingInterval":25000,"pingTimeout":60000}
    RESPONSE: 40
    DISCONNECTED

Which appears to at least mean it is communicating.

I have Apache 2.2 set to forward traffic to a virtual host for port 8082 along with web socket forwarding, I noticed the proxy_wstunnel module was causing issues when I tried to simply restart the apache2 process so I looked around online and found that it was no longer functional prior to 2.4 (actually, no idea how it was working before because apparently it is a new module that was configured to run on the server but figured I would try upgrading apache2 to 2.4 and see if it fixed it.)

Does anyone have some insight into how to correct and/or correctly diagnose this issue?

**Comment by nkzawa** [comment]
I'm not sure but isn't this multiple nodes issue? http://socket.io/docs/using-multiple-nodes/

**Comment by CoryGH** [comment]
I should have closed this out awhile ago - the issue was a process on my machine that tried to update npm and all npm libraries - which going from pre-1.0 node.js up was a nasty thing.

**Comment by nkzawa** [comment]
:smile:
