### ISSUE TITLE
Security: Please upgrade `debug` dependency to 2.2.0

### ISSUE THREAD

**Issue by globexdesigns** [socketio/socket.io-client#910]
See https://github.com/socketio/socket.io/issues/2314 for more info.

**Comment by globexdesigns** [comment]
I see that the fix for this has been merged. Could you please bump up the package.json version so that we can upgrade our dependencies?

**Comment by hank7444** [comment]
+1 it still has this issue

**Comment by globexdesigns** [comment]
This was fixed in 1.4.0
