### ISSUE TITLE
release new version

### ISSUE THREAD

**Issue by lironess** [socketio/socket.io-client#917]
Now, when engine-io.client is referencing xmlhttprequest from npm and not from a static url, everyone who want to use socket.io on private networks can. Please bump socket.io-client and socket-io version so everyone can download socket.io with private npm

**Comment by zhzehong** [comment]
+1

**Comment by tripu** [comment]
The required version of `engine.io-client` [has been updated recently](https://github.com/socketio/socket.io-client/commit/fc6451c3acc60f34eca6a3daca98e124e5f6fb3c). This fixes [a documented vulnerability in package `ms`](https://nodesecurity.io/advisories/46).

This needs to be published for other packages to benefit from the fix. [Node Security tools](https://www.npmjs.com/package/nsp) will complain and fail until that is done. (Our particular dependency chain is [`specberus`](https://www.npmjs.com/package/specberus) &rarr; [`socket.io`](https://www.npmjs.com/package/socket.io) &rarr; [`socket.io-client`](https://www.npmjs.com/package/socket.io-client).)

So, +1 to publish new version on npm!

**Comment by Choc13** [comment]
+1. Would like this so that karma can be updated too

**Comment by perrin4869** [comment]
+1

**Comment by tp** [comment]
Finally came down to this issue as well. Having trouble installing karma via an internal Sinopia installation.

**Comment by i059304** [comment]
+1
Do you have a time time estimation when a new version will be released?

**Comment by julianvmodesto** [comment]
+1

@rauchg could you please publish socket.io-client?

Socket.io-client needs to be republished in npm with the updated package.json. It was last published 3 months ago and is out of date.
https://www.npmjs.com/package/socket.io-client

Socket.io-client@1.3.7 still depends on engine.io-client@1.5.4 (instead of 1.6.4) that has the dependency on xmlhttprequest.

Cross-reference: https://github.com/socketio/engine.io-client/issues/348

**Comment by rauchg** [comment]
@julianvmodesto working on the last show-stopper issue right now before `1.4.0`. Should be out ASAP!

**Comment by julianvmodesto** [comment]
@rauchg appreciate it 😬✊

**Comment by americoneto1** [comment]
+1

**Comment by calsirlerilor** [comment]
+1, you cannot use engine.io-client@1.5.4 behind a firewall (that you don't control) since it uses an hardcoded url for xmlhttprequest

**Comment by julianvmodesto** [comment]
Wooh! 1.4 is out! :-)

**Comment by karsunke** [comment]
+1

**Comment by rauchg** [comment]
@karsunke it's out?

**Comment by tripu** [comment]
Thanks!

**Comment by luscus** [comment]
Do not despair, there is always light at the end of the tunnel - no mater how long the tunnel is...

+1

**Comment by rauchg** [comment]
?
