### ISSUE TITLE
could i use websocket protocol in nodejs client?

### ISSUE THREAD

**Issue by ahkimkoo** [socketio/socket.io-client#928]
it seems using xhr-polling protocol in nodejs client, could i use websocket protocol in nodejs client?

**Comment by fourpixels** [comment]
It automatically upgrades to websocket, once the initial connection is made. This is just to be sure that there is a possible connection with xhr-polling as a fallback (if couldn't upgrade).

**Comment by nkzawa** [comment]
Right, thanks @fourpixels !
