### ISSUE TITLE
`reconnectionAttempts` is not listed in the options for the client API

### ISSUE THREAD

**Issue by stepchowfun** [socketio/socket.io-client#929]
Hello! This is just a minor documentation issue.

On this page: http://socket.io/docs/client-api/

The `reconnectionAttempts` option is mentioned, but not listed in the options in the [`Manager(...)`](http://socket.io/docs/client-api/#manager%28url:string,-opts:object%29) section.

Is that intentional? I had to read the source to find out that `reconnectionAttempts` defaults to `Infinity`.

**Comment by rauchg** [comment]
It's not. We're refactoring the docs and open sourcing the so everyone can contribute :)

**Comment by Jokero** [comment]
Many options are not documented. For example, `transports`. Inexperienced users can't fully use the module, they will not look the source code :smile:

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
