### ISSUE TITLE
Depend on engine.io-client 1.6.5

### ISSUE THREAD

**Issue by dapetcu21** [socketio/socket.io-client#930]
`engine.io-client` has been [recently updated](https://github.com/socketio/engine.io-client/commit/62aca32284b17bd22b68f5e18b8c9c0f235da32f) to 1.6.5 which now depends on `ws` 1.0.1, which fixed a [remote memory disclosure vulnerabily](https://nodesecurity.io/advisories/67).

Can you, please, update the dependency in `package.json` and release a new version with this fix?

**Comment by andrewaustin** [comment]
I would like this too.

**Comment by globexdesigns** [comment]
Please issue a patch fix for this when possible.

**Comment by Nilos** [comment]
As this is security related it should be done asap!

**Comment by globexdesigns** [comment]
+1 Please issue a new version when possible. Should be a simple dependency change in package.json

**Comment by darrachequesne** [comment]
`1.4.1` is out!
