### ISSUE TITLE
Uncaught TypeError: Cannot read property 'byteLength' of undefined

### ISSUE THREAD

**Issue by jacargentina** [socketio/socket.io-client#931]
When trying to migrate server & client to the new release 1.4.0

On the client (chrome browser) i get the error:

    Uncaught TypeError: Cannot read property 'byteLength' of undefined

The offending line is here https://github.com/socketio/socket.io-client/blob/master/socket.io.js#L4089

**Comment by andrewaustin** [comment]
It looks like line 4089 should never execute on the client side because of the check on line 4081. The issue seems to be with https://github.com/socketio/socket.io-client/blob/master/socket.io.js#L4073. ```this.ws instanceof global.WebSocket``` is returning false for me.

**Comment by rauchg** [comment]
Looking into this.

**Comment by rauchg** [comment]
Found the issue. Releasing `1.4.1` shortly.

**Comment by rauchg** [comment]
@jacargentina @andrewaustin can you check again?

**Comment by andrewaustin** [comment]
1.4.1 fixes the issue for me.

**Comment by rauchg** [comment]
:+1: :clap: :ok_hand:
