### ISSUE TITLE
Testing on Firefox

### ISSUE THREAD

**Issue by luislobo** [socketio/socket.io-client#937]
Hi,

I've noticed there are no tests on Travis that uses any Firefox version.
Is this for any particular reason?

It'd be just a matter of adding something like, right?:
  - env: BROWSER_NAME=firefox BROWSER_VERSION=36
  - env: BROWSER_NAME=firefox BROWSER_VERSION=35

**Comment by nkzawa** [comment]
It seems because of `wd` module issue.

https://github.com/socketio/engine.io-client/commit/ca9ad8fecd22cc33d32950dbc033c161039cd027#diff-76b2596360a5d338d6cd7132af537418R6

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-client/pull/1011. Thanks for the heads-up.
