### ISSUE TITLE
Getting "err  Error locating github:component/global/archive/v2.0.1.tar.gz." with jspm install

### ISSUE THREAD

**Issue by damianofusco** [socketio/socket.io-client#941]
When i have:
"socket.io-client": "npm:socket.io-client@1.4.5"

In my jspm dependencies in package.json, then run jspm install, i'm getting the error:
"err  Error locating github:component/global/archive/v2.0.1.tar.gz."

It seems this dependency is within the has-cors package, but I thought to post an issue here as well as might have to do with a version of the dependency.

I was able to get rid by including a reference to socket.io-client from github insead of npm in my jspm dependencies:
"socket.io-client": "github:socketio/socket.io-client@^1.4.5"

before I had:
"socket.io-client": "npm:socket.io-client@^1.4.5"

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
