### ISSUE TITLE
Crashes in react native - no userAgent

### ISSUE THREAD

**Issue by stevecass** [socketio/socket.io-client#945]
This line in socket.ios.js `var isAndroid = navigator.userAgent.match(/Android/i);` crashes on react native as navigator.userAgent is not defined. Editing the line to  `var isAndroid = /Android/i.test(navigator.userAgent);` fixes the problem, and I don't see other effects from it the edit, but I'm not sure where the source of that is - as I understand socket.io.js is a generated file. I opened a PR (#944) but closed it after reading that the file is generated.

There are suggested workarounds online to the issue - setting navigator.userAgent in client code, but these break the react native Chrome debugger.

Would be great to fix this at source.

**Comment by danawoodman** [comment]
+1

**Comment by danawoodman** [comment]
This is actually an issue with engine.io-parser on:

https://github.com/socketio/engine.io-parser/blob/master/lib/browser.js#L19

**Comment by danawoodman** [comment]
@stevecass just created a PR on the engine.io-parser library where the offending code lives. Hopefully they merge it soon and Socket.io upgrades engine.io dep

**Comment by darrachequesne** [comment]
Hi! Was your issue fixed by https://github.com/socketio/engine.io-parser/pull/55?

**Comment by darrachequesne** [comment]
Seems it is (https://github.com/socketio/engine.io-parser/pull/55#issuecomment-269738902).
