### ISSUE TITLE
'error' event is not triggered on the socket on connection error

### ISSUE THREAD

**Issue by vicneanschi** [socketio/socket.io-client#947]
I've upgraded from 0.9 and noticed that error event is not triggered on socket when client can't connect to the server.

```
  socket = io.connect(url, opts);
  socket.on('error', function (error) { 
    // never triggered on connection error
  }).on('connect_error', function(error){
    // this is triggered instead
  });

```

Documentation says:

>  Socket::error. Fired upon a connection error

**Comment by vfrc2** [comment]
io.connect return Manager object not Socket, Socket object return in connect callback
