### ISSUE TITLE
Query Parameters automatically URL encoded

### ISSUE THREAD

**Issue by Codewolf** [socketio/socket.io-client#948]
I do not know if this is the expected behaviour or if there is a way around this, i have googled around for the answer to this question.

When submitting query parameters with (socket) io.connect the query parameters are urlencoded which is causing an issue with an API that i am trying to connect to.

example below:

```
socket = io.connect(host, {
        transports: ['websocket'],
        path: serviceEndpoint,
        query: "access_token=1|5-zURhzg6X-vEWUwqBM~b9D0vqHJ-bBR|211|1455710158|7-ykMSvs07-w13mfhpf.CBNJEmmH.GY5"
    });
```

query then becomes
`1%7C5-zURhzg6X-vEWUwqBM~b9D0vqHJ-bBR%7C211%7C1455710158%7C7-ykMSvs07-w13mfhpf.CBNJEmmH.GY5`.

**Comment by nkzawa** [comment]
I think it's the expected behavior. Do you mean it's double-encoded ?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
