### ISSUE TITLE
Uncaught Error: Cannot find module 'ws' (v1.1.0)

### ISSUE THREAD

**Issue by antoniobrandao** [socketio/socket.io-client#949]
I need to use v1.1.0 of socket.io-client, but when I run it in the Browser I get

```
Uncaught Error: Cannot find module 'ws'
```

But the 'ws' module is installed in node_modules (v0.4.31). 

Does anyone have the same problem?

**Comment by antoniobrandao** [comment]
This does not happen with versions above 1.1.0, but I really need to use 1.1.0 for compatibility reasons.

**Comment by carsonjones** [comment]
+1

**Comment by DVassilev** [comment]
I am getting this error on React Native at version 1.4.5.

**Comment by antoniobrandao** [comment]
I've managed to "solve" the problem by downloading the 1.1.0 version (version requirement in my case) from the CDN, and requiring it directly from a local folder (instead of using the NPM module). This was the "Cannot find module 'ws'" doesn't happen. Using Browserify. Still, it would be great if this didn't happen with the NPM module so I could have better dependency management.

**Comment by gabrielstuff** [comment]
This looks related to https://github.com/socketio/socket.io-client/issues/933

**Comment by darrachequesne** [comment]
> This does not happen with versions above 1.1.0
