### ISSUE TITLE
socket.json loop field

### ISSUE THREAD

**Issue by emps** [socketio/socket.io-client#950]
![j](https://cloud.githubusercontent.com/assets/2281169/13197554/76c24672-d7f9-11e5-8468-cb380f822572.jpg)
there is loop of same value inside him self
check 
socket.json.json.json.json.json.json.json ect....

**Comment by emps** [comment]
same with socket.io.nsps['/'].json.json. etc

**Comment by nkzawa** [comment]
It should have no problem. Please let me know if I'm missing something,.

**Comment by emps** [comment]
i dont think that is ok loop pointer 
it is behave same as
```
var demoSocket = { json: this };
demoSocket.json = demoSocket;
console.log(demoSocket)
```
![jj](https://cloud.githubusercontent.com/assets/2281169/13197780/53d93a42-d800-11e5-9fb2-d7b6b3838681.jpg)

**Comment by nkzawa** [comment]
@emps Actually, it's intentionally implemented like that, to support the following.

```js
socket.json.emit();
```
