### ISSUE TITLE
Setting rejectUnauthorized to false is not ignoring certificate error

### ISSUE THREAD

**Issue by aravindsrivats** [socketio/socket.io-client#954]
I've a self signed certificate setup with a different hostname on my server.  I get a 
`WebSocket Error: Network Error 12038, The host name in the certificate is invalid or does not match`
on IE.

I tried setting rejectUnauthorized to false but it still gives me the same error. 

```
var wsconnect = socket('https://url', {
  transports: ['websocket'],
  rejectUnauthorized: false
});
```

Am I doing this right?

**Comment by zeeshanjan82** [comment]
@aravindsrivats using process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

**Comment by roccomuso** [comment]
does it works?

**Comment by YenNavisens** [comment]
does this only works on nodejs but not with the client on browser? I can't get it work from browser. Still pop out `Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID` in chrome

**Comment by YenF** [comment]
does this only work on nodejs but not with the client on browser? I can't get it work from browser. Still pop out `Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID` in chrome

**Comment by mspettel13** [comment]
Did anyone ever figure this out? Having this problem now.

**Comment by darrachequesne** [comment]
`rejectUnauthorized` is indeed a Node.js-only option, I've updated the documentation to make it clearer: https://socket.io/docs/v3/client-initialization/#Node-js-specific-options
