### ISSUE TITLE
Uncaught TypeError: response.setEncoding is not a function

### ISSUE THREAD

**Issue by jstoeffler** [socketio/socket.io-client#961]
Hi,

I tried to install socket.io-client in a meteor app, it seems that browserify is responsible (see [this issue](https://github.com/substack/http-browserify/pull/10)), but I'm posting this here, because I believe other could have the same issue (and in case someone knows a better fix). Feel free to close the issue if you find it appropriate.

So my app crashes [there](https://github.com/mjwwit/node-XMLHttpRequest/blob/master/lib/XMLHttpRequest.js#L457), it's in the node-XMLHttpRequest (the repository doesn't accept issues), which is required by engine.io, which itself is required by socket.io-client.

So I decided to hack the browserify response object, like this:

```
import Response from 'meteor-node-stubs/node_modules/http-browserify/lib/response';
if(!Response.prototype.setEncoding) {
    Response.prototype.setEncoding = function(encoding){
        // do nothing
    }
}
```

And so far it works.

**Comment by cyclopse87** [comment]
Thanks for this buddy helped out a lot

**Comment by shaharyar123** [comment]
where to put this code ? any specific file ?

**Comment by jstoeffler** [comment]
In any file that gets loaded before you use the library. 

Some main/index file would work, or you could put it in a separate file that you'd name specifically so other understand it's a dirty fix.

**Comment by shaharyar123** [comment]
i have put this code in run(), it returns setEncoding = undefined, then i assign a function to it (according to  your solution) ,it returns setEncoding  = function, afterwords it returns setEncoding  = undefined and gives error. i think the XMLHttpRequest.js load continuously that's why its re-change the type of setEncoding ?

**Comment by jstoeffler** [comment]
That's weird. What's the `run()` function you're talking about ?

You probably want to do this outside a function, before your code is executed.

I don't understand why the `Response` would be re-created though.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
