### ISSUE TITLE
'connect' can't be listened in react native

### ISSUE THREAD

**Issue by xushuwei202** [socketio/socket.io-client#964]
Hi,
only  'connect_error' and 'connect_timeout'  can be listened,
You will find that the url about 'ws://echo.websocket.org/'  work well in  the site of 'http://www.websocket.org/echo.html'

My code as follow:

if (window.navigator && Object.keys(window.navigator).length == 0) {
  window = Object.assign(window, { navigator: { userAgent: 'ReactNative' }});
}

const io = require('socket.io-client/socket.io');
const socket = io('ws://echo.websocket.org/', {
  transports: ['websocket'] });

socket.on('connect', () => {
  console.log('connected!');
});

**Comment by ramilushev** [comment]
+1

**Comment by tarkanlar** [comment]
could anyone solve this issue?

**Comment by darrachequesne** [comment]
Hi! `socket.io-client` is not a Websocket client, it uses Websocket transport when available (defaulting to long-polling) but has its own [protocol](https://github.com/socketio/socket.io-protocol), that's why it can't connect (if I properly understand the issue).
