### ISSUE TITLE
Latest via npm is 1.4.6 but I see the latest here is 1.4.5

### ISSUE THREAD

**Issue by ksylvan** [socketio/socket.io-client#969]
1.4.6 broke some of my code but the latest at the repo is 1.4.5. What is the discrepancy?

**Comment by ksylvan** [comment]
1.4.6 breaks some socket.io-client using code, which works with 1.4.5, trying to figure out what changed.

**Comment by YasharF** [comment]
https://github.com/socketio/socket.io-client/commit/2bed4f433dcc09487c9be15ff013d767570aa8d9  1.4.8 is here in the repo
