### ISSUE TITLE
Is there support for session/cookie headers when connecting to an Express/Socket.IO server

### ISSUE THREAD

**Issue by frangelico** [socketio/socket.io-client#970]
I'm currently writing a nodejs worker service which after performing some work, will emit data changes via socket.io-client back to an express app (with socket.io server running).

However when I attempt to connect to the server, the connection fails with the following message:

"sessionId was not found in socket.request"

Code is as follows:
var ioClient = require('socket.io-client');
var socketClient;
socketClient = ioClient.connect("http://localhost:3000", { reconnect: true});
socketClient.on("error",function(error){
        console.log("error: " + error, true);
    });

Is this failure a result of Express app expecting a session/cookie headers? Which is not supported by socket.io-client? If supported, can someone show a working example?

Thanks

**Comment by bsdo64** [comment]
Did you solve it??
I meet same problem..
It have just engine.io's io hash...  'io={hash}'

**Comment by darrachequesne** [comment]
Please use Stackoverflow for that kind of question, thanks.
