### ISSUE TITLE
disconnect() not works in some cases

### ISSUE THREAD

**Issue by jose920405** [socketio/socket.io-client#971]
Steps to reproduce it.
- 1) login with user 1
- 2) logout user 1
- 3) login user 2
- 4) logout user 2
- 5) login user 1 again

Each message that is sent to this user, reaches 2 times.

I use `disconnect()` in logout function.

Swift 2.2

**Comment by PsyTae** [comment]
Are you using `socket.disconnect(true)` in the Client code, or in the Server code?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
