### ISSUE TITLE
Current NPM version uses engine.io-client broken on a slow-CPU and slow-network connection

### ISSUE THREAD

**Issue by vitche** [socketio/socket.io-client#972]
We have build a tool which works over TOR which sometimes has slow SOCKS proxies.
The out-of-the-box (NPM) socket.io-client fails while probing the connection because the socket gets nullified before it is used in .once('packet').

Seems the same error occurs in the browser version because we have lost connections in the browser versions, too.

I see that the engine.io-client is being rewritten currently. But hope that the suggested fix or just the idea of the bug may be useful for ones who have the same small speed problem.

Here is the suggested hot-fix: 
https://github.com/vitche/nodejs-onion-redis-client/blob/master/patches/engine.io-client/lib/socket.js.diff

**Comment by darrachequesne** [comment]
Hi! Could you provide a failing test? [Here](https://github.com/socketio/engine.io-client/blob/1.8.2/lib/socket.js#L285) it seems the `failed` flag should prevent such a case, isn't it?
