### ISSUE TITLE
Would be nice to be able to specify namespace in options

### ISSUE THREAD

**Issue by zacharynevin** [socketio/socket.io-client#973]
Hello,

I have a chat system that is also versioned. For example, I may have two paths: `/chat/v0.0.0` and `/chat/v0.1.0`. There is an NGINX gateway that sits in front that handles the proxying and ensuring that requests to each get proxied as `/chat/socket.io/...` to each (i.e. stripping the version number), so that each chat API version sees the same url.

However, on the client the namespace is pulled from the URL. For example (two clients shown for demonstration purposes):

```
var client = io('/chat/v0.0.0`) <-- Thinks the namespace is /chat/v0.0.0
var otherClient = io('/chat/v0.1.0) <-- Thinks the namespace is /chat/v0.1.0
```

Note that in the application I am not using both clients at once. Instead, the process is for making breaking changes to the chat-api with zero downtime. I deploy the new version on the server, and then point the frontend to that new version and take down the old one.

In this case, I get an `Invalid Namespace` error because on the server I have the namespace set to `/chat`. It would be nice to have something like the following:

```
var client = io('/chat/v0.0.0`, { namespace: '/chat' })
var otherClient = io('/chat/v0.1.0', { namespace: '/chat' })
```

In the meantime I can put the version in the namespace on the server.

**Comment by zacharynevin** [comment]
Would this be difficult/nearly impossible because of how multiplexing is handled?

**Comment by darrachequesne** [comment]
For future readers: you can use the `path` option:

```js
var client = io('/chat', { path: '/chat/v0.0.0' })
var otherClient = io('/chat', { path: '/chat/v0.1.0' })
```

Documented here: https://socket.io/docs/v3/client-initialization/#path
