### ISSUE TITLE
Socket problem 

### ISSUE THREAD

**Issue by EnVires** [socketio/socket.io-client#974]
there is a server (Node.js) and two clients ( website and Node.js)! (Node.js client) does not see some socket !
http://i.imgur.com/rgKQ7yM.png

**Comment by calbertts** [comment]
I think you have to put those two events inside the 'connect' callback and use the **socketf** parameter to bind those events, because those events can be setted once the connection exists.

**Comment by carpii** [comment]
Yup, assign your event handlers in the servers socket.on('connection') handler. 

This is not a valid bug, ticket should be closed.
