### ISSUE TITLE
Manager reconnect and socket reconnect

### ISSUE THREAD

**Issue by perrin4869** [socketio/socket.io-client#975]
Moving https://github.com/socketio/socket.io/issues/2343 here.

I think there should be a distinction between Manager events and Socket events.
Right now, a socket emits a `reconnect` event whenever the associated `Manager` does, which is not very intuitive. 

For example, if you need some authentication before reconnect can happen, and the authentication fails, I expect the manager to emit `reconnect`, but I do not expect the socket to emit `reconnect`.

The same logic could probably be applied to a `connect` event, but I'm not sure.
I could try to submit a PR, but this would be a breaking change.

**Comment by darrachequesne** [comment]
Done in Socket.IO v3: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#The-Socket-instance-will-no-longer-forward-the-events-emitted-by-its-Manager
