### ISSUE TITLE
extraHeader ignored in browser

### ISSUE THREAD

**Issue by fullstackwebdev** [socketio/socket.io-client#976]
This line, seems to detect if we are in a node.js environment:

https://github.com/socketio/socket.io-client/blob/13002fb444e587ccdf2aa84711c8f0890d47b5ad/socket.io.js#L2177

However, I am trying to set in the browser (Angular) :
extraHeaders : { Authorization : 'Bearer xxxx' }

for JWT authentication to my REST service, hapi-io, which supports token authentication for websockets.

How else can I set a header or accomplish the same thing? 

If I comment code around 2177, it doesn't not send the header. 

Thanks

**Comment by fullstackwebdev** [comment]
Note for people who found this via google in the future:

As a work around for now, I am passing the token in the query ( io.connect(undefined, { query : "token="+auth.getToken()} ); 

Then, on my server which is Hapi, I use hapi-auth-jwt2 which has a authentication strategy for tokens that has query parameter /?token=<TOKEN> built in and enabled by default.   Only use it with SSL.

However I would like to use extraHeaders if possible. Thanks!

**Comment by gaastonsr** [comment]
Thanks @fullstackwebdev. I'm having trouble to find the documentation of the options.

**Comment by brettmc** [comment]
@fullstackwebdev I've been fighting with extraHeaders in an angular app all day. I too think extraHeaders during the initial handshake would be the best way.

I just successfully implemented [this concept](https://facundoolano.wordpress.com/2014/10/11/better-authentication-for-socket-io-no-query-strings/) which seems like a more elegant solution than passing query parameters. I think it should be safe if you are using SSL/wss.

Basically, you let the socket connect, but then make the client pass their token in an 'authorize' message.
Something like this (server):
```
io.on('connection', function (socket) {
    socket.authorized = false;
    socket.emit('connected', {connected: true, authorized: false});
    socket.on('authorize', function(data) {
        //validate token, set socket.authorized = true, socket.username etc
```
and this (client):
```
var socket = io(host);
socket.on('connected' function (data) {
    console.log("connected but not authorized");
    socket.emit('authorize', {token: "oauth/JWT token goes here";
});
socket.on('authorized', function (data) {
    console.log("authorized");
});
```
I'm also wondering if you could use a middleware to reject all messages that don't have socket.authorized set...?

**Comment by gaastonsr** [comment]
They have a point. If I rembeber correctly since sending headers is not the in the official spec of Websocket is not something they want to support.

The way I fixed this in my case is by sending the value I want to send through a cookie. But query params works too.

**Comment by darrachequesne** [comment]
=> https://github.com/socketio/engine.io-client/pull/519.

**Comment by gaastonsr** [comment]
So this is supported now?

**Comment by vitriol** [comment]
So it seems like this was added to master. Does anyone know if other clients (android,ios) will implement this soon ?

**Comment by mikermcneil** [comment]
@vitriol @gaastonsr this is related to https://github.com/socketio/engine.io-client/issues/554

**Comment by darrachequesne** [comment]
@fullstackwebdev since `2.0.0`, you can now provide an `extraHeaders` object:
```js
const socket = io({
  transportOptions: {
    polling: {
      extraHeaders: {
        'x-clientid': 'abc'
      }
    }
  }
});
```

Added to the documentation [here](https://github.com/socketio/socket.io-client/blob/master/docs/API.md#with-extraheaders).

**Comment by acarstoiu** [comment]
This issue should be reopened for the `websocket` transport.
In the `socket.io` API documentation you've placed a link to the WebSocket RFC, chapter 4, but if you keep reading in there you'll encounter this paragraph:
```
 12.  The request MAY include any other header fields, for example,
        cookies [RFC6265] and/or authentication-related header fields
        such as the |Authorization| header field [RFC2616], which are
        processed according to documents that define them.
```
So, there's **no rule against setting other headers** from the browser, when establishing WebSocket connections - quite the contrary. By coincidence or not, I landed here precisely because of an authentication problem.

The [engine.io-client's documentation](https://github.com/socketio/engine.io-client/blob/master/README.md) should be ammended, too.

**Comment by acarstoiu** [comment]
I got it, you're missing a proper API in browser. Damn.

**Comment by onbetelgeuse** [comment]
From client side. You must to inverse your transport mode like that :  ['polling', 'websocket']  and set  withCredentials: true to activate credentials cookies and extraheaders
