### ISSUE TITLE
There's no connection using this library from NodeJS in a Unit Test

### ISSUE THREAD

**Issue by calbertts** [socketio/socket.io-client#977]
I'm trying to create a unit test by using this library, I already have my server working fine with the browser, in the client side I'm just including the **script** tag to create the **io** object.

When I try to create a connection from the unit test (using babel-node or node only) it never connects with the server... actually, I've tried from a different tab in the browser and it works fine from there, but from the test script it doesn't.

Any idea?

**Comment by darrachequesne** [comment]
Please use Stackoverflow for that kind of question, thanks!
