### ISSUE TITLE
How to use cluster on socket.io-client?

### ISSUE THREAD

**Issue by vermaslal** [socketio/socket.io-client#987]
Hi,

I want to use cluster on both side (Server and Client). I have got success on server side, but unable to do on client side. I am using node.js on both (Server side and Client side).

Please help.

**Comment by darrachequesne** [comment]
Please use [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) for such question.

**Comment by slidenerd** [comment]
Does a socket-io client integrate with node cluster by any chance. I couldnt find anything on stackoverflow on this topic under the [socket-io] tag

**Comment by vermaslal** [comment]
@slidenerd You can refer this question. https://stackoverflow.com/questions/38974360/how-to-use-cluster-on-socket-io-client
