### ISSUE TITLE
argument on error event should be objects according to docs

### ISSUE THREAD

**Issue by CxRes** [socketio/socket.io-client#988]
According to the docs, events for socket include:
- `error`. Fired upon a connection error Parameters:
  - Object error data

However in reality `error` callback emits a string instead of an Object. For example, a namespace error the callback emits `'Invalid namespace'`. Actually this seems to be the case for all tests. Either the docs or the design has to be wrong.

I presume that design is wrong because in an ideal scenario, if the developer wants the functionality, server should be able to tell the client why the error occurred.

**Comment by darrachequesne** [comment]
For future readers:

That was indeed a problem which was fixed in Socket.IO v3: connection errors would emit an Error object, while namespace errors would emit a string.

See also: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#A-middleware-error-will-now-emit-an-Error-object
