### ISSUE TITLE
Loss messages

### ISSUE THREAD

**Issue by AleksMx** [socketio/socket.io-client#989]
Hello, sometimes this code does not work (50/50):

socket = io('', {path: '/chat'});
socket.on('connect', function () {
   var wait = 1;
   setTimeout (function () {
      social.socket.emit ('test', '1234', function (data) {
         alert (data);
      });
    }, wait);
 });

Server:
io.on('connection', function(socket) {
    socket.on ('test', function (obj, callback) {
        callback ('server ok');
    });
});

If  I set 'wait' = 3000, this code work, The error occurs when the socket.io change protocol from polling to websocket. To reproduce the error open Chrome browser and set in the debug panel slow chanel (for example GPRS).

socket.io 1.4.5

Please fix this bug.

**Comment by darrachequesne** [comment]
Unfortunately I couldn't reproduce, even when using GPRS setting: https://github.com/darrachequesne/socket.io-fiddle/tree/issue/lost-message

Is is related to a given browser?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
