### ISSUE TITLE
Firefox: 'connect' event not fired on page reload

### ISSUE THREAD

**Issue by prasanthsd** [socketio/socket.io-client#990]
Hi,
Im having something like the below code.

```
<script src="/socket.io/socket.io.js"></script>
<script>
  var socket = io('http://localhost:8080');
  socket.on('connect', function(){});
  socket.on('event', function(data){});
  socket.on('disconnect', function(){});
</script>
```

The connect event does only fire on the first load of the page. After that if I refresh the page the event is not called. In chrome this works perfectly and it call connect.

**Comment by darrachequesne** [comment]
Hi! I am not able to reproduce on Firefox v48.0 (Ubuntu).

Do you get any message in the console? Are the scripts properly loaded?

**Comment by prasanthsd** [comment]
No messages in console and all the scripts are properly loaded. This happens consistently.

This was the workaround that I used for the time being:
http://stackoverflow.com/questions/39433922/socket-io-connection-event-not-firing-in-firefox

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
