### ISSUE TITLE
Problem connection to url with protocol wss://

### ISSUE THREAD

**Issue by akoufatzis** [socketio/socket.io-client#992]
I have a problem using this client in Node.Js to connect to an url using wss instead of http. I am using this client like:

`const socket = require('socket.io-client')('wss://mylocation);`

I want to use this library instead of the ws module for node.js so i can benefit from the autoconnection features that are missing from the ws module. I also have successfully established a connection using the ws module with the same url.

**Comment by darrachequesne** [comment]
Hi!

> I have a problem

What kind of problem are you having? Do you get any error?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
