### ISSUE TITLE
Chrome page crashes on lots of bidirectional messages: `RangeError: Array buffer allocation failed`

### ISSUE THREAD

**Issue by mtfurlan** [socketio/socket.io-client#993]
When the server is sending lots of messages and the client sends some messages, in chrome Version 53.0.2785.116 (64-bit) the page gives `RangeError: Array buffer allocation failed` on [line 1217 of the socket client][3].
Works fine(slowly) in firefox 48.0.

Demo showing the issue:
```
"use strict";

var express    =    require('express');
var app        =    express();
var http       =    require('http').Server(app);
var io         =    require('socket.io')(http, { pingInterval: 5000, pingTimeout: 15000 });

var server = http.listen(3030,function(){
  console.log("Express is running on port 3030");
});

io.on('connection', function(socket) {
  socket.on('last connect', function(args) {
    for(var i=0; i<9001; ++i){
      socket.emit('new message', JSON.stringify({
        id : "1474048951-af33e660",
        name : "data",
        type : "data"
      }));
    }
    socket.emit('end messages');
  });
});
```
And the package.js specifies versions:
```
"express": "~4.0.0"
"socket.io": "^1.4.5"
```
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Demo socket thing</title>
  </head>

  <body>

    <span id="count"></span> messages

    <script src="https://cdn.socket.io/socket.io-1.4.5.js"></script>
    <script type="text/javascript">
      console.log("Starting...");
      var count = 0;
      var socket = io('http://localhost:3030');
      socket.on('connect', function(){
        console.log("connected");

        socket.emit('last connect');
        for(var i=0; i<42; ++i){
          socket.emit('some message');
        }
      });
      socket.on('end messages', function(){
        console.log("done");
      });
      socket.on('new message', function(data){
        var msg = JSON.parse(data);

        document.getElementById("count").innerHTML = ++count;
      });
    </script>
  </body>
</html>
```

It starts failing between 4000 and 5000 messages from the server.
One weird thing I see is that [decodePayloadAsBinary][1] shows bufferTail as undefined, but the argument to [sliceBuffer][2] shows it as valid.

Also, for some reason in my demo the webpage crashes showing the

> Aw, Snap!
> Something went wrong while displaying this webpage.

page, while in my actual application the webpage doesn't always crash, and will just pause on the error properly most of the time so I can look at variable state.

[1]: https://github.com/socketio/socket.io-client/blob/master/socket.io.js#L4963
[2]: https://github.com/socketio/socket.io-client/blob/master/socket.io.js#L1212
[3]: https://github.com/socketio/socket.io-client/blob/master/socket.io.js#L1217

**Comment by darrachequesne** [comment]
@mtfurlan Hi! That error `RangeError: Array buffer allocation failed` is thrown in v8 when memory allocation fails, I think.

We could add a try/catch around `arraybuffer.slice()`, but I guess that wouldn't solve the underlying issue.

Maybe could you add some kind of throttling on the server side ? Or send batch of elements, instead of one by one?

**Comment by mtfurlan** [comment]
Well that's terribly reasonable and now I feel a bit silly for not having thought of it like that.
Thank you.
