### ISSUE TITLE
Fatal signal 11 (SIGSEGV) on client diconnect/close

### ISSUE THREAD

**Issue by ErickGallani** [socketio/socket.io-client#995]
I recently created an app with WebRTC using on the browser side NodeJS + Socket.io.

And on the Android side this socket.oi-client.

In my gradle:

> compile 'com.github.nkzawa:socket.io-client:0.4.2'

Everything works fine.

But every time I call on my android device the client.disconnect() or client.close() wheres client is my socketio object, I receive this error.

> A/libc(2495): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 2508 (Thread-117)

Any ideas why this happen?

**Comment by darrachequesne** [comment]
Closing, as it seems that issue belongs to https://github.com/socketio/socket.io-client-java.

**Comment by vincepunkrock** [comment]
@ErickGallani  I know this was a long time ago, but I just have the same problem. Did you find an answer to your question somewhere? Or did you find the solution to your problem?
